### ISSUE TITLE
Lunar Bug -  Automatically quit itself

### ISSUE THREAD

**Issue by sfdye** [alin23/Lunar#100]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Air 2020

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
	Dell 2720Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
	USB-C to USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Location

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:

I notice this reliably that Lunar has been quitting itself silently, is this something known?

**Comment by alin23** [comment]
Hi @sfdye !

Yes, it is a known bug. It will be fixed in the next version.

**Comment by sfdye** [comment]
Very nice 🎉

**Comment by alin23** [comment]
Should be fixed in 3.2.0. Feel free to reopen the issue if you still encounter this 😊

**Comment by sfdye** [comment]
This is fixed, but I just noticed the mode automatically switches to `manual` from `location` after time, without me doing anything.

**Comment by alin23** [comment]
It's possible that:
1. You have clamshell mode detection enabled and you are closing the Macbook lid:
![image](https://user-images.githubusercontent.com/3819725/80283780-04a8d500-8723-11ea-898c-d7bfa4cf3d0b.png)

2. You're hitting one of the hotkeys that enables Manual mode:
<img width="1062" alt="Screenshot Lunar Hotkeys" src="https://user-images.githubusercontent.com/3819725/80283769-ec38ba80-8722-11ea-824a-857af784e151.png">

**Comment by sfdye** [comment]
I see, disabled all the hot keys and let's see.

**Comment by sfdye** [comment]
In hindsight, this should not come as surprise for new user, so I think the global hot keys should be unset by default.
