### ISSUE TITLE
USB light sensor support

### ISSUE THREAD

**Issue by vguerci** [alin23/Lunar#101]
### Name of the feature

Light sensor

### What problem does this feature solve?

I use a laptop with an external monitor. I prefer to keep the laptop closed, so I cannot use the Sync Mode. Being capable of using a luminosity sensor would solve this.

### How should the feature work

An external Light sensor, possibly a DIY usb module. Lunar would need to implement something similar to what macOS does to translate these Lumens into Monitor settings. Could also fit plugged Lunar Sync Mode.

### Visual description

N/A / the module can be ugly, It can be stuck behind the screen for instance

See #94 for related discussion on the topic

**Comment by jstader** [comment]
I'm not sure how far along the usb light sensor is but it would be really cool if this supported devices like the [SpyderX Pro](https://spyderx.datacolor.com/about-spyderx/) that many people use for monitor calibration. That being said, I haven't used this functionality so I'm not sure about its ease of use or the reliability of the sensor. The possibility of applying different icc monitor profiles for different brightness/contrast levels would be neat too (if that's technically feasible).

**Comment by alin23** [comment]
Done in **Lunar 4**, but I'm still waiting for the hardware order to arrive to start shipping.

You can download Lunar 4 from the official website: https://lunar.fyi

And check out the details on the sensor here: https://lunar.fyi/#sensor

If you have other issues, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Comment by fotiDim** [comment]
@alin23 is SpyderX Pro supported now?
