### ISSUE TITLE
Monitor input selection/shortcut

### ISSUE THREAD

**Issue by bernadinm** [alin23/Lunar#102]
### Name of the feature
Change Monitor Input KVM Shortcut

*give a name to your wanted feature*

### What problem does this feature solve?

With multiple machines connected to a KVM enabled monitor like Dell U3419W it would be great to have the monitor change the input source with a hotkey.

*describe what doesn't work as it should now, and how this feature would solve that*

### How should the feature work

We can make a keyboard shortcut for lunar like FN + CTRL+ RIGHT ARROW or something that does this.

https://www.dell.com/community/Monitors/U3014-Is-there-a-shortcut-to-quickly-switch-inputs/td-p/4401157/page/2

*describe the way you would want this to work, as detailed as possible*

### Visual description

*if this is a UI change, try to add an image of how you think this should look like*

**Comment by alin23** [comment]
Hi @bernadinm!

Can you please test ddcctl to check if it can control your monitor's input through DDC? 
You can find ddcctl here: https://github.com/kfix/ddcctl

If that works then I'd be glad to implement that into Lunar!

**Comment by eliassendaniel** [comment]
> Hi @bernadinm!
> 
> Can you please test ddcctl to check if it can control your monitor's input through DDC?
> You can find ddcctl here: https://github.com/kfix/ddcctl
> 
> If that works then I'd be glad to implement that into Lunar!

I just tested this on Dell U3419W and can confirm that it works.

`./ddcctl -d 1 -i 15`

Allowed me to toggle display port input which is my PC and from there I can use the official Dell Software manager to toggle back to USB-C which is my macbook.

**Comment by danieleliassen** [comment]
> Hi @bernadinm!
> 
> Can you please test ddcctl to check if it can control your monitor's input through DDC?
> You can find ddcctl here: https://github.com/kfix/ddcctl
> 
> If that works then I'd be glad to implement that into Lunar!

I just tested this on Dell U3419W and can confirm that it works.

`./ddcctl -d 1 -i 15`

Allowed me to toggle display port input which is my PC and from there I can use the official Dell Software manager to toggle back to USB-C which is my macbook.

**Comment by bernadinm** [comment]
Wow. Thank you both @alin23 and @danieleliassen . This worked great.

I have my macbook on hdmi connected to hdmi-1 and this command worked for me to switch to this:

I've just tested this on DELL U3419W as well.

```
./ddcctl -d 1 -i 17 # hdmi-1
```
```
./ddcctl -d 1 -i 18 # hdml-2
```

I did try to switch back from HDMI-1 to USB-C but it looks like there is a current issue with ddcctl which doesn't seem to support that at the moment. https://github.com/kfix/ddcctl/issues/67

**Comment by bernadinm** [comment]
Perfect! Looks like this is now supported with USB-C! https://github.com/kfix/ddcctl/commit/a53138f05efe966b7125ccaef5e28a78479c5b06

I have tested and I am able to switch to USB-C on my MacBook now.

I've just tested this on DELL U3419W as well.

```
./ddcctl -d 1 -d 27 # USB-C
```

Now all we will need is your support with Lunar and it will be amazing!

**Comment by dbalatero** [comment]
I wrote up how you can hotkey it with ddcctl + hammerspoon: https://balatero.com/writings/hammerspoon/create-a-quick-monitor-input-switcher/

**Comment by alin23** [comment]
Done in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

This can behave unexpectedly if the system shuffles the monitor IDs around. Unfortunately there's still no way to store a persistent unique ID per monitor so settings can still be assigned to the wrong monitor sometimes. I'll be doing some debug sessions with users that have multiple monitors of the same model to see if there's any way to work around this limitation.

If you have issues, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
