### ISSUE TITLE
Lunar Diagnostics Report [A4A50119DBE752E244F2FAB5833ECD706897C912759EFCEF3E69A0D935A6A004] [3.2.2]

### ISSUE THREAD

**Issue by k7azadeh** [alin23/Lunar#104]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook pro 2017 15 inch

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-DisplayPort

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
I cannot change the brightness of the external monitor with the provided shortcuts.

**Comment by alin23** [comment]
Hi @k7azadeh ! Can you please try to see if [ddcctl](https://github.com/kfix/ddcctl) works for you? 
Because this sounds to me like a hardware/connection problem. If ddcctl can't change your brightness/contrast then something in your setup is failing to send DDC messages to the monitor.
