### ISSUE TITLE
Not compatible with iMac models before 2013

### ISSUE THREAD

**Issue by dlejay** [alin23/Lunar#105]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *It made it go black completely.*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Air 2014*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *Thunderbolt 2*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*Lunar does not sync the brightness with the iMac 2012 I use in Target Display Mode*

**Comment by alin23** [comment]
Hi! Can you please update Lunar to 3.2.3 and let me know what is the *Built-in Brightness* reported in the Lunar menu? Try changing the built-in display brightness and see if it is read correctly by Lunar.

![image](https://user-images.githubusercontent.com/3819725/81272989-e7df9c00-9056-11ea-9b0f-5792bdddfdea.png)

**Comment by dlejay** [comment]
Lunar updated to 3.2.3
The built-in display brightness is reported as ``0.0``. Also, I realise that when Lunar is on, I cannot change the brightness of my MacBook Air with F1-F2.

**Comment by alin23** [comment]
Lunar listens for the brightness keys when the cursor is on an external monitor. You have to have the cursor on the built-in monitor to change brightness there

**Comment by dlejay** [comment]
I understand. I was copying the screen of my Macbook to the screen of my iMac.

If I don't recopy, then the brightness is reported correctly but the iMac goes black.

Another thing that could be related: the iMac when in TDM (with screen copy) does not respond to F1-F2 from its keyboard (with or without Lunar).

**Comment by alin23** [comment]
I'm not sure if the iMac can be controlled by DDC. Unfortunately I don't have a way to test your setup so I really don't know how to fix this.

Try to rename the `iMac` display in Lunar to `LG UltraFine` (the case matters) by clicking on the display name
![image](https://user-images.githubusercontent.com/3819725/81278129-efef0a00-905d-11ea-98aa-6caab72ecc70.png)

This will force Lunar to use the native CoreDisplay API to control the brightness. If that works then I'll add iMac to the list of displays that can be controlled by CoreDisplay and you will be able to change the name back.

Do I understand this correctly?
1. The brightness is reported as 0 in mirror mode and the iMac brightness does not change at all
2. The brightness is reported correctly in extend mode (not mirror), but Lunar sets the iMac brightness to 0
3. Lunar can control the iMac brightness in Manual or Location mode

**Comment by dlejay** [comment]
If I let ``iMac`` and I use Manual mode, then by clicking ``75%`` or another brightness button, the iMac screen goes black. Also, in the macOS settings (under ``Display``), the brightness of the iMac is not changed. If I click to set the brightness with it, the screen behaves normally and is no longer black.

If I set ``LG UltraFine`` and click the same button, the brightness of the screens does not change, but Lunar says that the brightness has been changed as wanted (same for brightness up, down and other buttons).

The same thing happens in Location mode.

**Comment by dlejay** [comment]
I have just tried with another iMac 2013 (where keyboard brightness keys work). I have the exact same problems.

**Comment by alin23** [comment]
Does the iMac have Automatic Brightness in `Display` settings? 
![image](https://user-images.githubusercontent.com/3819725/81282932-88888880-9064-11ea-8d37-5f6a970ec3a5.png)

**Comment by dlejay** [comment]
I already tried to toggle that. No difference.

**Comment by alin23** [comment]
I meant that if it does have that then Lunar won't work because the brightness will be controlled by the system. And Lunar would also not be necessary if macOS can adapt the brightness for both the iMac and the Macbook Air.

I really don't know how I could fix this without having access to a similar setup. It would be great if you could clone the repo and try to fix it, and share the solution with a Pull Request. You are not the only one having issues with older iMacs so you would help others too.

**Comment by dlejay** [comment]
> And Lunar would also not be necessary if macOS can adapt the brightness for both the iMac and the Macbook Air.

I believe macOS doesn't setup automatically the brightness of the iMac when used as a target display.

>  I really don't know how I could fix this without having access to a similar setup. It would be great if you could clone the repo and try to fix it, and share the solution with a Pull Request. You are not the only one having issues with older iMacs so you would help others too.

I'd love to find a solution and share it but I am afraid this is beyond my skills.
From what I could find on the Internet, Target Display Mode seems to be a half backed feature of macOS and it's actually a legacy feature now that TDM doesn't work with newer iMacs. 

@alin23 I really appreciate the quality of the support that you've been providing, even if the issue can't be solved. Thanks a lot!

**Comment by alin23** [comment]
Thank you for the kind words and all the details! After the lockdown I'll ask around to see if anyone I know has access to an older iMac. Maybe I'll get lucky ¯\\_(ツ)_/¯

**Comment by oniz93** [comment]
@alin23 If you want to do some tests I have a iMac 2009 in target display mode. Actually I can't change brightness with lunar. The only way to change his brightness is via "Shades" (http://www.charcoaldesign.co.uk/shades) but it's high unstable on Mojave.

Let me know if I can help in some way

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
