### ISSUE TITLE
Lunar Diagnostics Report [DB90C14664B93891DD47B4469E4BEB4DD5CDFF02D2325A12858068AC1684CA78] [3.2.3]

### ISSUE THREAD

**Issue by redfern-cohere** [alin23/Lunar#106]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *I did not notice not changes*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Pro (Retina, 15-inch, Mid 2015) - macOS Mojave version 10.14.6*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *(Thunderbolt 2 port) miniDisplayPort-to-DisplayPort*

- Using an USB Docking Station or Hub:
    *no*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Location*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *$ ./ddcctl -d 1 -b ?
D: NSScreen #417385153 (2560x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: T56150420248
I: got edid.name: VP2770 SERIES
D: action: b: ?
D: querying VCP control: #16 =?
E: No data after 10 tries! 
E: DDC send command failed!
E: VCP control #16 (0x10) = current: 0, max: 0*

# Issue description:
*not able to change brightness*

**Comment by alin23** [comment]
Can ddcctl change your display brightness with a command like `ddcctl -d 1 -b 10` ?

**Comment by redfern-cohere** [comment]
No actual change to brightness.
$ ./ddcctl -d 1 -b 10
D: NSScreen #417385153 (2560x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: T56150420248
I: got edid.name: VP2770 SERIES
D: action: b: 10
D: setting VCP control #16 => 10
$ ./ddcctl -d 1 -b 90
D: NSScreen #417385153 (2560x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: T56150420248
I: got edid.name: VP2770 SERIES
D: action: b: 90
D: setting VCP control #16 => 90
$ ./ddcctl -d 1 -b 200
D: NSScreen #417385153 (2560x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: T56150420248
I: got edid.name: VP2770 SERIES
D: action: b: 200
D: setting VCP control #16 => 200
$ ./ddcctl -d 1 -b 0
D: NSScreen #417385153 (2560x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: T56150420248
I: got edid.name: VP2770 SERIES
D: action: b: 0
D: setting VCP control #16 => 0

**Comment by alin23** [comment]
Ok, then this is clearly a hardware problem. Impossible to tell what part of your setup is the issue here, but the usual culprits are:

1. Cable that doesn't use the DDC pin or uses it for something else like sending video data for allowing bigger resolutions (e.g. in Dual DisplayPort mode)
2. Monitor that disables DDC writes to allow for fancy features like Dynamic Contrast without flickering
3. Macbook GPU that has slow reply time for DDC causing the communication to timeout
