### ISSUE TITLE
Lunar Diagnostics Report [A6F2CA2383107D74250493970E896A0CE234A6275745576632BC4C35370855E1] [3.2.3]

### ISSUE THREAD

**Issue by mihar** [alin23/Lunar#107]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MBP16

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to TB3 dock to TB3 MBP16 port

- Using an USB Docking Station or Hub:
    Yes, HP G 120W

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
```D: NSScreen #724068947 (3840x1600 0°) 111.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: 97F8P77D09WL
I: got edid.name: DELL U3818DW
D: action: b: 20
D: setting VCP control #16 => 20
E: Failed to send DDC command!
```

# Issue description:
Can't change brightness/contrast

**Comment by alin23** [comment]
Hi @mihar ! This looks like a hardware connection issue. Try other ways of connecting your monitor (different cable, without the dock etc.) and find what combination makes DDC work for you. This can't be fixed in software.
