### ISSUE TITLE
Automatically checking for updates is broken

### ISSUE THREAD

**Issue by ahydronous** [alin23/Lunar#108]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 13" 2015, macOS Catalina 10.15.3

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    AOC 27"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Thunderbolt 2 to Displayport

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    All

# Issue description:
Lunar does not check for updates automatically, or at least gives no notification / pop-up if a new one is found. Whenever I decide to manually check, it often finds a new update. I can't pinpoint an exact version, but I'd say its been broken for ~1.5 month, maybe more.

**Comment by alin23** [comment]
That might be a bug in the Sparkle updater. I'll check the latest version to see if it fixes this.

**Comment by ahydronous** [comment]
I got an error that might be related: 'An error occurred while parsing the update feed.' when I try to update. Restarting Lunar does not fix it.

**Comment by alin23** [comment]
There is a maintenance operation on the update server right now. It's expected
