### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by jdha97** [alin23/Lunar#109]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    2016 Macbook Pro 15"

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dual HP 24w 23.8-inch Displays

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Both monitors connected to the dock with active Displayport to HDMI converters.

- Using an USB Docking Station or Hub:
    Yes, Plugable TBT3-UDC1

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
When using a dock, Lunar recognizes both monitors but only works on one of them. This issue is not present when using the monitors plugged directly into the MacBook.

**Comment by alin23** [comment]
This is a hardware issue. The dock doesn't correctly forward the DDC messages. It can't be fixed in software.
