### ISSUE TITLE
Animate brightness transitions

### ISSUE THREAD

**Issue by timtraversy** [alin23/Lunar#11]
Love this app. Currently when you change the monitor brightness it snaps to that new value immediately. Would you accept a PR that changed this behavior so that brightness changed smoothly from one value to another (i.e. `50%, 51%,...,74%, 75%`). Should just require writing values in a loop with a delay. Thanks!

**Comment by alin23** [comment]
Sure, I would accept any contribution. Just make sure you test it thoroughly on your monitor. DDC is a very time sensitive protocol so I'm not sure if setting values that fast would work alright yet.

**Comment by timtraversy** [comment]
Ok good to know, I'll take a look.

**Comment by timtraversy** [comment]
Getting this while trying to build your WAYWindow fork. Do you have something set up different on your local machine?
```
*** Building scheme "WAYWindow" in WAYWindow.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/timtraversy/Documents/VCS/Lunar/Carthage/Checkouts/WAYWindow/WAYWindow.xcworkspace -scheme WAYWindow -configuration Release -derivedDataPath /Users/timtraversy/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/WAYWindow/1.0.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/kw/csdt0wyj6_120h52z42g0j6w0000gn/T/WAYWindow SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/timtraversy/Documents/VCS/Lunar/Carthage/Checkouts/WAYWindow)
```

**Comment by alin23** [comment]
Have you run `carthage build --cache-builds --platform macos` to build dependencies?
I'm sorry I haven't written a contribution guide yet, I have very little time to work on Lunar

**Comment by timtraversy** [comment]
Yeah that worked for all the other Carthage deps except this one

**Comment by timtraversy** [comment]
```
Tims-MacBook-Pro:Lunar timtraversy$ carthage build --cache-builds --platform macos
*** xcodebuild output can be found in /var/folders/kw/csdt0wyj6_120h52z42g0j6w0000gn/T/carthage-xcodebuild.D8blfV.log
*** Valid cache found for Alamofire, skipping build
*** Valid cache found for Charts, skipping build
*** Valid cache found for HotKey, skipping build
*** Valid cache found for Magnet, skipping build
*** Valid cache found for KeyHolder, skipping build
*** Valid cache found for NSPageControl, skipping build
*** Valid cache found for Solar, skipping build
*** Valid cache found for Sparkle, skipping build
*** Valid cache found for SwiftDate, skipping build
*** Valid cache found for SwiftyBeaver, skipping build
*** Valid cache found for SwiftyJSON, skipping build
*** No cache found for WAYWindow, building with all downstream dependencies
*** Building scheme "WAYWindow" in WAYWindow.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/timtraversy/Documents/VCS/Lunar/Carthage/Checkouts/WAYWindow/WAYWindow.xcworkspace -scheme WAYWindow -configuration Release -derivedDataPath /Users/timtraversy/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/WAYWindow/1.0.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/kw/csdt0wyj6_120h52z42g0j6w0000gn/T/WAYWindow SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/timtraversy/Documents/VCS/Lunar/Carthage/Checkouts/WAYWindow)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/kw/csdt0wyj6_120h52z42g0j6w0000gn/T/carthage-xcodebuild.D8blfV.log
```

**Comment by timtraversy** [comment]
Oh I figured it out. From log:
`error: Build input file cannot be found: '/Users/alin/Github/alin23/WAYWindow/WAYWindow/WAYWindow.m'`

**Comment by alin23** [comment]
Thanks for debugging that! I fixed the problem.
Just `git pull` and `carthage build` again.

I remember the Solar dependency had an issue with the deployment target version being too high, you might encounter that too. 
I usually open `Carthage/Checkouts/Solar/Solar.xcodeproj` in Xcode and manually change the deployment target to 10.11 to match Lunar.

![image](https://user-images.githubusercontent.com/3819725/54345699-3dcfd400-464c-11e9-9fcc-05006dbb0561.png)

Then to rebuild Solar:
1. Delete the cached build with `rm -rf Carthage/Build/Mac/Solar.framework*`
2. Rebuild with `carthage build --cache-builds --platform macos`

**Comment by timtraversy** [comment]
Yes I got around the Solar bug, thanks. I’ll checkout out the fix.

**Comment by alin23** [comment]
Done!

**Comment by timtraversy** [comment]
I'm not seeing this in the most recent update. Is it animating on your monitor?

**Comment by alin23** [comment]
@timtraversy You have to enable smooth transition in the settings

**Comment by timtraversy** [comment]
Ah right. It looks good! But the app menu freezes during transitions which is surprising because it seems like you are doing the transition async.

**Comment by alin23** [comment]
Yes, it is async but it's still running on the main queue which is the same one that runs the UI loop.
You can see a basic explanation here:
>GCD provides three main types of queues:

>**Main queue**: runs on the main thread and is a serial queue.
**Global queues**: concurrent queues that are shared by the whole system. There are four such queues with different priorities : high, default, low, and background. The background priority queue has the lowest priority and is throttled in any I/O activity to minimize negative system impact.
**Custom queues**: queues that you create which can be serial or concurrent. Requests in these queues actually end up in one of the global queues.

You can try running the transition function on the global queue with a high qos to see if it makes a difference. As I said before, the slow DDC response blocks the whole system for me so I can't see any difference between the queues.
