### ISSUE TITLE
Lunar Diagnostics Report [B3920D9D959C24FB3D006EECF5C1AA67B3DD0EF4AC37CE21C6687B70A1BE47EB] [3.2.3]

### ISSUE THREAD

**Issue by DG0BAB** [alin23/Lunar#110]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    On Dell U3014: Yes
    On Eizo EV3285: No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    iMac 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Dell: DP -> Sonet Thunderbolt 3/USB-C to DP -> iMac Thunderbolt3 USB-C
    Eizo: USB-C -> iMac USB-C

- Using an USB Docking Station or Hub:
    Just the Sonnet Thunderbolt 3 to Dual DisplayPort Adapter (for 4K Displays) to connect the Dell

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
     No it gives the following output, when I try to set the brightness of the Eizo to 10
    D: NSScreen #1892317132 (3360x1890 0°) HiDPI
    D: NSScreen #722474510 (2560x1600 0°) 101.00 DPI
    I: found 2 external displays
    I: polling display 1's EDID
    I: got edid.name: EV3285
    D: action: b: 10
    D: setting VCP control #16 => 10
    E: Failed to send DDC command!

# Issue description:
Lunar can control the Dell but not the Eizo EV3285

**Comment by alin23** [comment]
Hi @DG0BAB ! 
If ddcctl can't control the monitor then it is a hardware issue. The issue could be with either the cable, monitor controller firmware or iMac GPU. Impossible to tell without further debugging.

Try switching the iMac port or use another Thunderbolt 3 cable if you can.
