### ISSUE TITLE
Lunar Diagnostics Report [FB348799B0BB4CEFC2D0F3633A5A11AA112C6A9D9559AA7856F07C4A9F530204] [3.2.3]

### ISSUE THREAD

**Issue by yogevyu** [alin23/Lunar#112]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
no...

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   MBP 2018 13'' retina

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   HDMI to usb-C dongle

- Using an USB Docking Station or Hub:
   yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    in this case sync, but all

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
just doesn't sync on this particular screen

**Comment by alin23** [comment]
Sorry for the very delayed response. Try using a direct cable without the dock, or a different connector on the monitor like display port if possible. 

It is a hardware problem that can only be solved by using the right cable/dock that has proper support for DDC. I'm still working on a list that contains a collection of working cables and adapters.
