### ISSUE TITLE
Lunar Diagnostics Report [2C5B71F2A7FBBC5FEFD3ED59E498F923C11679A2782641E10ECE4A2065B78E24] [3.2.3]

### ISSUE THREAD

**Issue by jasonminsookim** [alin23/Lunar#114]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *No*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *2018 Mac Mini*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *HDMI*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Locationl*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*

**Comment by alin23** [comment]
Hi, I've had multiple complaints about HDMI not working with DDC on the newer Mac minis. Unfortunately I don't have access to a Mac mini to test Lunar on it so all I can recommend is to try different connectors like Thunderbolt or DisplayPort if possible.
