### ISSUE TITLE
Ability to toggle Lunar's application on the display

### ISSUE THREAD

**Issue by mikeCentrol** [alin23/Lunar#115]
At the moment I have two monitors (both are AOC 2267W), the first monitor is connected via an HDMI to DVI cable and the second monitor is connected via a VGA to VGA cable. 
The VGA cable connected monitor appears to work with Lunar but the DVI monitor does not. 

I made updates to the brightness and contrast on the VGA connected monitor but cannot seem to match it back to the other monitor now. 

Any help would be greatly appreciated. 

Mike

**Comment by alin23** [comment]
Hey! I don't know how I didn't notice this issue for 26 days.

What I can suggest is to try different cables if you have more handy. It sounds like the HDMI to DVI convertor inside the cable doesn't pass DDC messages correctly.

I'll close the issue as this is a hardware problem but feel free to post updates here.
