### ISSUE TITLE
Weather-aware Location mode

### ISSUE THREAD

**Issue by keithtkl** [alin23/Lunar#118]
### Name of the feature

Location Mode w/ Weather

### What problem does this feature solve?

If it is a cloudy day the monitor will be too bright as Location Mode only take sunrise sunset time into account. It would be nice if Location Mode can also consider weather condition to adjust the monitor brightness

### How should the feature work

Also take cloud coverage % and precipitation % in the algorithm for Location Mode to calculate the brightness and contrast value

### Visual description

No UI change needed

**Comment by alin23** [comment]
This is a very good idea! I'll try to include it in the next major update.

**Comment by alin23** [comment]
I failed to do this: https://lunar.fyi/faq#cloud-cover
