### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by timtraversy** [alin23/Lunar#12]
<img width="463" alt="Screen Shot 2019-03-12 at 9 09 02 PM" src="https://user-images.githubusercontent.com/21370530/54246383-17564f80-450b-11e9-9a87-ec10b0c89dff.png">

Getting this error when trying to update to most recent version.

**Comment by karthicraghupathi** [comment]
This error is affecting me too. I was tailing the system logs and I noticed the following error:

```
error	00:24:27.048281 -0400	Lunar	Error: No valid unarchiver for /Users/karthicr/Library/Caches/site.lunarapp.Lunar/org.sparkle-project.Sparkle/PersistentDownloads/lE4hc4bH0/Lunar 2.2.1/Lunar-2.2.1.dmg.html!
error	00:24:29.668780 -0400	Lunar	Error: Failed to extract update. (null) (URL (null))
```

I don't know much about macOS apps but I think the `html` extension at the end of the file could be the cause of the issue. Hope that helps!

**Comment by timtraversy** [comment]
This has been fixed :) thanks @alin23
