### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by patrickrushton** [alin23/Lunar#120]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MacBook Pro 2015

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
Dell

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
DisplayPort

- Using an USB Docking Station or Hub:
No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Both

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:

When in sync mode, everything works great - the brightness keys change the Macbook's brightness and the Dell syncs to that.

When I close the Macbook, clamshell mode kicks in, and I would expect the brightness keys to now control the Dell. 

But instead, the brightness keys do nothing. 

I would like to be able to have brightness keys (or custom hotkeys) control the Macbook brightness when in sync mode, and the external monitor brightness when in manual mode (activated via clamshell detection). Is this possible?

**Comment by alin23** [comment]
Hi @patrickrushton 

Lunar can already do this. If you want to use the brightness keys, make sure you have the media keys listener enabled:
![image](https://user-images.githubusercontent.com/3819725/83981468-c0664280-a926-11ea-8bdc-36595dc84747.png)

For using different hotkeys, make sure you have hotkeys configured in Lunar settings:
![image](https://user-images.githubusercontent.com/3819725/83981492-f277a480-a926-11ea-9b94-145176c1f5ee.png)

**Comment by patrickrushton** [comment]
Yes, I'd already found those thanks. 

What I'd like is for the media key listeners to activate ONLY in clamshell mode. So that they will adjust the brightness on my Macbook when its open (and my ext monitor will sync to that), and when in clamshell mode, the brightness keys would automatically switch to controlling my external monitor brightness directly.

**Comment by alin23** [comment]
The brightness keys will still control your Macbook display when the lid is open and the cursor is on the Macbook display. The brightness keys will always control the monitor where the cursor is.

I think that this is a good compromise to be able to fine tune monitors one by one while still being able to control all of them at once when using the custom hotkeys.

**Comment by patrickrushton** [comment]
> I think that this is a good compromise to be able to fine tune monitors one by one while still being able to control all of them at once when using the custom hotkeys.

I'm confused by this last sentence. On my system the custom hotkeys do not control all the screens at once - they only adjust my external monitor, regardless of whether I'm in sync or manual mode.

**Comment by alin23** [comment]
All the external monitors I mean. Lunar supports any number of external monitors, and it doesn't control the built-in monitor at all as that is what macOS is good at.

So for example, if you had 3 monitors connected to your Macbook, the brightness keys would allow you to fine tune them one by one by moving the cursor on them, and the custom hotkeys would change the brightness/contrast for all of them at once.

**Comment by patrickrushton** [comment]
Gotcha. I'd expected the brightness keys to always adjust both, since that's the behaviour I'd prefer once I've got the sync profile working nicely. But I will try and get into the habit of moving my cursor to the MacBook internal display before I hit those keys.

Thanks for the replies and the nice app.

**Comment by alin23** [comment]
Yes, it's annoying to do that every time you want to adjust the Macbook brightness, but I hoped that this wouldn't be an action you do often since the adaptive algorithm of macOS is pretty good in keeping the Macbook brightness in sync with the ambient light. 

If you find yourself adjusting the Macbook brightness too often then you might want to reset the curve that the macOS learned over time by resetting the SMC controller: https://support.apple.com/en-us/HT201295
