### ISSUE TITLE
Lunar Bug High Sierra

### ISSUE THREAD

**Issue by alst-ovh** [alin23/Lunar#121]
3.2.3 won't run under High Sierra, 3.2.2 works perfect ?

**Comment by alin23** [comment]
There hasn't been any change that could cause this. You could try a complete reinstall by deleting the following files and folders and reinstalling the app from https://lunar.fyi :

- `/Applications/Lunar.app`
- `~/Library/Application Support/Lunar`
- `~/Library/Application Support/site.lunarapp.Lunar`
- `~/Library/Preferences/site.lunarapp.Lunar.plist`

**Comment by alst-ovh** [comment]
Doesn't Help, Library missing.

Process:               Lunar [3628]
Path:                  /Applications/Lunar.app/Contents/MacOS/Lunar
Identifier:            site.lunarapp.Lunar
Version:               3.2.3 (3.2.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Lunar [3628]
User ID:               501

Date/Time:             2020-06-09 10:00:19.636 +0200
OS Version:            Mac OS X 10.13.6 (17G13035)
Report Version:        12
Anonymous UUID:        C327CB2F-63E6-E493-3D4B-875D68ED33F7


Time Awake Since Boot: 1500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Applications/Lunar.app/Contents/MacOS/Lunar
  Reason: image not found

Binary Images:
       0x102b5e000 -        0x10300afff +site.lunarapp.Lunar (3.2.3 - 3.2.3) <D9F4851C-0429-3E49-B0FF-88578970D19A> /Applications/Lunar.app/Contents/MacOS/Lunar
       0x103938000 -        0x103939fff +com.sindresorhus.LaunchAtLogin (3.0.0 - 1) <553EA9C6-DCAD-3CE0-A738-E457B952D0E6> /Applications/Lunar.app/Contents/Frameworks/LaunchAtLogin.framework/Versions/A/LaunchAtLogin
       0x103945000 -        0x10398bff7 +org.sparkle-project.Sparkle (2.0.0 919-g80627a49 - 2.0.0) <0C630E32-4610-3950-BEE4-842FA8508BA4> /Applications/Lunar.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x103a02000 -        0x103a09fff +com.nerd0geek1.NSPageControl (0.0.1 - 1) <1DF91FFD-43BE-3AE7-9B2C-EF921D52DC84> /Applications/Lunar.app/Contents/Frameworks/NSPageControl.framework/Versions/A/NSPageControl
       0x103a20000 -        0x103a24fff +com.alinp.ModernWindow (1.0 - 1) <A361DFC8-E9A1-308D-A971-1E90A94E90C3> /Applications/Lunar.app/Contents/Frameworks/WAYWindow.framework/Versions/A/WAYWindow
       0x103a38000 -        0x103a44fff +nhurden.MediaKeyTap (1.0 - 1) <C0D1BB86-F8A5-3F38-BDAA-D725D60B8D61> /Applications/Lunar.app/Contents/Frameworks/MediaKeyTap.framework/Versions/A/MediaKeyTap
       0x109ccf000 -        0x109d19adf  dyld (551.5) <CB9BFB56-4511-36F1-A546-891FF770C01C> /usr/lib/dyld
    0x7fff40952000 -     0x7fff40952fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <2EF00EFE-06E8-3082-85C3-2988B422A19D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff41c40000 -     0x7fff42a9efff  com.apple.AppKit (6.9 - 1561.61.100) <3AB30D3C-ACD6-3738-BE81-0E1A24CB4FF5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff42af0000 -     0x7fff42af0fff  com.apple.ApplicationServices (48 - 50) <B2FE4B32-CD08-3DC6-9EE7-08736C169F5B> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff435ee000 -     0x7fff4398bfff  com.apple.CFNetwork (902.6 - 902.6) <46168F79-CCFA-349A-8508-B8CBCE27D440> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff439a0000 -     0x7fff439a0fff  com.apple.Carbon (158 - 158) <F8B370D9-2103-3276-821D-ACC756167F86> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff44106000 -     0x7fff44199ff7  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <AF2B41CC-DD7A-34EB-A842-00DC3B8F2E9F> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff4458f000 -     0x7fff44672fff  com.apple.CoreDisplay (99.14 - 99.14) <9B2B211D-EC0A-3569-BB37-887768CD6105> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff44673000 -     0x7fff44b0ffff  com.apple.CoreFoundation (6.9 - 1455.122) <8DFA8989-783F-3AF8-8BA7-05AF335B7827> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff44b11000 -     0x7fff45140ff7  com.apple.CoreGraphics (2.0 - 1161.21.3) <9ACBD792-2A70-3CFD-8115-084A23DD639F> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff45432000 -     0x7fff4549dff7  com.apple.corelocation (2245.0.41) <6BF57F70-732C-3140-B5A3-466ACF262765> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff45806000 -     0x7fff45806fff  com.apple.CoreServices (822.37 - 822.37) <31299671-DF38-3C71-A389-3555F9D06080> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff462e8000 -     0x7fff46322fff  com.apple.CoreVideo (1.8 - 0.0) <0DD4FFDF-E1F1-39D1-8246-5D0D9869F1EA> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff467ef000 -     0x7fff46bb6ffb  com.apple.Foundation (6.9 - 1455.122) <2DA81E9F-DF81-3D69-8E82-B662017E0D18> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff46ecd000 -     0x7fff46f68fff  com.apple.framework.IOKit (2.0.2 - 1445.71.6) <4B5C715C-6A49-366B-9080-ABADE6A3B3BD> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff4fa7d000 -     0x7fff4fcc9ff7  com.apple.QuartzCore (1.11 - 584.64.2) <FD9A3180-479E-3DAC-9CF0-0D214C7E46A7> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff50502000 -     0x7fff5082dfff  com.apple.security (7.0 - 58286.70.15) <CE6A59AD-49F3-38C3-80E6-F56F00C45DF0> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff50c95000 -     0x7fff50d05ff3  com.apple.SystemConfiguration (1.17 - 1.17) <41D509AB-AED3-30FF-BB00-615BB5A8AC00> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff532f9000 -     0x7fff53792fff  com.apple.WebKit (13605 - 13605.3.8) <1DDB40C0-5FB6-3495-B4CD-52D32251F88D> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff60c59000 -     0x7fff60c5aff3  com.apple.OSD (1.0 - 1) <E1F25D38-C823-3E39-9235-2A448E774F75> /System/Library/PrivateFrameworks/OSD.framework/Versions/A/OSD
    0x7fff6a370000 -     0x7fff6a371ffb  libSystem.B.dylib (1252.50.4) <8028C828-512C-39D4-9D60-3C09FAF56306> /usr/lib/libSystem.B.dylib
    0x7fff6a628000 -     0x7fff6a67efff  libc++.1.dylib (400.9) <142D6292-F30F-3949-9F37-3C97A579F540> /usr/lib/libc++.1.dylib
    0x7fff6baab000 -     0x7fff6be9c3b7  libobjc.A.dylib (723) <616AB826-9179-3924-AA61-AF760363A3F5> /usr/lib/libobjc.A.dylib
    0x7fff6c4c2000 -     0x7fff6c4d4ffb  libz.1.dylib (70) <47278BDC-596E-3037-B8DA-05FE9D5DBEF6> /usr/lib/libz.1.dylib

**Comment by alin23** [comment]
Check out the first point in the troubleshooting section: https://github.com/alin23/Lunar#troubleshooting
