### ISSUE TITLE
Lunar Feature: Dark Mode / AppleScript triggers 

### ISSUE THREAD

**Issue by patrickrushton** [alin23/Lunar#122]
### Name of the feature

Dark Mode / AppleScript triggers 

### What problem does this feature solve?

Like many people, I haven't updated to Catalina, so I don't have the automatic dark mode that is part of 10.15. Perhaps this is something Lunar can help with. I'm not sure if this should happen on sunset (based on location) or after reaching a brightness threshold (though that might get annoying). 

For maximum flexibility, it would be cool if rather than just toggling system dark mode, an applescript was triggered. Why? Because it can be useful to make additional adjustments for night-time reading. For example, this is the AppleScript that I currently have as a shortcut in BetterTouchTool. I do stuff like set the Things 3 and Bear themes (for an older machine that runs High Sierra) and change the PDF Expert theme (which doesn't sync to system dark mode), etc.

It would be really cool if Lunar was able to trigger this for me!

```
tell application "System Events"
	if dark mode of appearance preferences is false then
		tell appearance preferences
			set dark mode to true
		end tell
		tell process "Things"
			set frontmost to true
			click menu item "Dark" of menu of menu item "Appearance" of menu "View" of menu bar 1
		end tell
		tell process "PDF Expert"
			set frontmost to true
			click menu item "Night" of menu of menu item "Theme" of menu "View" of menu bar 1
		end tell
		set createUrl to "bear://x-callback-url/change-theme?theme=Toothpaste"
		open location createUrl
	else
		tell appearance preferences
			set dark mode to false
		end tell
		tell process "Things"
			set frontmost to true
			click menu item "Light" of menu of menu item "Appearance" of menu "View" of menu bar 1
			set createUrl to "bear://x-callback-url/change-theme?theme=Red%20Graphite"
		end tell
		tell process "PDF Expert"
			set frontmost to true
			click menu item "Day" of menu of menu item "Theme" of menu "View" of menu bar 1
		end tell
		open location createUrl
	end if
end tell
```

**Comment by alin23** [comment]
Hi @patrickrushton ! 
Unfortunately this is completely out of the scope of Lunar. This is just an app to control external displays, not make changes to the system appearance.

You can use crontab for this specific use case.
Run `crontab -e` to edit your crontab add add something like:
```crontab
30 19 * * * osascript /usr/local/bin/TurnOnDarkMode.applescript
```

You can also use `sunwait` to execute the script at sunset/sunrise: https://raspberrypi.stackexchange.com/questions/90099/execute-a-script-at-sunrise-sunset

**Comment by patrickrushton** [comment]
Fair enough. I always found the "dark mode at sunset" a nice feature in f.lux. I'll try the solutions you suggested.

**Comment by vguerci** [comment]
Just necro-bumping this one, as I was just thinking as well it would be nice to enable dark mode based on Lunar brightness, that is way better/finer than sunrise/sunset which doesn't suit my usage. I often toggle dark mode earlier than sunset, when it goes dark, which follows my Lunar curve...
Keep up the good job @alin23 ! :)
