### ISSUE TITLE
Mac mini 2018 HDMI connection not passing DDC messages

### ISSUE THREAD

**Issue by aisamu** [alin23/Lunar#125]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)? 
No 

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Mac mini 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
HDMI_HDMI

- Using an USB Docking Station or Hub:
No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
No

# Issue description:
Happy to try anything you'd like me to!

**Comment by alin23** [comment]
Unfortunately, if ddcctl doesn't work either, then it is a hardware connection problem. 

You can try different connections like the Thunderbolt 3 connector on the Mac Mini or a different HDMI cable. I don't know what the heck is wrong with these Mac Minis, I've had countless complaints from Mac Mini users about the HDMI connection.

It's possible that it just needs different DDC message timing but it's impossible for me to find the right values without physical access to a Mac Mini. I'll try to see if there is a way to create a small utility that can brute force these values and maybe you or someone else with a Mac Mini could run it and report if any value had any effect on the monitor.

**Comment by aisamu** [comment]
> You can try different connections like the Thunderbolt 3 connector on the Mac Mini or a different HDMI cable. I don't know what the heck is wrong with these Mac Minis, I've had countless complaints from Mac Mini users about the HDMI connection.

I assumed the usb-c dongle would have less chance of working, but it turns out I was wrong! 
Thanks for the tip!

> you or someone else with a Mac Mini could run it and report if any value had any effect on the monitor.

I'd gladly test this for you.

**Comment by alin23** [comment]
I'll post here the binary if I get some time to work on a possible solution for this. 😊

**Comment by Mic238** [comment]
I just upgraded my 2014 Mac mini to a 2020 one (or 2018). Can confirm this doesn't work not only with lunar but all similar softwares fail over HDMI connection. As HDMI monitor is appearing as a DisplayPort monitor on the OS, I think this is a hardware design issue and there is really nothing you can do with a software. I also found a few successes with USB-C to HDMI adaptor/cable that pass DDC correctly, I'm getting one on eBay and will update as it comes.

**Comment by alin23** [comment]
@Mic238 thanks for following up on this! I'll write something down about this in the README and on the official website.

**Comment by Mic238** [comment]
Adaptor arrived, lunar works only for a few seconds when it first plug in to the monitor and Mac, and never afterward even pull out and plug in again. I think it was the first few second they are handshaking still on fallback HDMI interface, and later transits to DP alt mode marking the end.

Also tried HDMI - Monitor + USB-C to HDMI capture card, both showing as DP alt mode, also no luck changing anything......

**Comment by alin23** [comment]
I think we can all agree this is a hardware problem. I'll close this.

Don't forget to update to **Lunar 4** as that has Gamma Tables support which works on any monitor and any input.
Even though it doesn't change the hardware brightness of the monitor, it's better than nothing.

You can download it from the official website: https://lunar.fyi

If you are having other issues, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
