### ISSUE TITLE
yer10!Lunar Diagnostics Report [912611C2EF6424C5E9BE5D5ED1DBEDA1A5F47A47CB68F1E03E72359E5197BFC6] [3.2.3]

### ISSUE THREAD

**Issue by creamsoda17022** [alin23/Lunar#126]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Kind of, it doesn't respond well and the display only dims when the diagnostic is run. After that, the brightness won't increase.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2014 w/ Retina

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    iMac 21", late 2012 – connected via Thunderbolt 2, used as a target display

- Using an USB Docking Station or Hub:
   no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    sync, also tried manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    kinda! I'm able to adjust slightly via terminal, but its max value is 255 and that seems like it is not the maximum brightness level for my iMac. I'm not too sure how to calibrate this, though?

# Issue description:
Lunar does change the brightness, but only between the minimum and a very low level—it's as if its range on the iMac is between the 0th brightness and 1st brightness level on a mac's 16-increment brightness meter. If that makes any sense?

**Comment by alin23** [comment]
That means the iMac has an even higher range than 255. Unfortunately DDC only supports 8-bit integers for specifying the brightness value so we can't do anything in this case. 

For this to work, the iMac display should have had some custom code inside its firmware to map its brightness range to 0-255 when DDC is used

Thanks for the report! It is a good insight to have, I'll try to add this information inside an FAQ somewhere. I wish I could do more to fix it but it is a firmware limitation and we don't have access to that.
