### ISSUE TITLE
Lunar Diagnostics Report [8C3AC84392049CFAE47C95EF4ACE023880236A437BBA586660BA8664D6288AF0] [3.2.3]

### ISSUE THREAD

**Issue by sommeow** [alin23/Lunar#127]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2018 - OS 10.15.5

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI to USB-C

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
External monitor not responding to Lunar settings

**Comment by sommeow** [comment]
Ope nevermind. Figured it out. I derped.

**Comment by alin23** [comment]
Hi @sommeow! Could you please write a short summary of what caused the confusion or the thing that didn't work? ^_^
I'm working on making Lunar more foolproof and real-world cases help me the most.

**Comment by sommeow** [comment]
I didn't read your caveats 🙃 (downloaded DMG from lunar.fyi ) and was using a hub because I was also charging another device. Removed the hub and it works fine now with just the DisplayPort to USB-C cable directly into Mac. Whoops. 😅

Anyway, Lunar is an amazing utility, thank you!

**Comment by alin23** [comment]
I'm glad it works in the end!

Yes, the official website is still a work in progress. I'm adding the caveats and a more detailed FAQ there to avoid confusions like this.
