### ISSUE TITLE
Lunar Diagnostics Report [A15A7F42388A7BB3B3A89598C87E5E3F17808BB3A9D453BAC0B9AA0C6E11EBC3] [3.2.3]

### ISSUE THREAD

**Issue by mtfewkes** [alin23/Lunar#131]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *write response here*

No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *write response here*

MacBook Pro 13-inch, 2018 Catalina 10.15.5

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *write response here*

USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    *write yes or no here*

No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location or Manual*

Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*

Luna

**Comment by alin23** [comment]
What is the monitor model that you are using with Lunar? The logs tell me that it doesn't respond to any kind of DDC messages. Even its name is unreadable.

**Comment by mtfewkes** [comment]
I am using a Mobile Pixels Duex Pro. It does have to use displaylink drivers so I’m not sure if that makes a difference

**Comment by alin23** [comment]
It's very possible that the DisplayLink driver doesn't have support for DDC on macOS. 
That is what these sources say:

1. https://displaylink.org/forum/showthread.php?t=65289
<img width="1680" alt="CleanShot 2020-06-25 at 17 09 47@2x" src="https://user-images.githubusercontent.com/3819725/85735894-b6a25480-b706-11ea-9a37-7527518c8ebb.png">

2. https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/16135240-add-brightness-support-to-non-windows-oses
![CleanShot 2020-06-25 at 17 11 16@2x](https://user-images.githubusercontent.com/3819725/85736240-fec17700-b706-11ea-9e5b-7c822f2c9855.png)
