### ISSUE TITLE
Mac mini 2018 HDMI connection not passing DDC messages

### ISSUE THREAD

**Issue by Caffa** [alin23/Lunar#133]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mac mini 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
So I am using a Prism + Monitor, and there is no change in my display. Also I gave permissions in security.

**Comment by alin23** [comment]
Thanks for the report!

I'm trying to find a friend with a Mac mini to try to fix this. It is impossible for me to find the issue without physical access to the device.

**Comment by alin23** [comment]
We'll track this in #125
