### ISSUE TITLE
Lunar Diagnostics Report [DFFE39E0222784AC60FBAF0B6B0B9DC4F35046411821D956E468519EC6BF5204] [3.2.3]

### ISSUE THREAD

**Issue by octetta** [alin23/Lunar#136]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (Retina, 15-inch, Late 2013)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    yes

# Issue description:
Works as expected. Using Acer KA270H

**Comment by alin23** [comment]
Thanks for the report! Will keep in mind that this particular setup works when getting other bug reports.
