### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by sidharthv96** [alin23/Lunar#138]
### Name of the feature
*Dark mode support in launch screen*

### What problem does this feature solve?

*The white BG doesn't respect my system wide dark mode settings*

### How should the feature work

*Launch BG should be in sync with system theme*

### Visual description

Current
![image](https://user-images.githubusercontent.com/10703445/87151557-b347c500-c2d1-11ea-946b-a1c96b9ab9aa.png)

Proposed
![image](https://user-images.githubusercontent.com/10703445/87151711-f86bf700-c2d1-11ea-8271-c596e3944f97.png)

This actually comes for a second till the BG is set when scrolling back from the hotkeys page.

**Comment by alin23** [comment]
Yes, I already tried a few dark designs when Mojave beta launched but I could not find something that I liked. 
Maybe I'll try again for the next release.

**Comment by alin23** [comment]
Unfortunately for others, I'll say pass on this.

First, I'd like to keep the colour coding of the pages (white - Display, yellow - Configuration, dark - Hotkeys)

Second, this is hard to do as Lunar uses hardcoded values and custom views as I had no idea what I was doing when I first started this.
