### ISSUE TITLE
Lunar Diagnostics Report [2F724E4869D432B156EAD1FA1F8D8120D4E4701B8FEA66CA061B82C3EE3D860D] [3.2.3]

### ISSUE THREAD

**Issue by quinncomendant** [alin23/Lunar#142]
# Issue details
- _Was the diagnostics process able to change the brightness on your external monitor(s)?_
No, nothing happened.

- _Mac device where Lunar is installed:_
2015 MBP 13"

- _Monitor connection to the Mac device:_
HDMI to a Sansui 4K TV.

- _Using an USB Docking Station or Hub:_
No

- _Lunar mode used (check it in the top-right corner of the Lunar interface)_
Manual (I tried all settings)

- _Does this utility work for you? https://github.com/kfix/ddcctl_
ddcctl also does nothing:

![Screen Shot 2020-07-11 at 11 47 42](https://user-images.githubusercontent.com/6884276/87229269-649b3900-c36c-11ea-81f9-8b66c4270890.png)

# Issue description:
I'm using my MBP in clamshell mode connected to a crappy 4K TV. ddcctl shows it is sending the DDC commands (successfully?) but nothing happens. Is there a trick for configuring a TV to allow external control of its settings?

**Comment by alin23** [comment]
Unfortunately, TVs don't support the monitor control commands needed for changing values like brightness/contrast/volume.
