### ISSUE TITLE
Lunar Diagnostics Report [B84FF1721A158D3DA33531EE7FC4F6223D45E42DEA28ACDA29C8B4C656275B65] [3.2.3]

### ISSUE THREAD

**Issue by glenngillen** [alin23/Lunar#144]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C, Hub, to miniDisplayPort, to Apple LED Cinema Display

- Using an USB Docking Station or Hub:
    Hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
Yes:

```
D: NSScreen #69521162 (1920x1200 0°) 94.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: 2A93404J0K0
I: got edid.name: LED Cinema
D: action: b: 19
D: setting VCP control #16 => 19
```

# Issue description:
Never changes the brightness. Have tested both sync and manual modes with zero success.

**Comment by alin23** [comment]
Hi! For Apple vendored displays Lunar uses a private macOS API to change the brightness in a more stable way. The detection is done based on the monitor name so you can just change the monitor name to something other than LED Cinema to fall back to the DDC method.

You can click on the monitor name in the Lunar UI to change it.

**Comment by cormacrelf** [comment]
No, this line would have to be `&&` for that to be the case.

https://github.com/alin23/Lunar/blob/6e58bd56a9a5c18dc4799cb0521f5f060ea5f55b/Lunar/Data/Display.swift#L322

**Comment by alin23** [comment]
Yep, a checkbox is a better idea for this. I guess that's why I added the `edidName` check, so users don't disable the feature by changing the name.

This will take some time though, I'm in a project crunch at my day job and can't afford to spend time on Lunar until that is finished.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
