### ISSUE TITLE
Lunar Diagnostics Report [4AD8CB5202E323EA2379004BF1182CD64DAF6A8E7D95A9302CA69884CD95A2D3] [3.2.3]

### ISSUE THREAD

**Issue by etienne-martin** [alin23/Lunar#147]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    nope

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI

- Using an USB Docking Station or Hub:
    Nope

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Tried all of them

# Issue description:
    I'm unable to change the brightness of my external monitor

**Comment by alin23** [comment]
Hi @etienne-martin ! Unfortunately I can't find the problem in the logs.

What Macbook Pro model are you using that still has a HDMI connector?
And what kind of monitor are you using?

Are you by any change using an HDMI to USB-C cable? Those can be hit or miss sometimes.

**Comment by etienne-martin** [comment]
Oh sorry I misinterpreted the question. I am in fact using a USB-C to HDMI cable. 

I have a MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) and my monitor is an ASUS PB278.

Thanks for looking into this. 

I will close the issue, feel free to reopen.
