### ISSUE TITLE
Unable to download the dmg file from official site

### ISSUE THREAD

**Issue by YuandaWang** [alin23/Lunar#15]
After clicking the "Download for Mac" button on "lunarapp.site", it shows a text file: version https://git-lfs.github.com/spec/v1
oid sha256:86de6cf6485c5a0de56d5f99f8bfeba470e14a5267a5bb8535bfb01e6d4a5acd
size 14402165

**Comment by tritethunder** [comment]
I have the exactly similar issue and If I try to upgrade the existing version from 2.1.2 to 2.3.0 it just failed.

**Comment by tritethunder** [comment]
![image](https://user-images.githubusercontent.com/555317/54725737-7c93eb80-4b70-11e9-9126-46307562ecbe.png)

**Comment by alin23** [comment]
This should be fixed now. I had to host the website somewhere else and I screwed up the routes a bit.

**Comment by tritethunder** [comment]
> This should be fixed now. I had to host the website somewhere else and I screwed up the routes a bit.

Thanks for the fix. working now.
