### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by zegangYang** [alin23/Lunar#157]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Hackintosh*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *Dell U2720QM*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *DisplayPort-to-DisplayPort*

- Using an USB Docking Station or Hub:
    *no*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*brightness set failed (monitor default brightness 31), the value always restore to 31 after any new value be set*

# log with debug mode on
```shell
17:39:23.278 💚 DEBUG PageController.setupHotkeys():181 - Setting up left and right arrow keys
17:39:23.278 💚 DEBUG AppDelegate.disableLeftRightHotkeys():118 - Unregistering left/right hotkeys
17:39:23.284 💚 DEBUG ModernWindowController.windowDidBecomeMain():18 - Requesting location permissions
17:39:25.521 💚 DEBUG DDC.getBrightness():565 - DDC reading brightness for 722478924
17:39:25.521 💚 DEBUG DDC.getValue():521 - DDC reading BRIGHTNESS for 722478924
17:39:25.561 💚 DEBUG DDC.getValue():521 - DDC reading CONTRAST for 722478924
17:39:25.601 💚 DEBUG DDC.getValue():521 - DDC reading AUDIO_SPEAKER_VOLUME for 722478924
17:39:25.640 💚 DEBUG DDC.getValue():521 - DDC reading AUDIO_MUTE for 722478924
17:39:28.797 💚 DEBUG AppDelegate.disableUpDownHotkeys():108 - Unregistering up/down hotkeys
17:39:28.797 💚 DEBUG ScrollableTextField.mouseEntered():144 - Registering up/down hotkeys
17:39:28.837 💚 DEBUG AppDelegate.disableUpDownHotkeys():108 - Unregistering up/down hotkeys
17:39:29.118 💚 DEBUG AppDelegate.disableUpDownHotkeys():108 - Unregistering up/down hotkeys
17:39:29.118 💚 DEBUG ScrollableTextField.mouseEntered():144 - Registering up/down hotkeys
17:39:30.245 💚 DEBUG AppDelegate.disableUpDownHotkeys():108 - Unregistering up/down hotkeys
17:39:30.245 💚 DEBUG ScrollableTextField.finishScrolling():222 - Changed CURRENT to 48.0
17:39:30.273 💜 VERBOSE Display.addObservers():586 - Set BRIGHTNESS to 48
["serial": "xxx", "name": "DELL U2720QM", "id": 722478924]
17:39:35.177 💚 DEBUG AppDelegate.applicationDidResignActive():354 - applicationDidResignActive
17:39:35.177 💚 DEBUG AppDelegate.disableUpDownHotkeys():108 - Unregistering up/down hotkeys
17:39:35.177 💚 DEBUG AppDelegate.disableLeftRightHotkeys():118 - Unregistering left/right hotkeys
17:39:35.684 💚 DEBUG DDC.getBrightness():565 - DDC reading brightness for 722478924
17:39:35.684 💚 DEBUG DDC.getValue():521 - DDC reading BRIGHTNESS for 722478924
17:39:35.724 💙 INFO Display.refreshBrightness():662 - Refreshing brightness: 48 <> 31
17:39:35.750 💜 VERBOSE Display.addObservers():586 - Set BRIGHTNESS to 31
["serial": "xxx", "name": "DELL U2720QM", "id": 722478924]
17:39:35.750 💚 DEBUG DDC.getValue():521 - DDC reading CONTRAST for 722478924
17:39:35.876 💚 DEBUG DDC.getValue():521 - DDC reading AUDIO_SPEAKER_VOLUME for 722478924
17:39:35.915 💚 DEBUG DDC.getValue():521 - DDC reading AUDIO_MUTE for 722478924
17:39:45.955 💚 DEBUG DDC.getBrightness():565 - DDC reading brightness for 722478924
17:39:45.955 💚 DEBUG DDC.getValue():521 - DDC reading BRIGHTNESS for 722478924
17:39:45.995 💚 DEBUG DDC.getValue():521 - DDC reading CONTRAST for 722478924
17:39:46.035 💚 DEBUG DDC.getValue():521 - DDC reading AUDIO_SPEAKER_VOLUME for 722478924
17:39:46.075 💚 DEBUG DDC.getValue():521 - DDC reading AUDIO_MUTE for 722478924
```

**Comment by alin23** [comment]
Hi @zegangYang ! 
You should probably disable the **Read external monitor brightness periodically** option as it doesn't work correctly for you and it always reads 31.
![CleanShot 2020-08-27 at 12 44 26@2x](https://user-images.githubusercontent.com/3819725/91424935-1fbb5b00-e863-11ea-802b-77d3714d293d.png)

**Comment by alin23** [comment]
Thanks for the coffee!! ☕

**Comment by zegangYang** [comment]
After I try your solution , I found only contrast can be adjusted,
The brightness can still not be adjusted manually.
And no error log in terminal
thanks for your reply.

**Comment by zegangYang** [comment]
I will try cl tool ddcctl later.

**Comment by alin23** [comment]
If you use Lunar in Manual mode, make sure to also have wide enough limits configured in the Lunar Configuration page:
![CleanShot 2020-08-27 at 12 59 23@2x](https://user-images.githubusercontent.com/3819725/91426424-2f3ba380-e865-11ea-90ce-1ab9aa6f6dd8.png)

If contrast works, there's no reason why brightness wouldn't work as well. I can only recommend restarting Lunar or reconnecting the monitor to your computer.

**Comment by zegangYang** [comment]
After I try ./ddcctl -d 1 -b 42 -c 6 in terminal.
Still the brightness could not adjusted.
Maybe the firmware of my monitor not compatible with ddccdl.
I will try upgrade my firmware.
Thanks a lot.

**Comment by alin23** [comment]
That's unfortunate, it's the first time I encounter a monitor that only responds to contrast messages. I hope you work it out in the end 😊

**Comment by zegangYang** [comment]
Finally ! 

The monitor firmware cause this issue.(`When DCI-P3 enabled`)

Here is my solution 

- monitor settings :  **color**-->**colorspace**-->**sRGB**

**Comment by alin23** [comment]
Good to know! I'll keep it in mind and maybe add it inside an information section on the website in the near future
