### ISSUE TITLE
Lunar Diagnostics Report [8B7FC6D719C49C61582D4696F9F3E5CF3C8301E3DFBD7D4776CD385046B67BB2] [3.2.3]

### ISSUE THREAD

**Issue by danielewood** [alin23/Lunar#163]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *One of them*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Mac Mini 2018*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C to DP for the working one, HDMI for the non-working one.*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Location*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*Cannot adjust HP Pavilion 32 over HDMI*

I switched both to use USB-C to DP, and it seems to work fine. 

Here is the diagnostics data for both on DisplayPort(Changes work on both): 
Lunar Diagnostics Report [8B7FC6D719C49C61582D4696F9F3E5CF3C8301E3DFBD7D4776CD385046B67BB2] [3.2.3]

**Comment by alin23** [comment]
Hi! Thanks for the report!

HDMI on Mac Mini is a known issue, I couldn't find the problem without access to a Mac Mini. I'll close this in favor of #125
