### ISSUE TITLE
Nothing happens when I open the app

### ISSUE THREAD

**Issue by j0hnsmith** [alin23/Lunar#166]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MacBook Pro (15-inch, 2018)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
LG 27UL850

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    *yes*, connected to monitor

- Lunar mode used (check it in the top-right corner of the Lunar interface)
no lunar interface

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
When I open the app nothing happens, I did the right click security thing. Can't see the app in dock, menu bar, activity monitor. Just nothing.

**Comment by alin23** [comment]
Check the first point of the Troubleshooting section: https://github.com/alin23/Lunar#troubleshooting

You probably have an older macOS version which doesn't come with Swift 5

**Comment by j0hnsmith** [comment]
Indeed, works now. Thanks
