### ISSUE TITLE
Lunar Feature - Brightness Matching

### ISSUE THREAD

**Issue by andrewphillipo** [alin23/Lunar#167]
### Brightness matching

I would like to be able to specify in 10% increments which brightness level the monitor has by comparison to the main screen. This would allow me to accurately to my eyes make sure that the two are not out of sync. This LG monitor at 100% is slightly brighter than the MacBook screen but at 50% on the MacBook that is maybe only 5% brightness on the screen!

Also in certain parts fo the brightness range there is colour shift when changing the brightness so it would be great to be able to correct this as well.

### What problem does this feature solve?

I want the monitor brightness to match the MacBook brightness at all settings.

### How should the feature work

We have Adaptive and Manual, an additional mode "Brightness Matching" could be added. Instead of the current screen with two ranges (why is contrast involved?) you have brightness and 10% increments (to represent what the MacBook is set to) on one side and the percentage you want the monitor to be on the other. People could be allowed to share config options for different monitor/macbook screen combinations.

Happy to draw a screen for this if you like the idea.

### Visual description

I will add a design in a bit then...

**Comment by alin23** [comment]
Hi! Thanks for the feature request!

> We have Adaptive and Manual, an additional mode "Brightness Matching" could be added. Instead of the current screen with two ranges (why is contrast involved?)

Contrast is a very useful setting for people with low vision, and I also like to have the contrast as low as 30 at night.
If you don't need contrast to change you can lock the value:

![image](https://user-images.githubusercontent.com/3819725/91991718-e9d31680-ed3b-11ea-9ae9-ddea14f247fa.png)


> I want the monitor brightness to match the MacBook brightness at all settings.

I was hoping that this could be achieved in Sync mode using the Limits, Offsets and the Brightness Clipping settings:

![image](https://user-images.githubusercontent.com/3819725/91991637-cf00a200-ed3b-11ea-80e6-c67f8896fe33.png)
![image](https://user-images.githubusercontent.com/3819725/91991692-e2137200-ed3b-11ea-8c92-14ad7910903b.png)

You can adjust those values until you get exactly the curve you want. For example, a -25 value for the brightness offset will map 50% brightness on the builtin display to about 5% brightness on the external monitor, and everything in between will just follow the curve:

![CleanShot 2020-09-02 at 16 51 06@2x](https://user-images.githubusercontent.com/3819725/91992467-d8d6d500-ed3c-11ea-8337-39b248252492.png)

And for the slightly higher brightness on the external monitor you can limit the brightness to what feels the same as the 100% value on the builtin display.

![image](https://user-images.githubusercontent.com/3819725/91992712-20f5f780-ed3d-11ea-998e-e04e48dfcf48.png)

**Comment by andrewphillipo** [comment]
Sorry you've nailed it already thanks!
