### ISSUE TITLE
Clicking on Location Mode dialog opens ipstack.com

### ISSUE THREAD

**Issue by rootulp** [alin23/Lunar#169]
Bug report:

1. Click anywhere in the Location Mode dialog
<img width="435" alt="Screen Shot 2020-09-02 at 11 30 25 AM" src="https://user-images.githubusercontent.com/3699047/92004028-b67a9280-ed0f-11ea-89aa-aed401fea23e.png">

2. Observe that ipstack.com is opened.

**Comment by alin23** [comment]
Thanks for the report! 

This is intended, I implemented it this way because it's the only way I can have links (actually only one link) in the popups.
It's a limitation of NSPopover+Markdown and I don't want to spend any more time trying to work around it.
