### ISSUE TITLE
Option not to change contrast

### ISSUE THREAD

**Issue by krystof-k** [alin23/Lunar#17]
I've got a problem with my Dell UP2516D. There is a feature called _uniformity compensation_ that modifies contrast according to brightness automatically. However Lunar in the adaptive mode always tries to override the contrast and I'm getting annoying alerts all the time.

![IMG_3008](https://user-images.githubusercontent.com/11633481/54866596-124c9800-4d76-11e9-9ee8-cba16b3e5056.JPG)

It'd be great to be able to choose whether I want to modify only brightness/contrast or both.

**Comment by alin23** [comment]
There is a Lock button under the brightness/contrast limits that you can click to enable the feature you want.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/3819725/54867067-c9501000-4d84-11e9-8fcb-da30175e2a1f.png">

**Comment by krystof-k** [comment]
Yes, but this still triggers the DDC/CI request and therefore causes the dialog.

**Comment by alin23** [comment]
Oh I see now. I'll release an update with a fix for this in a few minutes

**Comment by krystof-k** [comment]
Awesome!

**Comment by alin23** [comment]
Please try the latest update (2.3.2)

**Comment by krystof-k** [comment]
Works perfectly! You're incredible. 👍 Thanks!

**Comment by alin23** [comment]
Wow, that was fast! You welcome!
