### ISSUE TITLE
Interactive chart for adjusting brightness curve

### ISSUE THREAD

**Issue by a-b** [alin23/Lunar#170]
### Name of the feature

Interactive graph/chart

### What problem does this feature solve?

Visualize brightness/contrast settings. Let users adjust them by dragging the slider on the chart.

### How should the feature work

The graph on the preferences panel should have a slider that shows current settings.
In the manual mode, I can drag it to adjust settings interactively.

### Visual description

<img width="1062" alt="Screen Shot 2020-09-02 at 9 28 05 AM" src="https://user-images.githubusercontent.com/585662/92010696-f5541c80-ecfe-11ea-9807-3db03c0ac825.png">

**Comment by alin23** [comment]
That sounds cool but I have no idea how I could do that 😅

If you want to help, PRs are welcome!

**Comment by alin23** [comment]
I looked into this but it is waaay too hard to do.

In **Lunar 4** you can adjust the curve easier by just setting the external monitor brightness to what you'd like it to be, and Lunar will learn from that. More details about that here: https://lunar.fyi/#curve

You can download it from the official website: https://lunar.fyi

If you have other issue, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
