### ISSUE TITLE
Lunar Diagnostics Report [394B6505118CFA4DD733A84F71B8E37E5F8EAA7B9820220A21B38A4DDCC7C659] [3.2.3]

### ISSUE THREAD

**Issue by mazhead** [alin23/Lunar#171]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    On one yes (USB-C) on the 2nd one not (thunderbolt display connected via apple usb-c adapter)

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacMini 2020

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Dell Monitor via USB-C -> no issues, Thunderbolt display via Thunderbolt->USB-C adapter.

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Tested all 3. Currently using Location.

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    Yes works without issue:

./ddcctl -d 2 -b 1 
D: NSScreen #722491853 (1920x1080 0°) 82.00 DPI
D: NSScreen #69508288 (2560x1440 0°) 109.00 DPI
I: found 2 external displays
I: polling display 2's EDID
I: got edid.serial: <redacted>
I: got edid.name: Thunderbolt
D: action: b: 1
D: setting VCP control #16 => 1

./ddcctl -d 2 -rbc 
D: NSScreen #722491853 (1920x1080 0°) 82.00 DPI
D: NSScreen #69508288 (2560x1440 0°) 109.00 DPI
I: found 2 external displays
I: polling display 2's EDID
I: got edid.serial: <redacted>
I: got edid.name: Thunderbolt
D: action: rbc: 1
D: setting VCP control #5 => 1

# Issue description:
Dell monitor works without issue -> all settings.
Thunderbolt display does not react on any settings change in Lunar, via the ddcctl or via the system settings I have a fast response. The display light sensor also works (covering it the display changes brightness). I also tested to turn off the adaptive brightness in system preferences but no change -> lunar changes are not reflected.

**Comment by alin23** [comment]
This is related to the special treatment of Apple vendored displays. I'll add a checkbox to disable that in the next update

**Comment by mazhead** [comment]
Tried this scenario:
Renamed the display to something else to use the ddcctl. Unchecked "automatically adjust brightness" in system preferences. Restarted Lunar. 
Lunar now reports higher numbers by the thunderbolt display. If I change the brightness -> Lunar crashes.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
