### ISSUE TITLE
Lunar Diagnostics Report [42DCE54F4D3EE6D6DDD6275FD154FAD2E828D339ACC1BF871D4D6B8331BB6319] [3.2.3]

### ISSUE THREAD

**Issue by dougc84** [alin23/Lunar#172]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
2018 Mac Mini (i5, base specs)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB-C to USB-C

- Using an USB Docking Station or Hub:
No, though the monitor does have an integrated hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
Nope.  If I try running it, I get the following:

```
./ddcctl -d 1 -b 1
D: NSScreen #459130944 (2560x1080 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
E: Failed to poll display!
```

# Issue description:
I've used Lunar for a long time with my MacBook Pro 2018 and an LG 5K2K (34WK95U) monitor, due to the lack of system-integrated brightness and contrast controls.  My battery is bloating, and I need to send it in for repair.  In the meantime, since I need to continue working, I (reluctantly spent more money than I have and I) picked up a 2018 Mac Mini.  I installed Lunar and it pops up **Non-responsive DDC** after adjusting the brightness or contrast.  It moves a couple notches, and the error pops up with a lock icon on the OSD.  If I hit reset, the same thing occurs.

**Comment by alin23** [comment]
I had so many users report issues on the Mac Mini that I'm starting to think it might need special treatment. I really hope to get access to one in the following months. It's weird to also have issues with the USB-C connection, usually only the HDMI one has problems.

What kind of hub does your monitor have, maybe there's a problem on that side? Until you get ddcctl working, Lunar won't work as it uses the same code as ddcctl for passing messages to the monitor.

**Comment by dougc84** [comment]
@alin23 The hub is built into the monitor.  Since it's a USB-C connection, it provides two USB-A (2.0, I think) ports, and the USB-C gets converted to DisplayPort internally.  I've tried DP1.2 and 1.4 on the monitor (there is no 1.3 setting) and they both have the same issue.

I've seen similar issues across the web, and most say that only a USB-C to HDMI cable works.  Unfortunately, I don't (think) I have one of those.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
