### ISSUE TITLE
Lunar Diagnostics Report [46281ABF3D1E833477F7DE9F88714D05E530D60573A7C37D562D6D80D370FED8] [3.2.3]

### ISSUE THREAD

**Issue by 24khxn** [alin23/Lunar#174]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No, one monitor was not changed. 

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   Macbook Pro 16"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to HDMI to both monitors

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Location? I believe

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    Using both `./ddcctl -d 2 -b 100` and `./ddcctl -d 1 -b 100` affect the same external monitor, even though it correctly identifies two external monitors

# Issue description:
Explained in my attempt to use ddcctl, it seems like modifying the brightness on "either" screen will only modify one of my monitors. I am running two Samsung S32D850 monitors, tried plugging the HDMI in both sides of my computer to no avail.

**Comment by alin23** [comment]
Most likely the USB hub/dock is the issue. If you can try connecting the second monitor directly

**Comment by 24khxn** [comment]
Spot on, thank you! Unfortunate though, really liked the app.
