### ISSUE TITLE
Lunar Diagnostics Report [B9E343044785753B98CE8A4B57A460DA3E7A391C2BC53A0C77B2F3CD80685932] [3.2.3]

### ISSUE THREAD

**Issue by bitigchi** [alin23/Lunar#175]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MBP 2018, 13"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
Samsung s22f350, HDMI to USB-C

- Using an USB Docking Station or Hub:
Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
None of the modes work

- (only if you know how to compile a C program) Does this utility work for you? 
```shell
▶ ./ddcctl.sh
D: NSScreen #188943542 (1920x1080 0°) 102.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: S22F350
I: got edid.serial: H4ZJ800688
D: action: b: 42
D: setting VCP control #16 => 42
E: Failed to send DDC command!
D: action: c: 26
D: setting VCP control #18 => 26
E: Failed to send DDC command!
D: NSScreen #188943542 (1920x1080 0°) 102.00 DPI
I: found 1 external display
```

# Issue description:
Lunar does not seem to have any effect on my external monitor.
I can manually adjust the brightness, it's not a big deal, but it would be nice to be able to use Lunar.

Thank you very much for your labour!

**Comment by alin23** [comment]
Hi @bitigchi ! Looks like a hardware connection problem if ddcctl can't send commands to the monitor.

Try one of the following:
* Skip the dock/hub and connect the monitor directly to the Macbook
* Use a different connector on your monitor (DisplayPort, Thunderbolt etc.)
* Try different cables
