### ISSUE TITLE
Lunar Diagnostics Report [7BD251D185721B97FF99962D9600B7E907B9923EEB5A710D8FB4C107BC42EA2D] [3.2.3]

### ISSUE THREAD

**Issue by JonathanHuot** [alin23/Lunar#176]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MBP 2016

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C

- Using an USB Docking Station or Hub:
   DisplayLink Docking Station

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Tried all

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    
$ ./ddcctl -d 1 -b 10
```
D: NSScreen #4128833 (2560x1440 0°) 72.00 DPI
D: NSScreen #4128832 (1920x1080 0°) 72.00 DPI
I: found 2 external displays
I: polling display 1's EDID
E: Failed to poll display!
```

# Issue description:

No brightness change on my two different external monitors, but both are plugged into smae docking station "DisplayLink" in USB-C.

**Comment by alin23** [comment]
Hi @JonathanHuot ! Unfortunately DisplayLink doesn't provide support for DDC messages in their macOS drivers. They only support that on Windows as you can see here: https://displaylink.org/forum/showthread.php?t=65289 https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/16135240-add-brightness-support-to-non-windows-oses
