### ISSUE TITLE
Lunar Diagnostics Report [B0E9F93F978C18540862A9F0636DE8B0BB2481B5760C1FB14093CCB894430F47] [3.2.3]

### ISSUE THREAD

**Issue by stfairy** [alin23/Lunar#177]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    I have two identical monitors, ASUS MG28UQ.  The diag process only changed one of them.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    I connect both monitors to a KVM (StarTech SV231DPDDUA2) with DisplayPort-to-DisplayPort cables.  From the KVM, there is a DisplayPort-to-USB-C cable to one of the Thunderbolt port on MacBook, and then a DisplayPort-to-DisplayPort cable to an adapter (CableMatters 201055) which plugs into another MacBook Thunderbolt port directly.  Power is delivered through this adapter.  Two USB-A cables are plugged into the adapter as well, so it acts as a USB hub.

- Using an USB Docking Station or Hub:
    yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    No, it doesn't seem to work either.  It detects two monitors, but failed to send DDC command to one of them (the one that Lunar couldn't change).

```
% ./ddcctl -d 1 -b 20
D: NSScreen #441084854 (2560x1440 0°) HiDPI
D: NSScreen #441057885 (2560x1440 0°) HiDPI
I: found 2 external displays
I: polling display 1's EDID
I: got edid.name: ASUS MG28U
D: action: b: 20
D: setting VCP control #16 => 20
% ./ddcctl -d 2 -b 20
D: NSScreen #441084854 (2560x1440 0°) HiDPI
D: NSScreen #441057885 (2560x1440 0°) HiDPI
I: found 2 external displays
I: polling display 2's EDID
I: got edid.name: ASUS MG28U
I: got edid.name: æþ
D: action: b: 20
D: setting VCP control #16 => 20
E: Failed to send DDC command!
```

# Issue description:
With two external monitors, Lunar was only able to change the brightness of one of them.

**Comment by alin23** [comment]
Hi @stfairy ! The problem here is that there are too many layers of indirection between your Macbook and the monitors.
This is a hardware connection issue and you can only solve it by connecting one of the monitors directly to your Macbook and bypassing the KVM and the CableMatters adapter.
You could try bypassing just the CableMatters adapter for a first try to see if that fixes the issue.

I'll close this as I can't do anything to fix it in Lunar, but feel free to post updates here.
