### ISSUE TITLE
Lunar Diagnostics Report [AED0A8FC7837BF7A9112ECB72FA02C51596FC0C341365CFE687CDDC39E1EAB2B] [3.2.3]

### ISSUE THREAD

**Issue by lchao1** [alin23/Lunar#178]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no. the values change on the app but the actual brightness does not

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MBP Pro 2019 (16 inch)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   Displayport to USB C

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
It used to work fine but stopped working recently, not sure what changed. I did not install any other brightness/display programs or change the connection cable. The values can be changed on the app but the monitor brightness does not actually change anymore.

**Comment by alin23** [comment]
Can you check in your monitor settings to see if DDC/CI is enabled?
All I can recommend is.. restart the system and/or reconnect the monitor to different ports on your Macbook.

I'll close this as it is not related to a bug in Lunar but feel free to post updates here.
