### ISSUE TITLE
Lunar Diagnostics Report [488744338FB9CEF4773DBC0DC2A1AB44C5368D7B9154F0C6BB238F4431BB0830] [3.2.3]

### ISSUE THREAD

**Issue by OliverPearmain-Triller** [alin23/Lunar#179]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No, I cannot get any settings to change

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (Retina, Mid 2012) 15"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI to HDMI (I've also tried a DisplayPort-to-HDMI cable)

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    I've tried them all, none of them alter any settings

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    I've not yet tried it, I will endevour to do so and report back. 

# Issue description:
I am able to alter any settings on my monitor :-(
Is it possible that my monitor simply doesn't support DDC, it's an LG DM2780D?

**Comment by alin23** [comment]
Most of the TV monitors don't support DDC commands. I see your monitor is advertised as a monitor TV so it's possible that it doesn't support this.

I'll close this as it is a hardware issue, feel free to post any updates.
