### ISSUE TITLE
Lunar Diagnostics Report [84816EE2F9A0ADE09E8EBB221986EE6B07A10E7F6F72DE72E7C422020967039B] [3.2.3]

### ISSUE THREAD

**Issue by kismetthebear** [alin23/Lunar#180]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mac Mini (2018)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI

- Using an USB Docking Station or Hub:
    USB hub in monitor used for mouse & keyboard.  Direct HDMI connection for display signal from Mac Mini to monitor.

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual.

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Lunar does not appear to work at all with my combination of Mac and monitor, at least, not over HDMI, over which Dell claims to support DDC.  I confirmed that DDC is on.  The monitor in question is a Dell U3415W.

**Comment by alin23** [comment]
The Mac Mini is the issue here, the HDMI connection on it doesn't seem to send the DDC messages correctly. I've had multiple users report that.

Try a different connector on the Mac Mini if possible.

**Comment by kismetthebear** [comment]
Thanks for your prompt reply.  You were correct:  DisplayPort via one of the Thunderbolt ports does work.  Bought you some coffee.
