### ISSUE TITLE
Lunar Diagnostics Report [07F7E1DF47F341D98B18550FAAAB978875AFF4B6A25A543E645479B78B47464B] [3.2.3]

### ISSUE THREAD

**Issue by rikur** [alin23/Lunar#181]
# Issue details

- Was the diagnostics process able to change the brightness on your external monitor(s)?
  Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MBP 16"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-DisplayPort

- Using an USB Docking Station or Hub:
   HDMI used Apple dongle

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Duplicates a display for HDMI/DisplayPort and HDR enabled/disabled. I also have a monitor called "Solar" that I have no idea what it is. There is no way to delete displays.

**Comment by rikur** [comment]
Ugh I take that back, figured out how to delete displays.

**Comment by alin23** [comment]
I admit this functionality needs to be more obvious. I'm working on more UI improvements for the next update, thanks for letting me know I should also work on this one.

**Comment by rikur** [comment]
Thank you for such an important app! Sent a few coffees your way.
