### ISSUE TITLE
Lunar Feature: make dev don't support new sourcery version

### ISSUE THREAD

**Issue by whlsxl** [alin23/Lunar#183]
After run `make dev` I got an error
```
bash /Users/whl/Documents/source/macos/Lunar/gencode.sh
error: while reading .yml '.sourcery.yml'. 'The element XCRemoteSwiftPackageReference is not supported'
while reading .yml '.sourcery.yml'. 'The element XCRemoteSwiftPackageReference is not supported'make: *** [Lunar/Generated/Secrets.generated.swift] Error 2
```
Looks like an error from sourcery, does sourcery necessary?

**Comment by alin23** [comment]
Yes sourcery is important, and yes that's a problem with sourcery where it doesn't have support for Swift Packages.

You can try creating the `.sourcery.yml` manually for now with the following contents:

```yaml
project:
  file: Lunar.xcodeproj
  target:
    name: Lunar
templates:
  - Lunar/Templates
output:
  path: Lunar/Generated
args:
  appSecret: ${SB_APP_SECRET}
  encryptionKey: ${SB_ENCRYPTION_KEY}
  sentryDSN: ${SENTRY_DSN}
  analyticsHash: ${ANALYTICS_HASH}
```

**Comment by whlsxl** [comment]
This file is already in the root path 
https://github.com/alin23/Lunar/blob/master/.sourcery.yml

**Comment by alin23** [comment]
Oh right.. then maybe it would be useful to comment line 6 in https://github.com/alin23/Lunar/blob/master/gencode.sh#L6

**Comment by whlsxl** [comment]
But compile still need `Lunar/Lunar/Generated/Secrets.generated.swift` 😅

**Comment by alin23** [comment]
Here's a stub for that `Secrets.generated.swift`:
```swift
public struct Secrets {
    let appSecret: String
    let encryptionKey: String
    let sentryDSN: String
    let analyticsHash: String
}

public let secrets = Secrets(
    appSecret: "",
    encryptionKey: "",
    sentryDSN: "",
    analyticsHash: ""
)
```

**Comment by whlsxl** [comment]
Big thanks!
Carthage not support swift 3.0 for now, build `NSPageControl`, got error.
