### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by kevinstratt** [alin23/Lunar#185]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   MacBook Pro 2016, 2018

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell P2415Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   UBC-C-Displayport 

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *All*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   Yes

# Issue description:
 
With the dell monitor specified, lunar will only reach 90% brightness using the software. To get the display to be at 100% I have to use the monitor's utility menu. 

Lunar maps the brightness perfectly to all other displays I and my team have, just this one isn't working. 

It does map at every other stop correctly until 90. Setting a brightness of higher than 90 in lunar doesn't do anything on the monitor. For example, if I set it to 43%, the monitor shows 43% just fine. Just gets stuck at 90. 

Thank you so much for designing this program. I searched for a way to do this until I found Lunar, and have used it since beta with no problems. I honestly haven't had any of the problems in the troubleshooting at all, even on 6 monitor setups of the Mac pros. 

I assume I have always been lucky with adapters, cables, docks, etc., because we haven't seen anything. I have tried using other cables and dongles for this monitor, even on HDMI it does the same thing.

**Comment by amrwc** [comment]
I have the same issue on Dell S2340L. Maybe it's Dell-specific?

**Comment by alin23** [comment]
Hi!

I'm not sure what Lunar mode you're having this issue with, but if you're using Manual mode, there's a separate global limit in the configuration page:
![image](https://user-images.githubusercontent.com/3819725/94112846-af4a2e80-fe4e-11ea-9bb5-8e1c9a95bc13.png)

If you're using Sync or Location mode, the only limits are those on the left and right side of the monitor image:
![image](https://user-images.githubusercontent.com/3819725/94113241-41523700-fe4f-11ea-813a-7c35b30bfd92.png)

If none of these are limiting your brightness to 90, then it's possible your monitor has either an internal limit or a more extended range. You can try enabling **Extended Range** (the button near the **Adaptive** button under the monitor image).

If that still doesn't work, try to see if this ddcctl command sets the command to 95: `ddcctl -d 1 -b 95`
