### ISSUE TITLE
what are 'lunatic' and 'solar' and 'celestial' entries?

### ISSUE THREAD

**Issue by thisisjamessmith** [alin23/Lunar#186]
Hiya, more of a question than an issue but I see these items listed as monitors when hovering over the menu bar icon - what are these phantom monitors?? 

Also, thank you very much for this app, it's great!

**Comment by alin23** [comment]
When the system has an error reading the monitor firmware data and gives Lunar an invalid text for the monitor name, Lunar generates a random name from a predefined list.

You probably have those monitors remaining from when the connection between your device and the monitor failed for a few seconds. You can simply delete them manually from the quick actions menu by hovering over the Lunar icon in the menu bar.
