### ISSUE TITLE
Lunar Diagnostics Report [E0350C2C3AAF66B4315F436D0D36948B649B3A4E9509A60ECAA32C870F735C99] [3.2.3]

### ISSUE THREAD

**Issue by cwerner1** [alin23/Lunar#189]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
  No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 13", 2016 

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-DisplayPort

- Using an USB Docking Station or Hub:
  no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
 sync

- (only if you know how to compile a C program) Does this utility work for you? 

- [ ] https://github.com/kfix/ddcctl
  ddctl allows me to run  -rbc (reset brightness and contrast), also does switch the input  (-i)
but it doesnt set contrast or brightness by value

# Issue description:

AOC U2790B 
Brightness and Contrast is not possible to set

**Comment by alin23** [comment]
If ddcctl does not work, it's either an issue with the monitor (no support for DDC writes) or with the connection (try another connector on the monitor maybe?).

Lunar uses the same DDC implementation as ddcctl, so if that doesn't work, Lunar can't work either.

I'll close this as it isn't a bug in Lunar, feel free to post updates on what you've tried and what results you get.

**Comment by cwerner1** [comment]
I managed to get ddcctl and lunar working, with the same connector.

Settings at the monitor to set:  
**Luminance**
  * Eco mode:  _Standard_ 
  * DCR:  _Off_
