### ISSUE TITLE
Not working with multiple displays

### ISSUE THREAD

**Issue by simPod** [alin23/Lunar#19]
I have 3 external displays, Lunar however controls brighness only on one of them.

Can I help debug somehow?

**Comment by alin23** [comment]
Are those 3 displays of the same model? Lunar tries to create a unique ID for each monitor using hardware data it can read like serial numbers, date of fabrication etc. 
But for some monitors this data is just zeroes so Lunar sees monitors of the same model as just one.

**Comment by simPod** [comment]
Yes, they are the exact same one. Can close if not fixable as my hw may be incompatible :)

**Comment by alin23** [comment]
I would love to fix this problem but I can't debug it because I don't have access to multiple monitors of the same kind. Would you like to do some remote debugging?

For the beginning I could send you a part of Lunar that does the hw data extraction to see if there is anything different between the monitors that we could use.

**Comment by simPod** [comment]
Sure thing, bring it on

**Comment by alin23** [comment]
Download the binary here: [EDIDReader](https://media.githubusercontent.com/media/alin23/Lunar/master/bin/EDIDReader)

Run it in the terminal and redirect the output to a file with something like:
```shell
./EDIDReader > /tmp/edid.log
```

And upload that file to a pastebin or something and paste the link here.
Don't worry, the data is nothing sensitive or personal. Just manufacturer data.

I also uploaded the code here if you want to take a look or compile it yourself: https://github.com/alin23/Lunar/tree/master/EDIDReader/EDIDReader

**Comment by alin23** [comment]
@simPod It would be great if you could run the tool multiple times with different brightness/contrast settings per monitor to see if that changes the output.

Something like:
1. Set brightness and contrast to 50 for all the monitors
2. Run `./EDIDReader > /tmp/edid_b50_c50.log`
3. Set brightness to 25 and contrast to 75 for all the monitors
4. Run `./EDIDReader > /tmp/edid_b25_c75.log`
5. Set brightness and contrast to 
    - 10 for monitor 1
    - 20 for monitor 2
    - 30 for monitor 3
6. Run `./EDIDReader > /tmp/edid_b102030_c102030.log`

**Comment by simPod** [comment]
@alin23 hey, one issue when running:

```dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/simonpodlipsky/Downloads/./EDIDReader
  Reason: image not found
fish: './EDIDReader > /tmp/edid_b50_c5…' terminated by signal SIGABRT (Abort)```

maybe https://stackoverflow.com/a/25772532/519333?

**Comment by alin23** [comment]
Ok, I built it with the embed flag. Try downloading again from the same link

**Comment by alin23** [comment]
@simPod please try the latest update (v2.3.3) to see if it fixes your problem. 

**Note:** If the update fails, quit and relaunch Lunar to force a signature refetch. I had an issue with the signatures earlier today.

**Comment by simPod** [comment]
@alin23 On it. I had no access to those screens during weekend, sorry.

**Comment by alin23** [comment]
No problem! Let me know if it works ^_^

**Comment by simPod** [comment]
@alin23 it still controls only one screen of those 3 🤔 will send you logs we talked about on friday?

**Comment by alin23** [comment]
Yes, I'd like to see those logs. I'm still puzzled about this issue

**Comment by simPod** [comment]
Still having the issue even with EDIDReader version

```dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/simonpodlipsky/Downloads/./EDIDReader
  Reason: image not found```

But seems like it's still something in that bin rather in my pc

**Comment by alin23** [comment]
Isn't there another line above the `Referenced from` line? I don't see what is missing

**Comment by simPod** [comment]
Upgraded software and suddently it works
[edid_b25_c75.log](https://github.com/alin23/Lunar/files/3028895/edid_b25_c75.log)
[edid_b50_c50.log](https://github.com/alin23/Lunar/files/3028896/edid_b50_c50.log)
[edid_b102030_c102030.log](https://github.com/alin23/Lunar/files/3028897/edid_b102030_c102030.log)

**Comment by alin23** [comment]
@simPod 
Seems that my way of extracting EDID data is flawed. 
Can you provide me with the output of the following command?
```shell
ioreg -lw0 | grep IODisplayEDID 
```

This should output the EDID data as seen by the system

**Comment by simPod** [comment]
```
$ ioreg -lw0 | grep IODisplayEDID

    | |   |   | |           "IODisplayEDID" = <00ffffffffffff00061030a00000000026190104b5211578020f45ae5243b0260e4f54000000010101010101010101010101010101017c804050b0083470082068084bcf1000001a000000100000000000000000000000000000000000fc00436f6c6f72204c43440a202020000000100000000000000000000000000000000d>
    | |   |   | |           "IODisplayEDID" = <00ffffffffffff0009d117804554000033180103804728782e4180a7554ea0250c5054a56b8081c081008180a9c0b300d1c001010101565e00a0a0a0295030203500c48e2100001a000000ff004643453035383433534c300a20000000fd00324c1e581b000a202020202020000000fc0042656e5120424c333230300a2001d5020325f15090050403020111121314060715161f202309070767030c001000383683010000023a801871382d40582c4500c48e2100001f011d8018711c1620582c250055502100009f011d007251d01e206e28550055502100001e8c0ad08a20e02d10103e96005550210000180000000000000000000000000000000000000a>
    | |   |   | |           "IODisplayEDID" = <00ffffffffffff0009d11780455400000c1a0103804728782e4180a7554ea0250c5054a56b8081c081008180a9c0b300d1c001010101565e00a0a0a0295030203500c48e2100001a000000ff005733473032303539534c300a20000000fd00324c1e581b000a202020202020000000fc0042656e5120424c333230300a2001fb020325f15090050403020111121314060715161f202309070767030c001000383683010000023a801871382d40582c4500c48e2100001f011d8018711c1620582c250055502100009f011d007251d01e206e28550055502100001e8c0ad08a20e02d10103e96005550210000180000000000000000000000000000000000000a>
    | |   |   | |           "IODisplayEDID" = <00ffffffffffff0009d117804554000033180103804728782e4180a7554ea0250c5054a56b8081c081008180a9c0b300d1c001010101565e00a0a0a0295030203500c48e2100001a000000ff004643453035383437534c300a20000000fd00324c1e581b000a202020202020000000fc0042656e5120424c333230300a2001d1020325f15090050403020111121314060715161f202309070767030c001000383683010000023a801871382d40582c4500c48e2100001f011d8018711c1620582c250055502100009f011d007251d01e206e28550055502100001e8c0ad08a20e02d10103e96005550210000180000000000000000000000000000000000000a>
```

**Comment by alin23** [comment]
Ok, I think I'm getting somewhere. So in that hex data I can see some very slight differences. Most notably between the bytes 77 and 90:
```
1: 4643453035383437534c300a20

2: 5733473032303539534c300a20

3: 4643453035383433534c300a20
```

Which in ASCII is:
```
FCE05847SL0
W3G02059SL0
FCE05843SL0
```

These look like model numbers or something. But at least it's something that is unique for each monitor and hardcoded.

I've made some changes to the EDIDReader to see if I can extract the same data that `ioreg` gives us. Please download it again from [this link](https://media.githubusercontent.com/media/alin23/Lunar/master/bin/EDIDReader) and run it only once, the brightness/contrast doesn't matter now.

**Comment by simPod** [comment]
There you go

[lunar.log](https://github.com/alin23/Lunar/files/3030327/lunar.log)

**Comment by alin23** [comment]
@simPod Thanks for all the debugging you did! It really helped.

I have an alpha version for the multi-monitor support that I'd like you to try: https://send.firefox.com/download/5148f724e23184d8/#jUUW-Bnfhf1rrf0-5Oss_g

I had to rewrite the whole DDC implementation from C to Swift so it might not work perfectly from the first time. 

This thing is so hard to do because:
1. Vendors don't write all the monitor identification data that can differentiate between displays
2. Apple has deprecated some very useful APIs without giving us any replacement

So I had to do a lot of device tree traversal and matching just to get some unique IDs that don't change between login sessions. Even if this version doesn't work, I'm confident we're close to the solution.

**Comment by simPod** [comment]
@alin23 now it doesn't control any screen 🤔 Changing values has no effect

**Comment by alin23** [comment]
Can you send me the Lunar log? You can find it here: `~/Library/Caches/Lunar/swiftybeaver.log`

**Comment by simPod** [comment]
@alin23 yup. removed it, then relaunched and tried to change brightness

```13:57:02.205 DEBUG DataStore.init():200 - Checking First Run
13:57:02.363 DEBUG AppDelegate.manageBrightnessAdapterActivity():220 - Started BrightnessAdapter in Location mode
13:57:02.364 WARNING BrightnessAdapter.adaptBrightness():272 - Day moments aren't fetched yet
13:57:02.395 WARNING BrightnessAdapter.adaptBrightness():272 - Day moments aren't fetched yet
13:57:02.403 DEBUG AppDelegate.applicationDidFinishLaunching():379 - App finished launching
13:57:02.450 DEBUG BrightnessAdapter.fetchMoments():176 - Getting moments for 2019-04-03 13:57:02 +0000
13:57:02.458 DEBUG BrightnessAdapter.fetchMoments():179 - Computed moment from Solar
13:57:02.458 DEBUG AppDelegate.locationManager():399 - Zero LocationManager coordinates
13:57:02.458 DEBUG BrightnessAdapter.fetchMoments():176 - Getting moments for 2019-04-03 13:57:02 +0000
13:57:02.465 DEBUG BrightnessAdapter.fetchMoments():179 - Computed moment from Solar
13:57:15.284 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 10.0
13:57:15.285 DEBUG Display.addObservers():210 - Celestial: Set brightness to 10
13:57:15.627 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 30.0
13:57:15.628 DEBUG Display.addObservers():210 - Celestial: Set brightness to 30
13:57:16.556 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 36.0
13:57:16.556 DEBUG Display.addObservers():210 - Celestial: Set brightness to 36
13:57:17.049 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 44.0
13:57:17.050 DEBUG Display.addObservers():210 - Celestial: Set brightness to 44
13:57:17.501 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 71.0
13:57:17.502 DEBUG Display.addObservers():210 - Celestial: Set brightness to 71
13:57:17.768 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 54.0
13:57:17.769 DEBUG Display.addObservers():210 - Celestial: Set brightness to 54
13:57:17.925 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 45.0
13:57:17.926 DEBUG Display.addObservers():210 - Celestial: Set brightness to 45
13:57:19.654 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 47.0
13:57:19.655 DEBUG Display.addObservers():210 - Moony: Set brightness to 47
13:57:20.199 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 48.0
13:57:20.200 DEBUG Display.addObservers():210 - Moony: Set brightness to 48
13:57:20.475 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 51.0
13:57:20.476 DEBUG Display.addObservers():210 - Moony: Set brightness to 51
13:57:20.762 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 58.0
13:57:20.763 DEBUG Display.addObservers():210 - Moony: Set brightness to 58
13:57:20.955 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 47.0
13:57:20.956 DEBUG Display.addObservers():210 - Moony: Set brightness to 47
13:57:21.337 DEBUG ScrollableTextField.scrollWheel():207 - Changed CURRENT to 25.0
13:57:21.338 DEBUG Display.addObservers():210 - Moony: Set brightness to 25
13:57:24.356 INFO AppDelegate.applicationWillTerminate():383 - Going down
13:57:24.359 INFO ModernWindowController.windowWillClose():27 - Window closing```

**Comment by alin23** [comment]
Ok, I have no idea where to start debugging this 😅 

Some questions:
1. Do you have a Macbook with 2 GPUs?
2. Does Lunar detect 3 displays?
3. Can you send me an IORegistry dump file?
    1. Download the Xcode tools here: https://send.firefox.com/download/51129df2bfffd98d/#xmI2l_cV-26HLmDK4czdoQ
    2. Open the DMG, go to Hardware folder and launch IORegistryExplorer
    3. Press <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> to save the dump

Meanwhile, I'll prepare a heavily logged version for you to try because the current log doesn't give me any information.

Let me know if you don't have time for this, I know it's pretty tedious for you to do this.

**Comment by alin23** [comment]
Here's the version with updated logging: https://send.firefox.com/download/b0c91fc2e70e2cb9/#Pdqe5gT0zIBy9689S5MYgg

When you have time, please run this and send me the log from `~/Library/Caches/Lunar/swiftybeaver.log`

**Comment by simPod** [comment]
I'm absolutely fine with trying to help you :) Don't worry! Will do tomorrow, I'm remoting for the rest of the day. Best!

**Comment by simPod** [comment]
@alin23 just tried to download but I'm late 

![image](https://user-images.githubusercontent.com/327717/55754451-fd962280-5a4c-11e9-99ff-5c885e152963.png)

can u reup pls?

**Comment by alin23** [comment]
I re-uploaded it here: https://send.firefox.com/download/5bb98c70811756ec/#W3IRhBCHLZeD38aMAizq-g

**Comment by simPod** [comment]
got it, will send log tmrw

**Comment by alin23** [comment]
Thanks! ^_^

**Comment by simPod** [comment]
[swiftybeaver.log](https://github.com/alin23/Lunar/files/3057911/swiftybeaver.log)

There we go

**Comment by alin23** [comment]
Thanks for the log! It seems that your display index in the IO registry is 10 but your system only has 6 framebuffers. Can you send me the IO Registry dump I told you about earlier? It would help me visualize your device tree and see why the unit number is so high.

I re-uploaded the Xcode tools here: https://send.firefox.com/download/ca79a086d029a900/#uX_BoYOsf6GaZRB5BTdjOg
And the steps are:
1. Open the DMG, go to Hardware folder and launch IORegistryExplorer
2. Press Command+Shift+S to save the dump

**Comment by simPod** [comment]
Here it is https://send.firefox.com/download/b26543a82ba2fc46/#zTW8NUkvqC96b7I5iVW-Bg

**Comment by alin23** [comment]
Yep, seems like the unit number strategy of finding displays doesn't work because `CGDisplayUnitNumber` is bullshit. I have to find another way to match display IDs to their EDID data.

Thank you for everything! Your setup seems to contain all the edge cases I need to account for to make Lunar completely functional. I'll try to get you another version of Lunar that would (hopefully) work this time.

**Comment by simPod** [comment]
:D glad to help, looking forward!

**Comment by alin23** [comment]
@simPod Here is another version that I hope will work with multiple displays: https://send.firefox.com/download/89fbdfadb963415c/#MZwRgXoTXARcKt4m2WwvTQ

Please try it and also send me the log when you can ^_^

**Comment by simPod** [comment]
@alin23 Hi, I tried on my one screen setup and it doesn't controll brightness nor contract. Will try with more screens on monday.

[swiftybeaver.log](https://github.com/alin23/Lunar/files/3074288/swiftybeaver.log)

**Comment by alin23** [comment]
Thanks for the log! I don't see any problem this time, the display is found and the DDC requests seem to go through. Unfortunately I'll be away from a monitor for a few weeks so I can't try the changes myself, but I'll try to see if I did something wrong in the new Swift implementation.

**Comment by alin23** [comment]
@simPod Please try the latest update 2.5.0 and check if everything works now.

**Comment by simPod** [comment]
@alin23 Hi, just tried. I have only one display available now but the app doesn't control brightness nor contrast there 🤔

**Comment by alin23** [comment]
I don't get how this can happen. How is that display connected to your Macbook?

**Comment by alin23** [comment]
You can try sending me the Lunar log by clicking on the menu bar icon then click on **Open Lunar Diagnostics**
If that fails (because it relies on an external service), just send me the same log you have sent me the other times.

**Comment by simPod** [comment]
It's via HDMI, that is connected to HyperDrive USB-C hub. Sending you logs via email.

**Comment by simPod** [comment]
But the version from the time of [this comment](https://github.com/alin23/Lunar/issues/19#issue-426647296) was able to control both. However, I understand the logic is now rewritten.

**Comment by simPod** [comment]
That's interesting. On my 3-screen setup it seems to work 🤔

**Comment by alin23** [comment]
So now Lunar can control all your 3 monitors? For the one screen setup that doesn't work, please also send me an IORegistryExplorer dump, maybe the hub introduces another edge case that I didn't account for.

**Comment by simPod** [comment]
There you go https://send.firefox.com/download/0ac9be872e8735c7/#oSeNKlh48APaBhrZWgNG4g

**Comment by chasegiunta** [comment]
Admittedly I haven't read through this entire thread, but I'll echo that my external display is connected via HDMI through an external USB-C hub and Lunar seems to have no effect.

**Comment by alin23** [comment]
Unfortunately, most hubs don't correctly implement the DDC protocol. I can't do anything to make Lunar work with hubs.

**Comment by simPod** [comment]
Fair enough, can mention in readme or sth 🤔

**Comment by alin23** [comment]
I thought this would discourage people to try Lunar at all, so instead I'm now compiling a list of monitors and hubs that work to put it on the website and here on Github. 

It just.. you know.. takes time

**Comment by chasegiunta** [comment]
@alin23 I'd disagree that a caveat mention would discourage people from trying.

This may be outside the scope you're willing support, but if there are monitors & hubs that aren't supported, maybe Lunar could fallback to doing software dimming, similar to how Shades or some others implement dimming...?

The attractiveness is Lunar, IMO, isn't necessarily the adjusting monitor brightness/contrast natively- it's the syncing, min/max, adapting, offsets, location-awareness, etc. (Great work!)

As a side note: I plugged in my monitor directly, via displayport, and Lunar worked for brightness perfectly 😄- but it didn't work for contrast at all.

**Comment by alin23** [comment]
Ok, I guess I could add a simple caveat about the hubs.

About the software dimming part, that's actually harder than the hardware logic because I have to manually compute gamma tables instead of letting the OS do that for me, so I'd rather not do that. I really don't have that kind of time.
_(Plus, f.lux already does a darn awesome job on that side)_

Thanks for the kind words! Most of the Lunar commits in the last few months were only for users asking about fixes and features so I'm happy to see that it's appreciated.


If the contrast doesn't work, then there may be an incompatibility with the monitor. You could click on the Lunar menu icon and then click on `Open Lunar Diagnostics` to send me some logs. I'll take a look as soon as I'm free.

**Comment by HenryQW** [comment]
I think I'm having the contrast issue too.

![IMG_5961](https://user-images.githubusercontent.com/5896343/58836934-0886c100-8652-11e9-964e-1ca1d445c239.jpg)

**Comment by alin23** [comment]
@HenryQW that looks more like night shift being applied on the left monitor. I don't think contrast can shift the reds so much. Can you double check the contrast values on the monitors using the monitor physical controls/buttons and see if they match the values in Lunar?

**Comment by HenryQW** [comment]
@alin23 Thanks for the reply.

I rebooted my mac and it seems to be fine for location mode now. However, when adapting from the built-in display, the contrast surges to 96% on both monitors (yes, values match with Lunar), but U2417H is too bright to be readable. This appears to be the monitor issue, I always feel the newer model is somewhat crap...

**Comment by alin23** [comment]
@HenryQW you can adjust the limits for contrast to keep the contrast within the values that fit your monitors. For example my LG monitor looks best at max 75 contrast, anything over that and everything looks washed out and too white. So I adjust the max contrast to 75 and the display sync mode will compute the contrast so that it will always fall between 0 and 75.

Example:
![image](https://user-images.githubusercontent.com/3819725/58992417-728a9c00-87f3-11e9-9c09-c0b4bf664092.png)

**Comment by HenryQW** [comment]
Thanks for the tip @alin23, that definitely solved my problem.

**Comment by masonmark** [comment]
Sorry to add off-topic noise, but I just wanted to point out that this is one of the best user<->developer bug threads I have ever seen. Bravo to you both!! 👏🏻😅

**Comment by alin23** [comment]
Lunar works with multiple displays now so I'll close this issue. I've also added the caveats in the Readme, I'll add them on the website too in the following days.

@simPod thanks a lot, I couldn't have finished this without your help 🙏

**Comment by wojteksbt** [comment]
Hi, I have the latest version and unfortunately the same problem. I have two DELL U2410 monitors and Lunar has impact on only one of them (probably the one which was connected first).

**Comment by alin23** [comment]
Hi @wojteksbt 

Are the monitors connected directly to the macbook USB-C ports? Or are they connected through a hub/dock/adapter? Also can you please send me some logs through the *Open Lunar diagnostics* option? 
<img width="303" alt="Screenshot 2019-07-29 17 43 13" src="https://user-images.githubusercontent.com/3819725/62057523-7b628180-b228-11e9-816d-b224a6116100.png">

**Comment by wojteksbt** [comment]
Monitors are connected directly but, as I have pre 2016 MBP, via mini DisplayPort to HDMI cables. Sure, I'm happy to provide you these logs, but I won't be able to do it before Saturday.

**Comment by wojteksbt** [comment]
@alin23 sorry for late response, but logs from configuration are under this link: https://transfer.sh/11lQgk/lunar.log. Thanks

**Comment by wojteksbt** [comment]
Hi, I've just changed my machine to MBP 2019 and the same monitors connected via DisplayPort to USB-C cable work fine.

**Comment by alin23** [comment]
I'm glad to hear that ^_^ @wojteksbt

**Comment by wojteksbt** [comment]
And by the way, this software looks and works really really nice now :)! Good job @alin23 !
