### ISSUE TITLE
Lunar Diagnostics Report

### ISSUE THREAD

**Issue by jiayiliujiayi** [alin23/Lunar#191]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mac Mini (2018)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:

**Comment by alin23** [comment]
Mac Mini HDMI is a known issue: https://github.com/alin23/Lunar/issues/125

I'll close this and follow up on the above issue if I have any idea how to fix it.
