### ISSUE TITLE
Brignetss key changes the offset

### ISSUE THREAD

**Issue by ricardopolo** [alin23/Lunar#194]
This is a recording of what is see:
https://cln.sh/oaJf7D

When I use the brightness keys in my external keyboard it changes the offset in Lunar. I have it configured in sync mode, so I expected the keys not change the offset, only changes the brightness of the built in screen.

Is this expected?

**Comment by alin23** [comment]
Yes, this is how Lunar is designed for now. I posted the reason for this here: https://github.com/alin23/Lunar/issues/193#issuecomment-710009376

**Comment by ricardopolo** [comment]
Thanks! Would be great if this is possible to deactivate this behavior and only change to the build in monitor with the keys.
