### ISSUE TITLE
Lunar Diagnostics Report [1336CF9DECC84E0722C244A5E8D6F1A07CB2C75F07E413876E6DE4B459243E5A] [3.2.3]

### ISSUE THREAD

**Issue by josh-m-sharpe** [alin23/Lunar#196]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    macbook pro 2016

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
 hdmi -> KVM -> hdmi

- Using an USB Docking Station or Hub:
  na

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    https://www.amazon.com/CKL-Monitor-Extended-Display-CKL-844UA/dp/B07KTMH9T2/ref=sr_1_5?dchild=1&keywords=ckl+4+port+kvm&qid=1604324616&sr=8-5

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    no - it didn't.  Though it was able to detect the two monitors

# Issue description:
I've got two macbooks connected through a dual-monitor KVM to two identical HP 24".  The connections are all over HDMI, passing through the KVM switch.

For what it's worth, If I directly connect my mac to the monitors only brightness works.  Volume does not.

**Comment by RockyMM** [comment]
Hey @josh-m-sharpe , you linked a VGA switch, not a HDMI switch. Which KVM are you using?

**Comment by josh-m-sharpe** [comment]
Shoot, sorry.

I originally meant this one: https://www.amazon.com/gp/product/B07KTMVKWQ/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1

I have now also tried this one:
https://www.amazon.com/gp/product/B083NGXHWG/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

**Comment by RockyMM** [comment]
I would assume that Lunar is based on the same or very similar functionality as https://github.com/kfix/ddcctl Therefore this can't be helped, unless the author has some different idea?

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
