### ISSUE TITLE
Configuration export/import

### ISSUE THREAD

**Issue by Bounz** [alin23/Lunar#198]
### Name of the feature

Export/import settings

### What problem does this feature solve?

Proposed feature solves the problem with restoring settings after migration to new Mac or reinstalling OS.

### How should the feature work

Buttons in Preferences menu to export or import settings to/from file.

**Comment by alin23** [comment]
Sounds like a good idea! I'll consider it for the next version

**Comment by alin23** [comment]
For now, simply backing up the following file should be enough: `~/Library/Preferences/fyi.lunar.Lunar.plist`
