### ISSUE TITLE
Update Error! An error occurred while extracting the archive. Please try again later.

### ISSUE THREAD

**Issue by mvaneijgen** [alin23/Lunar#20]
Seems like I'm having the same issue as https://github.com/alin23/Lunar/issues/12 but on a different version? 

![](https://i.imgur.com/mn2wJIM.jpg)

**Comment by mwildx** [comment]
Same here

**Comment by alin23** [comment]
I tried the delta feature of the updater to make the updates smaller and faster. I'll try to see if this is the problem and come back with an update

**Comment by alin23** [comment]
Ok, it should be fixed now. Quit Lunar and launch it again, then click Check for Updates to update. It seems I forgot to sign some updates.
