### ISSUE TITLE
Lunar Feature

### ISSUE THREAD

**Issue by jstader** [alin23/Lunar#205]
### Name of the feature

Monitor switching/ default boot monitor

### What problem does this feature solve?

Macs with eGPU (at least macbooks) currently don't support external, egpu displays on boot when filevault is enabled. The user either has to open the clamshell to type in login info or plugin an additional monitor that uses the internal gpu.

### How should the feature work

This feature would allow the user to switch monitor inputs using ddc. This could possibly include setting a "boot" and "default" input in the future as well that would perform the switch at shutdown and then switch again on login.

### Visual description

A dropdown menu could be added on the page for each monitor showing the possible inputs (I can't tell if it is possible to determine what those are using ddcctl).

**Comment by alin23** [comment]
Yep, it's a good idea and has been requested before here: #102 
The dropdown under each monitor is how I have started to implement it. There is no way to check what connections the monitor has so I'll just have to list them all.

Could you please explain more what a boot input would mean. To be clear, DDC only allows for switching the input **from the current input to another**. It's not possible to do it the other way around (e.g. if the monitor input is set to HDMI1 where a PC is attached, even if the Macbook running Lunar is attached to USB-C, it can't tell the monitor to switch from HDMI1 to USB-C)

**Comment by jstader** [comment]
That’s good to hear! 

And as for the boot input, my current work-around for the egpu/FileVault issue is that I have the same monitor with an input from the dedicated graphics of my MacBook (through a thunderbolt dock) and an input from the thunderbolt egpu (from the same Mac). I boot the Mac with the integrated monitor input (“boot” input) and then I switch over to the egpu input after logging in. 

I realize this may be an uncommon use case but I figured I’d ask anyway. The linked issue solves most of this request however.

**Comment by alin23** [comment]
Oh now I understand! Yes, this is quite uncommon to implement in Lunar. 
Check to see if ddcctl can switch between the eGPU and your dedicated Macbook GPU and let me know. 

If that works, I'll think about how I can cram that boot/default GPU setting into some Advanced Settings window.

I'll close this in favor of the other issue to avoid duplicates.
