### ISSUE TITLE
Lunar Diagnostics Report [EDE2B3F456913F3ACC64C31CC4F13490D34F9C969743FFBE8551F31F53996284] [3.2.3]

### ISSUE THREAD

**Issue by thekeith** [alin23/Lunar#206]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
  M1 Mac mini 16gb RAM / 1tb SSD on Big Sur 11.0.1

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
  USB-C, USB-C->HDMI and HDMI fail

- Using an USB Docking Station or Hub:
  No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
  All of them

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   Yes

# Issue description:
Unable to change volume or brightness on LG 32UL750-W with USB-C to USB-C connection

**Comment by alin23** [comment]
> M1 Mac mini 16gb RAM / 1tb SSD on Big Sur 11.0.1

Thanks for the report but I have no way to test or debug this. It's weird that ddcctl works and Lunar doesn't as Lunar uses the exact same implementation as ddcctl.

Do you have your cursor on the external monitor when you are changing the volume with Lunar?

**Comment by thekeith** [comment]
Quick update - realized that ddctl was installed on my old computer and had assumed that when I migrated that it was also on the M1 Mac. Haven't been able to compile it, even when running terminal in Rosetta.

Cursor is on the only hooked up monitor on my Mac mini ;)

**Comment by kieselit** [comment]
I am using a new MacBook Air with M1 chip and I am able to compile ddcctl in the native terminal without Rosetta using "make intel", which of course is not correct, but ddcctl does not offer an "Apple GPU" option yet. The so compiled ddcctl at least sees that there is an external monitor connected, but trying to change its brightness, for example, it shows "I: polling display 1's EDID" and then "E: Failed to poll display!".

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
