### ISSUE TITLE
Lunar Diagnostics Report [F4E3B5731F9F0BBB33574E2195F8AABF0692BFC41FBE32255B0A0D645BF1FF71] [3.2.3]

### ISSUE THREAD

**Issue by timotk** [alin23/Lunar#207]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Macbook Pro 2019 16" with macOS Catalina

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
Mac -> USB-C Dock -> HDMI -> Dell U2415H

- Using an USB Docking Station or Hub:
Yes, tried both Microsoft Surface Hub and a Hyperdrive dock

- Lunar mode used (check it in the top-right corner of the Lunar interface)
  Tried both: *Sync, Location or Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
No. I get the following output:
```
$ ./ddcctl -d 1 -b 100
D: NSScreen #724846163 (2560x1440 0°) 118.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: ***********
I: got edid.name: DELL U2515H
D: action: b: 100
D: setting VCP control #16 => 100
E: Failed to send DDC command!
```

# Issue description:
Cannot change brightness on external monitor through Lunar. It was working on my previous Mac with the same USB dock and same cables. (I think it was a Macbook Pro 15" 2017 or 2018 model).

Lunar shows "Non-responsive DDC" in its UI.

**Comment by alin23** [comment]
Sounds like the GPU is the problem here. Try compiling ddcctl with both `intel` and `amd`. If none work, then there's not much we can do in software.

**Comment by timotk** [comment]
I tried both. Unfortunately, they don't work either.

Would you say the GPU does not support DDC?

Anyway, thanks for making Lunar. It worked very well before and looks great!

**Comment by alin23** [comment]
The GPU definitely supports DDC, but it has a different reply time than what is used for intel and amd inside ddcctl. I need access to an M1 GPU to be able to try to find that reply time constant.

Fortunately, I'll be getting an M1 Macbook by the end of this year.

**Comment by timotk** [comment]
This issue does not relate to the M1 Macbook though. I have the Macbook 16" (2019) model. It has an Intel Core i9, Intel UHD 630 and an AMD Radeon Pro 5500M.

**Comment by alin23** [comment]
> This issue does not relate to the M1 Macbook though. I have the Macbook 16" (2019) model. It has an Intel Core i9, Intel UHD 630 and an AMD Radeon Pro 5500M.

Oh sorry, I was responding to multiple issues related to M1 and I didn't notice this is something else entirely.

In your case then, all I can recommend is try different cables/connectors or bypassing the dock. I'm not saying the cables or the dock are bad, but they can interact differently with the new Macbook 16 since it has different GPUs inside.

Lunar (and ddcctl) are tested to work on Intel and AMD GPUs found in all Mac devices, everything that caused a problem until now was something external like cables, docks, hubs, monitor settings etc.

**Comment by alin23** [comment]
I'll close this since it is not a software issue that can be fixed but feel free to post updates here. I'll keep responding.
