### ISSUE TITLE
Keyboard shortcuts don't persist after reboot (stay disabled)

### ISSUE THREAD

**Issue by mvaneijgen** [alin23/Lunar#21]
I've a lot of keyboard shortcuts and yours conflict with mine. I don't need keyboard shortcuts for Lunar.app, so I delete them from the interface. But each reboot the keyboard shortcuts are back.

**Comment by alin23** [comment]
I can't reproduce this. Do you launch Lunar from /Applications?

**Comment by mvaneijgen** [comment]
Sorry, the UI confused me. When you delete a shortcut it becomes grey and has only the cmd, alt, swift shown, then when you relaunch the app, the other characters are back (and white-ish) which I thought ment they were reinstated, but only yellowed shortcuts are active. 

That is why I closed te issue.

**Comment by alin23** [comment]
Yes, that's how the hotkey library is implemented. i agree it's a bit confusing, I'll see if I can improve this somehow
