### ISSUE TITLE
Lunar Diagnostics Report [F644593B95E623149250E33BD2D3C93866834208909764180A3D8222FD35140B] [3.2.3]

### ISSUE THREAD

**Issue by lijunkang12** [alin23/Lunar#212]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Cannot change brightness or contrast on my external monitor (Samsung U28E590)

**Comment by lijunkang12** [comment]
My monitor has two hdmi ports, the first do not support 4k@60hz while the second one can. When connected to the first one,  Lunar works fine. However, when connected to the second one, Lunar cannot adjust brightness in any mode, no matter at 30hz or at 60hz.

I have another similar monitor of Samsung. Bizarrely, with that monitor at 4k@60hz, Lunar works perfectly.

**Comment by alin23** [comment]
Sounds like that specific monitor is disabling or overriding the DDC pin on the HDMI connector when using 4k@60hz.
Try going through the monitor settings to see if there is any way to disable that (although I doubt it).

I'll close this as it is not a software issue that can be fixed, but feel free to post updates here.
