### ISSUE TITLE
Native Apple Silicon support

### ISSUE THREAD

**Issue by KovalevArtem** [alin23/Lunar#215]
Add full support for new processors Apple Silicon

**Comment by KovalevArtem** [comment]
https://github.com/kfix/ddcctl/issues/86

**Comment by alin23** [comment]
From the ddcctl thread, it seems that M1 Macs don't currently expose the I2C devices. I'll be getting a Macbook Pro M1 in mid-December so I can better take a look but it looks like we're at Apple's mercy right now.

If there's no way to tell the GPU to send arbitrary DDC messages to the monitor, Lunar won't be able to work.

**Comment by rgaufman** [comment]
Mine just arrived today, would be great to have support. Very impressed with the CPU so far.

**Comment by alin23** [comment]
Closing this in favor of #210
