### ISSUE TITLE
x86 Big Sur - When Use media keys as hotkeys is selected, brightness keys change Lunar Brightness Offset rather than system brightness

### ISSUE THREAD

**Issue by mankittens** [alin23/Lunar#217]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2017 13" nTB w/ Big Sur

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell S3230DGF

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DisplayPort

- Using an USB Docking Station or Hub:
    CalDigit TS3+

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

# Issue description:
x86 MacBook with Big Sur installed. When Advanced -> Use media keys as hotkeys is selected, the brightness keys on the MacBook, instead of changing the system brightness, change the Brightness Offset.

![Screen Shot 2020-11-30 at 6 58 54 PM](https://user-images.githubusercontent.com/6647355/100691720-27950a80-333e-11eb-9bdc-22b3c9569695.png)

**Comment by mankittens** [comment]
That value with the arrow pointing at it goes up and down when I press my brightness keys.

**Comment by alin23** [comment]
This is how it is designed so that you don't get kicked out of Sync mode when changing the brightness. It is not a bug, but it's also not the best feature. I'm working on a better solution for the next version.
