### ISSUE TITLE
Lunar blocks use of right and left arrow keys when running

### ISSUE THREAD

**Issue by laneschmidt** [alin23/Lunar#219]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    2019 Macbook Pro -- Mojave 10.14.6

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    n/a

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    n/a

- Using an USB Docking Station or Hub:
    n/a

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Location

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Lunar blocks the use of the right and left arrow keys when it is enabled (Lunar logo is visible on the top bar). The keys simply do not work anywhere until I force quit Lunar. 

Thank you for this application!

**Comment by alin23** [comment]
Hi! This should only happen when the Lunar window is visible and focused. 

The next version of Lunar will use shift+left/right to avoid issues like this but it really should not listen for left/right arrows when the window is not in focus.
