### ISSUE TITLE
Contrasts resets randomly. I have it set to 75 locked on the sync setting

### ISSUE THREAD

**Issue by mvaneijgen** [alin23/Lunar#22]
If the brightness is on 100% every thing on my monitor is blown out. If I set it to 75 it feels fine, so I want the contrast to never go above 75&, but still dim both my external screens adaptive with my laptop. This is what I do:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/h1kGdem1-J4/0.jpg)](https://www.youtube.com/watch?v=h1kGdem1-J4)
video: https://www.youtube.com/watch?v=h1kGdem1-J4&feature=youtu.be
This seems like it should fix my issue, but then later (maybe 10 minutes) Lunar.app resets (?) and the setting is back to 100%, I have no idea what I do, maybe I trigger a shortkey that sets the brightness to 100%, but I thought I had disabled them all. 

As you can see it is also really hard to set a setting to a specific number (if you're working with a track pad (Wacom tablet in my case, with this mouse I also can't switch screens by scrolling left and right)), the arrow keys on my keyboard are also sometimes not recognised, so than I have to open up my laptop to use the internal trackpad (this one always works)

**Comment by alin23** [comment]
This is an issue with storing display settings introduced in the latest update. I'm working on fixing it right now. I'll let you know when it's fixed 😄

**Comment by alin23** [comment]
@mvaneijgen this should be fixed in 2.5.0
