### ISSUE TITLE
Lunar is blocking F14 and F15 keys when "media keys as hotkeys" is enabled

### ISSUE THREAD

**Issue by rwdmaster** [alin23/Lunar#221]
I'm running Lunar from a 13" 2019 MacBook Pro (MacOS Catalina) with two external monitors, a 32" 4k connected via Thunderbolt 3 and another 22" HD on portrait or vertical position connected via a DP connection from a Caldigit T3 plus hub. I use an external Apple Magic Keyboard 2 with numpad keys in Euro spec (Spanish) and usually on clamshell mode.

The "Use media keys as hotkeys" feature works AMAZING, I just drag my cursor over the monitor I want and the brightness media keys (F1 & f2 ) just work on each one as it should. 

Now, the issue is that when the above option is enabled, also my F14 & F15 keys work replicating the F1 & F2 keys, and I have mapped those F14 & F15 with Keyboard Maestro to do some repetitive tasks specific to my work, that would only work if Lunar is not running or that wonderful "Use media keys as hotkeys" option is disabled.

**Comment by alin23** [comment]
Unfortunately that's what F14 and F15 mean in macOS. The key codes are the same as for the Brightness keys on F1 and F2. They aren't different keys.
