### ISSUE TITLE
Lunar Diagnostics Report [9EEC907AF47BBB179785EC8DD6327D2C7B72770C04FBA045379F9925E2914EE9] [3.2.3]

### ISSUE THREAD

**Issue by trhnburak** [alin23/Lunar#225]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   No it doesnt.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
  MacbookPro 2017 13inch

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
   I am using hdmi to usb c converter

- Lunar mode used (check it in the top-right corner of the Lunar interface)
  All

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   D: NSScreen #458665474 (1920x1080 0°) 102.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: LG IPS FULLHD
I: got edid.serial: 
D: action: i: 17
D: setting VCP control #96 => 17
E: Failed to send DDC command!
So no it doesnt work.

# Issue description:
Hi I been usıing lunar for a while now it is my life saver when it comes to adjust my external monitor but after I cleaned my Mac with cleanmymac x and optimize launch agent it stoped working I tried uninstall and install again, uninstall cleanmymac x and leftover with easy find 3 but nothing has worked till now so I decide to contact with you I am an software developer too so you can be easy with me to explain stuff. I hope you return me to help thank you.

**Comment by trhnburak** [comment]
@alin23 I solve the problem it happen becuase of i use hdmi to usb c converter which couldnt send ddctl code to monitor. Just want to keep you inform.

**Comment by alin23** [comment]
I'm glad you managed to find the issue! ^_^
