### ISSUE TITLE
Lunar Diagnostics Report [DBF08E543B6FECBD788F5A24DE3A28DDAD227ED185436A93EF7CAA7A415457FF] [3.2.3]

### ISSUE THREAD

**Issue by theodric** [alin23/Lunar#234]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No. 

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MacBook Air M1 8 GPU cores

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
Thunderbolt 3-to-2 adapter to Belkin Express Dock to mini DisplayPort to monitor's mini DisplayPort. Also tried an Aukey USB-C to HDMI cable between laptop and monitor-- no worky. 

- Using an USB Docking Station or Hub:
No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
No

# Issue description:
NOTE: this whole setup works fine with the substitution of a Thunderbolt 2 MacBook Pro for the ARM Mac + Thunderbolt 3-to-2 dongle, leaving Thunderbolt cable, dock, miniDP cable, and monitor in play.

ddcctl reports "I: polling display 1's EDID\ E: Failed to poll display!" but possibly doesn't work because it assumes one of Intel, nVidia, AMD graphics, and the M1 has none of the above. I tried all three options, anyway.

We do get a brightness slider onscreen, but it doesn't actually change monitor brightness.
![Screen Shot 2020-12-23 at 19 06 52](https://user-images.githubusercontent.com/144880/103025409-0c3ea900-4552-11eb-9675-403cef554938.png)

**Comment by alin23** [comment]
Unfortunately, DDC is not usable yet on M1 Macs: https://github.com/kfix/ddcctl/issues/86

Closing this in favour of https://github.com/alin23/Lunar/issues/215
