### ISSUE TITLE
Not working with multiple displays - Lunar Diagnostics Report [7E768E377621E238FA400C7902C592E95E23882860352C8E28D8A1F554B04188] [3.2.3]

### ISSUE THREAD

**Issue by marknotton** [alin23/Lunar#236]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   Yes, but only one.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Hackintosh

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Display Port to Display Port

- Using a USB Docking Station or Hub:
    yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

# Issue description:
Only one monitor is able to change its brightness. The one that does work behaves exactly as I would expect; even the hotkeys work. The problem is my second monitor doesn't seem to be responsive to the changes. Both monitors are identical (VP2770-LED). I have a feeling the issue is related to one discussed previously https://github.com/alin23/Lunar/issues/19

I'm not sure how to troubleshoot this further. I'm guessing both monitors share the same reference or ID and need to be made distinguishable using a different method. I'm sure that's easier said-than-done though 😅

**Comment by alin23** [comment]
This issue has been fixed for some time in Lunar. The only way this problem can happen is if the connection is not able to forward DDC messages to each monitor independently.

In your case I'm guessing it's the hub/dock between your Hackintosh and your monitors. 

Bypass the dock and try direct connections if possible.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
