### ISSUE TITLE
2.4.0 Broken?

### ISSUE THREAD

**Issue by dougc84** [alin23/Lunar#24]
I downloaded the 2.4.0 release and... well... the UI updates nicely, but the monitor doesn't change.  Reverted back to the last version and it's back to working as normal.

Let me know if there's anything you need from me on this.

**Comment by landoncope** [comment]
It's broken for me also.

**Comment by alin23** [comment]
Yes, it seems like it doesn't work on all types of connectors anymore. I'm working on it. Thanks for the feedback!

**Comment by alin23** [comment]
I reverted some changes that might have caused this. Please try 2.5.0 and let me know if everything's ok now.

**Comment by dougc84** [comment]
Works for me!  Thanks @alin23 !

**Comment by alin23** [comment]
Awesome!
