### ISSUE TITLE
Lunar quits in manual mode

### ISSUE THREAD

**Issue by psoldunov** [alin23/Lunar#246]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MBP16 (C02DP1X2MD6R)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Samsung C49RG90

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DP1.4 -> DP1.2 Socket (TS3 Plus) -> T3 Cable

- Using an USB Docking Station or Hub:
   CalDigit TS3 Plus

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

# Issue description:
Lunar quits while in manual mode, most notably when media keys (F1 & F2) are used to adjust brightness on external monitor. Sometimes it quits after preference window is closed.

**Comment by alin23** [comment]
Could it be some other app killing it? 

If you don't have such an app on your system, could you please upload the Lunar logs located at ~/Library/Caches/Lunar/swiftybeaver.log ?

**Comment by psoldunov** [comment]
> Could it be some other app killing it?
> 
> If you don't have such an app on your system, could you please upload the Lunar logs located at ~/Library/Caches/Lunar/swiftybeaver.log ?

I really can't answer if there are other apps interfering with Lunar, but I have uploaded a log.
 
[swiftybeaver.log](https://github.com/alin23/Lunar/files/5824434/swiftybeaver.log)

**Comment by alin23** [comment]
Try disabling the "Read brightness periodically" option. It may cause the system to kill the app when the monitor takes too long to respond to DDC Read messages.
<img width="842" alt="image" src="https://user-images.githubusercontent.com/3819725/104815632-6ca5cb00-581e-11eb-8160-131fb8bc92a7.png">

**Comment by psoldunov** [comment]
> Try disabling the "Read brightness periodically" option. It may cause the system to kill the app when the monitor takes too long to respond to DDC Read messages.
> <img alt="image" width="842" src="https://user-images.githubusercontent.com/3819725/104815632-6ca5cb00-581e-11eb-8160-131fb8bc92a7.png">

Great! It doesn't crash anymore
