### ISSUE TITLE
Lunar Feature

### ISSUE THREAD

**Issue by GuanhongW** [alin23/Lunar#247]
### Name of the feature

Hotkey change multiple display together (Include Brightness, Contrast, and Volume)

### What problem does this feature solve?

Now, I only can use hotkey (MacOS default hotkey) change one monitor's setting that includes brightness, contrast, and volume.

### How should the feature work

The default hotkey can change all external displays and build-in display (includes speaker) together. Also, if users use MIDI setting as the output, they can use F10, F11, and F12 to change the volume together.

I tested the MIDI output. I select the default speaker and two displays' speaker in MIDI setting, I cannot use hotkey (i.e. F10, F11, and F12 change the build-in speaker's setting. But the two displays' speaker can be modified if my mouse in the select display.

I found if I select "Use F1, F2, etc. key as standard function keys" is working for brightness and contrast. But volume is not working. Because I used a external keyboard, I did not test the build-in keyboard.

**Comment by alin23** [comment]
Hi Guanghong!

I replied to your email but I'll leave the message here for others to see as well.  Lunar already has this feature, you have to use the custom hotkeys that are defined on the HOTKEYS page of the Lunar UI.
(swipe two times to the right or press the left arrow key twice to get to that page)

![image](https://user-images.githubusercontent.com/3819725/105010846-e4553f00-5a44-11eb-80d4-fc494e647aad.png)

**Comment by GuanhongW** [comment]
Hello Alin,

I think it is really hard to set the custom hotkey. I tried few time and cannot set ctrl+F1 again but it is very easy to set command + F1.

Also, if I only use F1 (not the standard function keys), the brightness only change when the cursor on the monitor. Another monitor does not change together. If I use fn+ctrl+F1, both monitor can change the brightness and contrast at the same time.
<img width="576" alt="Screen Shot 2021-01-19 at 9 11 21 AM" src="https://user-images.githubusercontent.com/34050610/105045906-6be78180-5a36-11eb-91b1-24d726e70e7b.png">
If this is a bug or something else?

**Comment by alin23** [comment]
It seems you don't fully understand what `Use F1, F2, etc. keys as standard function keys` does.

If that option is checked, the F1, F2 etc keys send F1, F2 etc key codes.
If it is unchecked, the F1, F2 etc keys send special system key codes like `BRIGHTNESS_UP`, `BRIGHTNESS_DOWN` etc. They are not F1, F2 keys anymore. They are called Media Keys. To send Function Keys key codes from this state you have to hold Fn.

So if you have the option unchecked, then F1 will send `BRIGHTNESS_DOWN` Media Key which Lunar intercepts and sends it to the active monitor. Control+F1 will send `Control+BRIGHTNESS_DOWN` which Lunar will interpret as Contrast Down for the active monitor.

To use the hotkeys on the HOTKEYS page from this state, you have to hold Fn and press the hotkey. So for example if you want to increase the Volume for all monitors, you have to press Fn+Control+F12.

**Comment by GuanhongW** [comment]
Yes, I think I understand what is `Use F1, F2, etc. keys as standard function keys`.

Assume I unchecked this option all time.
1. I cannot use fn + ctrl + F1 to set the hotkey in HOTKEYS page. I think it may conflict another shortcut in my computer which I don't know, because I can set up fn + ctrl + F2 easily.
2. I can using fn + ctrl + F1/F2 to change both monitors' light and using fn + ctrl + shift + F1/F2 to change both monitors' contrast. However, when I using the media key F1(BRIGHTNESS_DOWN) solely, only the monitor has cursor will change the brightness. If it is expected?

**Comment by alin23** [comment]
1. Yes, if Ctrl-F2 is already intercepted by another app then you won't be able to set it in Lunar. 
2. Yes, Lunar is designed to only control the monitor that has the cursor when using media keys. This is useful when you have monitors that have more/less backlight strength on the same brightness/contrast value.
3. Yes, that is expected. There is no contrast specific symbol so I just used the Keyboard Backlight OSD symbol to differentiate it from the brightness symbol.

**Comment by GuanhongW** [comment]
Thanks for your information. I hope if it is possible, you can add a feature let Lunar control both monitor when using media keys.

Also I found another thing. It may be a known bug. I used two same monitors (BenQ EW2780U). Sometimes, Lunar cannot identify the correct monitor. For example, my cursor is in monitor 1 and I use media keys to control monitor. Lunar may change monitor 2 and show the symbol in monitor 2. I know this is an issue in other application that cannot control two same monitor.

**Comment by alin23** [comment]
Hey, thanks for the coffee!
I'll see if I can add an option for that.

About the bug, it is a system bug. It confuses the monitors at the system level, Lunar can't do anything about that.

**Comment by GuanhongW** [comment]
Hopefully this system bug can be fixed. Nice application, I will let my friend try this!

**Comment by GuanhongW** [comment]
Another thing. Some monitor's speaker only can be 0 - 50. If it is possible add this limit into Lunar? The default is 0 -100. If I adjust more than 50, the monitor's speaker will be set to 25 and the sound will broke.

**Comment by alin23** [comment]
I'll try to add that as well. I had no idea there could be a limit on volume
