### ISSUE TITLE
Adjust Brightness and Contrast when Lid is Closed

### ISSUE THREAD

**Issue by MSzturc** [alin23/Lunar#248]
### What problem does this feature solve?

In Adaptive Mode the Brightness and the Contrast gets Adjusted when I press Brightness+/- Keys on my Keyboard. When i close my Laptop and only my external Display is active the Media Keys are working but only Brightness gets adjusted. As workaround i use the Lunar internal Hotkeys to adjust contrast. My expectation would be that similar to adaptive mode brightness and contrast would be adjusted when i press media keys.

### How should the feature work

Add a Checkbox into settings "Adjust Brightness and Contrast" to toggle new and old behavior.

**Comment by alin23** [comment]
Hi!

In Sync mode, Lunar actually doesn't adjust brightness and contrast. It adjusts the Offset value (which is kind of a Curve Factor right now).

<img width="709" alt="image" src="https://user-images.githubusercontent.com/3819725/105033027-3ce60580-5a60-11eb-869e-15b5425514e5.png">

For Manual mode, you can use Control + Brightness to adjust contrast.
<img width="567" alt="image" src="https://user-images.githubusercontent.com/3819725/105033098-55562000-5a60-11eb-848b-f8ec3ff34e91.png">
