### ISSUE TITLE
Lunar Diagnostics Report [7542F5836516084637BBCCCBA17FB52A371C7D4AF5449377DAB60BFCD6C821BB] [3.2.3]

### ISSUE THREAD

**Issue by jhorowitz** [alin23/Lunar#249]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (15-inch, 2019) running Big Sur 11.1

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    miniDisplayPort-to-DisplayPort-to-USB-C

- Using an USB Docking Station or Hub:
    Yes, a dongle

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
      Seems like it does not work:
      $ ./bin/release/ddcctl -d 1 -b 1
      D: CGDisplay AB33B9EC-C1D0-C1B9-6F65-125945793127 dispID(#724070549) (3440x1440 0°) 109.00 DPI
      I: found 1 external display
      I: polling EDID for #1 (ID 724070549 => IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Palena@3/AMDFramebufferVIB)
      I: got edid.serial: PXF7905Q0TYL
      I: got edid.name: DELL U3415W
      D: action: b: 1
      D: setting VCP control #16 => 1
      E: Failed to send DDC command!

# Issue description:
I can't adjust volume or brightness. I care most about volume, brightness is a nice to have. Any help you can give would be much appreciated! 

PS: Thank you so much for working on this!! I really appreciate your time and energy

**Comment by jhorowitz** [comment]
So, your question about the cable made me try switching to HDMI from DisplayPort which works perfectly. I'm still happy to debug if you'd like to use my issues to improve the codebase. If not, I'll close the ticket. Either way, I already shot you a donation as thanks for this great utility

**Comment by alin23** [comment]
Thanks for the coffee!

There's nothing to debug here, the code is just standard DDC requests, if it doesn't work, it's purely a hardware connection issue. I'm glad you got that working in the end 😊

**Comment by jhorowitz** [comment]
Great!
