### ISSUE TITLE
Doesn't start at login

### ISSUE THREAD

**Issue by landoncope** [alin23/Lunar#25]
I'm running macOS Majave 10.14.4, and Lunar never starts at login, even with the "Start at Login" option checked. I've tried unchecking/checking it, no change. 

What other information can I provide that would be helpful?

**Comment by alin23** [comment]
Please try the latest update (2.5.0) and let me know if the issue persists.

**Comment by lukerooneyio** [comment]
I'm having the same issue on the latest update 2.8.3, it does not start at login.

**Comment by alin23** [comment]
@lukerooneyio looking into it

**Comment by nicoelayda** [comment]
Experiencing this issue as well. Lunar 2.8.3 on macOS Mojave 10.14.6 (18G95).

Temporary workaround for now is to manually add Lunar to System Preferences > Users & Groups > Login Items.

**Comment by alin23** [comment]
Thanks for reporting! I'm having mixed results with a current fix, still not sure what the problem is. Hopefully I'll have a new version by the end of the week with a proper fix.

**Comment by DamiansDesign** [comment]
Also experiencing this. Lunar 2.8.3 on macOS Mojave 10.14.6 (18G103).

My system.log is flooded with messages like this:

```
com.apple.xpc.launchd[1] (site.lunarapp.LunarService[37480]): Could not find and/or execute program specified by service: 149: Could not find a bundle of the given identifier through LaunchServices: site.lunarapp.LunarService
com.apple.xpc.launchd[1] (site.lunarapp.LunarService[37480]): Service exited with abnormal code: 78
com.apple.xpc.launchd[1] (site.lunarapp.LunarService): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

```

I tried disabling 'Start at login', quitting Lunar and reopening, then re-enabling 'Start at login' and saw this in system.log:

```
com.apple.xpc.launchd[1] (site.lunarapp.LunarService[37488]): Could not find and/or execute program specified by service: 2: No such file or directory: site.lunarapp.LunarService
com.apple.xpc.launchd[1] (site.lunarapp.LunarService[37488]): Service setup event to handle failure and will not launch until it fires.
com.apple.xpc.launchd[1] (site.lunarapp.LunarService[37488]): Service exited with abnormal code: 78

```

Eagerly awaiting update. 

Thanks for your efforts!

**Comment by alin23** [comment]
Thanks for the detailed report @DamiansDesign !

I had my Macbook in service, that's why this took so long. I'm fixing this by Monday.

**Comment by alin23** [comment]
I managed to fix this but I couldn't release a new version because I had troubles signing the app with the Apple developer ID. By the time I fixed this, my Macbook died again and I didn't get a chance to push the changes. Hopefully the changes were backed up by Time Machine. I'm getting a new Macbook next week and if everything is ok with the backup, I'll release the new version, signed and notarized.

**Comment by DamiansDesign** [comment]
@alin23, 

Thanks for the progress update, and sorry to hear about your Mackbook. I recently had to retire my trusty 17" Macbook Pro that served me well for +8 years. I hope your new MacBook will serve you for years to come. 

Thanks for keeping us in the loop.

**Comment by krupenja** [comment]
@alin23 Lunar 2.9.0 does correctly start on login and works without issues. However, the system.log is still being spammed with the following every 10 seconds:

```
Nov 22 15:01:52 Igors-MBP com.apple.xpc.launchd[1] (site.lunarapp.LunarService[790]): Could not find and/or execute program specified by service: 149: Could not find a bundle of the given identifier through LaunchServices: site.lunarapp.LunarService
Nov 22 15:01:52 Igors-MBP com.apple.xpc.launchd[1] (site.lunarapp.LunarService[790]): Service exited with abnormal code: 78
Nov 22 15:01:52 Igors-MBP com.apple.xpc.launchd[1] (site.lunarapp.LunarService): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

Any ideas?

**Comment by alin23** [comment]
@krupenja Do you have Lunar installed in `/Applications`

**Comment by krupenja** [comment]
thank you for the quick response!

yep, I have Lunar installed in `/Applications`

**Comment by DamiansDesign** [comment]
@krupenja what version of macOS are you running?

I'm running Mojave 10.14.6 with Lunar 2.9.0, and I'm not seeing any system.log spam for Lunar.

Not sure if this will help, but perhaps try the following: 

Disable 'Start at Login' > Quit Lunar > Open Lunar > Enable 'Start at Login'.

**Comment by DamiansDesign** [comment]
Scratch that!

I just rebooted (to install latest security update) and Lunar is not starting up automatically, and I'm getting system.log spam for Lunar.

```
Nov 23 10:45:19 iMac com.apple.xpc.launchd[1] (site.lunarapp.LunarService[1342]): Service exited with abnormal code: 78
Nov 23 10:45:19 iMac com.apple.xpc.launchd[1] (site.lunarapp.LunarService): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Nov 23 10:45:29 iMac com.apple.xpc.launchd[1] (site.lunarapp.LunarService[1343]): Could not find and/or execute program specified by service: 149: Could not find a bundle of the given identifier through LaunchServices: site.lunarapp.LunarService
```
Also seeing a lot of these in the main device log (not sure if related):

```
XPC error encountered: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.lsd.modifydb was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.lsd.modifydb was invalidated.}
```
By manually opening Lunar, disabling 'Start at Login', quitting and re-opening Lunar the system.log spam stopped. The XPC error in main Device log continues to spam the log...it may not be related. There is so many of these errors, I can keep up with them and I can't pause the scroll for some reason. 

I have not re-enabled 'Start at Login' yet. 

@alin23 let me know if you need any further investigation or info from me.

**Comment by krupenja** [comment]
Some observations:

1. I am on  macOS 10.15.1 Catalina.
2. If I disable Start at Login, warnings in system.log stop.
3. With Start at Login enabled, Lunar successfully starts at login, but warnings are still there.
4. I am not getting the `XPC error encountered` mentioned by @DamiansDesign so this is likely unrelated.

**Comment by krupenja** [comment]
I think I have found a workaround:

1. Disable Start at Login from Lunar icon in the menu bar.
2. Open macOS System Preferences.
3. Go to Users & Groups -> Current User -> login Items.
4. Remove Lunar from the list.
5. Re-add Lunar back to the list.
6. Reboot.

This way I Lunar starts on log in *and* system.log does not get spammed with warnings (and does not balloon to over 1GB rather easily). Works on my machine at least.

**Comment by alin23** [comment]
@krupenja @DamiansDesign It is possible that Login Items still contains the old Lunar login item that didn't work and that's causing the errors. That might explain why your workaround fixed that. Unfortunately I can't force remove that old login item from code.

**Comment by borekb** [comment]
"Start at Login" also doesn't have any effect in my case – after restart, I have to start Lunar manually.

- MacBook Pro mid-2015
- macOS Catalina 10.15.3
- Lunar was installed via `brew cask install lunar`

**Comment by bluestarstudios** [comment]
On iMac, macOS High Sierra 10.13.6. Lunar installed in /Applications. And just like all of the above reports, it never starts up when using the "Start at Login" option. Adding it in manually now.

**Comment by ahydronous** [comment]
@alin23 same for me, 'start at login' still isn't working. Could you reopen this issue?

**Comment by krupenja** [comment]
Can confirm that I also actually seeing this on a new Macbook with fresh install of macOS and 3.2.2 Lunar.

**Comment by alin23** [comment]
I confirm it happens to me too, I just don't know what I'm doing wrong with the LoginItem.

I'll do some more research into this over the week. I really want to fix this.

**Comment by ahydronous** [comment]
Alternatively, instead of adding Lunar to startup 'invisibly', why not add it to System Preferences > Users & Groups > Login Items?
Dropbox does this too, and frankly I dislike that most apps choose to do it with some invisimagic (meaning I don't have an explicit list of which third-party programs are started at boot)

**Comment by alin23** [comment]
@ahydronous that's exactly what I'm trying to do, using the official Apple guidelines. The code is already there and is trying to add the Lunar service to Login Items. But for some reason it is not working.

**Comment by ahydronous** [comment]
@alin23 I can confirm 'start at login' works now! I'm presuming the `LaunchAtLogin` framework uses the other method I spoke about, since Lunar does not appear in Login Items (which is fine, its nice to have but I'd rather have it working solid like this than not at all :) ). Thanks for fixing it!

**Comment by alin23** [comment]
> @alin23 I can confirm 'start at login' works now! I'm presuming the `LaunchAtLogin` framework uses the other method I spoke about, since Lunar does not appear in Login Items (which is fine, its nice to have but I'd rather have it working solid like this than not at all :) ). Thanks for fixing it!

Finally! Yes, LaunchAtLogin uses the method that can't show the login item. This is also what Apple recommends so we'll go with this one from now on.
