### ISSUE TITLE
Lunar Diagnostics Report [6CE8A45058758072F54074697BF63CB7812EF11E8376F8C02D9F416A38938400] [3.2.3]

### ISSUE THREAD

**Issue by rmangan** [alin23/Lunar#255]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *no*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Pro 2020 M1*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *HDMI cable to USB-C hub*

- Using an USB Docking Station or Hub:
    *yes*
https://www.amazon.com/gp/product/B084ZDPNTT/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*brightness does not adjust, tested sync, manual, location modes.*

**Comment by alin23** [comment]
#210
