### ISSUE TITLE
Lunar Feature

### ISSUE THREAD

**Issue by KamilKot95** [alin23/Lunar#256]
Is it possible to change the contrast limit in sync mode?

**Comment by alin23** [comment]
Hi!

What do you mean by contrast limit?

If you mean the limit applied when using the percent hotkeys,
you can go into manual mode and adjust the contrast limit on the Configuration page (the yellow one) and it will apply for all the modes.

**Comment by KamilKot95** [comment]
![image](https://user-images.githubusercontent.com/18318153/106384478-54f84600-63cb-11eb-88da-3e50dc453f08.png)
![image](https://user-images.githubusercontent.com/18318153/106384486-604b7180-63cb-11eb-9eb1-0b82629528b3.png)
As you can see in manual mode I have max contrast limit equal 100. But in sync mode, it is 70.

**Comment by KamilKot95** [comment]
ok, I already solved It.

I didn't know that elements:
![image](https://user-images.githubusercontent.com/18318153/106384638-347cbb80-63cc-11eb-8545-9847fd8f4405.png)
are editable here.

Thanks, great application.

**Comment by alin23** [comment]
Sorry for the confusion 😅 I'll try to make this more obvious in the next update
