### ISSUE TITLE
Lunar Diagnostics Report [B3B9036517CCBCC9971C1DCAEFD54517247FBE7505E09E03394E55D1931070B7] [3.2.3]

### ISSUE THREAD

**Issue by ptsayli** [alin23/Lunar#257]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook pro M1 chip

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Lunar doesn't work for me, It is not able to control my MacBooks or LG-34UC98 monitor.

**Comment by alin23** [comment]
#210
