### ISSUE TITLE
Issue with keyboard shortcut

### ISSUE THREAD

**Issue by Mic238** [alin23/Lunar#26]
Hi there, 

I feel like the step of +-3 when controlling with keyboard shortcut is just too small, I wonder if it can be increased or even customised. Also the app doesn't seem to be recognise long press and only count as one adjustment on long press.

In comparison, the apple native control (both display and volume) divides 0-100 into 16 levels, each change would be +-6.67, and long press is recognised as continuously increase/decrease. 

Otherwise it's a perfect app for external display, thanks for making it!!

**Comment by alin23** [comment]
I think I can make the step customizable in the next version, it's a good idea.

I didn't know about the long press thing. Continuous pressing the keys should repeat the shortcut based on the key repeat system setting: 
![image](https://user-images.githubusercontent.com/3819725/58339164-a6f47480-7e51-11e9-85ae-b48f9d9300e7.png)

I'll try to see what's wrong with that.

**Comment by Mic238** [comment]
I don't think key repeat auto applies to function keys - saying long press play/pause and making music start and stop just doesn't make sense, so it need to be recognised by code

**Comment by alin23** [comment]
Yes, I found that the issue is in the CGEvent listening implementation of the library I'm using [Magnet](https://github.com/Clipy/Magnet).

I think I'll better leave this as is, and implement the brightness/contrast up/down hotkeys using a different approach that also supports brightness keys.

**Comment by alin23** [comment]
We'll track this in #23 from now on
