### ISSUE TITLE
Lunar Diagnostics Report [45B71C3F1A4270C17B886D615E1B615B52E453106D8745BEBDABFCF9394020A0] [3.2.3]

### ISSUE THREAD

**Issue by ageva8** [alin23/Lunar#260]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    2018 Macbook Pro

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Max brightness even with extended mode does not reach display max brightness

**Comment by ageva8** [comment]
`ddcctl -d 1 -b 255` didn't work, but `ddcctl -d 1 -b 100` did. Seems my display doesn't return anything for the query with `ddcctl` -- don't know if that's the issue. Either way, Lunar seems to work fine in normal rather than extended mode for max brightness. So seems like switching to extended mode is what messed it up. Sorry!

**Comment by alin23** [comment]
Oh that makes sense then 😅 an extended range would mean that you would reach max brightness at about 39 `(100/2.55)` and anything above that wouldn't be allowed by your monitor.
