### ISSUE TITLE
Lunar Diagnostics Report [F1C06F5D5AA79C8DA53D305E8C37E1365BE44F7A5CDC0E1E9AACE34F192CE6E8] [3.2.3]

### ISSUE THREAD

**Issue by shah-ravi** [alin23/Lunar#262]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mac Mini M1 2020

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-HDMI

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Connected to a 4k TV (LG UN7300) that I use as a monitor. Cannot change brightness or contrast via Lunar.

**Comment by alin23** [comment]
#210
