### ISSUE TITLE
Lunar Diagnostics Report [E0B16BE459246C73945237A2A156C14600BDC96C9991B1B4C637BE7F1912B312] [3.2.3]

### ISSUE THREAD

**Issue by derplak** [alin23/Lunar#263]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *YES*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook Pro (Retina, 15-inch, Late 2013)*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *Thunderbolt output via Mini DisplayPort to VGA Adapter *

- Using an USB Docking Station or Hub:
    *Yes, an 2nd Gen TP-Link 7-Port USB 3.0 Ultra Slim Hub Including 3 BC 1.2 Charging Ports*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync + Adaptative*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *Nice resource but I didn´t know*

# Issue description:
*Only clicked Open Lunar Diagnostics and I came here*

**Comment by alin23** [comment]
I'm glad Lunar works for you! ^_^
