### ISSUE TITLE
Lunar Diagnostics Report [A92C722F65A26F749A6DDC3FA9FA53DAA6673329C853B8FDC03A9A4D038FDD74] [3.2.3]

### ISSUE THREAD

**Issue by firewhank** [alin23/Lunar#264]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mac mini 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI TO HDMI

- Using an USB Docking Station or Hub:
    NO

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    **

# Issue description:
My monitor is PHL 276E8V it's using HDMI 2.0 and basically can't change the brightness to any value .

Also my monitor specs says it has DDC/CI

**Comment by alin23** [comment]
#125 
It's a known hardware issue. Unfortunately, I can't do anything to fix it in software.

**Comment by firewhank** [comment]
I see, but from the monitor model or because of a component? Like the HDMI or something else

**Comment by alin23** [comment]
The Mac Mini HDMI connector is usually the issue. The USB-C port seems to work for other users.

**Comment by firewhank** [comment]
A just tried with an usb-c to HDMI and the program work. I just need to check if it handles 4k with 4:4:4:4 at 60 Hz. I've seen some posts saying the Mac mini 2018 could not do it over usb c
