### ISSUE TITLE
Respect system scroll direction for brightness and contrast values

### ISSUE THREAD

**Issue by svh1985** [alin23/Lunar#265]
### Name of the feature

Scrolling with my mouse in the brightness and contrast values feels weird because it is the opposite of how other scroll areas behave

### What problem does this feature solve?

Respect the system scroll direction setting

### How should the feature work

If the user has set scroll direction in the system to natural the scroll behavior inside of the value fields should act the same as other scroll area's

**Comment by alin23** [comment]
Hi!

Lunar already respects the scroll direction setting. You can see the code for that here:

https://github.com/alin23/Lunar/blob/master/Lunar/Views/ScrollableTextField.swift#L250-L254

With that logic above, scrolling up should always increase the value no matter what setting you have.
