### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by sametsafak** [alin23/Lunar#266]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook pro 2017, i7, 16GB Ram*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *DELL S2716DG 1440p*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C to HDMI*

- Using an USB Docking Station or Hub:
    *Yes*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Adaptive*

# Issue description:
I am using latest version of mac os big sur, when I minimize or maximize windows, my mac becomes very very laggy for 4-5 seconds like 1 fps. When I quit lunar, It becomes normal. Please check and fix this issue.

**Comment by alin23** [comment]
Hi! This is caused by your monitor having a slow response time and the lag happens because the macOS kernel has to wait for the response. 

Lunar can't cause lag like that.

**Comment by sametsafak** [comment]
Hi @alin23! Hmm. My monitor is a gaming monitor, with 1ms response time, gsync and 144hz but I guess you mean a different response time. When I quit Lunar im not having this lag. It's response seems normal. Btw im using hdmi port to connect. If you're not sure and need some logs, I can help. Thanks.

**Comment by alin23** [comment]
Yes, I'm not referring to the frame rate. Lunar works by sending a special type of message to the monitor through the DDC protocol. 

But Lunar doesn't send that message directly, it asks the macOS GPU driver to send it. After the driver sends the message, the whole system has to wait for the monitor hardware to respond to that message through the same DDC protocol. If the monitor is busy doing other stuff (like rendering 3.6 million pixels, 144 times each second), then the response will arrive late and you will feel like the system is unresponsive.

There's nothing we can do in software, logs wouldn't help. You could try a different connection like DisplayPort or USB-C but I can't be sure it would help.

**Comment by sametsafak** [comment]
Thanks a lot for detailed explanation. I was thinking buy a new macbook with m1 to get better GPU power... You saved my bucks!

**Comment by alin23** [comment]
Lunar can't work on M1 as it doesn't provide support for DDC. You would have lost support for Lunar completely 😅
