### ISSUE TITLE
Bug on M1 Air Big Sur 11.2  / Dell U2419HC 

### ISSUE THREAD

**Issue by Juliancheh** [alin23/Lunar#267]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   M1 Air, Big Sur 11.2

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2419HC 

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
   No (but the monitor has usb-c passthrough/usb ports)

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
I have been using Lunar with great joy on Catalina with a 2020 MacBook Air and this monitor.
Today I plugged in a brand new out of the box M1 Air. My monitor is not recognized by Lunar on this computer (whereas on my old Air the model name appeared on Lunar's list when I first installed the app). 
Nothing else augments the issue settings-wise. 
I am eager to get this working again and will so buy you coffees if you can save me from monitor unsync hell!

**Comment by alin23** [comment]
M1 doesn't have support for DDC: #210

**Comment by radioactive76** [comment]
Just a datapoint, the F1/F2 brightness controls (connected via a Thunderbolt 3 cable) *do* work with an M1 Mac Mini with the 27MD5KL (5k Ultrafine), without Lunar running. 

If you want access to the machine to see how it's working, let me know.

**Comment by Juliancheh** [comment]
Got it. Apologies for the redundancy! Thank you for all your hard work. I hope that some day I can use Lunar again :'')
