### ISSUE TITLE
Lunar Diagnostics Report [91027CD0F3E3A641474521C8B491602987624FAEC88C5860530F02CBCC14FA03] [3.2.3]

### ISSUE THREAD

**Issue by gregorreally** [alin23/Lunar#268]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
  2020 Mac Mini (Apple Silicon M1) - MacOS 11.2 Big Sur

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
 USB-C-to-USB-C

- Using an USB Docking Station or Hub:
No 
(My monitor, AOC 24P2C, includes a USB hub and KVM. However, Lunar can control my second 2011 Mac Mini (Intel)   - MacOS 10.13 High Sierra - so I don't think the hub/KVM functionality is necessarily an issue.)

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync and Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   Haven't tried.

# Issue description:
As mentioned above the monitor can be controlled by Lunar on a 2011 Mac Mini running MacOS 10.13 over HDMI. However on my new Mac Mini 2020 running MacOS 11.2 over USB-C Lunar doesn't pick up the monitor type/name. The monitor label is Moony and there is a red error message that says 'Non-responsive DDC'. Changing to HDMI on the M1 MacMini doesn't appear to make Lunar work - but that needs more extensive use case testing (ie rebooting the machine with no USB-C connection etc.) At this stage, I would suspect the M1 GPU or Big Sur being the issue.

**Comment by alin23** [comment]
#210
