### ISSUE TITLE
Lunar Diagnostics Report [BD0E7B65E7A01A12F0D4248391656D29427580CBC09C23AB29938E4BE60A8B39] [3.2.3]

### ISSUE THREAD

**Issue by SethCaldwell** [alin23/Lunar#271]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Mac Mini M1

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
HDMI to HDMI

- Using an USB Docking Station or Hub:
 No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
I was hoping that Lunar would be able to control my external monitor but it is not able to.

My monitor is the HP Z27. It is a 27" 4K LED Backlit IPS LCD Monitor.

**Comment by SethCaldwell** [comment]
Also did not work USB C to USB C.

**Comment by alin23** [comment]
https://github.com/alin23/Lunar/issues/210#issuecomment-766174204
