### ISSUE TITLE
about lunar

### ISSUE THREAD

**Issue by Shimmer2** [alin23/Lunar#273]
Hello! My monitor has three input ports, Two HDMI and one DP interface, MAC computer connection DP, Nitendo switch connection HDMI2, When I switch to HDMI2 playing switch games, And my MAC computer still controls the brightness and volume of the display, May I switch DP/HDMI2 by lunar?

**Comment by alin23** [comment]
Lunar 4 will be released soon and will support changing the input from the Mac device to other inputs. 

But using Lunar to switch from other inputs to the Mac device will not be possible because most monitors only allow controls from the current input.
