### ISSUE TITLE
Lunar Feature: Syncing home automation lights to monitor brightness

### ISSUE THREAD

**Issue by ajma** [alin23/Lunar#274]
### Name of the feature

Sync Brightness based on Philips Hue light

### What problem does this feature solve?

Synchronizing monitor brightness with my home automation lights

### How should the feature work

The easiest would be to pick a light from Philips Hue to sync with and then poll for the brightness and keep the monitor in sync with the Hue light.
A more manual option would be to have an API that could set the monitor brightness and then I can setup a virtual device on my home automation system that calls the API to set the brightness

### Visual description

*if this is a UI change, try to add an image of how you think this should look like*

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

Lunar 4 has CLI integration (open Lunar menu, click on **Install CLI Integration**).
So you could poll for any display brightness using something like:
```shell
lunar get brightness
```

... or if you have multiple monitors, poll a specific one using:
```shell
lunar displays CF4CF870-1DB2-B8D5-0857-D6964E3302DB brightness
```

And use that value to control whatever home lighting you have.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
