### ISSUE TITLE
Lunar Diagnostics Report [3B9E878F68E11F9D95ED9E0CAA303F0F0801D91155AC2469B6D0533A8AC7E560] [3.2.3]

### ISSUE THREAD

**Issue by aj-abdujabborov** [alin23/Lunar#277]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *no*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Pro 2020*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *HDMI to USB-c*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*Increasing/decreasing brightness has no effect on external monitor (though manually with its buttons, the monitor's brightness can be changed)*

**Comment by alin23** [comment]
Is your Macbook Pro 2020 the model with the M1 CPU?

If so, there's no way to send DDC messages on that CPU yet: https://github.com/alin23/Lunar/issues/210#issuecomment-766174204

**Comment by aj-abdujabborov** [comment]
No it has an Intel CPU. The issue is resolved though. It turned out that the HDMI to USB-C cable was the problem. Lunar worked (and resolution issues with my monitor were resolved) after I used an HDMI-to-HDMI cable with a 4k60fps HDMI-to-USB-C adapter. 
Thank you!
