### ISSUE TITLE
Lunar Diagnostics Report [776B59545D6230EDA44FD3F79765F315648FDD4F0BFBCA51F75E0127DB3EC4A7] [3.2.3]

### ISSUE THREAD

**Issue by DeeprajPandey** [alin23/Lunar#279]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2015

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI to HDMI

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    I did not try building ddcctl from source but I had tried the binary which didn't run and it said that the developer was not recognised.

# Issue description:
Using with BenQ GW2480 and DDI is enabled in the monitor menu. Unsure why it's not working.
It works when I use an HDMI to thunderbolt adapter and connect to the thunderbolt port but doesn't work on the HDMI port.

**Comment by alin23** [comment]
Use the connection that works. It's not a software problem that I can fix. some cables/ connectors simply don't work.
