### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by landoncope** [alin23/Lunar#28]
Just updated the app a day or two ago. When I have both external monitors plugged in, it crashes instantly. If I unplug the Dell U2412M, it doesn't crash. It's probably that unassigned UUID issue. How can I send a crash report?

**Comment by alin23** [comment]
I'm releasing a fix for that right now. Thanks for reporting!

**Comment by alin23** [comment]
@landoncope can you please try this version to check if the issue is solved: https://send.firefox.com/download/ea953962762c242b/#bf8KJZyLvaXg0qbwonkmLw

**Comment by landoncope** [comment]
Thank you, 2.8.2 resolved the crash.
