### ISSUE TITLE
Lunar Diagnostics Report [33DCF3C8FC4F6998F9A23B75398923F2343615335FB8CAE7AE7CAC93721720DC] [3.2.3]

### ISSUE THREAD

**Issue by hederickprinsloo** [alin23/Lunar#282]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *It only changed the brightness to very very low. Sync option only works every now and then. 

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook pro 16 inch i7

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB C to HDMI

- Using an USB Docking Station or Hub:
    *No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
  

# Issue description:
*Having the application on Sync does not work as expected. Changing brightess manually does the same. External display only reacts every now and then. not every time. LG 24 inch 4k monitor

**Comment by hederickprinsloo** [comment]
I also get the message, Non-Responsive DDC.

**Comment by alin23** [comment]
If you see **Non-Responsive DDC**, that means that the connection between the Macbook and the monitor is not stable enough. 

USB-C to HDMI cables usually have cheap converters inside them that can cause this, I had one myself that did this, bought for $30 from AliExpress. 

I'd recommend to invest in a better USB-C hub like the ones from Baseus. I had good experience with their products.

**Comment by hederickprinsloo** [comment]
Thank you.

I was thinking of buying a better hub that can handle 4k@60Hz in any case. 

I will reinstall the app then. 

Regards,,

HF Prinsloo
