### ISSUE TITLE
Lunar Diagnostics Report [ABC197A0F5259451C5650D885691F9092EF9E8095C2B0F69BF9534F122357485] [3.2.3]

### ISSUE THREAD

**Issue by ffledgling** [alin23/Lunar#284]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    2019 MBP 15"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to USB-C

- Using an USB Docking Station or Hub:
    Yes, but monitor usb-c does not go via hub, it's connected to the mac directly.

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Location

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    N/A

# Issue description:

Lunar periodically "forgets" the brightness and contrast settings and rests the monitor to the values set by the external monitor. This is very jarring, especially when working at night. It goes from 25 to 60 for example. It then does not turn back on it's own, instead when I open the lunar app's preferences UI and hit left arrow to go to the hotkeys page, it then somehow "remembers" and reapplies the settings.

I'm not sure why this happens and I haven't been able to see if any other mode has this issue, but I use location mode almost exclusively and this always has an effect.

This is a relatively recent problem (past 2ish weeks) and might possibly be related to the recent update to v3.2.3

**Comment by alin23** [comment]
That's odd. Lunar doesn't have to _remember_ a brightness, it just sends it to the monitor and the monitor sets it permanently. 

There are a few possibilities I can think of:
- something else modifies your monitor brightness (do you have other apps similar to Lunar running?)
- You accidentally press one of the percentage hotkeys (Ctrl-Cmd-0/1/2/3/4)
- Lunar has a bug in how it computes the brightness based on the sun position (although if Lunar sets the right brightness after opening the UI, it seems unlikely. Also what could actually happen here is that Lunar computes and sets a new brightness every 60 seconds on Location mode, so the UI opening might just be a coincidence and what you are seeing is the 60 seconds interval passing)

**Comment by ffledgling** [comment]
@alin23 Thanks for the prompt reply.

(1) is a possibility, I use osx's built-in night-shift. I can dry disabling it to see if that changes anything
(2) I don't think this is the case, the brightness is often set to 60% or 55%, which afaik is not an accessible setting from the %age hotkeys
(3) This seems in line with what I've seen, when I look at the monitor menu I see both contrast and brightness set to 55 and 60 for example. You could totally be right about the UI coincidence, but it happened at least 3 times that I can recall, which seemed more casual then coincidental.

In a situation where the monitor's display cable is unplugged and replugged into the computer, or the monitor's power is unplugged and replugged, would that cause the monitor to "reset" somehow? I'm trying to eliminate possible physical causes where a lose cable causing a blip doesn't cause a reset.

**Comment by alin23** [comment]
1. Night shift doesn't affect the monitor hardware brightness, it simply changes the color temperature in software. Lunar works very well with Night Shift so you can keep it on.
2. The percentage hotkeys also take into account your limits. So for example if you have MIN brightness set to 20 and MAX set to 90, then 50% would mean `(50% * (90 - 20)) + 20` **=** `55`

Yes, if the monitor is replugged, Lunar resets the list of displays, but doesn't reset the brightness or contrast values, it keeps the last values, so I don't think it could be this.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
