### ISSUE TITLE
Lunar Diagnostics Report [7C58F3868FA9CA1F0C72EA8623C52BB9715F8D4E6C5AFD3B6B05D082BEFE716D] [3.2.3]

### ISSUE THREAD

**Issue by araujoantonio** [alin23/Lunar#285]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Tried on Macbook Pro 13 2017 and Macbook Pro 15 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Tried on HDMI-to-USB-C and with hub (HDMI-HDMI)

- Using an USB Docking Station or Hub:
    yes and no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync and Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Does not work on a Samsung 4K TV

**Comment by alin23** [comment]
Hi! TVs don't support DDC commands. Only monitors.
