### ISSUE TITLE
Lunar Diagnostics Report [F38584EF6379F4DC320FA835678C7513CDEB36815789ED5E586ED4FC7929DFD5] [3.2.3]

### ISSUE THREAD

**Issue by kapsyst** [alin23/Lunar#289]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Macbook Pro 2019 (16 inch)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB-C to HDMI via KVM switch (works when directly connected)

- Using an USB Docking Station or Hub:
Using PWAY KVM switch

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
No

# Issue description:
Dell U2417H monitors.
Detects monitors but they do not respond to brightness changes from Lunar. Bypassing the PWAY KVM switch works perfectly - any idea why this may be?

**Comment by alin23** [comment]
The KVM switch is not forwarding the DDC messages properly. It is a hardware problem and can't be fixed in software.
