### ISSUE TITLE
Unreachable links in help texts

### ISSUE THREAD

**Issue by hmijail** [alin23/Lunar#29]
The informative/help text that appears on hover over the small *i*s (like the ones by the offset controls) show a link. That link is physically unreachable because when one moves the mouse cursor from the *i*, the whole text goes away. 
And if the goal is to make it a skill game, it's too hard! ;)

**Comment by alin23** [comment]
Oh yeah, I forgot about that 🤦‍♂️

Thanks for letting me know, I'll fix it this week. Until then, you can click on the link here:

[How does the curve factor affect brightness?](https://www.desmos.com/calculator/zciiqhtnov)

**Comment by alin23** [comment]
This should be fixed now :)
