### ISSUE TITLE
Apply current brightness/contrast settings on wake from sleep

### ISSUE THREAD

**Issue by c-bandy** [alin23/Lunar#292]
### What problem does this feature solve?

My external screen does not persist settings written by DDC/CI on startup. This means if the computer goes to sleep (and so does the screen) then the brightness and contrast settings will be reset to default on wake, which is highly annoying.

### How should the feature work

Apply the current brightness/contrast on wake from sleep. If this causes side effects screens that do not work this way then it can be added as a setting.

---

I don't know if there are other setups that work this way but that has been the experience with this screen. It would be awesome if Lunar could help me solve this problem 🙏

**Comment by alin23** [comment]
That's odd, I've never heard of a monitor that does that. 

I'll add this feature in the next version, it shouldn't cause any problems for other monitors.

**Comment by c-bandy** [comment]
Yeah, I actually think my monitor has a defect ^^;

**Comment by orkhan10** [comment]
I have the same problem. Please consider fixing this soon! ❤️

**Comment by nicbou** [comment]
Same here. I wake the computer from sleep in the morning, in Location mode, and the display is at minimum brightness, no matter what I do. I have to use manual mode instead.

**Comment by orkhan10** [comment]
I am always on manual mode. This happens on manual mode to me. But lately after waking it from sleep it has a higher brightness than it was before the sleep. (As I have mentioned in the above it used to wake with minimum brightness)

**Comment by alin23** [comment]
@orkhan10 @nicbou Thanks for further validation!

I already fixed this and will be released soon in Lunar 4. I'm preparing for a beta testing week in a few days so if you'd like to help, please send me a message about this here: https://alinpanaitiu.com/contact/

**Comment by alin23** [comment]
Fixed in Lunar 4. Download it from the official website: https://lunar.fyi
