### ISSUE TITLE
Lunar Diagnostics Report [70FE0F6C2386028A9B4BD21E8546A41E520495A3E7661F2EA151A63EB070FF09] [3.2.3]

### ISSUE THREAD

**Issue by brianc118** [alin23/Lunar#293]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MBP 16" 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   MBP -> USB-C / Thunderbolt Hub (Displayport MST) -> HDMI to monitor

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Any

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
None of the controls work

**Comment by alin23** [comment]
Try bypassing the DisplayPort hub if possible. This is a hardware connection problem and can't be fixed in software.
