### ISSUE TITLE
Samsung U28E590D not working

### ISSUE THREAD

**Issue by BerkeAras** [alin23/Lunar#294]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Mac Mini M1 2020*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *Samsung U28E590D*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *HDMI-HDMI*

- Using an USB Docking Station or Hub:
    *no*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

# Issue description:
*Cannot set brightness of Samsung U28E590D*

**Comment by alin23** [comment]
#210
