### ISSUE TITLE
Lunar Diagnostics Report [88DD9009223394F45FA8981EB00084865B1D730FFC0AFE1130E1979073538AF3] [3.2.3]

### ISSUE THREAD

**Issue by stephanie-walter** [alin23/Lunar#297]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    macbookpro 2020 bigsur M1

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DELL U2518D Display (connected in DP to USBC)

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    manual but none of them work

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   I dont know how to compile

# Issue description:
It was working on a MBP 2017, same external screen, same cable. I switched to the MBP 2020 M1 (with touchbar) and it doesnt.

**Comment by alin23** [comment]
#210
