### ISSUE TITLE
Lunar Diagnostics Report [DD56128A709A034C0F97996A5E3DA52940D718C1689CACDEA356B3F11055C34C] [3.2.3]

### ISSUE THREAD

**Issue by mrquatsch** [alin23/Lunar#299]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mac mini m1

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    [monitor type] [monitor connection]-to-[computer connection]
    Dell P1924H HDMI-to-HDMI
    Dell P1924H DisplayPort-to-usb-c

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Application can't control monitor settings

**Comment by alin23** [comment]
#210
