### ISSUE TITLE
Lunar Diagnostics Report [60B9B38EC98013FFF433F4DB477BF76791A295D875EDA2D4240EBA707500D724] [3.2.3]

### ISSUE THREAD

**Issue by Permanento** [alin23/Lunar#302]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Air 2020 M1

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Thunderbolt

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Each of them

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
External monitor haven't changed brightness in each mode. I have Samsung C34J791WTI

**Comment by alin23** [comment]
#210
