### ISSUE TITLE
Lunar Diagnostics Report [767F6190A9DA3D517D50CCC5A9BC3917F8BFCD6087043E101A402FBB58C25B96] [3.2.3]

### ISSUE THREAD

**Issue by Marcusly17** [alin23/Lunar#303]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *no*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook Air 2020 M1*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C-to-USB-C*

- Using an USB Docking Station or Hub:
    *no*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location and Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*nothing works*

**Comment by alin23** [comment]
#210
