### ISSUE TITLE
Lunar Diagnostics Report [7F6C5BD41C74BE6A7DD22D35BDD11EBFB2AA97509DA4FD81E7F310E89667BDEB] [3.2.3]

### ISSUE THREAD

**Issue by mikewiener** [alin23/Lunar#304]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    2020 mac mini

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-HDMI

- Using an USB Docking Station or Hub:
    yes 

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
brightness controls don't work, it doesn't seem to be detecting the monitor correctly

**Comment by alin23** [comment]
If it's the M1 Mac Mini, check #210 

Otherwise, Mac Mini HDMI port is known to have problems: #125
