### ISSUE TITLE
Lunar Diagnostics Report [DEDC92FAB7FBBBF1712C93161E17EC1684461BFFFD8BBE3752CCE568A146AFFA] [3.2.3]

### ISSUE THREAD

**Issue by bbuchalter** [alin23/Lunar#309]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (13-inch, M1, 2020) macOS 11.2.3

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
```
~/Downloads/bin/release$ ddcctl -d 1 -b 1
D: CGDisplay 056F0324-37BE-54C4-0857-D6964E3302DB dispID(#2) (1920x1080 0°) HiDPI
I: found 1 external display
E: Failed to parse WindowServer's preferences! (/Library/Preferences/com.apple.windowserver.plist)
I: polling EDID for #1 (ID 2 => (null))
E: Failed to poll display!
```

# Issue description:
Tried to change brightness, but could not.

**Comment by alin23** [comment]
#210
