### ISSUE TITLE
Lunar Diagnostics Report [0B1AB908C18C1A090A66720609D481D0B7431D7374D9DE0643AA5B105E1EAFB4] [3.2.3]

### ISSUE THREAD

**Issue by bastien2101** [alin23/Lunar#317]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *write response here*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *write response here*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *write response here*

- Using an USB Docking Station or Hub:
    *write yes or no here*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location or Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Comment by bastien2101** [comment]
Thank you so much.

I missed Lunar a lot.

I am very happy.

Bastien.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bastien2101** [comment]
I bought the pro version.

Is it possible to sync with location ? I did not succeed.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by alin23** [comment]
Could you send a screenshot of what doesn't work?

Location mode should be available if you gave Lunar permissions to retrieve the device location.

Lunar should have prompted you for permissions of first launch.

**Comment by bastien2101** [comment]
okay it seems to work.

Can I custom the curve when on location mode ?
And would there be a way to be on sync mode with a light sensor ?

Bastien.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by alin23** [comment]
You can adjust the curve of Location mode by simply setting the brightness to what you need it to be. Lunar will learn from that. More details here: https://lunar.fyi/#curve

There's also a Curve Factor on the Configuration page of Lunar, that will adjust the slope of the curve.

Sync mode is only meant for Macs with a built-in light sensor (Macbooks, iMacs). What device are you using?

**Comment by bastien2101** [comment]
I am using macmini.

So I guess it is not possible to sync with light in my room.

But location is good.

Thank you.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
