### ISSUE TITLE
Lunar Diagnostics Report [988AB194C17472AEE0B159E6C490E0F05AAC5785F7753627D329798C6D502513] [3.2.3]

### ISSUE THREAD

**Issue by stephenhau** [alin23/Lunar#319]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MBP 16 inch, late 2016

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
LG5K first version, via Thunderbolt

- Using an USB Docking Station or Hub:
MBP -- LG5K -- USB hubs

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Thank you for Lunar, I love it! 
I cleared the keyboard shortcuts, but they keep reappearing. I don't want to use keyboard shortcuts with Lunar as they clash with shortcuts used by other programs (various Adobe apps, custom shortcuts in BetterTouchTool).

**Comment by alin23** [comment]
If you click the **x** button to clear the shortcut, it will be disabled, even if it reappears. You can notice that the text is white/discolored when it reappears after disabling. It is only enabled when the text is yellow

**Comment by stephenhau** [comment]
Thank you for your explanation alin23! Unfortunately, I had to uninstall Lunar for now – the MBP display kept going really dim at unexpected moments during a project. I'll give it a try again later.

**Comment by alin23** [comment]
Weird, Lunar doesn't control the MacBook builtin display in any way. It only controls the external monitors. 

What you're describing usually happens to me (unrelated to Lunar) when I manually set the brightness of the MacBook really low in an environment with lots of ambient light, and macOS learns that mapping and next time the light sensor reads the same value it dims the display too much.

**Comment by stephenhau** [comment]
Hi Alin, yep, weird! Your explanation is very possible, so I'll give Lunar another try - thanks!
