### ISSUE TITLE
Can't navigate between screens on a Wacom pen & touch tablet

### ISSUE THREAD

**Issue by mvaneijgen** [alin23/Lunar#32]
The left and right swipe works perfectly to move between screens on my build in track pad, but when I use this app I'm at my desk and use a Wacom tablet (which has pen and touch support). And swiping on that device nothing happens and because the dot at the bottom are not interactive (great idea to do make them interactive). 

Also having just a right and left arrow would be really appreciated.

**Comment by alin23** [comment]
You can navigate by using the left and right arrows on the keyboard

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gianlucatruda** [comment]
> You can navigate by using the left and right arrows on the keyboard
> 
> Sent with [GitHawk](http://githawk.com)

Arrows keys aren't working for me. Has anyone else experienced that issue?
