### ISSUE TITLE
Lunar Diagnostics Report [4495A45845B026A00C5A90D29E717D0289C2189688680355711D60A69CE58D5F] [3.2.3]

### ISSUE THREAD

**Issue by ikdunby** [alin23/Lunar#322]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *No*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Mac Air M1 2020*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *HDMI-to-USB-C*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *All tried*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*The app is unable to change brightness on external display
Dell P2419H*

**Comment by alin23** [comment]
#210
