### ISSUE TITLE
Lunar Diagnostics Report [BB351BB2DBE0922CEDF60D7BB76D19D3325401E7E4EDCA3B1F2BB6113AACD563] [3.2.3]

### ISSUE THREAD

**Issue by arielle-s** [alin23/Lunar#325]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no :(

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Mac mini (M1, 2020)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB-C-to-USB-C

- Using an USB Docking Station or Hub:
   no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
  manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
doesn't change anything! I've also tried other app I found online, Monitorcontrol, it doesn't do anything either:(

**Comment by alin23** [comment]
#210
