### ISSUE TITLE
Lunar Diagnostics Report [C5F06E93629CCB06BA34ECBD313A6FDC0C9163D923D1D751CBE92C88C1B93E7A] [3.2.3]

### ISSUE THREAD

**Issue by ElMudo** [alin23/Lunar#326]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mac Mini (2020, Apple silicon, M1)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C

- Using an USB Docking Station or Hub:
    No (direct connection, single cable, no adapers)

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual (Sync and Location had no affect)

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    Haven't tried (Xcode is not installed on this device)

# Issue description:
Brightness controls have no affect. Same for contrast. Apple's on-screen brightness feedback is displayed, but the brightness does not change. Your program (which looks great, by the way!) works with this same monitor (Dell U2520D) connected via HDMI to a Macbook Pro (2020). So I thought I'd try it on the Mini too. The problem is probably due to the Mini using Apple silicon. I'll try you extra diagnostic tool when I have the time to install xcode. Thanks for what is a really nice tool (on Intel silicon) ^_^

**Comment by alin23** [comment]
M1 will be supported soon using Gamma tables: #210
