### ISSUE TITLE
Feature request: Show Brightness/Contrast Level while pressing keys

### ISSUE THREAD

**Issue by jans-y** [alin23/Lunar#33]
**Hi,**

**Thank you for a great software.**

I have switched to yours from _KAMIKAZEUA/NativeDisplayBrightness_ which I forked to include contrast controls, however it stopped working after update to 10.14.6.

The feature I miss is the some kind of current brightness/contrast level UI. MonitorControl and NDB both use Apple-like UI which is not necessary for me to look the same.

I also like on NDB that it shows current level next to the icon in the menu bar.

**Thank you for consideration.**

**Comment by alin23** [comment]
The problem is that reading the brightness and contrast through DDC doesn't work. I can do something to show the last brightness sent by Lunar but I have no way to show the actual brightness of the monitor

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jans-y** [comment]
Hi,

I think it is perfectly okay to show last Lunar’s values.

I am aware that it could be incorrect in some edge cases so this could be optional.

Thanks

**Comment by alin23** [comment]
This has been implemented in 2.9.3
