### ISSUE TITLE
Lunar Diagnostics Report [428712B95A0C22EB28F769A053CC17FE8EBC0DB0FA66299FC3586DC9F98F91BA] [3.2.3]

### ISSUE THREAD

**Issue by jeremypng99** [alin23/Lunar#330]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *yes*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Pro 2017*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *hdmi to usbc*

- Using an USB Docking Station or Hub:
    *yes*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*
unable to use media keys to change brightness of external monitor

**Comment by alin23** [comment]
Lunar 3.2.3 is not supported anymore.

Download latest Lunar 4 from the official website or click on Check for Updates in the Lunar menu to update.

**Comment by jeremypng99** [comment]
hi, I updated to the latest version and I still face the same issue. am unable to control brightness of the screen through brightness keys even though the external monitor is the active monitor.

**Comment by alin23** [comment]
Sorry, I should have mentioned this first: media keys work a bit differently in Lunar 4.

Read more about this here: https://lunar.fyi/faq#hotkeys

You should try Ctrl+Brightness keys for controlling the external monitor, the cursor placement is not taken into account anymore, unless you want to fine tune a single monitor in a multi-monitor setup
