### ISSUE TITLE
Lunar Diagnostics Report [D959943D96EB26D7C151560A0752F61530CA266C8F9F22F4D8C28670E43574FC] [3.2.3]

### ISSUE THREAD

**Issue by WebRitual** [alin23/Lunar#331]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Air M1

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI

- Using an USB Docking Station or Hub:
    yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    has an issue with installing.

# Issue description:
Can't adjust Dell UltraSharp U2719D 27 brightness and contrast.

**Comment by alin23** [comment]
Lunar 3.2.3 is not supported anymore.

Download latest Lunar 4 from the official website or click on Check for Updates in the Lunar menu to update.
