### ISSUE TITLE
Support for Apple Cinema displays 

### ISSUE THREAD

**Issue by Siioh** [alin23/Lunar#332]
### Name of the feature
Support for Apple Cinema Displays (the ones before the Apple LED Cinema).

### What problem does this feature solve?
The Apple Cinema Displays feature a USB connection to control brightness just like the Apple LED Cinema Display.  Including these displays would allow for hardware-based control of the Apple Cinema Display brightnesses.  As of now, it seems to only recognize using software-based control for this display, even though my Mac has the availability to change the brightness through software (just like the Apple LED Cinema Display and Apple Thunderbolt Display).

### How should the feature work
Should be integrated just like the other displays.

### Visual description
N/A

**Comment by alin23** [comment]
@Siioh can you post a screenshot of the Lunar UI so I can see how Lunar recognizes this monitor?

Also try Lunar Diagnostics and click on Send Diagnostics afterwards. That should detect if the display supports the same method used for LED Cinema displays.

**Comment by alin23** [comment]
I added support for this in Lunar 4.0.5 but only by guessing the monitor name as I haven't received any further details from you, and there aren't any readily available details on the internet about these monitors' firmware data.

Let me know if 4.0.5 still doesn't work and please provide the details asked in the last comment if possible.

**Comment by Siioh** [comment]
Hi, sorry for the delay.  I have just sent the diagnostics from Lunar 4.0.5 and have attached a screenshot of what it shows for my Apple Cinema Display in Lunar 4.0.5.
![Screen Shot 2021-05-31 at 1 48 44 PM](https://user-images.githubusercontent.com/6395622/120227486-3db15400-c217-11eb-83e8-c77d9b7975dd.png)

**Comment by alin23** [comment]
Yes, that **Native Controls** tag means that Lunar controls brightness using the same method used for Ultrafines and LED Cinema.

Does it not change anything?

Also, about diagnostics, you haven't finished the process.
Read carefully what the diagnostics say as it prompts you to press some keys for continuing the tests.

You missed this:
> Press any key to start tests for this display... (click outside this container if keys don't work)

**Comment by Siioh** [comment]
I have sent another set of diagnostics with comments at the bottom.  Let me know what you think.

**Comment by alin23** [comment]
Ok got them. The numbers look right. For example here, the brightness of the built-in display was set to `1`, the Sync Mode algorithm sent `20` to the Cinema HD monitor, and then Lunar read back the brightness using CoreDisplay and it really is `20`.

----

### Setting built-in brightness to `1` using `displayServices`

Built-in brightness (as reported by):
* IOKit: `0.0830078125`
* ARM Props: `0.0`
* CoreDisplay: `0.0830078125`
* DisplayServices: `0.009999999776482582`
* Sync Mode Consensus: `8.30`

Cinema HD monitor brightness (as reported by CoreDisplay): `20`

----

1. Are you not seeing any change in brightness? The connection part seems to work ok.
2. Does changing the brightness through macOS's native controls work in any way? (menu bar, control center, or from System Preferences)

**Comment by Siioh** [comment]
Notably, after trying on my LED Cinema Display too, the CoreDisplay method still doesn't work.  It resorts to DDC, which does work successfully for it.  I have sent another set of diagnostics for it.

There is no change in brightness for the Cinema HD Display when running that set of diagnostics above even though it seems to report it changed in the diagnostics.  However, all of the macOS native controls work as expected through the menu bar/control center and from System Preferences.

**Comment by alin23** [comment]
I guess that means macOS is using other private APIs to control the displays. I have no idea really.

I'll take a look again through CoreDisplay's functions, maybe it's one of those `SetLinearBrightness` functions instead of `SetUserBrightness`.

I'll send you a test build through email when it's ready. But it will take a few days as I really need a break now.

Thank you for the detailed feedback on this! It really helps.

**Comment by alin23** [comment]
Hey could you try this build and see if it works? https://static.alinpanaitiu.com/Lunar.zip

**Comment by Siioh** [comment]
Hi, the diagnostics on this build crashes immediately upon starting diagnostics (it gets to the page where it says it will begin, then crashes).

Otherwise, trying to manually adjust the brightness on the Apple Cinema Display through this build of Lunar still does not change the brightness.

**Comment by alin23** [comment]
Try this build, which has a few more fixes: https://static.alinpanaitiu.com/Lunar2.zip

If diagnostics still crash, let me know.
Also, please click on **Install CLI Integration** in the Lunar menu to install the `lunar` command and then try the following commands in the **Terminal** and see if your monitor reacts to any of them:

**these should set the monitor brightness to 20%**

```shell
lunar core-display SetDynamicLinearBrightness first 0.2
lunar core-display SetLinearBrightness first 0.2
lunar core-display SetUserBrightness first 0.2

lunar display-services BrightnessChanged first 0.2
lunar display-services SetBrightnessSmooth first 0.2
lunar display-services SetBrightness first 0.2
lunar display-services SetLinearBrightness first 0.2
```

Please also post the results of these commands:

```shell
lunar display-services CanChangeBrightness first
lunar display-services IsSmartDisplay first
lunar display-services AmbientLightCompensationEnabled first
lunar display-services HasAmbientLightCompensation first
```

**Comment by Siioh** [comment]
The diagnostics still crash on this build.

The first set of commands is able to successfully change the brightness of the Apple Cinema Display.

Here are the results of the second set of commands:

![Screen Shot 2021-06-06 at 2 45 59 PM](https://user-images.githubusercontent.com/6395622/120936476-f2df8280-c6d5-11eb-976e-146d3d40836a.png)

**Comment by alin23** [comment]
I need to know which one of the commands did change the brightness. All of them?

**Comment by Siioh** [comment]
Specifically, from the first set of commands, the monitor changes in brightness in response to:

`lunar display-services SetBrightnessSmooth first 0.2`

and

`lunar display-services SetBrightness first 0.2`

It seems to increase brightness with the first command, then decrease the brightness on the second command.

**Comment by Siioh** [comment]
Here are some screenshots for reference:

![Screen Shot 2021-06-06 at 2 54 11 PM](https://user-images.githubusercontent.com/6395622/120936692-1eaf3800-c6d7-11eb-802c-b87ae6ea547e.png)
![Screen Shot 2021-06-06 at 2 54 18 PM](https://user-images.githubusercontent.com/6395622/120936693-1f47ce80-c6d7-11eb-869b-3209b311ee1f.png)

**Comment by alin23** [comment]
Try multiple values for the second command  (run them one by one, don't paste all of them at once):
```shell
lunar display-services SetBrightness first 0.1
lunar display-services SetBrightness first 0.5
lunar display-services SetBrightness first 1.0
lunar display-services SetBrightness first 0.2
```

Does the perceived brightness correspond to the value used?

**Comment by Siioh** [comment]
Yep, this changes the perceived brightness.

It also reflects this change in the macOS control bar brightness and System Preferences as expected.  They all appear to be the corresponding percentages (10%, 50%, 100%, 20%) of the brightness bar too.

**Comment by alin23** [comment]
The last build I sent actually uses that exact method for setting the brightness for Cinema HD displays. Are you sure it doesn't work when changing the brightness from the Lunar UI?

Can you make sure **Smooth Transition** and **Refresh values from monitor settings** are disabled in the Lunar Configuration page? 

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/3819725/120936874-eaf20380-c712-11eb-80e4-ec1e51533e19.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/3819725/120936895-0a892c00-c713-11eb-97c6-38d44a9a36e5.png">

**Comment by Siioh** [comment]
I have attached a video of trying to adjust the brightness through Lunar in the most recent build that you sent.  The screen does not seem to change brightness after scrolling for the brightness value.

https://user-images.githubusercontent.com/6395622/120937183-04c32480-c6da-11eb-87e3-120303eff6c8.mov

**Comment by alin23** [comment]
Try this build: https://static.alinpanaitiu.com/Lunar3.zip

**Comment by Siioh** [comment]
Using this build, the CoreDisplay method works for both my Apple Cinema HD Display and Apple LED Cinema Display!

The brightness control through the Lunar UI and diagnostics both work on this build.  If helpful, I have just sent those diagnostics.

Thanks for your continued effort to resolve this!

**Comment by alin23** [comment]
Awesome 👏 I'll include this in the next update, hopefully tomorrow

**Comment by alin23** [comment]
Done in v4.1.0!
