### ISSUE TITLE
Lunar Diagnostics Report [46A6BBB770C4D5CA6D387696BA7975314EDB958D54B657F5802714530C1CCF18] [3.2.3]

### ISSUE THREAD

**Issue by florind1587** [alin23/Lunar#333]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   Macbook pro 15" 2015, on MacOS Mojave

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   HDMI

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Can't assign new shortcut for brightness/contrast (CTRL+brightness button).
Using the shortcut for brightness, the max brightness is achieved at 40%.

**Comment by francosalcedo** [comment]
Same here.

**Comment by alin23** [comment]
Hi! Lunar 3 is not supported anymore. 

Lunar 4 can be downloaded from the [official website](https://lunar.fyi) and only supports macOS Catalina or higher.
