### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by bcaddy** [alin23/Lunar#334]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook pro 2018

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG Ultragear 34GP83A-B

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI

- Using an USB Docking Station or Hub:
    yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    n/a

# Issue description:
I'm not sure if this is a Lunar issue or a macOS issue. Until today I could adjust the brightness of the active monitor (whichever one had an active window) with the F14 and F15 keys. Now those keys only adjust the brightness of the internal monitor. The brightness of the external monitor can be adjusted with CTRL+F1 or CTRL+F2 but those only adjust the external monitor.

**Comment by alin23** [comment]
It's a new behaviour introduced by Lunar 4. Read more about it (and how you can revert it) here: https://lunar.fyi/faq#hotkeys

**Comment by bcaddy** [comment]
I’m sorry, I don’t see where it talks about my issue in the hot keys section or how to revert to the previous behavior

**Comment by alin23** [comment]
Oh sorry, wrong link. This is the good one: https://lunar.fyi/faq#monitor-with-cursor

**Comment by bcaddy** [comment]
I followed those instructions but it didn't change anything. It's still using the new behavior

**Comment by alin23** [comment]
Are you using Sync Mode? There's a special case for that, explained in the Hotkeys FAQ.

----

#### Special cases of Brightness keys

These special cases apply when 2 or more external monitors are used with Lunar.

* **Sync Mode**
    * *Brightness keys (with no modifiers) are ignored* by Lunar and handled by the system
    * This ensures the built-in display is adjusted by keys, and the external monitors are adjusted by the Sync algorithm
* **No built-in display** (MacBook lid closed, Mac Mini, Hackintosh)
    * `Ctrl`+`Brightness` controls the monitor where the cursor is
    * This allows for fine tuning the Sync curve per monitor, by only using the keys and not having to use the Lunar UI

**Comment by bcaddy** [comment]
Nope, manual only. I have a single external monitor and laptop is open as I'm using that as my secondary display

**Comment by alin23** [comment]
Hmm indeed, in the case of laptop with lid open and single display, Lunar ignores the brightness keys entirely and leaves the system to handle it.

Only Ctrl+Brightness will control the external monitor.

I prefer not to take my hands off the keyboard when controlling monitors so I like to be able to use only the keyboard for both laptop and external monitor. There's no way to go back to the old behaviour in this case, sorry.

**Comment by bcaddy** [comment]
Bummer, thanks for your help

**Comment by pakerwreah** [comment]
I spent days trying to fix this issue, which ends up being a "new feature" 🤷🏻‍♂️ 
Why not make this an option to have 100% the old behavior?
