### ISSUE TITLE
Unresponsive after 4.0.0

### ISSUE THREAD

**Issue by iRoachie** [alin23/Lunar#336]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2016

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2515H

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C Digital AV Multiport Adapter (from apple)

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Since v4.0.0 the app crashes by itself after some time by itself. When checking Activity Monitor it seems the application is hitting 100% and going non-responsive. The solution is to force close the process and restart the application. I'm currently on 4.0.5 and I've had to do this twice today.

**Comment by alin23** [comment]
This is an isolated issue related to your setup as me and a lot of other users don't have this problem. 

Could you please run some diagnostics? Click on **Open Lunar Diagnostics** in the Lunar menu, press keys when prompted by the text, and after the process ends click on **Send Diagnostics**
