### ISSUE TITLE
Not working for Philips PHL 346B1C

### ISSUE THREAD

**Issue by vizFlux** [alin23/Lunar#337]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *Philips PHL 346B1C*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C-to-USB-C*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *All modes*

# Issue description:
*Decrease and increase brightness against the mentioned monitor is not working*

**Comment by alin23** [comment]
Is it possible that you're running into this problem: https://lunar.fyi/faq#always-asks-for-permissions

Or are you trying to change the brightness using the UI and that doesn't work either?

Some diagnostics would help here as well. 

Click on **Open Lunar Diagnostics** in the Lunar menu, press keys when prompted by the text, and after the process ends click on **Send Diagnostics**.

**Comment by vizFlux** [comment]
> Is it possible that you're running into this problem: https://lunar.fyi/faq#always-asks-for-permissions
> 
> Or are you trying to change the brightness using the UI and that doesn't work either?
> 
> Some diagnostics would help here as well.
> 
> Click on **Open Lunar Diagnostics** in the Lunar menu, press keys when prompted by the text, and after the process ends click on **Send Diagnostics**.

Not able to finish the diagnostics, but stuck at this point

```Looks like your setup doesn't support DDC
This means Lunar won't be able to control the hardware values of your monitor through the connected cable

The following features won't be supported:
	•	Changing the hardware brightness (hardware, as in, the same brightness you can change using the monitor's physical buttons)
	•	Changing the hardware contrast
	•	Changing the monitor volume
	•	Switching to another monitor input
	•	Powering off the monitor

Lunar will still be able to decrease (but not increase) brightness using gamma tables, a software control method. If you see the red Software Control tag under the monitor name, you should manually set the monitor brightness and contrast to the highest possible values using the monitor physical buttons.```

**Comment by alin23** [comment]
Really? No _press any key to continue_ prompt after this last line?

**Comment by alin23** [comment]
I have a few fixes prepared for 4.0.6 but nothing directly related to this problem (as I can't reproduce it or find what causes it)

I'll try to fix as many things as I can and hopefully something will indirectly fix this as well. 

But if you could try a few more times, maybe the Diagnostics process will finish at least once and I would have the technical data needed to figure this out.

**Comment by vizFlux** [comment]
> Really? No _press any key to continue_ prompt after this last line?

It was there, but I was not able to proceed even following the exact instructions multiple times.

**Comment by alin23** [comment]
You have to make sure to not click on the scrolling text as that steals focus and the key events are not registered anymore. 

Simply open Diagnostics and press keys until finished. Only click on the send button when it ends. 

I'll do something about this focus problem but right now there are a lot of edge cases I have to treat first.
