### ISSUE TITLE
Not working with Duet Display

### ISSUE THREAD

**Issue by samwzlim** [alin23/Lunar#338]
Is Lunar supposed to be able to work with Duet Display? I have an old iPad hooked up to my mac via Duet Display and it only works with software controls in the Lunar app.

**Comment by alin23** [comment]
No, hardware brightness (and volume) can only be controlled using DDC which is a cable communication protocol over HDMI/DisplayPort/Thunderbolt/DVI/VGA.

Virtual displays like Sidecar, Airplay or Duet don't support this.
