### ISSUE TITLE
Lunar Diagnostics Report

### ISSUE THREAD

**Issue by Hitmn1** [alin23/Lunar#339]
# Issue details
- Network mode failure on iMac M1 and LG27UL850-W

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    iMac M1 2021

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to USB-C (Thunderbolt 3 cable)

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    ---

# Issue description:

I have the following problem. My iMac M1 is connected to a LG 27UL850-W via USB-C. Furthermore, a Raspberry Pi Zero W is connected via HDMI and the DDC server is installed. If I switch the monitor to the HDMI input with the Raspberry Pi Zero W and I query the server via Safari, it says "OK". But as soon as I switch to the USB-C connection of my iMac M1, the query only returns an "Error". What am I doing wrong? All updates for the Raspberry Pi Zero W are installed, Lunar on the Mac is also up to date.

**Comment by alin23** [comment]
Try turning off the monitor, wait a few seconds, then turn it on again. 

Some monitors have some voodoo ritual like this that needs to be done until they accept 2 inputs at the same time.

**Comment by Hitmn1** [comment]
This doesn't solve the problem.

**Comment by alin23** [comment]
Unfortunately this is not a problem with Lunar, you have to find the method that makes your monitor accept 2 inputs. 

I have the exact same monitor with Macbook Pro M1 on USB-C and Pi Zero W on HDMI.
When DDC doesn't work from Pi, turning off the monitor completely (while the input is set to USB-C) and turning it on again usually fixes this for me.

Try running the diagnostics with the input of the monitor iMac M1. You should see some more details, like this:

----

### The assigned network controller wasn't able to control this monitor

#### If you have technical knowledge about `SSH` and `curl`, you can check the following:
* See if the controller is reachable using this curl command: `curl http://192.168.1.51:3485/displays`
  * You should get a response similar to the one below:
  * ```
    Display 1
      I2C bus:  /dev/i2c-2
      EDID synopsis:
         Mfg id:               GSM
         Model:                LG Ultra HD
         Product code:         23304
         Serial number:
         Binary serial number: 314041 (0x0004cab9)
         Manufacture year:     2017
         EDID version:         1.3
      VCP version:         2.1
    ```
  * If you get `Invalid Display` try turning your monitor off then turn it on after a few seconds
  * If you get `Display not found`, make sure your Pi is running an OS with a desktop environment, and the desktop is visible when the Pi HDMI input is active
* Check that the server is running
  * SSH into your Pi
  * Run `sudo systemctl status ddcutil-server`
* Check if `ddcutil` can correctly identify and control your monitor
  * SSH into your Pi
  * Run `ddcutil detect` _(you should get the same response as for the `curl` command)_
  * Cycle through a few brightness values to see if there's any change:
    * `ddcutil setvcp 0x10 25`
    * `ddcutil setvcp 0x10 100`
    * `ddcutil setvcp 0x10 50`
