### ISSUE TITLE
Settings don't work (brightness/contrast min/max/locked)

### ISSUE THREAD

**Issue by kerberjg** [alin23/Lunar#34]
I'm using Lunar 2.8.3 on macOS 10.14.5 (iMac Pro)

When trying to change the brightness and/or contrast min/max values (or constant locked) either in Location or Manual mode, I see the numbers change in preferences, but they're not applied to monitors. Whenever I close the Preference window and open it again, the values are always reset to: 0, 100, unlocked.

The adaptive location mode does work (minus for the aforementioned issue) and manual mode with the status bar percentage options works as well, however I'm unable to set any custom values myself.

I'm running two Dell P2414H monitors using DisplayPort.

**Comment by alin23** [comment]
Try to run Lunar diagnostics from the menu bar icon and send me the log. Sounds like there's a problem with the db file not being saved (maybe some wrong permissions, I can't be sure).

**Comment by kerberjg** [comment]
There you go: https://transfer.sh/GNsG1/lunar.log

Also screenshots for reference:

Before closing:
![Screenshot 2019-09-02 at 21 04 55](https://user-images.githubusercontent.com/16939117/64130870-5e8c1180-cdc5-11e9-9527-944d752151d0.png)

After closing and reopening:
![Screenshot 2019-09-02 at 21 05 10](https://user-images.githubusercontent.com/16939117/64130871-6055d500-cdc5-11e9-868a-3d303a5e2ba2.png)

**Comment by kerberjg** [comment]
PS: Location Services are enabled for Lunar in System Preferences

**Comment by alin23** [comment]
There's no error about the settings in the log. I also get this problem from time to time but I never found what causes it. 

Can you try to exit Lunar from the menu bar and relaunch it? 

I'm out of ideas for now, I have to find a better way to debug these things.

**Comment by 1player** [comment]
Same here, with an LG 27UD69P. The locked setting seems to work, but setting min and max values has no effect whatsoever.

**Comment by kerberjg** [comment]
@alin23 I already have before sending the logs, as well as reinstalling everything (after having deleted all configs and logs from ~/Library)

Another thing I notice is that most settings from the leftmost pane aren't saved either, like Noon duration, Daylight extension and Curve factor.

Exceptions and "Smooth transitions" are always saved correctly, though I'm unsure about Location.

When I set the manual percentage via the menu bar entries, that setting is correctly kept after a reboot too.

**Comment by alin23** [comment]
I have a possible fix in the working. I'll try to release an update in the next few days. I just have to test it more on my setup to make sure I don't screw up something else in the process

**Comment by alin23** [comment]
@1player @kerberjg I released Lunar 2.9.0 with some fixes on the settings side. I hope this is fixed because I really don't know what else to try.

I'll close the issue for now, feel free to reopen it in case it is not solved yet.

**Comment by ahydronous** [comment]
This issue still persists for me.

I'm on Catalina 10.15.1 (19B88), Lunar 2.9.0

**Comment by alin23** [comment]
This should be fixed on 2.9.1. It was a read file permission setting that was missing
