### ISSUE TITLE
Can't use media keys since last update

### ISSUE THREAD

**Issue by paw-lu** [alin23/Lunar#340]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macboook Pro 2019*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *[LG 27UK850-W 27" 4K UHD IPS Monitor with HDR10 with USB Type-C Connectivity and FreeSync, White](https://www.amazon.com/gp/product/B078GVTD9N/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C-to-USB-C*

- Using an USB Docking Station or Hub:
    *no*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *N/A*

# Issue description:

I'm unable to use the media keys (<kbd>☼</kbd> and <kbd>🔊</kbd>) to modify the volume and brightness of my monitor after the prompted for an update.

I've tried going through the FAQ and issues, I must be missing someting. I've made sure Lunar is enabled under `Accessibility`, have `Listen for brightness\volumn keys` as ☑, and have `Send keys to all monitors` as ☐. <kbd>⌃</kbd> + <kbd>☼</kbd> also does not seem to work for the external monitor. The hotkeys (<kbd>⌃</kbd> + <kbd>F1</kbd>, etc), all seem to work as expected

<img width="1062" alt="Screen Shot 2021-06-03 at 8 35 38 AM" src="https://user-images.githubusercontent.com/30049606/120672891-8fd8bc00-c447-11eb-9e62-0972e606500e.png">

<img width="780" alt="Screen Shot 2021-06-03 at 8 42 40 AM" src="https://user-images.githubusercontent.com/30049606/120673027-ada62100-c447-11eb-97d0-6ce8f9492b5d.png">

---

Thanks for sharing your work! It's been really useful.

**Comment by alin23** [comment]
It's most likely a corrupt permissions DB. A lot of users encountered this, I have no idea what causes it but until now I only had Catalina users report it, so I'm guessing it is a macOS bug fixed in Big Sur.

Here are some troubleshooting steps you could take to fix this: https://lunar.fyi/faq#always-asks-for-permissions

**Comment by paw-lu** [comment]
> A lot of users encountered this

Apologies for not finding those!

> I have no idea what causes it but until now I only had Catalina users report it

FWIW I'm on Big Sur 11.3.1

---

Thanks for the helping out! I'll test out the linked steps!

**Comment by paw-lu** [comment]
Running

```sh
tccutil reset all fyi.lunar.Lunar
```

and restarting fixed it for me.

Thanks @alin23 for helping me out! Appreciated!
