### ISSUE TITLE
Recursive call makes Lunar consume 100% CPU and stop responding

### ISSUE THREAD

**Issue by kopiro** [alin23/Lunar#348]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 2019 16"

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG 27UL + Dell U2419H 24"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to HDMI for the LG - USB-C to USB-CDongle to HDMI for dell

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    No

# Issue description:

I've seen this CPU spikes happening so often after last Pro upgrade..

![image](https://user-images.githubusercontent.com/839700/121016525-854a5980-c79c-11eb-9802-edcc95983cc4.png)

**Comment by alin23** [comment]
Hi @kopiro ! Thanks for the report, I'm aware of the issue and almost done with fixing it. I'm hoping to release a new version with a fix today or tomorrow.

Could you please help me with some more details to make sure I'm not missing something? A process sample from Activity Monitor would be helpful:
![image](https://user-images.githubusercontent.com/3819725/121022586-217b5d00-c7ab-11eb-9c3d-08f978d34cd5.png)

**Comment by nanot1m** [comment]
I have the same issue
[Spindump.txt](https://github.com/alin23/Lunar/files/6622042/Spindump.txt)
[Sample of Lunar.txt](https://github.com/alin23/Lunar/files/6622043/Sample.of.Lunar.txt)

**Comment by alin23** [comment]
Thanks for the debug data!

I managed to finally fix this. I'll release the fix as soon as possible.

**Comment by alin23** [comment]
This should be fixed in v4.1.0. Let me know if it still happens and I'll reopen this.

Process samples from Activity Monitor would be very helpful if anyone encounters this issue again.
