### ISSUE TITLE
Lunar Diagnostics Report [38B82F11E935D63DACD9EFADC2E45CD8C010BA35411FA89D8C6A8A9BD34E6EC0] [3.2.3]

### ISSUE THREAD

**Issue by varunoberoi** [alin23/Lunar#349]
Both volume & brightness media keys won't work with the external display. It was working before, stopped working after an update.

**Comment by alin23** [comment]
Hi @varunoberoi!

Lunar 3.2.3 is not supported anymore.

Download latest Lunar 4 from the official website or click on Check for Updates in the Lunar menu to update. 

If you have problems with brightness and volume keys not working, follow the steps here: https://lunar.fyi/faq#always-asks-for-permissions

The current version of Lunar 4 has some memory errors that can arise in very specific situations so if you notice crashes, please be patient as I'll release a build with a lot of fixes today or tomorrow.
