### ISSUE TITLE
Lunar leaks memory

### ISSUE THREAD

**Issue by hhelenav** [alin23/Lunar#353]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
   MacBook Air (Retina, 2020)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell UltraSharp U2520D, happens without external display, too

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync with external display, manual without

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    No, as "Open Lunar Diagnostics" is not clickable. Might be, because there is no external display.

# Issue description:
Lunar seems to leak memory. After running Lunar 4.0.5 for a few days it uses up to >33GB of memory. After quitting and relaunching it, it starts with ~14MB and got up to 81,5MB while writing this issue.
<img width="746" alt="Bildschirmfoto 2021-06-14 um 19 11 56" src="https://user-images.githubusercontent.com/33583023/121933543-83593b00-cd46-11eb-87a7-1266df548d17.png">

**Comment by alin23** [comment]
Thanks for the details!

Lunar should consume about 200MB with the UI loaded, and about 80MB when it is in background. This is definitely a bad memory leak, I'll look into it.

**Comment by alin23** [comment]
This should be fixed in v4.1.0. Let me know if it still happens and I'll reopen this.

**Comment by hhelenav** [comment]
Did not happen again, after installing the update. Thank you!
