### ISSUE TITLE
Disabling automatic update

### ISSUE THREAD

**Issue by fredericmalo** [alin23/Lunar#354]
Hello, 

Where can I disable automatic update checks please? I cannot find any way in preference pane, but it surely exists in some config files, thanks !

**Comment by alin23** [comment]
You can swipe right to the Configuration page (the yellow one) and click on Advanced. 

That's if you're on Lunar 4. Lunar 3 doesn't have this option exposed in the UI, but you might be able to disable it using the command:

`defaults write site.lunarapp.Lunar SUEnableAutomaticCheck 0`

**Comment by fredericmalo** [comment]
Too great, thanks !
