### ISSUE TITLE
Sync mode stopped working with last update

### ISSUE THREAD

**Issue by dacrypt** [alin23/Lunar#357]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 16' 2019

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG HDR 4k

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    The send button is blue, but clicking on it does nothing

# Issue description:
Only manual mode is available. It was working before applying previous update. I tried restarting, reinstalling, powering on/off, etc.

------------------------------------

Note: Don't copy/paste this output in an email as that is not enough. Clicking the Send Diagnostics button will send more useful technical data. If you want to aid the developer in debugging your problem, make sure to complete the full diagnostics by pressing the necessary keys when prompted.
Diagnosing display LG HDR 4K [997499D0-F172-8E37-BD4B-593E52DB4F2B]
	•	ID: 459096059
	•	EDID Name: LG HDR 4K
	•	I2C Controller: 122639
	◦	This monitor should be controllable through DDC
	•	Network Controller: NONE
	◦	This monitor can't be controlled through the network
	•	DDC Status: responsive
	•	Apple vendored: NO
	◦	DisplayServicesCanChangeBrightness: false
	◦	DisplayServicesHasAmbientLightCompensation: false
	◦	DisplayServicesIsSmartDisplay: false
	◦	DisplayServicesGetBrightness: 0.00 [error]
	◦	DisplayServicesGetLinearBrightness: 0.00 [err or])
	◦	Doesn't support CoreDisplay
	•	Vendor ID: 7789
 
Press any key to start tests for this displ ay...

Testing DDC Control:
Do you want to test reading brightness?

Caution!! This can cause a kernel panic and you'll have to restart your MacBook Pro if it happens!

Press the Enter key to test reading. Press any other key to skip reading test and continue diagnostics...

Reading brightness...

Received brightness value: 50 (50.00%)

	•	Setting brightness to 1
	•	Setting brightness to 100
	•	Setting brightness to 25
	•	Setting brightness to 50
4 out of 4 tries seemed to reach the monitor
Was there any noticeable change in brightness? : YES

Press any key to continue diagnostics...

Diagnostics done for display LG HDR 4K [997499D0-F172-8E37-BD4B-593E52DB4F2B]

If you want to send diagnostics, make sure to fill in the Name and Email fields. Don't copy/paste this output in an email as that is not enough, clicking the button will send more useful technical data.
You can also add additional comments below this line.

Only manual mode is available. This stopped working with latest (before the hotfix) update

**Comment by alin23** [comment]
@dacrypt is your Macbook lid closed? Sync Mode can only work if the lid is open.

**Comment by dacrypt** [comment]
Is opened. It was working fine for months until I installed the last update

**Comment by alin23** [comment]
Maybe the builtin display detector logic was broken by compiling with Xcode 13. I'll take a look. 

Could you please install the CLI integration from the Lunar menu and run `lunar builtin all` and post the output?

**Comment by alin23** [comment]
@dacrypt Can you check if Lunar 4.1.2 fixes your issue? 
Click on Check for updates in Lunar menu to update.

**Comment by dacrypt** [comment]
Unfortunately, it didn't fix the issue. :( 

https://imgur.com/a/CPSJRrs

```
➜  ~ lunar builtin all
ID: 69734662
Brightness: 89.55
Contrast: 89.55
```

**Comment by alin23** [comment]
@dacrypt I just released v4.1.4

Your question surfaced a lot more issues with Sync Mode. I hope this fixes your problem.

**Comment by dacrypt** [comment]
This was totally my fault. I was trying to use a pro feature of the new lunar version 4,  without actually applying a license. I'm sorry for wasting your time. Thanks for providing this fantastic tool.

**Comment by alin23** [comment]
No worries ^_^

**Comment by nicbou** [comment]
I have the same issue. I used to be able to use location mode. Does that mean the feature was removed from the free version?

**Comment by alin23** [comment]
@nicbou Lunar 3 is still free and available for download if you'd rather use that. The download link is on the front page: https://lunar.fyi

Lunar 4 has been launched about 1 month ago after 1 and a half years of work on improving Lunar 3 and it still is mostly free. 

But yes, Location Mode is one of the Pro features now as you can see here: https://lunar.fyi/#pro
