### ISSUE TITLE
Forgot to sign the binary?

### ISSUE THREAD

**Issue by ErinPo** [alin23/Lunar#36]
It looks like the current release's DMG was not signed with an Apple developer ID.

**Comment by alin23** [comment]
The current version is signed with a free developer certificate.
This is what `codesign` says:
> codesign --verify ~/Downloads/Lunar-2.8.3.dmg -v
        ~/Downloads/Lunar-2.8.3.dmg: valid on disk
        ~/Downloads/Lunar-2.8.3.dmg: satisfies its Designated Requirement


I'm in the process of releasing a new version signed with a paid Apple developer certificate, hopefully notarised and published on the App store also.

**Comment by ErinPo** [comment]
Yeah, a notarized binary would be ideal for Catalina. Great to hear you are working on it.

**Comment by alin23** [comment]
@ErinPo Lunar 2.9.0 is now properly signed and notarized ^_^

I'll close the issue for now, feel free to reopen it in case it is not solved yet.
