### ISSUE TITLE
Lunar seems to ignore custom colour profiles

### ISSUE THREAD

**Issue by jcass77** [alin23/Lunar#365]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro M1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
   Samsung LU28E590DS

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   USB-C-to-DisplayPort, USB-C-to-HDMI

- Using an USB Docking Station or Hub:
    Same result with and without

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    Yes

# Issue description:
I have a custom colour profile calibrated, which is slightly warmer than the standard. For some reason this is not reflected in the below screenshot but the observed white point is **much** more red:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/10268911/122663460-e9a4ea00-d19a-11eb-9216-49726b5a7cb3.png">

The moment that Lunar adjusts the brightness (either due to the brightness changing on the synced internal display or by pressing Control+F1 or F2), it seems to revert to the cooler default profile:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/10268911/122663328-df362080-d199-11eb-8929-dad7b7e0fe0f.png">

The calibrated profile appears to become effective again when I open the 'Displays' system settings and click on the 'Colour' tab, but only until Lunar again adjusts the brightness.

The colour profile is also the same on the native display, though this has no effect.

**Comment by alin23** [comment]
To be able to change brightness on M1, Lunar changes the Gamma table values (which are the same values that a colour profile changes).

Lunar actually honours the gamma values that are already set by other programs as you can see by the `initial<color>Gamma` values here:

https://github.com/alin23/Lunar/blob/4b87220e08daae3a0c4691e1659e4244e9d9ecb1/Lunar/Data/Display.swift#L1562-L1576

If the changed gamma value isn't visible by Lunar, there's no easy way to know what that profile values are.

**Comment by alin23** [comment]
@jcass77 
It's better to change the temperature of the monitor directly from the monitor's own settings by using its physical buttons or touch controls. 

Those values can't be changed by Lunar.
