### ISSUE TITLE
Setting minimum contrast by typing a value is not possible

### ISSUE THREAD

**Issue by jjeising** [alin23/Lunar#366]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
   MacBook Pro 2016

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
   Multiple Dell Displays

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   DisplayPort

- Using an USB Docking Station or Hub:
   Thunderbolt Hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Sync Mode

- Tried Lunar Diagnostics?
   No.

# Issue description:

When trying to enter a value for minimum contrast, I'm able to type in the field. I'm not able to leave the field via Tab, as this enters a tab in the input field. I'm not able to leave the field with Enter. If I leave the field with escape, the entered value persists, but is not used or accepted. After restarting Lunar, the previous value is used.

This happens if the entered value for minimum is greater or equal the maximum.

**Comment by alin23** [comment]
That is normal. It wouldn't make sense to have a minimum value equal or greater to the maximum.

**Comment by jjeising** [comment]
> That is normal. It wouldn't make sense to have a minimum value equal or greater to the maximum.

I totally understand your constrain. But maybe there could be some kind of error message or reset to the maximum possible value? Currently the only indication is, that I'm not be able to leave the input. If I press Escape I leave the input and the value will persist, but it won't be accepted:

https://user-images.githubusercontent.com/40333/122800830-b1e59180-d2c3-11eb-9b85-f30a18f86981.mp4

(75 is the maximum value in this example, `[3] [0] [Enter], [9] [9] [Enter] [Enter] [Space] [Backspace] [Tab] [Backspace] [Esc]` are the inputs).

**Comment by alin23** [comment]
Indeed, it's a bit confusing when it doesn't do anything on Enter/Tab, and a lot more confusing when the value persist on Escape. 

I haven't tested this in a while so I didn't know what the experience is like. I'll try to convey why the value is not accepted.

**Comment by alin23** [comment]
This is fixed now, the window should shake if the text field value is invalid.
