### ISSUE TITLE
Locked Contrast is not respected

### ISSUE THREAD

**Issue by jjeising** [alin23/Lunar#367]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
   MacBook Pro 2016

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
   Multiple Dell Displays

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   DisplayPort

- Using an USB Docking Station or Hub:
   Thunderbolt Hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Sync Mode

- Tried Lunar Diagnostics?
   No.

# Issue description:

In sync mode, a locked contrast setting is not respected. Only setting minimum = maximum helps, which is still limited, because minimum has to be one smaller than maximum.

Screenshots with Locked enabled while changing brightness:

![2](https://user-images.githubusercontent.com/40333/122688751-6a58fa00-d21e-11eb-94f3-56ebb58d8a1c.png)
![1](https://user-images.githubusercontent.com/40333/122688752-6af19080-d21e-11eb-9666-3c07ffd3d5e7.png)

**Comment by alin23** [comment]
Ok I'll take a look.

**Comment by alin23** [comment]
This should be fixed in 4.2.2

**Comment by jjeising** [comment]
Thank you, looks like it works fine here 🎉
