### ISSUE TITLE
Lunar asks for Accessibility Access on every Start

### ISSUE THREAD

**Issue by jjeising** [alin23/Lunar#369]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
   MacBook Pro 2016

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
   Multiple Dell Displays

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   DisplayPort

- Using an USB Docking Station or Hub:
   Thunderbolt Hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Sync Mode

- Tried Lunar Diagnostics?
   No.

# Issue description:

Lunar shows the "Accessibility Access" dialog on every start, while working fine without these rights. When using Lunar in Sync Mode and using only some (higher?) F-keys for controlling external display brightness Lunar works totally fine without granting accessibility access.

![3](https://user-images.githubusercontent.com/40333/122688945-b22c5100-d21f-11eb-8db0-a3e2c5b2a7ee.png)

**Comment by alin23** [comment]
It is a macOS bug. Read about how to fix it here: https://lunar.fyi/faq#always-asks-for-permissions

**Comment by jjeising** [comment]
> It is a macOS bug. Read about how to fix it here: https://lunar.fyi/faq#always-asks-for-permissions

The FAQ says:

> Lunar asks for Accessibility permissions **even though I already gave it permissions**. Location mode is greyed out.

But I didn't gave permissions to Lunar. I don't think lunar needs this permission as it works fine without. Shouldn't it be possible to use Lunar without granting the permission?

Am I missing something here?

**Comment by alin23** [comment]
Oh I see. Lunar requires the permission to listen for brightness and volume key events. If you don't want to use that, disable **Listen for brightness/volume keys** on the Hotkeys page and Lunar won't ask for permissions anymore.
