### ISSUE TITLE
Brightness offset does not work

### ISSUE THREAD

**Issue by krupenja** [alin23/Lunar#37]
1. Enable Sync mode.
2. Under configuration, change Brightness offset to some custom value (e.g. -50 or 50).
3. Close Lunar preferences,
4. Open preferences again.

The Brightness offset value is back to default (-9).

macOS 10.14.6, MacBook Pro 13" Mid-2014, Dell U2518D monitor.

**Comment by alin23** [comment]
Thanks for reporting! I'm aware of the settings not being saved issue. I'm still trying to find the cause, but it takes time because I'm also busy with finding a job.
