### ISSUE TITLE
Check for updates automatically popup cannot close

### ISSUE THREAD

**Issue by tapitapeh** [alin23/Lunar#370]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro M1 / 16GB/ 512GB / Big Sur 11.3.1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2720Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to USB-C

- Using an USB Docking Station or Hub:
   -

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    Yes

# Issue description:
Check for updates automatically popup cannot close. Not sure if its the Lunar bug or Big Sur bug.
Please check attachment below.

![ezgif-2-d70f82db85b4](https://user-images.githubusercontent.com/7647443/122806617-225cd480-d2fd-11eb-881d-158635a00ce1.gif)

Thanks

**Comment by alin23** [comment]
Hard to say if it is macOS or [Sparkle](https://sparkle-project.org) (the updater framework), but it's definitely not a Lunar issue. 

I'll take a look at the [Sparkle repo](https://github.com/sparkle-project/Sparkle) to see if this issue is known
