### ISSUE TITLE
About the main display

### ISSUE THREAD

**Issue by Shimmer2** [alin23/Lunar#371]
After connecting the extended display, Mac will distinguish between the main display and the secondary display. When opening the app from the extended display dock, the window is on the main display by default. Can lunar automatically set the display where the mouse is located as the main display? For example, when the app is opened on the extended display, the window is on the extended display. When the main display opens the app, the window is displayed on the main display. It would be great to add this function! thank you!

**Comment by alin23** [comment]
Doesn't this happen by default?

I'm away from a monitor now, so I can't test this. 
Can you do a screen recording where you click on the Lunar dock icon on the external display? I think that should open the window on the display where you clicked.

**Comment by alin23** [comment]
This should now behave as expected in v4.5.1
