### ISSUE TITLE
Orange dot on screen

### ISSUE THREAD

**Issue by iRoachie** [alin23/Lunar#372]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 15, 2017

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2515

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    I ran it but did not send.

# Issue description:
There's an orange dot on the monitor when lunar is running. I haven't seen it anywhere in issues or the FAQ.

https://user-images.githubusercontent.com/5962998/122940732-bac97800-d342-11eb-9d6b-7f28ede40aea.mp4

**Comment by alin23** [comment]
That is an indicator for when Lunar is doing lengthy operations like:
* Smooth transitions on brightness/contrast
* Sending brightness/contrast over the network to a Raspberry Pi controller

It should only blink until the operation is done, not stay visible at all times. I'll check why it doesn't disappear in some cases.


https://user-images.githubusercontent.com/3819725/122941533-241aac80-d37e-11eb-8aa8-5ab3693e700a.mp4

**Comment by alin23** [comment]
This should be fixed in 4.2.3. Click on Check for Updates in the Lunar menu to upgrade.

I've also posted some info about what the dot represents here: https://lunar.fyi/faq/#yellow-dot
