### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by StefanoChiodino** [alin23/Lunar#373]
Hey, I love lunar and have used it for a few months.

This happened for the first time today:
<img width="273" alt="Screenshot 2021-06-22 at 18 38 25" src="https://user-images.githubusercontent.com/1428893/122973599-51b92300-d389-11eb-80ec-cb88c5c46cf8.png">

**Comment by alin23** [comment]
I know there's a memory leak somewhere but I haven't been able to find it as this happens so rarely.

If it ever happens again, can you please send a process sample before you quit the app?

To do that, find Lunar in Activity Monitor, select it, click on the 3-dots menu and click Sample Process

<img width="1337" alt="Shot_Activity Monitor_Activity Monitor_vRyfMnWW" src="https://user-images.githubusercontent.com/3819725/122990418-96a28100-d3ac-11eb-990a-43874ed929a5.png">

**Comment by StefanoChiodino** [comment]
Thanks, I had to kill it and didn't think about this, but hopefully I'll track it down for you 👍

**Comment by alin23** [comment]
@StefanoChiodino 

Please give Lunar 4.5.1 a try and let me know if this still reproduces. 

I think I've fixed most of the big leaks for now.
