### ISSUE TITLE
Network controls lost after M1 Macbook wakes up from sleep

### ISSUE THREAD

**Issue by aaaldo** [alin23/Lunar#375]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
Macbook M1 + Raspberry Pi Zero W

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
LG 27UK670 / BK7U

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB-C-to-USB-C for the mac, HDMI for the Pi

- Using an USB Docking Station or Hub:
No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Sync

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

Yes

# Issue description:
Hello, I'm currently facing a problem regarding Lunar networks controls. Every time my macbook goes back from sleep, Lunar loose its connexion with the network controls. Only solution i've found is to use the "reset network controls" manually, but this method is not producing expected results all the time either.

I've set a Pi Zero W as suggested, plugged it on my monitor on another HDMI port for display out. I've also plugged it on a dedicated power outlet.

**Comment by alin23** [comment]
Lunar already has 3 separate safe measures to try to reconnect to the Pi after the Mac wakes up, but they can still fail if those measures are applied when the monitor is still not responding for the Pi. Lunar will still keep retrying indefinitely, so if the Pi can control the monitor, Lunar should eventually select Network Control for the monitor

I'm sorry but there's nothing more I can do here. Some manual work will always be needed in these cases where so many things can fail (monitor takes too long to wake up, monitor starts blocking non-visible inputs, Mac resetting the monitor output multiple times on wake etc.)

If clicking the Reset Network Controls button doesn't work, nothing will work until the monitor starts accepting commands from the Pi again (which I usually fix by turning off the monitor completely, then turn it on again)

If you think Lunar should work with Network Control when it doesn't, try doing a curl request to the Pi to see what Lunar sees and why it can't use the Pi:
```shell
curl <your Pi hostname>.local:3485/displays
```
