### ISSUE TITLE
Add comparison of free/paid version of Lunar to FAQs

### ISSUE THREAD

**Issue by corbinschwartz** [alin23/Lunar#376]
### Name of the feature

Comparison of free vs paid version of Lunar

### What problem does this feature solve?

I'm considering buying a license, but I'm not aware of which features are paid and which which are free.
From checking Lunar.fyi (and the readme of this repo) it isn't clear what requires a Pro license.

### How should the feature work

Make a standard table of free / paid features available somewhere

### Visual description
```
             Free | Pro
Feat1         x   |  x
Feat2         x   |  x
Feat3             |  x

```

**Comment by alin23** [comment]
This will soon be detailed here: https://lunar.fyi/pro

**Comment by alin23** [comment]
Comparison table added here: https://lunar.fyi/#pro
