### ISSUE TITLE
Single dot flashing on display

### ISSUE THREAD

**Issue by kistanovdev** [alin23/Lunar#379]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro (16-inch, 2019)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
C34J79x:
  Resolution:	3440 x 1440 (UWQHD - Ultra-Wide Quad HD)
  UI Looks like:	3440 x 1440 @ 60.00Hz

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
  Connection Type:	Thunderbolt/DisplayPort

- Using an USB Docking Station or Hub:
 no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Any

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    yes

# Issue description:
- There is a single yellow light flashing on my screen. I couldn't tell where it was coming from. I force quit all the apps, it was still there. Then, I started force quitting the extensions. The lunar pro is the one causing this issue.  It disappears after a restart, but sometimes it turns on again. It happened on Big Sur, and now is happening on Monterrey.

**Comment by alin23** [comment]
https://lunar.fyi/faq#yellow-dot

The current version has a bug where the dot keeps blinking when it shouldn't. A fix will be released soon.

**Comment by kistanovdev** [comment]
My apologies. I tried to look on the website, but I guess I am not good enough at looking around :)

**Comment by alin23** [comment]
No worries 😌 Lunar has become quite complex and information about it is scattered all around. 

I'll try to keep every useful info on the website and faq from now on so keep checking those if you have questions about anything. 


And if you can't find the info there, [contact me](https://alinpanaitiu.com/contact) so I know to update the website 😊
