### ISSUE TITLE
Entire system slows down and monitor disconnects?

### ISSUE THREAD

**Issue by jswilliams** [alin23/Lunar#38]
I'm not sure how to get any debug info on this since when I run the diagnostics the monitor ends up disconnecting and then it doesn't show that there's any diagnostics information available. Is there an area a flat file should be saved that I can access?

Basically what's happening is when I change the contrast/brightness manually or when it changes automatically in sync mode, the entire system starts lagging. The mouse pointer will jump around and both the built in monitor and external monitor starts skipping/dropping frames. After about 5 seconds of this the external monitor goes black and essentially disconnects from MacOS. If I unplug the dongle and plug it back in (or do the same with the HDMI) then the monitor comes back on and Lunar starts syncing again, until the next time a large contrast/brightness change happens which just causes the slow down/monitor disconnection again.

I'm running a Mid 2018 15" MacBook Pro with a 560X. I have a LG 34UC80-B 34-Inch 21:9 Curved UltraWide QHD monitor connected via one of the official Apple USB-C HDMI/USB/USB-C dongles.

Let me know if there's anything I can add to this to help.

**Comment by alin23** [comment]
Try to disable Smooth Transition on the Lunar settings page and see if that fixes your issue. Some monitors have slow DDC response times and Smooth Transition does a ton of DDC requests. Unfortunately I have no way of logging hardware timing issues like this so we can only try to solve this by trial and error 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jswilliams** [comment]
Thanks, that's all it was, I should've read the help tooltip better before enabling it.

**Comment by jswilliams** [comment]
Actually it's still happening, just not as often. My monitor must have an extremely slow DDC processing speed.

Maybe an option that adds a debounce time to the DDC requests could mask the issue and prevent the monitor from crashing (at the cost of making it even less smooth). I mainly work with C# and TypeScript but I could try taking a look at it if you have a lot on your plate right now.

**Comment by alin23** [comment]
Yes, sounds like a debounce would be the best idea for slow monitors. I'll work on that on Monday. Also if you'd like to learn some swift, feel free to send a rough PR, everything helps as I'm very busy with a new job at the moment.

Thanks for reporting all these details! I wouldn't have been able to fix this issue otherwise 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alin23** [comment]
Also thank you for the generous donation! Always brightens my day to see that people care enough about my work to spend a few dollars on it 😊 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by darshanprakash** [comment]
I have always been searching for a solution to control external displays since the first time I ever connected my mac to an external display. Thanks a lot for developing this tool. I'm your fan!

**Comment by alin23** [comment]
@jswilliams Try the new polling interval setting in Lunar 2.9.0 to fix this. I'll close the issue for now. 

Feel free to reopen it if it doesn't fix your issue ^_^


@darshanprakash thank you for the kind words! I'm happy to hear you find Lunar so useful!
