### ISSUE TITLE
Lunar Bug: How to turn on my monitor after using the turn off button

### ISSUE THREAD

**Issue by phucty** [alin23/Lunar#380]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro 16 2020

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Acouto Mobile Monitor, 17.3 Inches
    https://www.amazon.co.jp/-/en/Monitor-Non-Shiny-Included-Lightweight-Compatible/dp/B08LL3PKXK

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    *write yes or no here*

# Issue description:

I use Lunar to turn off the monitor as the photo. Then, I could not turn on the monitor anymore. This monitor does not have a power button. I can't use the monitor now. Could you please help me resolve the issue?

![Screen Shot 2021-07-06 at 18 00 40](https://user-images.githubusercontent.com/41727776/124573052-26076400-de84-11eb-872f-dbc26121d120.png)

**Comment by alin23** [comment]
After a monitor is turned off, it doesn't accept any input or commands from any other device. You can turn it on using the physical buttons or touch controls on your monitor
