### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by jpandres** [alin23/Lunar#381]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
MacBook Pro (13-inch, 2020, 2.3 GHz Quad-Core Intel Core i7)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
all

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
usb-c

- Using an USB Docking Station or Hub:
no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
sync, manual, location

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

yes

# Issue description:
Even though I disabled the hotkeys for the volume (cmd f10, f11, f12), and work as expected, I cannot use those shortcut in other applications. Once I quit lunar I can use the shortcut in other applications.
![image](https://user-images.githubusercontent.com/29607133/124592227-22101d80-de55-11eb-95b2-c6213a475b72.png)

**Comment by alin23** [comment]
@jpandres you have unchecked the **Hold Option for fine adjusments**. You haven't disabled the hotkeys.

To disable them, click on the **X** button on the right side of the hotkey input box.

**Comment by bric3** [comment]
Hi there, the UI is really confusing, I fell for the same issue.

Is it possible to disable all hotkey at once, without changing the default mapping.

Another idea would be ignore shortcuts when a specific application is active (that's what Magnet does).

**Comment by alin23** [comment]
The confusing part is the difference between media and function keys. I tried to explain it everywhere I could but there's no better way to do it. 

For example F1/F2 can mean either Brightness up/down or Function Key 1/2 depending on your system setting. 

No, there's no way to disable all Hotkeys at once. It's not that hard to disable what you need by clicking on the x button. 

The checkbox is for enabling fine adjustments using the Option modifier, not for disabling the Hotkey

**Comment by bric3** [comment]
Yes I understand there's currently no way to disable hotkeys at once, that's what I'm suggesting : a global toggle. I find the _remove hotkey_ by clicking `x` is somewhat not intuitive, for example I would use this only to reconfigure a single shortcut.

**Comment by alin23** [comment]
> Yes I understand there's currently no way to disable hotkeys at once, that's what I'm suggesting : a global toggle. I find the _remove hotkey_ by clicking `x` is somewhat not intuitive, for example I would use this only to reconfigure a single shortcut.

Usually reconfiguring is done by simply clicking on the hotkey and pressing the new combo. There's no need to remove the current hotkey manually. I feel like that's what every app on macOS is doing (mostly because everyone uses the same MASShortcut framework). 

But for the _disable all_ case, would a menu item accessible from the menu bar help? 

Maybe a **Disable all hotkeys** right under **Force update display list**?

**Comment by bric3** [comment]
Hi,

> Maybe a Disable all hotkeys right under Force update display list?

Yes that might work. Maybe the setting page should somehow react to this settings. Like graying out hotkeys.

**Comment by alin23** [comment]
Yes, it will have the same effect as clicking on the x button for all the hotkeys.

**Comment by bric3** [comment]
OK, cool, thank you.

Should I open a new issue, so that's easier for you to track.

Or maybe for the idea to ignore shortcuts for a certain app, like Magnet does

<img width="272" alt="image" src="https://user-images.githubusercontent.com/803621/132874405-cca95ef1-fbc9-40dc-91e6-00207cc04260.png">

<img width="245" alt="image" src="https://user-images.githubusercontent.com/803621/132874469-1ab0d095-ccbf-4d6c-9c0b-79fee82c7f5c.png">

**Comment by alin23** [comment]
@bric3 can you try [this beta](https://static.lunar.fyi/Lunar-4.8.6-beta1.zip) and see if the new **Disable all** button is what you need?

![Shot_Lunar_Settings_HR8yU6nX](https://user-images.githubusercontent.com/3819725/133335867-7b85e40d-8e3a-4804-9f03-193fb679be31.png)

The `Ignore "app"` feature would add a lot more complexity and I don't think would be useful to a lot of people, I'd like to postpone that until I get more requests.

**Comment by bric3** [comment]
Hi @alin23 

Sorry for the late reply. Yes it works. Perfect, I think it's easier to setup this part now.
Thank you
