### ISSUE TITLE
Media keys no longer work in manual mode

### ISSUE THREAD

**Issue by bafulton** [alin23/Lunar#383]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    <img width="262" alt="Screen Shot 2021-07-08 at 9 26 17 AM" src="https://user-images.githubusercontent.com/1216468/124929511-93271080-dfce-11eb-833d-f1417021a98b.png">

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2718Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to DisplayPort

- Using an USB Docking Station or Hub:
    No--direct cable

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
    Yes, I've sent diagnostics (a few moments ago)

# Issue description:
Before I updated to Lunar 4, pressing the brightness up/down keys on my bluetooth keyboard while my mouse was on my external screen would result in the brightness of the external screen being modified (the brightness display would pop up and everything!). Since updating to Lunar 4, using the brightness keys only ever changes the brightness on my macbook's screen. Nothing in my monitor/cable/port setup has changed. I've tried rebooting, reinstalling Lunar, and disabling/re-enabling accessibility, all to no avail. Manually clicking on the Lunar icon in the taskbar and setting the brightness via that menu still works.

**Comment by alin23** [comment]
Please check this (extremely frequently) asked question: https://lunar.fyi/faq#monitor-with-cursor

If media keys don't work at all with Lunar (e.g. Ctrl+Brightness doesn't change the external monitor brightness), it's also possible that you're running into this macOS bug: https://lunar.fyi/faq#always-asks-for-permissions

**Comment by bafulton** [comment]
Aha, fixed! Thank you!

<img width="312" alt="Screen Shot 2021-07-08 at 9 47 38 AM" src="https://user-images.githubusercontent.com/1216468/124933044-91128100-dfd1-11eb-8df3-6efebbbe920e.png">
