### ISSUE TITLE
Lunar Bug - After turning off the monitor, monitor does not display anything (not even OSD).

### ISSUE THREAD

**Issue by jerryzejia** [alin23/Lunar#384]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):

Macbook Pro 16 inch

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):

Dell S2721DGF (27 inch, 165Hz, 1440p)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *write response here*

HDMI-to-USB-C port on Macbook 

- Using an USB Docking Station or Hub:
  
No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location, Sensor or Manual*

Location

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

No. 

# Issue description:
*write a short description of what doesn't work as expected*

I turned my Dell S2721DGF monitor off with the red button in Lunar. After turning it back on by pressing the physical power button, the screen was completely black. The OSD was also not showing when I pressed the buttons on the back of the monitor. 

Fixed by unplugging and replugging the monitor.

**Comment by alin23** [comment]
This is how your monitor reacts to the power off message sent through DDC. It is not a bug in Lunar. 

All Lunar does when you press that button is send a DDC message with `set DPMS to 5` to the monitor (which in DDC standard means `enter standby mode`). It's up to the monitor to interpret and do something with this message.

**Comment by jerryzejia** [comment]
I see, thanks for the quick response and the explanation!

**Comment by alin23** [comment]
This is specific to a monitor. Mine doesn't react like that and a lot of others don't either. 

I'll try to explain how Lunar uses DDC in more detail on some page to clear out confusions like this one in the future 😊
