### ISSUE TITLE
Lunar turns off my external monitors once I acknowledge that the PRO trial is over. 

### ISSUE THREAD

**Issue by JamieSlate** [alin23/Lunar#385]
# Issue details
- 2020 MBA M1
- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *LG 24M47vq*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *Hdmi to a usbc hub*

- Using an USB Docking Station or Hub:
    *yes*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location, Sensor or Manual*

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    *write yes or no here*

# Issue description:
* upon launching lunar I get a modal window that takes over my entire screen… It says license verification failed… "The pro features will be deactivated until the licensing server can be reached for verification."  This is okay because the free version is cool. But then once I click okay, my external monitor turns off completely. I'm going to assume good faith that this isn't a  diliberate attempt to pressure people to buy pro.*

**Comment by alin23** [comment]
Hi @JamieSlate 

Lunar doesn't have any code that does this. Something weird is going on in your setup.

Can you please send the logs from `~/Library/Caches/Lunar/swiftybeaver.log` ?

**Comment by alin23** [comment]
Please also make sure you have the latest `4.5.5` version as previous versions had a bug where the license verification message was being show wrongly.

Also, no Lunar dialog should take over your entire screen, you should at most see something like this: 

<img width="328" alt="Shot_Spotify_Kazi Ploae - Boschetari de lux_mcFqy4l0" src="https://user-images.githubusercontent.com/3819725/125450086-e9e5a5ac-3af4-4cca-8d8d-c21bfe5e66df.png">

Can you please show a screenshot with what you are seeing?

**Comment by alin23** [comment]
I can't say for sure yet without seeing the logs, but I think you're running into this: https://lunar.fyi/faq#bad-ddc

**Comment by JamieSlate** [comment]
So far I uninstalled Lunar and reinstalled and am waiting to see if the problem replicates itself. So far it has not.

**Comment by alin23** [comment]
Reinstalling Lunar (if you were already on the latest version) does absolutely nothing.

The installer simply copies `Lunar.app` in `/Applications` which if it was already updated, will be exactly the same as before.

I'm just hoping you were on an older version and you downloaded the latest installer.

**Comment by alin23** [comment]
I'll close this as it's most likely you weren't on the latest version.

If your monitor ever loses signal because of Lunar, make sure to disable DDC as in the FAQ above because that means your monitor doesn't support DDC requests well.
