### ISSUE TITLE
Removing a shortcut prevents it being used again?

### ISSUE THREAD

**Issue by max-sixty** [alin23/Lunar#387]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
Macbook Pro 2019

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
LG UltraFine 5K x2

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB-C

- Using an USB Docking Station or Hub:
No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Any

- Tried Lunar Diagnostics?
[I couldn't find the "Lunar menu" — let me know if this is required]

# Issue description:
I'm using Lunar Pro, it's great!

One issue — if I set a shortcut, and then remove that shortcut, I can no longer set the same shortcut again. This happens even after restarting the app, and is shared across at least "Toggle Adaptive Mode" and "Show Lunar". 

And because I tried to work out whether this was happening, I now have many shortcuts that won't work in Lunar.

Is it just me or does this reproduce?

**Comment by alin23** [comment]
Removing a shortcut does indeed cause Lunar to not unregister it properly. 

But it seems that reassigning one action to a different shortcut unregisters the old shortcut correctly so you can re-register the old one again:


https://user-images.githubusercontent.com/3819725/125676155-5216fc26-7ca9-4ff0-b6d1-c4dbafa52488.mp4

I'll fix this in the next version, thanks for the feedback!

**Comment by alin23** [comment]
@max-sixty 

The update with the fix was just released!

Click on Check for Updates in the Lunar menu to upgrade.

**Comment by max-sixty** [comment]
That's amazingly fast! Thanks — it works now!
