### ISSUE TITLE
Why does Lunar ask for access to input monitoring on Catalina?

### ISSUE THREAD

**Issue by ErinPo** [alin23/Lunar#39]
MacOS has a new privacy access privilege named input monitoring which apparently allows apps to monitor keys pressed on the keyboard in other apps. I use a number of different accessibility tools and none ask for this privilege. I did not consent and could not identify any limitation in functionality.

What is it needed for in Lunar?

**Comment by alin23** [comment]
Most probably the hotkeys library causes this. I haven't written any code for input monitoring, you can always check the source.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alin23** [comment]
This should be fixed on 2.9.1. I had to patch the Magnet library for this. Turns out it was listening for modifier keys so that it could map hotkeys like _double tap Command_

**Comment by ErinPo** [comment]
2.9.1 freezes my Mac as soon as I run it with forced shutdown the only solution. I reverted to the previous version.

**Comment by alin23** [comment]
@ErinPo  Install the latest version which is 2.9.9. That system freeze was fixed in 2.9.2 actually but it seems you have to check for updates manually
