### ISSUE TITLE
Updates re-register global keyboard shortcuts

### ISSUE THREAD

**Issue by borekb** [alin23/Lunar#390]
Lunar is updated frequently on my computer (which is a good thing!) but every time it does so, it adds all global shortcuts again. It would be great if updates remembered the previous state of my user configuration of this.

<img width="1062" alt="Screen Shot 2021-07-20 at 12 11 29" src="https://user-images.githubusercontent.com/101152/126306773-2f85c899-3c9b-4f77-869f-0e43765f47a5.png">

**Comment by alin23** [comment]
There were a few updates that had to reset all settings (because of structural changes).

Although 4.6.3 was not one of them, did this reset the hotkeys as well?

**Comment by borekb** [comment]
@alin23 thanks for a quick response, I certainly had to reset it several times in the past but I'm not sure if it was also necessary in the recent update – I'll be watching this.

At this point, this is the output:

```console
$ defaults read fyi.lunar.Lunar | grep first

    firstRun = 1;
    firstRunAfterDefaults5Upgrade = 1;
    firstRunAfterLunar4Upgrade = 1;
    firstRunAfterM1DDCUpgrade = 1;
```

**Comment by alin23** [comment]
@borekb 4.7.0 should fix this. Let me know if you stil encounter the issue after update and I'll reopen it
