### ISSUE TITLE
Lunar Pro 4.6.3 turns off external monitor upon launch

### ISSUE THREAD

**Issue by JamieSlate** [alin23/Lunar#391]
2020 MBA M1

Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
LG 24M47vq

Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
Hdmi to a usbc hub

Using an USB Docking Station or Hub:
yes

Lunar mode used (check it in the top-right corner of the Lunar interface)
Sync, Location, Sensor or Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

Sent

https://user-images.githubusercontent.com/64977064/126455862-4e3c523d-e198-4245-aedd-6907bc186b4c.MOV

# Issue description:
*write a short description of what doesn't work as expected*

When I turn on Lunar, my external monitor goes black for a long time.... eventually it turns back on but only momentarily, then turns black again. There is no 'waiting it out' for this issue. The screen goes on and off randomly in an endless cycle until I quit Lunar.

**Comment by alin23** [comment]
Please check this FAQ: https://lunar.fyi/faq#bad-ddc

**Comment by JamieSlate** [comment]
I know with 100% certainty that Lunar can work on my computer because it used to (and no, I did not update MacOS). Your linked solution—to disable DDC completely—isn't really a solution at all, because the entire point of using Lunar Pro is to control computer brightness with software.

**Comment by alin23** [comment]
> I know with 100% certainty that Lunar can work on my computer because it used to (and no, I did not update MacOS). Your linked solution—to disable DDC completely—isn't really a solution at all, because the entire point of using Lunar Pro is to control computer brightness with software. 

Lunar has only got DDC support on M1 a few updates ago. Until now you have been using Gamma, probably unknowingly. 

There is nothing in Lunar that can cause that behavior on purpose. 

You can also check this outside of Lunar using a simple I2C write:

```sh
cd /tmp; curl -O https://static.lunar.fyi/i2cwrite; chmod +x ./i2cwrite; ./i2cwrite
```

**Comment by alin23** [comment]
You can inspect the code for the i2cwrite utility (and compile it yourself if you want) here: https://gist.github.com/alin23/b476a02a8cd298436848e28476aed07b
