### ISSUE TITLE
Contrast setting off by 50

### ISSUE THREAD

**Issue by ubuntudroid** [alin23/Lunar#392]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    *MacBook Pro, 16" 2019*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *Asus ROG PG279Q*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *HDMI-to-USB-C (via docking station with HDMI port, so actually HDMI-to-HDMI(docking station)-to-USB-C*

- Using an USB Docking Station or Hub:
    *yes*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync*

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    *yes*

# Issue description:
In any mode changing the contrast value seems always to be off by 50.

E.g., setting the value to 61 in Lunar will set the real value on the display to 11. Setting it to 52 will set it to 2. Setting it to to 82 will set it to 32. And setting it to anything lower than 50 will simply set it to 0.

Brightness works fine though.

**Comment by alin23** [comment]
Increase the DDC limit for contrast:

![image](https://user-images.githubusercontent.com/3819725/126560337-2ab28381-47c2-4eb5-95a4-53b037eb6866.png)

And set the MIN Contrast to 50. 

The fault here is with your monitor having non-standard values for the contrast control.

**Comment by ubuntudroid** [comment]
@alin23 Thanks for the super fast reply! However, don't I also have to set the MAX value for contrast to 150 as well? I tried that, but I can't for some reason.

Anyway, I set values like this, and they work fine for 0 and 100: 
![CleanShot 2021-07-21 at 23 43 01](https://user-images.githubusercontent.com/519867/126564079-8aa63e1d-b62d-47cd-a14c-a3a77cb86601.png)

Note, that I had to set the MIN value to 25 to get a value of 0 in Lunar match 0 in my display. However, when I enter e.g. 75 I would assume that the display contrast value would be 50, but instead it is 63. I tried to play around with the contrast curve factor, but couldn't set it to non-integer values which I guess I would have needed to make up for the discrepancy of the MAX value of 100 and the DDC limit of 150. Or am I completely off here?

**Comment by alin23** [comment]
The MIN and MAX values are percentages. If your DDC limit is 150, then a MIN of 25% would map to the value 37.5

<img width="796" alt="Shot_Safari_Contrast setting off by 50 · Issue #392 · alin23Lunar_XY4OfadC" src="https://user-images.githubusercontent.com/3819725/126565647-9b06c4b6-8400-40b6-9c4e-03066e3dda2a.png">

If you're sure that a DDC value of 150 maps to your monitor's 100% contrast, then that's what you have to set for the DDC Contrast limit.

You can also test specific values using the CLI:

```sh
lunar ddc CF4CF870-1DB2-B8D5-0857-D6964E3302DB CONTRAST 150
```

The third argument is the serial which you can easily find using the following command:

```sh
lunar displays | egrep 'Name:|Serial:'
```

**Comment by ubuntudroid** [comment]
Got it, that makes perfectly sense! I settled with MIN Contrast of 33 (rounding down). Works perfectly fine now! Many thanks!
