### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by techx-guy** [alin23/Lunar#393]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 2014

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG 27" 4k

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DP to mini-DP

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    No

# Issue description:
Lunar v4 installed and now i get random spikes in cpu usage that slows the machine to a halt. I have to either unplug the monitor or quit lunar

**Comment by alin23** [comment]
You can always go back to Lunar 3 if Lunar 4 is not working for you. The download link is on the front page: https://lunar.fyi

Unfortunately I can't fix anything with the current information, there are no other reports of what you experience, and there are no diagnostics or logs from your side.

**Comment by alin23** [comment]
@techx-guy 
Lunar 4.7.0 was just launched with a bunch of fixes on the DDC side and fault detection.

If you still encounter CPU usage spikes when Lunar runs in background, let me know.

We could maybe chat on Lunar's [Discord channel](https://discord.gg/dJPHpWgAhV) to debug this if you have some time. 

On my laptop I never experience this and I had no other reports so far so we'll have to collect information from your machine to find the problem.
