### ISSUE TITLE
Prevent the GUI window from showing when a monitor is reconnected

### ISSUE THREAD

**Issue by enricodias** [alin23/Lunar#394]
I need to disconnect and connect my mac in the same monitor multiple times a day. Every time I connect it, the Lunar GUI shows up in the screen and I need to close it manually. Is there any way to prevent this? I haven't found anything about this in the FAQ or in the issues.

**Comment by alin23** [comment]
Lunar only redraws the window if it is already shown. Are you sure the window is not already open but hidden somewhere like on a different space or in the Dock?

**Comment by alin23** [comment]
Try closing the Lunar window with Cmd-W or by clicking the red button on the top right part of the window and then disconnect and reconnect the monitor. 

Does the Lunar window appear by itself then?

**Comment by enricodias** [comment]
> Are you sure the window is not already open but hidden somewhere like on a different space or in the Dock?

I'm sure. It was really closed and Lunar redrawn it every time.

> Try closing the Lunar window with Cmd-W or by clicking the red button on the top right part of the window and then disconnect and reconnect the monitor.

I just tested and it had no effect. The window still shows up.


I'm using one of those hubs that connects everything with the same thunderbolt cable, I'm not sure if it makes any difference.

**Comment by alin23** [comment]
No it shouldn't make any difference how you connect the monitor. Thanks for testing!

Do you have the menu bar icon hidden or the dock icon shown in Advanced settings? 

[Click here to go to Advanced settings directly](lunar://advanced)

**Comment by enricodias** [comment]
I keep the menu bar icon visible only, but I just tested with the menu bar icon hidden, with the dock icon shown and with everything hidden. It behaved the same way.

**Comment by alin23** [comment]
Ok, I'll try testing again this behavior. Just to make sure, you are on version 4.6.5 correct?

**Comment by enricodias** [comment]
Yeap, 4.6.5. I just installed it yesterday.

**Comment by dtliao0303** [comment]
I can confirm this happens to me after updating to v4.6.5. When ever I wake my mac from sleep, the GUI windows is there

**Comment by alin23** [comment]
Thanks for the confirmation! I'll prioritize this for 4.7.0 tomorrow

**Comment by alin23** [comment]
This should be fixed in 4.7.0
