### ISSUE TITLE
Lunar 3 infected with Bundlore

### ISSUE THREAD

**Issue by yikai-wu** [alin23/Lunar#396]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 2015

- Mac OS version:
   10.14.6

- Lunar Version:
  3.2.3 and 3.2.2

# Issue description:
Avast Security reports that Lunar is infected with Bundlore-HI[Adw].

**Comment by alin23** [comment]
Report it as a false positive to Avast. 

There's nothing infected there, you can even compile those versions yourself from the lunar3 branch of this repo.

**Comment by alin23** [comment]
https://www.virustotal.com/gui/url/467bc287ede481344651c41daa6ede832a231302e1df8eba4e4858200f3bf84a/detection

Virustotal reports clean from all scanners. 

It's possible you might have another malware on your system that's infecting everything you download. 

I'd suggest to do a thorough scan with either Avast or [MalwareBytes](https://blog.malwarebytes.com/detections/adware-bundlore/)
