### ISSUE TITLE
OLED Brightness Adjustment Bug

### ISSUE THREAD

**Issue by astro-lee-k** [alin23/Lunar#398]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    ASUS ZenBook Pro Duo 15 (Hackintosh in macOS Bug Sur 10.15.7)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    4k OLED 

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Internal screen, eDP connection

- Using an USB Docking Station or Hub:
    N/A

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Auto: Manual*

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    Yes. However, the diagnostics is stuck and can never finish.
<img width="941" alt="Screen Shot 2021-07-31 at 10 03 08 PM" src="https://user-images.githubusercontent.com/42949962/127756859-b8296097-420e-4444-a2d1-64326ec6ee00.png">

# Issue description:
Brightness through DDC is not working although Lunar shows DDC is supported. (Hopefully to get DDC work.) Lunar prompts to fallback to software control, and then the brightness adjustment through software works for about 30 second, and then the brightness adjustment stop functioning with the lock icon shown in brightness adjustment.

<img width="944" alt="Screen Shot 2021-07-31 at 10 09 54 PM" src="https://user-images.githubusercontent.com/42949962/127756905-2be5cfb3-3495-4dcc-b95e-2998ecc015c5.png">

**Comment by alin23** [comment]
Hi @astro-lee-k . Diagnostics is not stuck, it is waiting for your input.

You need to press any key to continue the process, and make sure to not click anywhere until the process ends.

![Shot_Safari_OLED Brightness Adjustment Bug · Issue #398 · alin23Lunar_y5ZE9mEg](https://user-images.githubusercontent.com/3819725/127760308-597324be-f147-46d8-8fe7-66c0e2bc83b4.png)


About DDC, if Lunar says it is not responding then that's exactly what happens. Lunar is able to find an I2C controller for your monitor, which makes Hardware Controls the default. And then Lunar tries to send DDC requests to your monitor but after more than 20 consecutive failed DDC writes, Lunar declares that controller unresponsive and prompts you to fall back to Gamma mode.

Please go through the whole diagnostics process, and read carefully what's written while it runs as that information will help you understand what's the thing in your setup that blocks DDC. This is not an OLED bug, it's just something in your setup that blocks DDC.

**Comment by astro-lee-k** [comment]
I already press some keys to start the test but nothing happens for 10 mins. Isn't the "Press any key to start tests for this display" suppose to disappear or some texts should be generate after I press some keys?

**Comment by alin23** [comment]
Yes, the process should start showing more text when you press any key. But you have to remember to not click anywhere else before pressing keys because other inputs or buttons will steal focus and the key events won't be registered. 

You're probably clicking inside the email and name fields. That's why the keys aren't working for the diagnostics.

**Comment by astro-lee-k** [comment]
Hello, I've tried many time and did not click on other places when I started the test. I'm sure might be something to do with your code.

**Comment by alin23** [comment]
Ok, I'll try this again tomorrow when I get access to my laptop. 

I still have people regularly sending diagnostics so I don't think there's any problem (if you're on v4.7.0). But I'll check it anyway.

**Comment by alin23** [comment]
@astro-lee-k I forgot to let you know about this. The FAQ also has almost all cases where DDC can fail. 

Maybe you can find how to fix it here: https://lunar.fyi/faq#brightness-not-changing

**Comment by astro-lee-k** [comment]
> @astro-lee-k I forgot to let you know about this. The FAQ also has almost all cases where DDC can fail.
> 
> Maybe you can find how to fix it here: https://lunar.fyi/faq#brightness-not-changing

Thank you so much. I decided to use the software method at the moment. Also tried again today and am pretty sure the Lunar Diagnostics has some glitch not allowing me to run the diagnosis.

Another I was wondering is that is there a way to customize the brightness curve on different monitors?

**Comment by alin23** [comment]
Yes, each monitor has its own Curve factors inside the [gear icon menu](https://app.lunar.fyi/display/settings) near the reset dropdown 

There's also an auto learning curve feature that adjusts the curve automatically based on your manual adjustments: https://lunar.fyi/#curve

**Comment by shiecldk** [comment]
Can you also make brightness adjustment available for built-in displays adjustment? I had to set my monitor to external monitor in the hackintosh setting in order to use Lunar. I was hoping to know how do Lunar check and disable brightness adjustment for built-in displays?

**Comment by alin23** [comment]
Lunar does not disable brightness adjustment for builtin displays. It just doesn't implement it. 

I chose to leave builtin display adjustments to the system because it does a pretty good job for that. 

I understand that for hackintosh that is not the case, I'll think about how to handle this edge case.

**Comment by shiecldk** [comment]
Thank you! Would love to pay fo the pro or make donation to this project if this would work!

**Comment by shiecldk** [comment]
Would it be possible to adjust the brightness through ACPI call?
I found the brightness adjustment works for me in Ubuntu:
https://github.com/s-light/ASUS-ZenBook-Pro-Duo-UX581GV/issues/1#issuecomment-632839056

**Comment by atrslb** [comment]
Email me: atrslb hotmail.com
