### ISSUE TITLE
Lunar doesn't work with Samsung U28E590

### ISSUE THREAD

**Issue by lijunkang12** [alin23/Lunar#399]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro M1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Samsung U28E590

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)

    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

  yes

# Issue description:
The monitor does not respond to brightness settings from Lunar. May be a M1 specific issue because it used to work with an Intel Macbook pro connected with a miniDisplayPort-to-DisplayPort.

**Comment by alin23** [comment]
Hi @lijunkang12 

Please check this FAQ for your issue: https://lunar.fyi/faq#bad-ddc

It's possible that one of the smart features of the Samsung is blocking DDC.
