### ISSUE TITLE
Make hotkeys configurable

### ISSUE THREAD

**Issue by alin23** [alin23/Lunar#4]

**Comment by honza171** [comment]
Also a checkbox to launch app on login automatically or not would be welcome.

**Comment by MasterRee** [comment]
First, thanks for making this slick utility! Both of the features requested above would resolve the most significant issues with the app. Currently, the hotkey conflicts with the shortcut to open the "Downloads" folder.

**Comment by alin23** [comment]
Working on it ^_^ I may have some free time next week for this

**Comment by alin23** [comment]
Done in v2.2.0
