### ISSUE TITLE
CLI integration

### ISSUE THREAD

**Issue by guthibs** [alin23/Lunar#400]
In the dropdown menu there is the option to install CLI integration. After confirmation that CLI has been installed, in Terminal command "lunar --help for example", it gives "command not found".

It is a bit unclear how to proceed and use the CLI. Am I missing something or does need to install differently?

**Comment by alin23** [comment]
Most likely you don't have permissions to write into the `/usr/local/bin` directory 

Try running the following command to gain permissions then try the installation again. 

```sh
sudo chown -R $(whoami) /usr/local
```

**Comment by alin23** [comment]
I've added the following message in case `/usr/local/bin/lunar` can't be created:

<img width="372" alt="Shot_Lunar_Settings_bwqlEQ1x" src="https://user-images.githubusercontent.com/3819725/128368599-8a539f51-1f48-4765-867c-15f83d885a5b.png">

It will be released in 4.7.3, thanks for the feedback on this!

**Comment by guthibs** [comment]
Ah, thanks.

I'm running macOS 11.5.1. I found out I had Full Disk Access for Lunar in the Security & Privacy not enabled. So also sudo chown -R $(whoami) /usr/local gave me "Operation not permitted". When enabled, installing CLI in the dropdown menu just works right away.

**Comment by alin23** [comment]
Are you on a work laptop or on some kind of non-admin account? Full Disk Access should not be needed if your user has write access to `/usr/local/bin/`

**Comment by Jeff9387346** [comment]
Macbook Pro, 11.5.1.  Just installed Lunar (NICE!) but Install CLI Integration indicates success, yet the command line LUNAR fails.  Looking at /usr/local/bin there is no LUNAR file or folder.

How to address?

**Comment by alin23** [comment]
> Most likely you don't have permissions to write into the `/usr/local/bin` directory 
> 
> Try running the following command to gain permissions then try the installation again. 
> 
> ```sh
> sudo chown -R $(whoami) /usr/local
> ```

@Jeff9387346 Same as above

**Comment by alin23** [comment]
Try this then:
```
sudo chown $(whoami) /usr/local/bin
sudo chmod 755 /usr/local/bin
```
