### ISSUE TITLE
Adobe Lightroom App Exceptions

### ISSUE THREAD

**Issue by guthibs** [alin23/Lunar#401]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Mac Mini M1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2720Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to USB-C

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Auto

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    yes

# Issue description:
It seems that Adobe Lightroom CC or Classic can not be added to the exceptions list. Other apps like VLC or Photoshop give no issue. After trying to add Lightroom, nothing is added to the list in Settings.

**Comment by alin23** [comment]
Thank you for the report! This will be fixed in 4.7.3 in the next few days

**Comment by alin23** [comment]
@guthibs Can you try this beta and see if it fixes your issues?

https://static.lunar.fyi/Lunar-4.7.2-beta4.zip

I'll have to wait a bit before releasing 4.7.3 because a lot of people are getting annoyed by too frequent updates.

**Comment by guthibs** [comment]
Thank you. Lunar 4.7.2-beta4 works with including Lightroom CC and Classic. 

But now (I must say I have not checked it with other apps), it seems Lunar doesn't do anything when opening the apps. Or I must misunderstood what to expect. My expectation was that when dimmed at 50% and the excluded app is set at 100% that when opening the app, the brightness goes from 50% to 100%. Is that correct?

I checked other apps to exclude. Also 4.7.2 gives the same result.

**Comment by alin23** [comment]
The app exception values are actually offset. So if you have `Brightness: +50` on Lightroom let's say, then when a Lightroom window is visible on an external monitor, Lunar will add 50 to that monitor's current brightness.

Some times, macOS doesn't correctly report the window being visible on the monitor, and it seems I can't fix that in Lunar. Best way to have that working is to have the app in fullscreen

**Comment by silencial** [comment]
Having the same issues. Lunar does not do anything when I open the app that is added to the exception list, even for fullscreen.

**Comment by alin23** [comment]
@silencial is the app fullscreen on an external monitor?

**Comment by silencial** [comment]
> @silencial is the app fullscreen on an external monitor?

Yes, FYI the app is IINA. I also tried other apps and make them fullscreen but the the results are the same.
