### ISSUE TITLE
Support Input switch to Thunderbolt for Dell U4021QW

### ISSUE THREAD

**Issue by chris-kuo** [alin23/Lunar#402]
### Switch to thunderbolt input for Dell U4021QW

Enable switching to thunderbolt input on Dell U4021QW

### What problem does this feature solve?

Currently Lunar doesn't support switching to thunderbolt input on Dell U4021QW (EDID Name: DELL U4021QW)

### How should the feature work

Add  case thunderbolt = 25 to enum InputSource in Lunar/DDC/DDC.swift (line 55). Also update displayNames() and other affected in the same source file.

### Visual description

N.A.

**Comment by alin23** [comment]
@chris-kuo thanks for the detailed feature request. This will be released in v4.8.0 soon

**Comment by chris-kuo** [comment]
Thank you!

**Comment by alin23** [comment]
4.8.0 was released with a fix for this issue
