### ISSUE TITLE
Virtual displays support (DisplayLink)

### ISSUE THREAD

**Issue by rossinek** [alin23/Lunar#403]
### Name of the feature

Virtual displays support (DisplayLink)

### What problem does this feature solve?

Before using a MacBook with the M1 chip, I used to use two external monitors and I really liked this setup. Unfortunately MacBooks with the M1 chip don't natively support two external monitors, but there is a workaround: you can connect another monitor using a dongle or hub with the DispayLink chip. This creates a virtual monitor which the system recognizes and sees e.g. in the displays settings.

Lunar is a great application that I've been using for a long time and I would really like it to also support a monitor connected in this way. At the moment Lunar does not show this monitor at all.

### How should the feature work
 
I guess that [it may not be possible to adjust brightness of such monitor natively](https://github.com/alin23/Lunar/issues/176#issuecomment-687710328), but until recently I was using temporary solution (the only one available for M1 at that time) that used overlay. It would be wonderful to at least be able to adjust the brightness of the second external monitor to the others using this approach.

**Comment by alin23** [comment]
This is already done but not released yet. Here's a beta if you want to test this: https://static.lunar.fyi/Lunar-4.7.2-beta10.zip

Virtual displays visibility can be enabled in [Advanced settings](https://app.lunar.fyi/advanced) 

This is still off by default to avoid showing iPad Sidecar and Airplay displays.

**Comment by rossinek** [comment]
That's awesome news ❤️ I tested it and unfortunately overlay is added to the wrong display (the one with DDC support) so it adjust brightness and contrast with hardware controls and also has an overlay. Virtual monitor stays untouched.

**Comment by alin23** [comment]
@rossinek To clear out some confusion from the start, Lunar's Software Controls doesn't add any overlay.

If you're interested in how it works, you can read a lot more about it here: https://alinpanaitiu.com/blog/journey-to-ddc-on-m1-macs/#gamma-tables

But basically, it changes the values that are used by the system's formula for calculating the color brightness, to simulate lowering the brightness.

Now Lunar simply does that for the monitor ID provided by the system. If the Gamma changes are instead applied to the other monitor, that may be a problem with how the system treats virtual displays.

I have another user testing this solution and for him the same beta works alright, I'm not sure what could be different in your case.

If you have some command line experience, it would be helpful if you could install the [Lunar CLI](https://lunar.fyi/#cli) and provide the `lunar-displays.txt` file generated by running this command:

```sh
lunar displays --verbose --all --system-info --edid > ~/Desktop/lunar-displays.txt
```

**Comment by rossinek** [comment]
Maybe it's because my connection:
- the first monitor is connected with USB-C to macbook
- the hub with DisplayLink is connected to USB port on a first monitor
- the second monitor is connected to a hub
Here is the file generated by Lunar CLI:
[lunar-displays.txt](https://github.com/alin23/Lunar/files/6971544/lunar-displays.txt)

**Comment by alin23** [comment]
> the hub with DisplayLink is connected to USB port on a first monitor

That is most likely the problem. Try connecting that to a separate USB-C port of the Macbook if possible.

**Comment by rossinek** [comment]
I did it and restarted the system. Unfortunately, no effect.

**Comment by alin23** [comment]
@rossinek here's a script that does the simplest thing to test if Gamma works at all: https://static.lunar.fyi/gamma.swift

To run it, make sure to quit Lunar (and any other Gamma-using apps like f.lux and Gamma Control) and then use the following commands in a terminal:

```sh
cd /tmp
curl -O https://static.lunar.fyi/gamma.swift
swift gamma.swift
```

What it does:

1. Prints all the display IDs present on your system
2. Goes through each display ID and sets the `redGammaFactor` to `0.6` to create a visible reddish color change
3. Keeps running indefinitely to keep the gamma changes applied until you press <kbd>Ctrl</kbd>+<kbd>C</kbd>

Please post the output here and let me know if the DisplayLink monitor changes in any way.

**Comment by rossinek** [comment]
> Are you able to control the gamma of the DisplayLink monitor with this app?
> 
> https://michelf.ca/projects/gamma-control/

No, it has no effect on this second external monitor.

> ...
> Please post the output here and let me know if the DisplayLink monitor changes in any way.

No, it's the only one not changed 😞 
Output:

```
objc[2418]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1effdec10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1146cc2b8). One of the two will be used. Which one is undefined.
objc[2418]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1effdec60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1146cc308). One of the two will be used. Which one is undefined.
objc[2419]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1effdec10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x113ecc2b8). One of the two will be used. Which one is undefined.
objc[2419]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1effdec60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x113ecc308). One of the two will be used. Which one is undefined.
displayIDs [1, 2, 6]
NSScreen.screens ["Built-in Retina Display", "DELL P2419HC", "Pb248"]


Screen for ID 1: NSScreen Built-in Retina Display(id: 1, builtin: true, screen: true, hasMouse: false, visibleFrame: (0.0, 0.0, 1680.0, 1025.0), frame: (0.0, 0.0, 1680.0, 1050.0), empty: false)

	Trying to change Gamma to a red colour profile
	Gamma set without errors for 1



Screen for ID 2: NSScreen DELL P2419HC(id: 2, builtin: false, screen: true, hasMouse: false, visibleFrame: (1680.0, 787.0, 1920.0, 1080.0), frame: (1680.0, 787.0, 1920.0, 1080.0), empty: false)

	Trying to change Gamma to a red colour profile
	Gamma set without errors for 2



Screen for ID 6: NSScreen Pb248(id: 6, builtin: false, screen: true, hasMouse: true, visibleFrame: (3600.0, 755.0, 1920.0, 1200.0), frame: (3600.0, 755.0, 1920.0, 1200.0), empty: false)

	Trying to change Gamma to a red colour profile
	Gamma set without errors for 6
```

**Comment by alin23** [comment]
I'm sorry to say but the problem is probably with your DisplayLink adapter. 

I can't do anything to fix this in software.

**Comment by rossinek** [comment]
It's probably related to this issue: https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/18840574-support-night-shift-and-f-lux-for-mac-os
If I understand correctly there is no support for color management for displaylink monitor for macos.
Thank you @alin23 very much for your help and a great tool 🤝

**Comment by alin23** [comment]
Yes, that's probably the limitation we're running into. I recommend the [Network Control (Raspberry Pi)](https://lunar.fyi/#fallback) solution for the DisplayLink monitor. 

I already have one report from a user that's successfully using this with Lunar.

**Comment by rossinek** [comment]
Nice, fortunately I can try this because I have one unused rasperry pi at this moment. As far as I understand I need to connect a monitor to my macbook and connect this monitor also to raspberry pi with the second cable (HDMI)?

**Comment by alin23** [comment]
Correct. After installing the ddcutil server on the Pi and connecting the HDMI of the monitor to the Pi HDMI port, Lunar should detect the server on the network and ask if you want to use network control for the monitor.

**Comment by rossinek** [comment]
I'm waiting for HDMI->DisplayPort adapter to be able to connect second HDMI to monitor (my hub with displaylink chip has only HDMI port). I'll let you know if it worked.

**Comment by alin23** [comment]
Just to make sure we're on the same page, the Pi has to connect directly to the monitor, not through another DisplayLink adapter/hub.

The problem we need to bypass here is the adapter.

> I'm waiting for HDMI->DisplayPort adapter

I'm guessing here that you want to connect the Pi HDMI to the monitor DisplayPort, correct?
That should work ok for network control.

**Comment by rossinek** [comment]
I want to connect:
- MacBook -> hub with DisplayLink chip [hdmi out] -> monitor [displayport in]
- Raspberry Pi [hdmi out] -> monitor [hdmi in]
is it correct setup?

**Comment by alin23** [comment]
Yes, that will work

**Comment by rossinek** [comment]
No success. My guess is that this display does not support DDC on inactive input.

This is the output of `ddcutil detect` when DisplayPort (macbook) is selected as input (on monitor):
```
Invalid display
   I2C bus:  /dev/i2c-2
   EDID synopsis:
      Mfg id:               ACI
      Model:                PB248
      Product code:         9379
      Serial number:        FCLMQS062251
      Binary serial number: 16843009 (0x01010101)
      Manufacture year:     2015,  Week: 51
   DDC communication failed
```

And this is the output when HDMI (raspberry pi) is selected as input:
```
Display 1
   I2C bus:  /dev/i2c-2
   EDID synopsis:
      Mfg id:               ACI
      Model:                PB248
      Product code:         9379
      Serial number:        FCLMQS062251
      Binary serial number: 16843009 (0x01010101)
      Manufacture year:     2015,  Week: 51
   VCP version:         2.1
```

We've probably run out of options 🤷‍♂️

**Comment by alin23** [comment]
Try turning off then turning on the monitor again while the display input is set to the DisplayLink

This is what makes DDC on inactive input work for my LG.

**Comment by alin23** [comment]
> We've probably run out of options 🤷‍♂️

Based on Lunar's Network Control statistics, almost all monitors enable DDC on inactive input. I'd say you just have to try various combinations of restarting the monitor/Pi and switching inputs until you find what works.

**Comment by rossinek** [comment]
Unfortunately my old monitor seems to not support it. I tried all options with disconnecting/connecting and disabling/enabling each device but raspberry pi still cannot control monitor if it's not the active input. I cannot switch virtual display with the main one because it does not support charging macbook (at this moment I have just one usb-c cable that connects main monitor, displaylink hub with all of USB devices and the second monitor).

Thank you for all the help. That was pretty fun.
It's actually not that important to me. It's good to have a working Lunar for the main monitor 😉
