### ISSUE TITLE
Lunar Diagnostics Report [NO LOGS] [47C3F5F0A2228078C2413185F28DCB85197230D68F0D83FD3457D1360BDA6E1F] [3.2.3]

### ISSUE THREAD

**Issue by bronisMateusz** [alin23/Lunar#406]
Hi, I have a problem with Dell P2314H connected through DVI connector. Application doesn't change brightness and contrast. I use MacOS 12 Beta 5.

**Comment by alin23** [comment]
Hi @bronisMateusz . Lunar 3 is not supported anymore. Please download Lunar 4 if you want to take advantage of more supported monitors. 

If you still have problems with Lunar 4, please take a look at this FAQ: https://lunar.fyi/faq#brightness-not-changing
