### ISSUE TITLE
Settings (brightness/constrast/noon etc) don't stick

### ISSUE THREAD

**Issue by ahydronous** [alin23/Lunar#41]
I still experience the issue brought up at https://github.com/alin23/Lunar/issues/34.
Setting brightness and contrast manually and locking them makes them stick, but any setting except for 'smooth transitions' in location mode does not get saved.

There is also the additional problem that changing values only gets applied with the arrow keys. Scrolling lowers or raises the value number, but does not apply any change.

**Comment by alin23** [comment]
Thanks for the detailed feedback! I'll reopen #34 and close this to avoid duplication
