### ISSUE TITLE
Can't change brightness when monitor isn't connected 

### ISSUE THREAD

**Issue by sn0wyfall** [alin23/Lunar#410]
When I try to change my brightness when my external monitor is not connected, it doesn't work. I have to quit Lunar in order to change my brightness. 

How do I fix this issue? What information do I need to give?

**Comment by alin23** [comment]
What settings do you have on the [Hotkeys page](https://app.lunar.fyi/hotkeys)?

If you have the brightness keys set to **All external**, built-in won't be adjusted.

**Comment by sn0wyfall** [comment]
Below is a picture of my hotkeys configuration. Generally with my monitor connected I am able to change the brightness of either display, depending on which one I'm currently focused on. However when the monitor is disconnected I can't change the built-in brightness (even though that's the only one that's "active")

![image](https://user-images.githubusercontent.com/24374968/133943776-5b9dc0a3-6931-4037-9fcf-58cd1725b4bd.png)

**Comment by alin23** [comment]
Is there a reason why you're not on latest version?

4.8.5 has a bug where in Manual mode with **Send Keys to All Monitors** disabled, there's no way to control the builtin display.

**Comment by sn0wyfall** [comment]
Because it asks me to update every other day lol

Thanks, I updated it and now it's fixed
