### ISSUE TITLE
Lunar not compatible with F.lux? 

### ISSUE THREAD

**Issue by Jseeca** [alin23/Lunar#412]
M1 user here. Just want to confirm is Lunar compatible with F.lux? I get flickering (filter turns on and off) and on the offical site in the FAQ section it says because it conflict with the DCC mode. But I'm not sure why? Isn't f.lux just an overlay that goes over the screen? What does it have to do with DCC control. Issue get's resolved if I quit lunar, so I can have one or the other but not both running at the same time :(

**Comment by alin23** [comment]
@Jseeca DDC doesn't interfere with f.lux. Only Software Control which uses Gamma. 

Can you point me to the part of the website where it says DDC is not compatible with f.lux?

**Comment by alin23** [comment]
To clear out the confusion, f.lux isn't just an overlay. 

F.lux changes the gamma tables of the system for each screen so that the red appears brighter than the other colors. 

When DDC is not supported ([there are a lot of reasons why that could happen](https://lunar.fyi/faq#brightness-not-changing)) Lunar can use Software Control which also changes the gamma tables so that all colors appear less bright to give the impression of brightness dimming. 

That is the only case where Lunar interferes with f.lux. Night Shift is a good alternative in that case as it seems to work at a lower level than gamma tables and isn't affected by Lunar.

**Comment by Jseeca** [comment]
Quote from the website 

> **One of my monitors is flickering - it shows white and then orange quite frequently. What should I do?**
> (This answer is PC and Mac when used with non-Apple monitors) Look in the On-Screen Display (OSD) and see if you can turn off DDC/CI (the monitor configuration protocol). Some older monitors did not handle color changes well and would reset to white before accepting new settings. This is fine if you change settings once a month, but not so good if you do it more often like f.lux does.

[](https://justgetflux.com/faq.html)

So like DCC control controls the monitor settings itself, whilst both overlays and Gamma tables change the display on a software level (not through monitor), although Gamma is runs on a lower level than a overlay? And by extension Night shift runs even lower?

In poining out the gamma tables out I just turned them off and it seems to have fixed it. Looks like there was a conflict in the Lunar Gamma tables and f.lux. Seems to work together now. Thanks!

**Comment by alin23** [comment]
Oh you meant the f.lux website FAQ. I got things confused and thought you were referring to the Lunar website having that statement. 😅

The problem stated in that FAQ happens so rarely that I never had it reported by a Lunar user. 

In your case, as you saw, it was only related to both Lunar and F.lux changing the Gamma tables at the same time, DDC works fine with f.lux. 

I'm guessing you turned off **Apply Gamma**? In that case, yes, that's the solution. Lunar's gamma control should never be used when f.lux is running.

**Comment by alin23** [comment]
> So like DCC control controls the monitor settings itself, whilst both overlays and Gamma tables change the display on a software level (not through monitor), although Gamma is runs on a lower level than a overlay? And by extension Night shift runs even lower?

Yes, you got this right. 

By definition, an overlay would be a fullscreen, always-on-top, semi-transparent window that has a specific colour to alter the graphics behind it. 

Gamma tables are lists of numbers that create a specific curve of brightness for each color (red, green and blue). Altering that with the system APIs will change how the colors get rendered on the screen. 

Night Shift probably still works with gamma tables, but those are probably a different set of tables that are hidden from the public APIs, and the tables that we can change apply over the Night Shift ones.
