### ISSUE TITLE
Allow 'Always 120Hz' option on built-in displays of the 2021 Macbook Pros

### ISSUE THREAD

**Issue by sagz** [alin23/Lunar#418]
### Name of the feature

Force/Always 120Hz

### What problem does this feature solve?

Unlocks the screen to go beyond 60Hz to 120Hz/90Hz etc steps.

### How should the feature work

Would love to see a force 120Hz option. Probably in the Lunar options screen.

### Visual description

An additional option to '120Hz' instead of just 'ProMotion' as it shows in the Sys Prefs dialog
<img width="549" alt="image" src="https://user-images.githubusercontent.com/964843/139786234-2ccbcb47-b958-4867-9cbe-ac8f594e9941.png">

**Comment by alin23** [comment]
ProMotion isn't designed like that. 

If you would force the display to always refresh 120 times per second but the rendered content (apps, videos etc) are not designed to redraw at that speed, you won't notice any difference. It would just use more power for nothing. 

If an app is updated to support 120hz, the system will use that refresh rate automatically. There's no need to force anything.

Also there is no API to do that anyway. With some tedious reverse engineering, someone might find a private API that can do that, but I don't think there's any benefit in it. 

@waydabber maybe you want to try this in [BetterDummy](https://github.com/waydabber/BetterDummy) just for fun 😊 
The _render dummy in a Metal layer_ idea might work for both this and the [1000 nits issue](https://github.com/alin23/Lunar/issues/417)

**Comment by waydabber** [comment]
Hey @alin23 

It seems CGVirtualDisplay is maxed out at 60Hz so I don't think even with the proposed renderer dummy it would work with 120Hz. 1000nits thing might work, but I am afraid the renderer dummy will have minor compression artifacts which limits its real value (but still it could be useful for for text editing in direct sunshine for example)...

120Hz can technically be forced on the display by 120Hz rated app doing some invisible activity at 120Hz (just like the gammaenforcer we both use in our apps), but I agree that this would probably have the only benefit of draining the battery.

**Comment by waydabber** [comment]
(btw we might have an app called MaxDrain - it could do super intensive computational and graphics stuff, drive the display at sustained 1000nits and force 120Hz refresh while taxing the memory and SSD subsystem as well and driving the fans at 100% - that would be a popular app I guess! ;)).
