### ISSUE TITLE
Suggestion: at first launch, set brightness and contrast to 50 instead of 100

### ISSUE THREAD

**Issue by ahydronous** [alin23/Lunar#42]
Setting both brightness and contrast to an eye-popping 100 at first launch almost completely whites out the screen on most monitors. It made me think Lunar was incompatible/bugged until I figured out what to change.
Setting them to a more conservative 50/50 leads to a much cleaner user experience, and hopefully some saved eyeballs if Lunar is installed at night!

**Comment by alin23** [comment]
Yes, I'll change the defaults. Usually Lunar should start in Sync mode and the brightness would be exactly right because it would be taken from the built-in display. But there is a bug that starts Lunar in Manual mode by default
