### ISSUE TITLE
Displayport works, but no connection over HDMI

### ISSUE THREAD

**Issue by dahmc** [alin23/Lunar#423]
# Issue details
Device 1: MacBook Pro 13" 2015, 12.0.1
Device 2. Mac Mini 2018, 11.6.1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
BenQ EX3501R

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
Device 1: Mini-Displayport to Displayport
Device 2: HDMI

- Using an USB Docking Station or Hub:
no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Sync, manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

yes

# Issue description:
On device 1, using Displayport, I can easily connect and it works flawlessly.
On device 2, using HDMI, I can't get any DDC connection.

Is there an issue with HDMI? On the website says it supports it.

**Comment by alin23** [comment]
Hi @dahmc 

This is a hardware issue. Lunar simply implements DDC which is a standard which works regardless of the port/cable/monitor used.

If DDC doesn't work, then the issue is with the monitor/GPU/hub/dock etc.

**Comment by alin23** [comment]
Check out the troubleshooting steps in this FAQ: https://lunar.fyi/faq#brightness-not-changing

**Comment by alin23** [comment]
Sorry, I just noticed this: 
> Device 2. Mac Mini 2018, 11.6.1

The Mac Mini HDMI port blocks DDC, that's a known issue without any solution: #125

**Comment by dahmc** [comment]
@alin23 Thanks for the quick reply.

I wasn't aware that the Mac Mini HDMI blocks DDC, I'll try to use a different port then. Thank you
