### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by mattwight** [alin23/Lunar#428]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro M1 pro 2021 16inch

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell S2721QS

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DisplayPort-to-USB-C
    (Also tied HDMI-to-USB-C)
    

- Using an USB Docking Station or Hub:
    yes - Anker PowerExpand 5-in-1 Thunderbolt 4 Mini Dock

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    Yes

# Issue description:
I am able to control the brightness and contrast of the monitor fine but can't control the volume at all. I've tried a few different cables combinations and so far had no luck.

**Comment by alin23** [comment]
Hi @mattwight 

That means that your monitor either doesn't implement the VCP code for volume control, or it blocks DDC volume control commands.

There's no way to fix that in software.

**Comment by mattwight** [comment]
Hi @alin23 

I've managed to get it working by turning the monitor speaker off and on again in the monitor OSD settings. My only issue now is that it works for changing to the volume of the monitor speakers but not the monitors AUX out port. 

Do you know if this is something I should expect? 

Many thanks, 
Matt

**Comment by mattwight** [comment]
Thanks for your reply! Ok cool, I'll do some digging into my monitor settings / drivers and see what I can do.
