### ISSUE TITLE
Using '←' and '→' doesn't work anymore

### ISSUE THREAD

**Issue by ahydronous** [alin23/Lunar#43]
Using either arrow keys to switch between setting tabs doesn't work anymore and gives the 'bong' error sound. This even persists through app restarts or OS reboots. The only way to access the settings page is undocking my Mac and swiping with the touchpad.

**Comment by alin23** [comment]
Sometimes it doesn't work at first launch. Close the window with Cmd+W (but don't quit Lunar) and open the Lunar window again from the menubar (or with Cmd+Option+Shift+L) and the arrow keys should work. I'll see why it doesn't work on first start

**Comment by ahydronous** [comment]
Even after hiding the window with Cmd+W opening it through 'Preferences' still doesn't allow me to use the arrow keys. However, hiding and then opening it with Cmd+Option+Shift+L does allow me to use arrows keys :). Hopefully that helps in tracking it down!

**Comment by alin23** [comment]
Thanks for the details! It definitely helps

**Comment by alin23** [comment]
This should be fixed on 2.9.1
