### ISSUE TITLE
Brightness keys on the Apple Magic Keyboard do not respect the Media Keys settings

### ISSUE THREAD

**Issue by keebuhm** [alin23/Lunar#432]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    *MacBook Pro (15-inch, 2018)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG 27'' Class 4K UHD IPS LED Monitor with VESA DisplayHDR 400 (27UL850-W)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    No

# Issue description:
    Brightness keys on the Apple Magic Keyboard do not respect the Media Keys settings. In particular, when "Brightness keys adjust" settings are set to apply to "Display with cursor", using Brightness keys on the external keyboard will continue to change the brightness of the built-in display even though the built-in Brightness keys work as expected.

**Comment by alin23** [comment]
@keebuhm can you post a screenshot of your Hotkeys page?

For me, your use case works as expected with the following settings:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/3819725/151243428-70c8d4c3-8563-4f08-a0f9-8636894eef1e.png">

**Comment by alin23** [comment]
Tested this countless times and it works as expected. I'll close the issue until new information comes up.

@keebuhm If you still experience this with the above settings, please send:

1. A screenshot of your Hotkeys page of Lunar
2. The log file at `~/Library/Caches/Lunar/swiftybeaver.log`

Maybe also make sure the F14/F15 hotkeys are enabled in System Preferences:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/3819725/151509154-52655fb5-7a5a-46cf-bc32-d4976195186f.png">
