### ISSUE TITLE
Dropdown showing two background panels

### ISSUE THREAD

**Issue by DamiansDesign** [alin23/Lunar#433]
@alin23 

Since a recent update (apologies, I don't recall which) the dropdown pane appears to have 2 separate backgrounds (see image).

![Screen Shot 2022-01-28 at 12 17 29 pm](https://user-images.githubusercontent.com/5009907/151476210-cc9f4ebe-1f94-40c8-8d29-b774823afbb0.png)
 
Lunar Pro v5.2.3
iMac (27-inch, Late 2013)
macOS 10.15.7 (19H1615)

**Comment by alin23** [comment]
This is caused by the Reduce Transparency setting in macOS Accessibility. 

I'll see if I can fix it.

**Comment by DamiansDesign** [comment]
@alin23 

Thanks for the quick reply. Just letting you know I don't have Reduce Transparency enabled.
