### ISSUE TITLE
App Exception button not responsive

### ISSUE THREAD

**Issue by lijunkang12** [alin23/Lunar#44]
When I click on the plus button for App Exception, nothing happens. Any clue why?

**Comment by alin23** [comment]
Yes, there's a missing permission. I'll release a fixed version next week

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lijunkang12** [comment]
Cool, many thanks!

**Comment by alin23** [comment]
This should be fixed on 2.9.1
