### ISSUE TITLE
Disable Update Popup

### ISSUE THREAD

**Issue by litori** [alin23/Lunar#441]
Please give an option to disable to random Update Popup for new releases.  It is incredibly intrusive when you are in another full screen app and it pops up out of no where.  I do not need daily popups, since this app is updated so often, please give the option to disable it.  Thank you.

**Comment by alin23** [comment]
You can disable update checking or change the update check interval from [Advanced settings](https://app.lunar.fyi/advanced) 

![Advanced settings](https://camo.githubusercontent.com/387232026a627270bdf2d97ba6faa7f31a58589e6e3d13110ded06df6033cd40/68747470733a2f2f7374617469632e6c756e61722e6679692f696d672f616476616e6365642d73657474696e67732f313932305f616476616e6365642d73657474696e67732e706e67)
