### ISSUE TITLE
Sensor mode is constantly setting brightness to very high/low and instantly resets it to the value before after current update v5.4.3

### ISSUE THREAD

**Issue by michaelworm** [alin23/Lunar#442]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro 2019

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
   LG UltraFine 27UN880-B

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   USB-C-to-USB-C

- Using an USB Docking Station or Hub:
   no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Sync

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    yes

# Issue description:
I've got the issue that the the brightness goes up/down about +60 brightness and instantly resets to the brightness before the change.
Strangely when the sun goes down, the brightness will be set higher to actual brightness but when the sun is rising in my area, it will be set lower than my current brightness. This occurs about every 10-20 seconds.

Disabling sensor mode and using location mode is not changing brightness as I described - everything is running normally.

I am using Hardware DDC, not software dimming.

Resetting Lunar didn't solve the issue.

<img width="1018" alt="Bildschirmfoto 2022-03-09 um 17 13 55" src="https://user-images.githubusercontent.com/3817545/157484152-2d1818a5-4b4a-4f5d-9798-bd9114bfbaef.png">

**Comment by alin23** [comment]
> the brightness will be set lower to actual brightness but when the sun is rising in my area, it will be set higher than my current brightness. 

I don't really understand this sentence. What does `brightness` and `actual brightness` mean here?

**Comment by michaelworm** [comment]
It's a strange behaviour let me try to explain it. 

The brightness which got set in the sensor mode is currently 47. Then after a few seconds (maybe 10-20) the brightness goes up to 83, stays a little and gets reduced again to 47.

This is switchting all the time.

This morning, the brightness was set lower than my actual brightness but this evening the brightness is set higher than my actual brightness.

<img width="391" alt="Bildschirmfoto 2022-03-09 um 17 29 26" src="https://user-images.githubusercontent.com/3817545/157485845-262e863e-da8a-49f1-ad04-f246c16ed7c4.png">

So it's going from this...
<img width="1062" alt="Bildschirmfoto 2022-03-09 um 17 25 50" src="https://user-images.githubusercontent.com/3817545/157485510-032f3325-de6c-4c77-a97c-6afcef9a28be.png">
 
...to this
<img width="1018" alt="Bildschirmfoto 2022-03-09 um 17 24 26" src="https://user-images.githubusercontent.com/3817545/157485538-29e2c9f8-9a1f-4aab-9dc4-fb211d7d0456.png">

**Comment by alin23** [comment]
@michaelworm is it possible that the sensor stops responding when this happens?

I just tested by turning off my sensor, and as expected, Lunar switched to Sync Mode automatically which led to a higher brightness because the built-in display had higher luminance.

I suspect that this is also happening in your case, but instead you get Location Mode (since Sync Mode is not available for you). That also explains why the brightness goes higher after noon and lower in the morning.

You can force Lunar to only use Sensor Mode by switching from **Auto** to **Sensor Mode**:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/3819725/157498371-8755a162-3444-48b6-8ee6-98d22bcdf6c3.png">

You could check if this is really what's happening by running `ping lunarsensor.local` in a terminal and leaving it there until the problem occurs again. When the you notice the issue, take a look at the terminal to see if there's any timeout similar to the following:

```swift
❯ ping lunarsensor.local
PING lunarsensor.local (192.168.0.104): 56 data bytes
64 bytes from 192.168.0.104: icmp_seq=0 ttl=255 time=54.819 ms
64 bytes from 192.168.0.104: icmp_seq=1 ttl=255 time=6.062 ms
64 bytes from 192.168.0.104: icmp_seq=2 ttl=255 time=97.042 ms
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
Request timeout for icmp_seq 10
Request timeout for icmp_seq 11
64 bytes from 192.168.0.104: icmp_seq=12 ttl=255 time=61.180 ms
64 bytes from 192.168.0.104: icmp_seq=13 ttl=255 time=111.303 ms
64 bytes from 192.168.0.104: icmp_seq=14 ttl=255 time=29.134 ms
```

**Comment by michaelworm** [comment]
@alin23 using only Sensor mode (not auto mode) still doesn't help.

So I was pinging the sensor in the terminal and made 2 screenshots when the issue occured again.

In this screenshot, everything is running normal. So ~65 brightness is the correct brightness for my light situation right now:
<img width="1723" alt="Bildschirmfoto 2022-03-10 um 09 37 20" src="https://user-images.githubusercontent.com/3817545/157622162-656c551b-d146-459c-8d36-a2b21a45045d.png">

Then I made a screenshot when the issue occured, it jumped up to 81 brightness and got reduced to ~65 instantly after that:
<img width="1714" alt="Bildschirmfoto 2022-03-10 um 09 37 28" src="https://user-images.githubusercontent.com/3817545/157622342-60a1574d-58aa-49fe-bb0f-593722e16f32.png">

The ping is continuing so there was no timeout for the sensor.

Location mode gives me 67 brightness for my current location, so Lunar was not switching to Location mode I guess:
<img width="1062" alt="Bildschirmfoto 2022-03-10 um 09 38 04" src="https://user-images.githubusercontent.com/3817545/157623117-e2d19b15-ae9f-40cc-aae2-5c2ba5560fb1.png">

**Comment by michaelworm** [comment]
Are there any application logs which I can give you? Maybe there is an issue which can be seen in the logs.

**Comment by alin23** [comment]
You can also activate **Verbose Logging**, let Lunar run until the issue occurs, then send me the log file at `~/Library/Caches/Lunar/swiftybeaver.log` (ideally compressed)

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/3819725/157631018-e0f94e3b-6a68-4cb9-8ecb-8db3a46425e8.png">

**Comment by trm217** [comment]
I am also encoutering an issue with low brightness and blackout after wake up.
I have an external monitor and my (open) MacBook pro next to it. 
On wake up the external monitor starts as expected, but the built-in is blacked out. 🤔

**Comment by alin23** [comment]
Can you try this beta?

https://files.lunar.fyi/Lunar-5.4.3-beta3.zip

**Comment by trm217** [comment]
I can't consistently reproduce this behaviour at the moment. If I find a way to do so, I'll test the beta 👍🏻

**Comment by michaelworm** [comment]
> You can also activate **Verbose Logging**, let Lunar run until the issue occurs, then send me the log file at `~/Library/Caches/Lunar/swiftybeaver.log` (ideally compressed)
> 
I started the verbose logging and directly after the issue occured at about 10:52:28.432, please see the logfile: https://www.file-upload.net/download-14874548/swiftybeaver.log.html

**Comment by michaelworm** [comment]
> You can also activate **Verbose Logging**, let Lunar run until the issue occurs, then send me the log file at `~/Library/Caches/Lunar/swiftybeaver.log` (ideally compressed)
> 
[swiftybeaver.log](https://github.com/alin23/Lunar/files/8222270/swiftybeaver.log)

I started the verbose logging and directly after the issue occured at about 11:00:28.437, please see the logfile:

**Comment by alin23** [comment]
@michaelworm unfortunately the logs don't show where the brightness was set. I've compiled another beta and posted it on the other issue: #439

**Comment by michaelworm** [comment]
@alin23 Here is the log from the new beta, the issue occured twice:
[swiftybeaver.log](https://github.com/alin23/Lunar/files/8230518/swiftybeaver.log)

**Comment by alin23** [comment]
Yes, it's clear now that the higher brightness (84) comes from Location Mode.

```swift
Set BRIGHTNESS to 65 for LG HDR 4K [ID 459128971] (old: 66)   ["alternativeControlForAppleNative": "Unknown", "isAppleDisplay": false, "serial": "4D6BAA6C-12D1-EC69-8E7B-7AA6A5977FEC", "id": 459128971, "neverUseNetworkControl": false, "connected": true, "name": "LG HDR 4K", "neverFallbackControl": false, "control": "DDC Control", "hasI2C": true, "alwaysFallbackControl": false, "hasNetworkControl": false, "alwaysUseNetworkControl": false, "applyGamma": false, "isSource": false, "showVolumeOSD": false]
...
5   Lunar                               0x0000000102abcee0 merged partial apply forwarder for closure #2 () -> () in closure #2 () -> () in Lunar.SensorMode.adapt(ambientLight: Swift.Double, display: Lunar.Display) -> () + 80
...

Set BRIGHTNESS to 84 for LG HDR 4K [ID 459128971] (old: 65)     ["hasI2C": true, "showVolumeOSD": false, "serial": "4D6BAA6C-12D1-EC69-8E7B-7AA6A5977FEC", "control": "DDC Control", "alternativeControlForAppleNative": "Unknown", "isSource": false, "alwaysFallbackControl": false, "id": 459128971, "connected": true, "neverFallbackControl": false, "hasNetworkControl": false, "neverUseNetworkControl": false, "alwaysUseNetworkControl": false, "isAppleDisplay": false, "applyGamma": false, "name": "LG HDR 4K"]
...
5   Lunar                               0x0000000102a51bb0 merged partial apply forwarder for closure #2 () -> () in closure #1 () -> () in Lunar.LocationMode.adapt(Lunar.Display) -> () + 80
...
```

Are you still using `Auto: Sensor`?

**Comment by michaelworm** [comment]
For the test with the beta I was using Auto: Sensor mode, but for now I am using Location mode which is okay for my current lightning situation.

What is really strange is that when I am using Location mode right now, it gives me the brightness 79 which is lower than the bug which set it to 84, 24 minutes ago? I would assume that the brightness in Location mode and the brightness which gets set during Auto: Sensor mode bug should be the same?

Also the bug appears to happen when using Sensor mode alone, without Auto detecting.

Thanks for the fast and continues support! I really enjoy using Lunar, thanks for the great work!

**Comment by alin23** [comment]
Well, if 24 minutes have passed already, the sun elevation is probably also different so you get another brightness.

It's also possible that the bug makes it so that Location Mode uses Sensor Mode's curve slope which can result in a different brightness.

It's a mess, but at least I have an idea why it's happening now. I'll try to come up with a working fix today.

**Comment by alin23** [comment]
It's a shot it in the dark but here'a a beta with the first fix that came to mind: https://files.lunar.fyi/Lunar-5.4.3-beta7.zip

Until I get to further investigate (and maybe reproduce) the issue, I'm hoping that this could at least decrease the number of occurences.

**Comment by michaelworm** [comment]
Thanks alot, will do!

**Comment by alin23** [comment]
Great! Thanks for testing and helping me with this!
