### ISSUE TITLE
Can't control volume on new Macbook

### ISSUE THREAD

**Issue by fuksinjo** [alin23/Lunar#443]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro M1 Pro 14" (Late 2021)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG ULTRAWIDE 25UM58

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   HDMI

- Using an USB Docking Station or Hub:
    No, directly HDMI to HDMI connection.

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    Yes, didn't work

# Issue description:
Controlling volume doesn't work. Selected output is Lg Monitor, cable is plugged directly in monitor, bc monitor supports it. I've been using this method on my other Windows pc, and on older Intel Macbook Pro (using MonitorControl app at that time). All I see when I press volume up/down keys on keyboard is volume icon that is crossed (like it's disabled).

Also, I am wondering what is the refund policy if this feature ends up not working?

**Comment by alin23** [comment]
Hi @fuksinjo ! Paddle offers refunds with no-questions asked in the first 14-days of the purchase.

The volume control feature is standard, not per monitor. If it doesn't work, it's something related to your hardware that blocks it.

Can you check if MonitorControl volume works on this Mac?

**Comment by alin23** [comment]
Oh wait I noticed the problem now. 

> * Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
HDMI

The HDMI port of the MacBook doesn't support DDC as noted in [this FAQ](https://lunar.fyi/faq#brightness-not-changing)

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/3819725/159116682-2b9b116d-1f9f-4d27-a171-6595dd95e303.png">


Please use one of the Thunderbolt ports to get DDC support.
