### ISSUE TITLE
Enable/disable mirroring for a specific screen

### ISSUE THREAD

**Issue by dominik-lekse** [alin23/Lunar#451]
### Name of the feature

Enable/disable mirroring for a specific screen

### What problem does this feature solve?

In the relevant setup, there is a primary Macbook connected via Thunderbolt to an external display which is the *main* display. The internal display of the Macbook is used as a secondary *extended* display. In addition, there is a secondary Mac connected to external display via DisplayPort.

Sometimes switching the external display to the secondary Mac is necessary while the primary Macbook needs to be available via the internal display only.

Lunar is used for DDC based input switching of the external display from the Macbook (Thunderbolt) to the Mac (DisplayPort) and vice versa.

Before switching the external display from the primary Macbook to the secondary Mac, I would like to quickly enable mirroring on the for the external display on the Macbook. With mirroring enabled, the mouse cursor of the Macbook would stay within the bounds of the internal display and would *not get lost* on the still connected external display.

Enable/disable mirroring could be done in macOS *System Preferences* - *Displays* but requires lots of clicks: Click *Display Settings*, select external display, switch *Use as* dropdown from *Main display* to *Mirror for Built-in Liquid Retina XDR Display*.

It would be great to have to enable/disable mirroring feature with a single click in the Lunar interface right ideally right next to the DDC input switch for an external display.

### How should the feature work

Provide a button or checkbox in the *Lunar menubar interface* and/or likewise in the *Lunar preferences screen* to enable/disable mirroring for externals display.

Consider to allow the user to configure whether this feature is shown.

To me it seems the functionality to enable/disable mirroring for a specific screen is already implemented in Lunar as part of the *Blackout* feature. This request asks to be able to enable/disable mirroring in Lunar *without* changing the brightness of the display.

### Visual description

![lunar-preferences-mirroring-button](https://user-images.githubusercontent.com/4815608/164026682-170214e1-ae43-403b-8fc1-779aaf0a218a.png)

![lunar-interface-mirroring-button](https://user-images.githubusercontent.com/4815608/164026622-979ad97e-267e-4463-b2f0-98c9f734e9cb.png)

**Comment by alin23** [comment]
Hi Dominik!

There's already a hotkey provided by macOS for this: <kbd>⌘</kbd>+<kbd>Brightness Down</kbd>

Doesn't that work for your use case?

**Comment by dominik-lekse** [comment]
@alin23 Thanks for responding quickly.

I indeed tried the shortcut. However, it results in the opposite what I want to achieve. The shortcut enabled mirroring of the external display on the internal Macbook display which in my setup looks weird.

With the feature, I would like to be able to quickly enable mirroring of the internal display on the external display. The following screenshot is from macOS display settings.

<img width="668" alt="macos-display-settings-3" src="https://user-images.githubusercontent.com/4815608/164031588-79d6abf5-6f6e-4d12-8d41-b7704a27e939.png">

**Comment by alin23** [comment]
This wording is a bit hard to understand.

Do you want:
1. The MacBook display to show the contents of the external monitor
2. Or the external monitor to show the contents of the MacBook display?

**Comment by dominik-lekse** [comment]
I am asking for "external monitor to show the contents of the MacBook display".

This is what is already done by Lunar when performing a *Blackout*. However, I am asking to be able to enable/disable mirroring quickly without changing brightness because I want the display bright before switching to a different input source.

**Comment by alin23** [comment]
This ended up being too specific of a use case for Lunar, given that Lunar has to have full support for multi-monitor setups.

I've created a simple Shortcut for this here if you still need it: https://github.com/alin23/mac-utils#mirrormacbooktomonitor

Shortcuts allows both binding a keyboard shortcut and running from the Menu Bar so this should fit your use case.

![cln0002861559](https://user-images.githubusercontent.com/3819725/167415064-b66a104c-2397-4714-8ff6-d14bc5197f77.png)

**Comment by dominik-lekse** [comment]
@alin23 Many thanks for providing the shortcut. I like the solution and confirm it is working.
