### ISSUE TITLE
Lunar actions in Apple shortcuts

### ISSUE THREAD

**Issue by dominik-lekse** [alin23/Lunar#453]
### Name of the feature

Provide Lunar actions in Apple shortcuts

### What problem does this feature solve?

Given Lunar provides granular actions in Apple shortcuts, users could control e.g. display brightness, or display input as part of their Apple shortcuts.

User could embed Lunar features in their (larger) Apple Shortcuts workflows.

### How should the feature work

Lunar could provide fine granular *actions* in Apple Shortcuts. It will be up to the user to combine them to meaningful workflows.

Example actions:
- Set brightness/contrast of specific display
- Set video input source

Actions in Apple Shortcuts would resemble the features which are already provided via the `lunar` command.

### Visual description

- No change in Lunar UI necessary

**Comment by alin23** [comment]
I already started this while doing the CLI but the Shortcuts system is not flexible enough yet. Lunar is very dependent on hardware changes, and Shortcuts for Mac doesn't yet support what I need to represent Lunar's data model inside it.

But I'll keep it in mind, I also want this to be possible.

**Comment by alin23** [comment]
This is now implemented in the latest alpha: `v5.8.1a6`

![update to alpha](https://files.lunar.fyi/update-channel.png)

## Example Movie Time Shortcut

![movie time shortcut example](https://img.panaitiu.com/_/1620/plain/https://files.lunar.fyi/shortcuts-movie-time.png)

## Full list of Shortcuts (so far)

![shortcuts list](https://files.lunar.fyi/shortcuts-list.png)

**Comment by dominik-lekse** [comment]
@alin23 Tried the actions today and they work great! Many thanks.
