### ISSUE TITLE
The XDR button does nothing

### ISSUE THREAD

**Issue by agravier** [alin23/Lunar#454]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):

    M1 MacBook Pro (16-inch, 2021), MacOS 12.2.1 (21D62)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):

    Built-in Liquid Retina XDR Display, 16-inch. There is no other monitor connected.

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):

    built-in

- Using an USB Docking Station or Hub:

    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Auto: Manual*

- Tried Lunar Diagnostics?

> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

Yes, it stays stuck at "preparing monitor diagnostics". I wait a few minutes. I can close it without issue. Nothing new appears in the swiftybeaver.log file.

# Issue description:

When I click on "XDR", nothing happens. Nothing new appears in the log.

When I use the brightness key to try to go past 100, nothing happens either, besides the MacOS OSD popup showing 100. The following lines appear in the log:

```
14:11:49.402 INFO Hotkeys.handleBrightnessKeys():1144 - brightnessUp + []
14:11:49.410 INFO Hotkeys.handleBrightnessKeyAction():1059 - all (lidClosed: false)
14:11:49.414 INFO Hotkeys.adjust():1036 - showOSD(builtinDisplay)
14:11:49.415 INFO Hotkeys.adjust():1015 - Showing OSD for Built-in [ID 1] on brightness=100
14:11:49.416 INFO Hotkeys.adjust():1044 - showOSD(allDisplays)
14:11:49.632 INFO DisplayController.listenForRunningApps():1705 - New running applications: []
```

**Comment by alin23** [comment]
Do you have a Pro license? Maybe your trial has ended.

**Comment by alin23** [comment]
I've made this clearer for the next version:

<img width="421" alt="cln0001751112" src="https://user-images.githubusercontent.com/3819725/164182411-7c828be7-ddda-473b-b0ce-cf7ee4647450.png">

**Comment by agravier** [comment]
Ah, yes, that's the thing :) Thanks

**Comment by agravier** [comment]
On a related note, I think that a feature matrix would help (pro vs unlicensed vs lite). This is one of those pages customers expect and look for on a software sales page. I know the main page gives a list of features with a "pro only" sticker, but compact summary table is valuable IMO.

**Comment by alin23** [comment]
That's already there: https://lunar.fyi/#pro

**Comment by alin23** [comment]
Lunar Lite is a completely different app, it doesn't have anything to do with Lunar.

**Comment by agravier** [comment]
Ah sorry, I missed it at the bottom there, right 👍 — for Lunar lite, I got confused by somehow navigating from the main page to https://lunar.fyi/lite, which uses the same "Lunar" name and same domain. And the same icon?

**Comment by alin23** [comment]
That app is specifically made for App Store users that only want brightness dimming and don't want to download apps outside the App Store.

It uses part of Lunar's code, so it is linked to the full version of Lunar in part. But it's a very basic version of the app, stripped of DDC and low-level code.

I'll try to make it clearer what Lite is for, thanks for the insight!
