### ISSUE TITLE
Notch is enabled in Lunar, but windows do not fill the screen when disconnected from Monitor

### ISSUE THREAD

**Issue by namzo** [alin23/Lunar#456]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 16" 2021

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG Ergo 32UN880

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DisplayPort-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
Yes

# Issue description:
When I disconnect from monitor, there is some space at the top of windows that were maximized. I have the "Notch enabled" in the lunar app but it seems the app still resized the windows.

I only started to notice this after the Notch feature was added.

How can I fix this? Or is there a way to disable the Notch feature completely?

**Comment by alin23** [comment]
I think you're talking about the notch being hidden in fullscreen spaces/windows 😅

You're misunderstanding what that Notch Enabled button is for.

When you see Notch Enabled, that means Lunar is not changing anything. The fullscreen hiding the notch is the default macOS behaviour, you can't disable that. A fullscreen window will always be rendered below the notch.

Lunar can only **disable** the notch, not enable it.

**Comment by alin23** [comment]
You can read more about this macOS behaviour here: https://www.macrumors.com/2021/10/18/macos-hides-notch-on-new-macbook-pros/

Again, it's not caused by Lunar and it can't be overridden/disabled.

**Comment by namzo** [comment]
I understand how it works. Perhaps I didn't explain properly. I meant maximized windows, not fullscreen.

When Notch is Enabled, Lunar shouldn't be changing anything, but the windows are sized like when the Notch is disabled. 

So it creates a blank space (reserved for the menubar, if Notch was disabled). So when I unplug from my Monitor, some windows have a space above them. This happens not just for the active app, but also minimized/hidden apps.

Screenshot:
<img width="1728" alt="Screen Shot 2022-04-30 at 04 57 27 PM" src="https://user-images.githubusercontent.com/1392665/166110707-4424b5eb-1e83-4c06-be4b-44708e2a8329.png">

PS: Sorry for creating a duplicate issue. It was an error.

**Comment by alin23** [comment]
> PS: Sorry for creating a duplicate issue. It was an error 

No worries!

Lunar is not resizing windows, it just switches to a screen resolution that is smaller than the screen height to hide the notch. The resizing is done by macOS.

**Comment by alin23** [comment]
You're probably expecting for the windows to go back to the full height, but macOS usually just keeps the old height. It's the default system behaviour and Lunar doesn't influence that.

If you see Notch Enabled, you can be sure Lunar is not doing anything to your windows.

**Comment by namzo** [comment]
Okay, got it. I just tried it again without Lunar running and was able to replicate the issue. Thanks!
