### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by simon-tannai** [alin23/Lunar#457]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    *MacBook Pro (15-inch, 2017)*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *Acer Nitro VG252Q*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *DisplayPort*

- Using an USB Docking Station or Hub:
    *yes*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync*

- Tried Lunar Diagnostics?
    *yes*

# Issue description:
Hello !

I'm using Lunar on my Macbook Pro with an external monitor connected through a Dell Hub.
The monitor only suports software brightness dimming.

It's working fine but when I have Lunar launched, I have some kind of small unintentional flickering pixel line. It's happening especially when I have a lot of pixels changing (swetching Chrome's tabs for example).

Is there any configuration to set in Lunar to avoid this ?

**Comment by alin23** [comment]
Hi Simon! Not sure what that pixel line is, no one reported this so far. Can you show a recording?

**Comment by alin23** [comment]
Since there's no new information I'll assume this is related to the Gamma issues and consider it fixed in the latest Alpha until new info appears.

**Comment by davidchai717** [comment]
Also experiencing this when the auto blue light filter starts kicking in at night. Some of that flickering remains on my monitor even after I unplug my mac from it... and it usuallygoes away by the next morning. I'll attach a pic next time I see it

**Comment by alin23** [comment]
> Also experiencing this when the auto blue light filter starts kicking in at night. Some of that flickering remains on my monitor even after I unplug my mac from it... and it usuallygoes away by the next morning. I'll snap a pic next time I see it

That's normal, Lunar alters Gamma tables and if you use f.lux or other apps that also work with Gamma, flickering will happen because the apps override each other. It's best to use the system Night Shift as that works at a lower level than blue light filter apps, and is compatible with Lunar.

Although I noticed that Night Shift can also cause flickering on some specific monitors, there's nothing you can do if that's the case for you, it's not a Lunar bug.
