### ISSUE TITLE
Adjustment limit counted incorrectly

### ISSUE THREAD

**Issue by lijunkang12** [alin23/Lunar#458]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro M1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Samsung U32R59x

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    None

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

# Issue description:
It says I have reached my 100 daily adjustment limits, even though I have just launched Lunar for the first time since 5 days and haven't yet done more than 5 adjustments.

**Comment by alin23** [comment]
Ok, will look into it. Thanks for reporting.

**Comment by alin23** [comment]
Found the issue. I'll release the fix in v5.6.4 on Monday.

**Comment by lijunkang12** [comment]
Great, thanks!!!

**Comment by alin23** [comment]
This should be fixed in v5.6.4
