### ISSUE TITLE
Custom brightness when charging vs battery

### ISSUE THREAD

**Issue by satvikpendem** [alin23/Lunar#459]
Is there a way to detect if the computer is charging and if so, set the brightness to a custom value, such as max brightness, and if it's on battery, set it to a different custom value so as to save battery life?

I'm on the new M1 MacBooks that have the XDR screens so I'd like the max brightness to be the XDR maximum.

**Comment by alin23** [comment]
This is possible, but it's not something I'd like to add in Lunar. I'd like to wait for macOS to add **Automation** inside **Shortcuts.app** and then use that to control Lunar based on system triggers like charging/battery etc.

Hopefully we'll see that at WWDC in June.

If you can't wait and want to do this yourself, Lunar has a very powerful CLI that can do what you need:


### Install CLI

```sh
/Applications/Lunar.app/Contents/MacOS/Lunar install-cli
```

### Enable XDR Brightness

```sh
lunar displays builtin enhanced true
```

### Set brightness to 50%

```sh
lunar displays builtin brightness 50
```
