### ISSUE TITLE
Toggle XDR bug

### ISSUE THREAD

**Issue by Blaisorblade** [alin23/Lunar#465]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
  MacBook Pro M1 Max 16'' (2021)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
   Builtin monitor, nothing else connected

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *None*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- Tried Lunar Diagnostics?

    *No — "external monitor diagnostics" was disabled (as no external monitor was connected).*

# Issue description:

When enabling "Toggle XDR brightness based on ambient light" — with the default threshold of 10000 lux, and trying to enable XDR manually (with measured ambient light around 700-1300 lux), Lunar will first raise XDR brightness, but then disable XDR altogether after a few seconds (and sometimes decrease brightness below max SDR). This happens with either setting of MacOS's "Automatically adjust brightness".

Of course, the configuration conflict sounds obvious, but narrowing it down took me a while — I thought this was a conflict with MacOS, not within Lunar. But if I enable XDR by hand, I mean it.

Two complications:
- This option seems to treat XDR like a boolean — if I lower the threshold below the measured ambient light, Lunar toggles the screen to max XDR brightness (100/100). That isn't ideal.
- Lunar must have thought the brightness was changing — both 700 and 1300 were lux values reported by lux (in fact, it even went down to 300), within a few minutes. But I'm sitting still, next to a window with a cloudy German sky, without significant weather changes. So "adjust based on natural light" needs more complex heuristics.

**Comment by alin23** [comment]
@Blaisorblade  This has been fixed for the next version, try updating to the latest alpha to test it:

![alpha channel](https://files.lunar.fyi/update-channel.png)

**Comment by Blaisorblade** [comment]
Thanks a lot, I'll try later. I'll reopen if I have feedback!
