### ISSUE TITLE
Lunar Menubar UI Obfuscates System Windows

### ISSUE THREAD

**Issue by zulaica** [alin23/Lunar#469]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    - MacBook Air (M1, 2020)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    - Built-in

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    - Built-in

- Using an USB Docking Station or Hub:
    - No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    - Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    No, not applicable

# Issue description:
System dialogs generated by Lunar are rendered below the menubar UI. See the attached screenshot which displays the result after clicking "Check for updates." Either the Lunar menubar UI should close after clicking "Check for updates" or the corresponding dialog should have a higher z-index.

<img width="524" alt="Screen Shot 2022-06-22 at 12 59 48 PM" src="https://user-images.githubusercontent.com/4645082/175126477-ed9aaf7f-259e-44f9-9973-bb8dd2f45777.png">

**Comment by zulaica** [comment]
The same occurs when opening Lunar's Preferences.

<img width="829" alt="Screen Shot 2022-06-22 at 1 08 52 PM" src="https://user-images.githubusercontent.com/4645082/175127328-2bb4d80d-3b52-40e2-9826-cf2af3e98d05.png">

<img width="993" alt="Screen Shot 2022-06-22 at 1 09 02 PM" src="https://user-images.githubusercontent.com/4645082/175127377-a24520bf-6cb3-45ab-89fd-a8e3800f9bb6.png">

**Comment by alin23** [comment]
This is not an issue most of the time as the dialogs appear in the center of the screen: [Demo video](https://share.cleanshot.com/QZeo4A)

Those dialogs are handled by the Sparkle updater framework and they have the `dialog` window level which will always be lower than the `popover` window level of the menu.

Closing the menu automatically after clicking the button is simply confusing for the user so I'm not considering this option.

I think it's easier for the user to just click on the menubar icon and close the menu if this issue appears. It's never been reported in half a year of having the new UI so I'm pretty sure it very rarely happens.

**Comment by alin23** [comment]
It's completely normal even for the Preferences window. Popovers are given a higher window level by macOS.
