### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by Blaisorblade** [alin23/Lunar#472]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
MacBook Pro M1 Max 2021

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
2 LG 27UP 850 (27'', 4k — MacOS thinks they're 32'' LG Ultrafine)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
Both USB-C-to-USB-C

- Using an USB Docking Station or Hub:
no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

Lunar 5.7.2 and 5.7.1

- Tried Lunar Diagnostics?

No, it crashed my monitor at the first attempt, so I gave up for now.

# Issue description:

1. Reducing brightness on 1 monitor affects the expected one, but reducing _sub-zero_ brightness on the same monitor affects the other one
2. Blackout for 1 monitor affects both — 1 monitor becomes very dark, the other almost as much, exactly as could be explained by issue 1.

**Comment by Blaisorblade** [comment]
The same issue is affecting 5.6.8 now, so it might not be a regression, but a misconfiguration or a need to reboot. Still pretty annoying :-|

**Comment by Blaisorblade** [comment]
Unplugging and replugging monitors enough worked around the issue (tested with Lunar 5.7.2), so the issue becomes that the detection can be unreliable. OTOH this has happened once in... I guess a couple months, so it's not so common 😄 .

**Comment by Blaisorblade** [comment]
Correction: the issue didn't get fixed — but it's only affecting me if I close the laptop's clamshell.

**Comment by alin23** [comment]
The problem is caused by monitor vendors flashing the same exact firmware with identical serial numbers for all monitors in the same batch. I've written something about this in [this FAQ](https://lunar.fyi/faq#mixed-up-ids), but I should probably explain it in more detail in a blog post since so many people get caught up in this issue. 

There's no way to fix it.
