### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by AdrianCGonzalez** [alin23/Lunar#473]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro M1 Max

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell S2721DGF, Dell U2715H

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   Dual HDMI thunderbolt adapter

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    No

# Issue description:
When attempting to setup hotkeys for input switching on my monitors in version 5.7.2 I am unable to set the same hotkey across multiple monitors for switching input. As I would expect all monitors to switch to the specified input with the single hotkey.

**Comment by alin23** [comment]
This is by design. It's not possible to switch multiple inputs at the same time because DDC needs a warmup time after a screen reconfiguration is triggered by input switching. 

Some monitors might allow this but it's the exception but the rule.
