### ISSUE TITLE
Lunar Feature - Use existing ESPHome Lux sensor as input

### ISSUE THREAD

**Issue by poldim** [alin23/Lunar#475]
### Name of the feature

External Lux Sensor

### What problem does this feature solve?

I love your lux sensor implementation and even better that you provide an option to run it on ESPHome firmware.  But I already have a lux sensor attached to an ESP8266 that's running a custom sensor yaml for an [OPT3001 Ambient Light Sensor](https://www.ti.com/lit/ds/symlink/opt3001.pdf).  Can you allow configuration/setting that lets me bring in this value rather than making another set of hardware?

### How should the feature work

The sensor's value is exposed via the [ESPHome Web Server API](https://esphome.io/web-api/index.html#rest-api).  Provide an input field where I can point lunar to collect the lux value from a specific URL.

in my case, http://esphome-living-window-lights.local/sensor/window_lights_illuminance results with `{"id":"sensor-window_lights_illuminance","value":13,"state":"13 lx"}`

![image](https://user-images.githubusercontent.com/16869713/179891333-078a5549-aeea-4afa-9079-e6da4f54ea22.png)

**Comment by alin23** [comment]
If you would be willing to change the existing sensor ID to `ambient_light` and then map the IP of your ESP to the `lunarsensor.local` hostname inside your `/etc/hosts` file, then Lunar will be able to pick up the lux values automatically. 

You can keep the name of the sensor to "Window Lights Illuminance", only the ID is important for Lunar. 

If you don't want to do those changes, you can try running the lunarsensor server locally which can fetch those values and send them to Lunar: https://github.com/alin23/lunarsensor

I don't want to get in the weeds of making this even more configurable as it can take weeks of work from time I don't currently have, for something that almost nobody uses.
