### ISSUE TITLE
Lunar Feature low power mode force ProMotion enabled

### ISSUE THREAD

**Issue by v1nos** [alin23/Lunar#476]
### Name of the feature

Force ProMotion enabled even on "low power mode"

### What problem does this feature solve?

ProMotion turns off automatically on low power mode or is at least locked to 60hz (u can check in finder or any other application) I think if ProMotion could still do the max 120hz and work like regular even when low power mode enabled it would be good. I would like to enable low power mode for battery saving/heat reasons but I don't want it to affect the ProMotion side of things as 120hz is a primary reason for picking this device. 

### How should the feature work

ProMotion remains as normal even when low power mode is enabled, currently when you enable low power mode ProMotion automatically gets either limited or turned off as 60hz is obviously noticeable. The feature should work in such a way that ProMotion can still do what it did before, give 90/120hz during scrolling animations or whenever deemed necessary and not have a 60hz lock during low power mode.

### Visual description

Button to force ProMotion on as regular even when low power mode is active

**Comment by alin23** [comment]
Hi 👋 thank you for taking the time to write about this!

I'm not sure how much you know about refresh rate power usage, but the difference between 60hz and 120hz is pretty high in terms of battery used. 

There's only so much a laptop can do to lower power usage, and disabling ProMotion makes up a big chunk of that. 

I feel it's pointless to enable LPM and then force enable one of the most power hungry features back. You're better off just not using LPM at all. 

But even if I wanted to do this, there's no public or private API to force ProMotion to be on in LPM. I've already looked at this out of curiosity while I was doing the research for XDR Brightness.

**Comment by v1nos** [comment]
Hi, thanks for the quick response.

That makes sense I just assumed low power mode would also do some CPU or
GPU limiting stuff, and I thought I'd like to have that while also having
ProMotion enabled.

Anyways thanks for the response!

**Comment by alin23** [comment]
> I just assumed low power mode would also do some CPU or GPU limiting stuff

It does limit the CPU frequency and it might also throttle background QoS tasks, but unless you're doing heavy CPU tasks, the power savings will amount to almost nothing.

In my experience the refresh rate and the screen brightness are the biggest battery drains in normal usage. In higher than normal usage (compiling stuff, encoding video etc.) nothing really helps. 

If I know I have to let the MacBook do some compiling for a few minutes on battery and I really need to make the most out of it, I usually enable Blackout for that period of time to at least limit the power usage of the screen.
