### ISSUE TITLE
[Feature] Automatic Dark Mode switching — similar to f.lux

### ISSUE THREAD

**Issue by Aloekior** [alin23/Lunar#478]
### What problem does this feature solve?

Lunar keeps telling me to disable f.lux and use shifty + night shift instead.
In my case, f.lux doesn't do anything but toggle night mode on after sunset because this is way more consistent and at, at least for my preference, better times than letting macOS do it (macOS usually only applies dark mode after entering display sleep for a moment and after wake up dark mode will be applied — f.lux on the other hand will just force it to switch even without display sleep, which works every time).

### How should the feature work

Add a feature to Lunar, similar to the time schedule / location modes, to enable / disable dark mode at a set time (e.g. after sunset / sunrise) automatically, similar to f.lux' "macOS dark theme at sunset" feature in "Color Effects" settings.

**Comment by alin23** [comment]
Hi @Aloekior 

That feature is already in macOS, no need for another app. I never noticed Dark Mode being applied after entering display sleep *(maybe you have something misconfigured)*, the setting is usually applied on the configured Night Shift schedule.

That's what I actually use, I'm certain it works on schedule and doesn't take into account display sleep/wake.

![img](https://media.cleanshot.cloud/media/4001/ftkwETGDEcFwQ3vAbmepBmOsSPuhoPFr8JRMG475.jpeg?response-content-disposition=attachment%3Bfilename%3DShot-System%2520Preferences-14-19.jpeg&Expires=1660152448&Signature=KItSCjoB3r1ToykNGxjg1nHqyVnBG~TZPyaUFOT-dxiDKA~zYsLQHheUcqiw~liN~zdaxfjcVP8sMU1nNuI2kbGE81UXTOIxkh15vL~satmWqJH230FYu0Nm3JBRyJwp9BDCz1nAOY7KHrEQdFKwzey66c58rrrTBzNhzaW2wiQZBC4A4U8udq9cW3hztKgUh9aN4zAMHeZ0nbK5FyywMzZ~KAQB94Cuy1vFD2lw-WuSldXI5fE7Yl2uZFj3dGCpW5c~LwaGUjr2qTN0ECq6qO~BNniw4EoiW4qlKS5iWamGsofm22W75ID~-YtARBEjMVbXTbURuJ3pw43MxiLK6Q__&Key-Pair-Id=K269JMAT9ZF4GZ)
