### ISSUE TITLE
Alpha release showing as available update to stable channel with Latest

### ISSUE THREAD

**Issue by NilsEnevoldsen** [alin23/Lunar#479]
Latest reports that Lunar 5.7.4a2 is available:

<img width="823" alt="latest" src="https://user-images.githubusercontent.com/222743/184186538-09ff840c-81bf-40f4-a4d1-76eedd3cc339.png">

But Lunar itself reports that I am up to date with 5.7.3:

<img width="372" alt="lunar" src="https://user-images.githubusercontent.com/222743/184186571-78ef2f78-a9f4-4ba7-86f7-862b9967ab88.png">

Since I'm unsure if this is an issue with Latest or Lunar, I'm reporting to both projects: https://github.com/mangerlahn/Latest/issues/194#issue-1336218422

**Comment by alin23** [comment]
**Latest** is working correctly, and is using the appcast.xml defined in Lunar's Info.plist.

But the alpha updates are restricted to users that opt in to the alpha channel. You can do that yourself as seen here:

![alpha update channel](https://files.lunar.fyi/update-channel.png)

**Comment by NilsEnevoldsen** [comment]
Is there any standardized way for Latest to know what channel I am on? Does other software maintain multiple appcast.xml to handle update channels?

**Comment by alin23** [comment]
There's no standard for the update channel. They are arbitrarily chosen by the app developer, and are fetched by the Sparkle updater using a delegate method:

```swift
func allowedChannels(for updater: SPUUpdater) -> Set<String> {
    return Set(["beta"])
}
```

It's not possible for Latest to know that information beforehand.
