### ISSUE TITLE
2.9.1 version totally freezes

### ISSUE THREAD

**Issue by lijunkang12** [alin23/Lunar#48]
I have updated to 2.9.1 released ten minutes ago. However, if I open Lunar when I connect my mac to an external display, or if I connect my mac to an external display when Lunar is already opened, the mac totally freezes. Neither the trackpad nor the keyboard is responsive anymore and I have to force reboot the mac.

**Comment by alin23** [comment]
@lijunkang12 can you help me diagnose the problem? I'm building a version with a possible fix to this right now. Meanwhile can you answer these questions?

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *write response here*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *write response here*

- Using an USB Docking Station or Hub:
    *write yes or no here*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location or Manual*

**Comment by lijunkang12** [comment]
Yes of course !

I use a Macbook Pro early 2015. It is connected to an external display using miniDP to DP without usb docking station or hub. Both location mode and manual mode freeze totally.

**Comment by alin23** [comment]
Thanks for the details! Please try this version and let me know if it still freezes and also if Sync mode works well.

https://transfer.sh/a6uAL/Lunar-2.9.2.dmg

**Comment by lijunkang12** [comment]
Unfortunately it still freezes.

**Comment by alin23** [comment]
Would you like to hop on a private temporary chat to continue this? https://shick.me/lunarfreeze

**Comment by alin23** [comment]
This is fixed in 2.9.3
