### ISSUE TITLE
Lunar asks for location permission every day

### ISSUE THREAD

**Issue by alana314** [alin23/Lunar#480]
# Issue details
Macbook Pro 2019 

- Tried Lunar Diagnostics?
No

# Issue description:
I revoked location access to Lunar and other apps, and now it asks for permission every day. I get that Lunar probably uses location to determine sunset times, but I don't need that feature. Is there a way to stop having it ask permission for my location?

BTW I love the app, and purchased pro not because I need the features but just to support.

**Comment by alin23** [comment]
That's odd, Lunar asks for location permissions as any other app would do, and macOS is the one that should stop Lunar from asking when the permissions are revoked.

When Lunar asks, do you press the **Don't Allow** button?

![image](https://user-images.githubusercontent.com/3819725/184547320-d1f2a55b-738c-4cba-a8b8-ca8b79bb0e86.png)

In my case, after I do that, Lunar doesn't ask again. Maybe macOS allows apps to ask again after 24 hours, but I don't see that documented anywhere.

**Comment by alana314** [comment]
Yes, after I click don't allow, it asks again the next day. Here's how it looks in system preferences.
I'm on OS Monterey 12.3.1.

<img width="612" alt="Screen Shot 2022-08-14 at 10 12 02 AM" src="https://user-images.githubusercontent.com/1194589/184547675-426c3109-2cfd-4e7a-99ee-917eca7348e5.png">

**Comment by alin23** [comment]
I've released alpha5 with a fix for this. Switch to the alpha channel and check for updates :)

![alpha channel](https://files.lunar.fyi/update-channel.png)
