### ISSUE TITLE
What can I do when DDC sometimes fails and Lunar has "No Control"?

### ISSUE THREAD

**Issue by merchako** [alin23/Lunar#482]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 2021 M1 Max 14" running macOS Monterey 12.5 (21G72)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG WQHD+ 38WN95C-W

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C (DP alt)

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    All (usually Auto, Location, or Sensor)

- Tried Lunar Diagnostics?
   Yes. If I run the Lunar diagnostic, I get "Software Gamma."

# Issue description:
Inconsistent DDC control. Sometimes when I plug my monitor in, I get full DDC control: brightness, contrast, audio volume—everything I want. Other times, Lunar tells me I have "No control." This makes me sad.

> When working: `DDC Control`
> Before diagnostic: `No Control`
> After diagnostic: `Software Gamma`

If I unplug and replug, if often doesn't fix itself. If I run a DDC reset, nothing happens. (I also want to avoid Full Resets because I need a custom brightness and contrast curve.) 

What can I do to make DDC work more consistently? Or how can I quickly and consistently remedy the loss of control when it happens? I'm not sure if this is a problem with Lunar or with my monitor.

**Comment by alin23** [comment]
That's a macOS/monitor issue that happens for a very small number of people, and it usually fixes itself when restarting the Lunar app. 

There's a hotkey that you can use to make this action faster:

![image](https://user-images.githubusercontent.com/3819725/185659703-f0e321e4-4af3-4a6e-9141-849545d9e90d.png)

**Comment by merchako** [comment]
I was a little confused and upset when I saw that my issue wasn't in the list of Open Issues anymore, but then I realized that you had replied immediately with a solution. Wow. Your support is impressive, and I'm incredibly thankful.
