### ISSUE TITLE
Request: shortcut for Facelight

### ISSUE THREAD

**Issue by patrickrushton** [alin23/Lunar#484]
I haven't been able to find if there's already a global hotkey that I can use to toggle Facelight. So hereby a request for one!

Or even better, allow turning on/off via Applescript or Apple Shortcuts.

**Comment by alin23** [comment]
Hi @patrickrushton the shortcut is Ctrl-Command-5 as shown on the [hotkeys page](https://app.lunar.fyi/hotkeys) and on the [official website](https://lunar.fyi/#facelight)

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/3819725/188110341-e877b080-9dd4-4834-ab16-19d04e476814.png">

![image](https://user-images.githubusercontent.com/3819725/188110452-78f1c86a-469d-42a4-84c4-d923b57b9144.png)
