### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by abstarstrong** [alin23/Lunar#485]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    iMac (21.5-inch, Late 2009)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell P2314H

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    miniDisplayPort-to-DisplayPort

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    N/A

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    N/A (app doesn't run)

# Issue description:
I installed the app and it doesn't run. I'm on MacOS 10.13 and when I try to run the program it doesn't run. I followed instructions listed in a closed issue about this (issue #121) but that didn't help. I would love to get this running. Thanks

**Comment by alin23** [comment]
The app is for MacOS 11.0 and above only. Download the old Lunar 3 for your MacOS version: https://static.lunar.fyi/releases/Lunar-3.2.3.dmg

**Comment by abstarstrong** [comment]
I did and this is the issue
________________________________

**Comment by alin23** [comment]
You might need the Swift runtime manually installed on older MacOS versions: https://support.apple.com/kb/DL1998?locale=en_US

**Comment by abstarstrong** [comment]
worked! thank you!
