### ISSUE TITLE
Lunar Feature

### ISSUE THREAD

**Issue by dmose** [alin23/Lunar#488]
### Name of the feature

Easy (automatic?) submission of monitor info to db.lunar.fyi

### What problem does this feature solve?

Right now, db.lunar.fyi doesn't contain info for my current monitor, nor for the monitor I'm considering purchasing, so it's hard for me to tell if I would lose functionality or not.

I'd happily submit info to the database, particularly if it could help other people, and might convince them to submit their info too (so I could find out about the new monitors I'm considering).

### How should the feature work

a) Simplest version might be just for me to paste the output of `lunar displays` or `ddctl` into this github issue.
b) More advanced would a `lunar cli` subcommand to submit it automagically for me.
c) Thing that would probably help expand the database a lot more: expose b) through the GUI
d) Thing that would probably help most of all: automatically submit anonymized data (perhaps with prompting)

### Visual description

c) [Button or Menu Entry] Anonymously submit my monitor info to http://db.lunar.fyi to make Lunar more useful for more people

**Comment by alin23** [comment]
Hi @dmose 

The data is already submitted and anonymized automatically through Sentry. It takes between one and three days to see your own monitor data on db.lunar.fyi after the first launch of Lunar. 

That's if you don't have Sentry blocked as many do, and if there is no burst of events which could make the ingester drop a few events for keeping throughput. 

You can see this mentioned in the privacy policy: https://lunar.fyi/privacy

I'm not interested in making a manual process for submitting data there, I simply don't have time for this kind of work right now or in the near future.

**Comment by dmose** [comment]
No worries; I didn't realize that was already happening automatically.  Wonderful!
