### ISSUE TITLE
Request: disable showing the dropdown

### ISSUE THREAD

**Issue by bliep** [alin23/Lunar#49]
Somewhere along the development line a new feature in lunar shows a dropdown from the menubar every time a setting is manually changed (or hovering over the icon). Is there an option to disable showing this somewhat large dropdown? Tnx!

**Comment by alin23** [comment]
Check for updates and install Lunar 2.9.5. 

You'll find a new option for disabling that: 
![image](https://user-images.githubusercontent.com/3819725/69968378-f3b4b880-1522-11ea-8820-37f76e153c0a.png)

**Comment by bliep** [comment]
That was fast 👍
