### ISSUE TITLE
External monitor becomes uncontrollable after a while on macOS Ventura

### ISSUE THREAD

**Issue by zierka** [alin23/Lunar#490]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    *MacBook Pro 14-inch, 2021 (M1 Pro)*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *Philips 27" (PHL 272B8Q)*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *MacBook USB-C/thunderbolt port - USB-C Multiport adapter - DisplayPort cable - Monitor*

- Using an USB Docking Station or Hub:
    *yes*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    *yes*

# Issue description:
The external monitor becomes uncontrollable after a while (after multiple sleep-wake cycles) (the brightness lock overlay appears when trying to set the brightness). A physical disconnect-reconnect fixes the issue. Lunar diagnostics also fixes the issue. This issue started happening after upgrading to macOS Ventura (13.0).

**Comment by alin23** [comment]
@zierka try updating to the latest alpha (`v5.8.0a4`) which adds a workaround for this issue:

![](https://files.lunar.fyi/update-channel.png)

**Comment by zierka** [comment]
Switched to Alpha channel, so far so good, I'll let you know if the issue persists.

**Comment by zierka** [comment]
It's till happening with `5.8.0a4`.

**Comment by alin23** [comment]
The problem will always happen, there's no fix for it. 

What we want is for Lunar to auto restart when it happens. 

Can you try enabling the **Avoid safety checks** option in [Advanced settings](https://app.lunar.fyi/advanced)?
