### ISSUE TITLE
USB Input Selection

### ISSUE THREAD

**Issue by aruediger** [alin23/Lunar#493]
### Name of the feature

Change USB input (without changing monitor)

### What problem does this feature solve?

I have two laptops connected to a Dell Thunderbolt Display. I want the Monitor to always display Laptop 1 while having my USB devices (trackpad, keyboard) switched between Laptop 1 and 2.

### How should the feature work

Make a dedicated shortcut or configure per Display options.

Dell's DDM tool [seems to support this](https://www.dell.com/community/Monitors/DDM-USB-upstream-switch/td-p/7869587) by running `ddm.exe /SwapUSB` but I don't know which DDC commands are issued.

**Comment by alin23** [comment]
Thanks for the feature request @aruediger 

Unfortunately this is not a standard DDC command as you can see in the latest [MCCS specification](https://files.lunar.fyi/mccs.pdf).

I don't have the means to reverse engineer and support non-standard commands for every type of monitor.

**Comment by aruediger** [comment]
Fair enough. Thanks anyway!

**Comment by aruediger** [comment]
BTW: Any hints about how one would attempt to trace what DDC commands get sent by that tool?

**Comment by alin23** [comment]
You could first try DDPM on macOS which has a command-line utility as well at `/Applications/DDPM/DDPM`: https://www.dell.com/support/kbdoc/en-ed/000060112/what-is-dell-display-manager?lwp=rt

I usually use Hopper Dissasembler to look inside binaries. From a first look, it seems that Dell actually uses a USB connection for proprietary features like these:

![image](https://user-images.githubusercontent.com/3819725/201146524-cf257201-a121-429b-a51d-f6a716ee49d7.png)

DDC is not an USB protocol, so what Dell does is completely different and outside any standards. If it's doing this communication over USB serial as I suspect, Wireshark sniffing might be a better choice to reverse engineer the protocol.

**Comment by aruediger** [comment]
Thanks for checking!

I was assuming that they have some custom DDC to do this but this is definitely out of scope.

`SwitchUSBConnection` might be the juicy bit here.
