### ISSUE TITLE
Bring Reduce White Point for macOS

### ISSUE THREAD

**Issue by validatedev** [alin23/Lunar#494]
### Name of the feature

Reduce White Point

### What problem does this feature solve?

Unlike iOS, macOS does not have "Reduce White Point" feature. But as we know, with gamma tables, this could be achieved and the feature is implemented for some programs. Here's the screenshot from the app "Gamma Control":
<img width="546" alt="t72HH" src="https://user-images.githubusercontent.com/29679552/202711683-3b4d44c0-b6ed-494f-adbc-e4b9224702d8.png">
When I use the monitor, I am so distracted with white pixels. This feature can solve the issue.

### How should the feature work

For every screen (and there might be an extra global knob also), we should change the white point intensity. There might be a checkbox for the setting to activate the feature.

### Visual description
<img width="373" alt="Screenshot 2022-11-18 at 16 07 46" src="https://user-images.githubusercontent.com/29679552/202712750-ce715aca-c4a6-4f14-8aab-5378e49fa023.png">

**Comment by alin23** [comment]
Hey! That's already possible from the [Colors menu](https://app.lunar.fyi/display/colors)

![image](https://user-images.githubusercontent.com/3819725/202713126-d73bd09b-abf4-464b-81e1-633241f507d5.png)

Keep in mind that this will trigger a macOS bug which disables any HDR capabilities, so if you have any HDR/XDR display, don't use it there if you need the additional brightness/color depth.

**Comment by validatedev** [comment]
Oh thanks for the quick response! It's all fine as I don't have any HDR screen. Works flawlessly :)
