### ISSUE TITLE
Stop event handlers on user switching

### ISSUE THREAD

**Issue by mattclarkdotnet** [alin23/Lunar#496]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Mac Studio (M1 Max/32GB/1TB)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell S2721QS and Dell U2718Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C/TB4 to DisplayPort

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Location
   But I do also make manual tweaks

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    No
    There is no "Open Lunar Diagnostics" menu item in the Lunar menu (see attached file)

# Issue description:
Steps to reproduce:
Have two user accounts on the same Mac
Install Lunar for each account, with auto location based dimming (not sure if this is required, but it is the setup causing the issue for me)
Switch between the accounts regularly
Change the display brightness manually (e.g. using F1/F2)
* Issue 1: sometimes (very unpredictably) Lunar will complain about a non-responsive display (see attached file)
* Issue 2: sometimes after issue 1 occurs, Lunar beachballs

In chat with Alan on Discord, he suggested I get a process sample next time there's a beachball, and I will do this but it might take a few days.

Looking at the code, it seems there is a loginPublisher function (AppDelegate.swift, line 1300) to record whether a given Lunar instance is part of the currently active GUI user session, but the displayController.loggedOut boolean it updates isn't used much.  One possible option might be to have the logged out Lunar process discard all messages until it becomes logged in again?

<img width="589" alt="Screenshot 2022-12-17 at 11 46 41 am" src="https://user-images.githubusercontent.com/648794/208223028-251be14a-2c96-4613-80b6-73700389710b.png">
<img width="608" alt="Screenshot 2022-12-17 at 11 56 02 am" src="https://user-images.githubusercontent.com/648794/208223035-1fb3efbb-639d-4c25-a1f0-6b512240f2e2.png">

**Comment by mattclarkdotnet** [comment]
Oops, it's just that the menu item name has changed.  "Failed to read" is the error when I run the diagnostics.
<img width="950" alt="Screenshot 2022-12-17 at 12 06 20 pm" src="https://user-images.githubusercontent.com/648794/208223925-a0baa268-98f4-4db9-84e3-db5c9500d0a6.png">

**Comment by alin23** [comment]
> there is a loginPublisher function (AppDelegate.swift, line 1300) to record whether a given Lunar instance is part of the currently active GUI user session, but the displayController.loggedOut boolean it updates isn't used much

The part that matters is actually the `sessionDidResignActiveNotification` updating `screensSleeping` which is used in about 50 places inside Lunar's code: https://github.com/alin23/Lunar/blob/master/Lunar/AppDelegate.swift#L1395-L1397

![image](https://user-images.githubusercontent.com/3819725/208983758-81f5c353-bf5e-4bb1-8f02-1abe85fdc5fd.png)

It's very likely I missed a few places though, but it's close to impossible to find those places without a process sample.

I've added a few more checks blindly in the following alpha if you'd like to test it: https://f.lunar.fyi/0IHDEK/Lunar-5.8.1a7.dmg

**Comment by mattclarkdotnet** [comment]
Thanks Alin.  Bizarrely the problem hasn't reoccured since I opened this issue.  Since I can't reproduce it l'll close it.
