### ISSUE TITLE
Lunar crashing occasionally

### ISSUE THREAD

**Issue by mattclarkdotnet** [alin23/Lunar#498]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Mac Studio M1 Max

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell S2721QS, Dell U2718Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to DP

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sensor

- Tried Lunar Diagnostics?
    No

# Issue description:
A couple of times, upon returning to my Mac after being away, the Lunar process has crashed.  Both crash reports attached.
[Archive.zip](https://github.com/alin23/Lunar/files/10297927/Archive.zip)

**Comment by alin23** [comment]
Thanks for reporting!

It would be great if you could try the latest alpha, because as I said on Discord, the current version doesn't cope well with user switching. 

The crash seems to be caused by a race condition somewhere, impossible to know the real reason.

I can only hope that the fixes in alpha 7 will mitigate this.

**Comment by mattclarkdotnet** [comment]
I will do that after the holidays. I love this app, thank you for the craft you put into it, enjoy the break.

**Comment by alin23** [comment]
I had a crash fixing session over the last week. Hopefully v5.9.3 will fix your issues, let me know if you still notice anything.

**Comment by mattclarkdotnet** [comment]
It's been crash-free since the last alpha, so I agree this is closed.
