### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/KoCWZ/lunar.log.enc]

### ISSUE THREAD

**Issue by zhangfb** [alin23/Lunar#50]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *write response here*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *write response here*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *write response here*

- Using an USB Docking Station or Hub:
    *write yes or no here*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location or Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*

**Comment by alin23** [comment]
@zhangfb please respond to the questions in the issue template so I can better understand what is the issue

**Comment by alin23** [comment]
I see the following issue in your log: 
`WARNING AppDelegate.locationManager():604 - User has not authorized location services`

If you are using Location mode in Lunar you have to enable Location Services for the app in `System Preferences -> Security & Privacy`:
![image](https://user-images.githubusercontent.com/3819725/69969134-83a73200-1524-11ea-91b3-999ec8de9c3d.png)
