### ISSUE TITLE
Lunar can't seem to read data from Sensor

### ISSUE THREAD

**Issue by ngocphamm** [alin23/Lunar#501]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Mac Studio M1 Max

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2415. Set of 2.

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to DisplayPort. Set of 2.

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sensor

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

    Menu item name changed, but yes, I tried. 

![CleanShot 2023-01-11 at 08 49 08](https://user-images.githubusercontent.com/395123/211822908-a89ad0e8-3593-42cf-ab93-d98029b66289.png)

![CleanShot 2023-01-11 at 08 48 33](https://user-images.githubusercontent.com/395123/211822940-6db73081-0006-43ce-bbf2-5ba94f1f5c62.png)

# Issue description:
It looks like Lunar fails to read/connect to Sensor. It has always been a bit unreliable, but got a lot worse since the update to 5.9 and up, I think.

![CleanShot 2023-01-11 at 08 41 06](https://user-images.githubusercontent.com/395123/211824037-ecbbfc6f-d24b-4725-8e6b-7d5f6f24cc0a.png)

I can still ping, and read the data from sensor using Terminal, even thought there are occasional timeout, I guess. Another laptop (Macbook Pro Intel Core i9 2019) on the same network can also detect and use the Sensor.

```
~ »  ping lunarsensor.local
PING lunarsensor.local (192.168.203.203): 56 data bytes
Request timeout for icmp_seq 0
64 bytes from 192.168.203.203: icmp_seq=0 ttl=255 time=1090.244 ms
64 bytes from 192.168.203.203: icmp_seq=1 ttl=255 time=86.225 ms
64 bytes from 192.168.203.203: icmp_seq=2 ttl=255 time=100.734 ms
64 bytes from 192.168.203.203: icmp_seq=3 ttl=255 time=121.268 ms
64 bytes from 192.168.203.203: icmp_seq=4 ttl=255 time=144.651 ms
64 bytes from 192.168.203.203: icmp_seq=5 ttl=255 time=164.887 ms
64 bytes from 192.168.203.203: icmp_seq=6 ttl=255 time=185.596 ms
64 bytes from 192.168.203.203: icmp_seq=7 ttl=255 time=204.805 ms
```

```
~ »  curl -N lunarsensor.local/events                                             
retry: 30000
id: 34890048
event: ping
data:

event: state
data: {"id":"sensor-ambient_light_tsl2591","state":"166","value":165.8009}

event: state
data: {"id":"sensor-ambient_light_tsl2561","state":"nan lx","value":NaN}

event: state
data: {"id":"sensor-ambient_light_tsl2591","state":"166","value":165.8532}

event: state
data: {"id":"sensor-ambient_light_tsl2591","state":"166","value":165.9104}

event: state
data: {"id":"sensor-ambient_light_tsl2591","state":"166","value":165.9104}

retry: 30000
id: 34894789
event: ping
data:

event: state
data: {"id":"sensor-ambient_light_tsl2591","state":"166","value":165.9431}

event: state
data: {"id":"sensor-ambient_light_tsl2591","state":"166","value":165.9933}

event: state
data: {"id":"sensor-ambient_light_tsl2591","state":"166","value":166.0451}
```

**Comment by alin23** [comment]
There's a bug in v5.9.2, can you check if this build fixes it? https://f.lunar.fyi/ITteuz/Lunar-5.9.3a1.dmg

**Comment by alin23** [comment]
The detection works like this:

1. Check if the hostname `lunarsensor.local` resolves to an IP every 10 seconds
2. When it is resolved, check for the availability of the following light sensors in a serial manner (because the ESP server is slow and can't respond in parallel):
    1. `ambient_light_tsl2591`
    2. `ambient_light_tsl2561`
    3. `ambient_light`
3. If any sensor is available, start listening to its event data source (note that this doesn't use polling so we first need the sensor to send an event)

These things can take from a few seconds to about a minute. I never had it not working on my side, but there is a way to troubleshoot if the sensor is at fault.

You can try running a local mock sensor and pointing Lunar to it:

```sh
defaults write fyi.lunar.Lunar sensorHostname localhost
killall Lunar

cd /tmp
git clone https://github.com/alin23/lunarsensor
cd lunarsensor

sudo launchctl bootout system/org.apache.httpd  # free up the port 80

make  # install dependencies and start the server
```

Then start Lunar and check how fast it connects to the sensor. The mock server will send events with 400lux only, but it should be enough to check if the latency comes from the sensor or from Lunar.

**Comment by ngocphamm** [comment]
I will try this later today 😃

**Comment by robinhanhart** [comment]
> There's a bug in v5.9.2, can you check if this build fixes it? https://f.lunar.fyi/ITteuz/Lunar-5.9.3a1.dmg

Had the same issue, Lunar didn't find the esp8266 sensor. 5.9.3a1 fixed it for me. Thanks!

**Comment by alin23** [comment]
@robinhanhart Thanks for confirming! Preparing to release this today.

**Comment by alin23** [comment]
Here's a newer release candidate with more fixes around UI, crashes and adaptive modes: https://f.lunar.fyi/uOLSaA/Lunar-5.9.3a1.dmg

The most notable fix in this is learning sub-zero brightness values based on the ambient light *(which didn't work correctly before)*: 

https://user-images.githubusercontent.com/3819725/212117782-1ea83c65-4ce6-4f3b-97eb-8648c643f589.mp4


@ngocphamm @robinhanhart I'd be thankful if you could try it and report if it works.

**Comment by ngocphamm** [comment]
@alin23 Unfortunately I'm not in my workspace where I have the mac M1 and the light sensor, and I won't be for the next few days, so I don't think I can help testing this build. Sorry.

**Comment by alin23** [comment]
> @alin23 Unfortunately I'm not in my workspace where I have the mac M1 and the light sensor, and I won't be for the next few days, so I don't think I can help testing this build. Sorry.
> 
> 
> 
> I am with the 2019 laptop, and external monitor using Sync mode, so if that needs tested, please let me know.

That's ok, thanks for letting me know 😊

**Comment by robinhanhart** [comment]
@alin23 External sensor works well with the updated version. 👍 
Btw I'm also on a Mac Studio M1 Max
