### ISSUE TITLE
The dimming dissapears randomly

### ISSUE THREAD

**Issue by fermmm** [alin23/Lunar#502]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Air M1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    BenQ EX2780Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI with a hub (good quality hub)

- Using an USB Docking Station or Hub:
    Hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Clock mode

- Tried Lunar Diagnostics?
    Yes, I think is not related with the issue

# Issue description:
The "software dimming" of the external monitor stops randomly, it's not caused by any specific action, sometimes it happes while I'm watching the screen without touching anything. Sometimes happens in a couple of hours and sometimes in minutes. The brightness bar remains at the position of the desired brightness, then when I click on the slider the dimming is back, to be removed later randomly again.
I tried "Monitor Control" app and the dimming does not have this problem. I know this may be a hard to reproduce bug, in that case maybe you should reimplement the software dimming in the way MonitorControl app does it.

**Comment by alin23** [comment]
Hi @fermmm Lunar and MonitorControl use the same software dimming methods. In fact the dev that implemented it in MonitorControl was guided by me on Discord. 

Are you using f.lux or anything similar that could reset the Gamma tables?

Just to be sure, check if Gamma is selected for software dimming in the [Controls menu](https://app.lunar.fyi/display/controls):

![image](https://user-images.githubusercontent.com/3819725/211893272-753a1105-fd7a-4da4-b53f-1b24bec34d17.png)

**Comment by fermmm** [comment]
> Hi @fermmm Lunar and MonitorControl use the same software dimming methods. In fact the dev that implemented it in MonitorControl was guided by me on Discord.
> 
> Are you using f.lux or anything similar that could reset the Gamma tables?
> 
> Just to be sure, check if Gamma is selected for software dimming in the [Controls menu](https://app.lunar.fyi/display/controls):
> 
> ![image](https://user-images.githubusercontent.com/3819725/211893272-753a1105-fd7a-4da4-b53f-1b24bec34d17.png)

Yes gamma is selected

**Comment by alin23** [comment]
Oh now I see that I recommended Lunar to you on MonitorControl. So first, if you mostly want to lower the brightness at two times of day (sunset/sunrise) then Location mode is better for what you want. Clock Mode is by definition an advanced mode for people that need specific schedules.

All the other UI issues you are talking about are personal choices, because first and foremost Lunar is made for me to use. You seem to prefer native elements, so maybe Lunar is not the best choice for you. Maybe you can develop your own simple automation using MonitorControl and [m1ddc](https://github.com/waydabber/m1ddc).

I'll be happy to give you a refund if you can give me your order number.

**Comment by fermmm** [comment]
Ok I don't like the UI, and the fact that this app is the only option for MacOS with this feature. I prefer you fix the bug before a refund, so I can use it, whay you closed it? the bug is still there. I have no other option than using your app, the advice you mention takes work and knowledge to be done.

So the gamma options is bugged? I'll try the Overlay option and see if the bug is gone, in that case you should remove the Gamma option until it works.

**Comment by alin23** [comment]
Gamma works alright for me and about 5k other users that use it every day, I'm guessing it might be something specific to your setup. 

I'd like to help but I need more info, do you use f.lux or anything that could change Gamma at the same time you use Lunar (like MonitorControl, Gamma Control etc.)? Do you change color profiles or use anything that could change them automatically?

> if you say you made the app just for you then with that logic it should be free of charge.

I made it for me **first and foremost**. If other people like it, they will pay for it.

**Comment by fermmm** [comment]
> I'd like to help but I need more info, do you use f.lux or anything that could change Gamma at the same time you use Lunar (like MonitorControl, Gamma Control etc.)? Do you change color profiles or use anything that could change them automatically?

No, I don't have f.lux installed or other software like that, when I open Lunar I close MonitorControl because I know it may cause issues. The only thing like that is "true tone" OS feature, I have that enabled.

**Comment by fermmm** [comment]
Also there is an OS feature called "Night Shift" I see it disabled but now I checked in the display configuration menu of the OS and I had it enabled by time, maybe that was also the issue. In that case if a OS feature is not compatible with the gamma feature it should be removed or fixed, maybe the 5K users you have are not using gama option or the ones using it don't want to spend their time reporting the issue.

**Comment by alin23** [comment]
Night Shift and True Tone work alright with Gamma dimming. I have reliable data on if Gamma or Overlay is used, and people are pretty fast in yelling at me when a feature doesn't work how they want. 

That's how I'm aware that the current v5.9.2 version has quite a lot of bugs introduced by my crash fixing session. Just in case, try using the latest version I'm working on to make sure it's not some bug I've already fixed today: https://f.lunar.fyi/PZiXRQ/Lunar-5.9.3a1.dmg

Ok, how often can you reproduce this? You could try enabling Verbose Logging, try to reproduce the issue, then send me the file located at `~/Library/Caches/Lunar/swiftybeaver.log`

![image](https://user-images.githubusercontent.com/3819725/211903747-96e5bd60-060d-4f60-b01b-ff4c0860f59e.png)

I'm thinking this could be caused by the zero Gamma bug (a macOS bug that can make displays completely black when a specific color profile and gamma formula is present). Lunar has a detector running in the background for that, and resets any dimming when it detects the bug manifesting to avoid black screens that are only fixable through a restart.

**Comment by fermmm** [comment]
It heppened in Overlay mode, but takes more time in this mode or maybe the same happens for a different reason, I don't know. 
This is the log file copied just after the problem happened and I touched the brightness slider to restore the overlay:
[swiftybeaver.log](https://github.com/alin23/Lunar/files/10397131/swiftybeaver.log)

**Comment by fermmm** [comment]
More info: I noticed the dimming failing inside the "dim time" that I have configured in clock mode. I don't know when it happened, I just noticed the high brightness at at some point. Today I closed session of macOS and I thought that this time the issue may be caused by that so I tried closing session again, then when starting session I tried to open the lunar UI clicking on the status icon and the menu appear missplaced, then after a couple of clicks Lunar crashed. I restarted the session again and this time it worked fine, that seems to be another bug not related anyway.

**Comment by alin23** [comment]
Yes the crashes are unrelated, I'm working on them as fast as I can. This might be a Clock Mode issue after all.

Can you try enabling Gamma and using Sync Mode instead for a while?

That mode should detect the automatic brightness changes done by the system to the builtin MacBook screen, and sync them to your monitor through a curve algorithm. 

Changing the brightness of the external monitor manually will make Lunar learn that and adjust the curve algorithm accordingly.

**Comment by fermmm** [comment]
> Yes the crashes are unrelated, I'm working on them as fast as I can. This might be a Clock Mode issue after all.
> 
> Can you try enabling Gamma and using Sync Mode instead for a while?

I cannot do that. I tried that feature before and could not make it work as I wanted, I always have discomfort with the brightness of one monitor, that curve algorithm does not match the brightness of both monitors.

Did you find the bug with the log I sent or you have no idea where it is? Are you going to fix it?

**Comment by fermmm** [comment]
Location mode also changes brightness in amounts I'm not comfortable with and I have no control over it. Is there a way to customize that? I don't understand the UI

**Comment by alin23** [comment]
God, just give me your order ID so I can give you a refund. I don't want to continue this, there's just so much disrespect it's not worth $23.

**Comment by fermmm** [comment]
why disrespect? I'm telling the truth. You may not have idea where is the bug I'm developer and that is normal. I really don't understand the UI. If you have 5K users it's because there is no alternative, that is not disrespect it's the truth. I don't want a refund because I don't have other option. I think disrespect is closing this issue without fixing. I don't like this eather but I don't have other option and I cannot refund because of that.

**Comment by alin23** [comment]
Alright then, if you don't want the refund, you're free to make the app work for you however you please. You bought the app as it is and you had a 14-day trial to decide before buying. I'm not selling my time as support for this amount of money. 

The bug may be there, I can't reproduce it, and I don't have enough data on it to find it and fix it. I'm at the end of a full week of 12h days of fixing bugs in this spaghetti code mess, I have to take a break. 

The app is good enough for most people for now.
