### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by nikosolihin** [alin23/Lunar#503]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    *Mac Studio 2022 with M1 Max*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *LG UltraFine 4K 32UN880* [Product Link](https://www.lg.com/us/monitors/lg-32un880-b-4k-uhd-led-monitor)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C-to-DisplayPort cable*

- Using an USB Docking Station or Hub:
    *No, directly plugged into one of the USB-C ports on the Mac Studio*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- Tried Lunar Diagnostics?
> 1. Click on **Open external monitor diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    *Yes, all steps passed.*

# Issue description:

All steps passed during setup (brightness, contrast, volume, etc.). However, I cannot switch the monitor to any other input sources.  Worked if I use the monitor button.

Any clue as to why this is?

**Comment by alin23** [comment]
Hi @nikosolihin 

Unfortunately, not all monitors support the input switching DDC control.

If nothing happens when you switch to any input from Lunar, or if you just see the monitor blink, that means it's the monitor not supporting that.

**Comment by nikosolihin** [comment]
@alin23 Thanks for your response. Do you by any chance have a list of monitors that support DDC input switching?

**Comment by alin23** [comment]
No, vendors don't publish this information and I don't have a way to aggregate it other than simply asking around because it can't be detected in software.

**Comment by nikosolihin** [comment]
@alin23 Gotcha. Thanks so much. Keep up the awesome work with Lunar!
