### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by johnfu360** [alin23/Lunar#504]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
  I have rx6600 with DPX3. HDMI x1. I was try use 1 HDMI and 1 DP, but every time I enable the app, the HDMI monitor will turn on for 1 sec then go to black screen, I try many times, but still the same

**Comment by alin23** [comment]
Sounds like your setup doesn't support DDC, and behaves anomalously when a DDC command is used. 

There's nothing I can do to fix it, it isn't a software problem. 

You can try something like [GammaDimmer](https://lowtechguys.com/gammadimmer) to get brightness dimming without DDC.

**Comment by johnfu360** [comment]
Thank you
