### ISSUE TITLE
Lunar Bug (license holder)

### ISSUE THREAD

**Issue by stephenjason89** [alin23/Lunar#507]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    mac studio ultra ventura 13.1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Eve spectrum

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   thunderbolt and also type-c to display port

- Using an USB Docking Station or Hub:
   no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    any

- Tried Lunar Diagnostics?
> 1. Click on **Open external monitor diagnostics** in the Lunar menu

> 2. Follow through the steps when asked

          yes it is working

# Issue description:
If i turn on my monitor's HDR
then when i adjust the brightness, everything turns to greyscale.

**Comment by alin23** [comment]
This is a monitor or macOS problem. Lunar simply sends a Set Brightness command to the monitor. If it goes to grayscale, it's the monitor not handling that command correctly.
