### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by stephenjason89** [alin23/Lunar#508]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Mac studio ultra ventura 13.1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    eve spectrum

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   thunderbolt & type c to display port

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   location

- Tried Lunar Diagnostics?
> 1. Click on **Open external monitor diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    yes

# Issue description:
*write a short description of what doesn't work as expected*

<img width="599" alt="image" src="https://user-images.githubusercontent.com/3810177/218622534-385f3879-db4b-42c4-a716-0a57a4be0fc4.png">
I have 2 monitors and 1 monitor is horizontal and the other vertical

under the horizontal monitor setting clicking on advance settings->control->panel settings
this shows the vertical monitor's panel setting and not the horizontal.
If i check the vertical then it is also reversed. It shows the horizontal panel setting.

**Comment by alin23** [comment]
This is a widespread issue in macOS where monitors with very similar firmware data show up as identical to apps and it's impossible to distinguish between them. 

Because of that macOS assigns UUIDs for them in a random manner and apps like Lunar can't know which settings were for which monitor. 

You can read more about the problem here: https://notes.alinpanaitiu.com/Weird%20monitor%20bugs

It's not fixable in software.

**Comment by stephenjason89** [comment]
Hello @alin23  thank you for taking the time to reply

I understand what you're saying and have experienced this first hand

But i think this error is a bit different 


As you can see, i labeled my monitor Horizontal and Vertical

And at the time of this testing, if i change the Vertical monitor's brightness i can see that the vertical monitor brightness is changed. Now if i put the computer to sleep, then the issue you linked might happen and the macos might not be able to correctly identify the monitor and switch the two. 

But my issue is, without putting the computer to sleep if i change the advance setting of vertical monitor like resolution, then it changes the other one (horizontal) 

This is after i have just tested that vertical monitor's brightness is correctly being changed on the correct monitor.

Thanks 🙏

**Comment by alin23** [comment]
It is the same problem though, even if it might not appear so. 

For changing the resolution, Lunar uses a private system framework called MonitorPanel, the same one that's used by the system resolution/scaling in Display Settings. 

To set a resolution to a display, Lunar gets an instance of an MPDisplay class using its id. If the system can't differentiate between the monitors, the instance can be for the wrong display. 

For DDC, Lunar has its own DDC port matching logic independent of the system matching, so it's entirely possible that DDC commands are sent correctly but things that use MonitorPanel fail.

**Comment by stephenjason89** [comment]
@alin23  thank you for explaining this further. Would you happen to know a way to change the monitor's uuid or edid? 
Do you think flashing 2 different firmware could help? One with f106 the other f107 for example? 

Or maybe there's an adapter that can spoof it plugging it in between the pc and monitor

**Comment by alin23** [comment]
🤔 different firmware could be a good idea. I'm not sure if that version shows up in the EDID, but if it does then it would help. 

Otherwise, using different connections always helps: one DP/USB-C and one HDMI. That's because the system EDID UUID includes the connection type in one of the bytes. 

There's also the possibility of changing the EDID, but I haven't tried it on macOS. Windows has a [nice utility for this](https://ez.analog.com/video/w/documents/750/advantiv-edid-editor)

It should be enough to just change the manufacture week or year to get a different EDID UUID.

**Comment by stephenjason89** [comment]
I'm using a mac studio and all inputs of mac studio is type c

So i have tried type c to dp and type c to type c (thunderbolt) but it's not working. 

I think it should be the other way around with 2 different inputs to the computer.

Thank you for linking the tool on windows. After the edid change is it stored at the monitor? I'm thinking of changing it with a windows pc then plugging the monitor back on my mac.

**Comment by alin23** [comment]
Yes, the EDID is stored in the monitor memory persistently. You can try that.

About the connection, HDMI-to-USB-C adapters/cables most of the time report themselves as HDMI connections so that also changes the byte in the UUID. But I'm guessing you don't have such an adapter around.

**Comment by stephenjason89** [comment]
@alin23  thank you, yes i believe hdmi would be an option. But my monitor currently doesn't support hdmi 2.1 and I'm running 3840x2160 at 144hz.

I'm using an eve spectrum btw. 
I would try to change it via windows tool and will let you know if I'm successful.


Thank you so much for the help
Really appreciate it
