### ISSUE TITLE
Make Pro code available under a proprietary source-available license

### ISSUE THREAD

**Issue by CONIGUERO** [alin23/Lunar#509]
Pro features' code is currently unavailable.

It would be beneficial for paid users to be able to access the source code to the Pro features and contribute fixes/debug the program in its entirety.

For this, a source-available approach can be used, where the free portions are MIT-licensed while Pro ones are separately available under a proprietary license that only allows usage if the user bought the features, disallows redistribution/cracking, etc.

I believe this to be the best approach for transparent, efficient, community-friendly development while at the same time not negatively affecting the app's business model.

**Comment by alin23** [comment]
Thank you for the request but I don't want to do this. 

I've had enough competition from people stealing my hard worked code without any attribution, going as far as demeaning my work on the internet. 

I like it this way.
