### ISSUE TITLE
Screen not working anymore with MacOS after clicking "Notch enabled" - persists after uninstalling Lunar

### ISSUE THREAD

**Issue by va1entin** [alin23/Lunar#511]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro 2021

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG UltraWide 5K

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   Thunderbolt

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Not sure

- Tried Lunar Diagnostics?
> 1. Click on **Open external monitor diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    Diagnostics are greyed out until I connect my monitor, which makes the system unusable as described below.

# Issue description:
I just tried Lunar with my new LG UltraWide 5K screen via Thunderbolt and after initial setup, I made the grave mistake of clicking on the "notch enabled" button inside Lunar. The screen went into an endless loop of being detected and not detected (I saw it appear and disappear constantly in MacOS system settings). Hoping that I could solve the issue quickly, I uninstalled Lunar but the issue persists - basically I can't use my screen anymore with this device.

I tried rebooting, shutting down, plugging and unplugging but the problem persits. I have not yet tried reinstalling MacOS as I'm hoping that is not what it will take to reverse whatever Lunar did.

**Comment by alin23** [comment]
Weird. All that button does is set a native resolution on the MacBook using the system framework for setting resolutions.

Was that Notch Enabled button appearing on the LG screen? It should only appear for the MacBook screen

**Comment by va1entin** [comment]
The button showed up for the LG screen. I tried changing the brightness via Lunar before but nothing happened.

How can I reset the native resolution that Lunar might have set? Do you have reset instructions to reverse everything Lunar can change?

**Comment by va1entin** [comment]
When the screen briefly turns on just to disappear immediately the resolution is very distorted - in case that is relevant.

**Comment by alin23** [comment]
That resolution is set persistently inside the system screen configuration. Uninstalling Lunar doesn't remove that because you can make any change to the screen configuration through System Settings -> Display. I wouldn't have a way to detect what is done through Lunar and what isn't.

You can try deleting the configuration files yourself from the command line:

```sh
rm ~/Library/Preferences/ByHost/com.apple.windowserver.displays.*.plist
```

Then restart the computer.

I'd be grateful if you could help me with some info after this is fixed so I can understand why this happened.

**Comment by va1entin** [comment]
Thank you for the fast reply. This did not resolve the issue unfortunately.

**Comment by va1entin** [comment]
FYI: I can't run Lunar diagnostics because it is greyed out until I connect my monitor - which makes the system unusable immediately.

**Comment by alin23** [comment]
Oh there's also a global config file:

```sh
sudo rm /Library/Preferences/com.apple.windowserver.displays.plist
```

**Comment by va1entin** [comment]
> 



> Oh there's also a global config file:
> 
> ```shell
> sudo rm /Library/Preferences/com.apple.windowserver.displays.plist
> ```

That resolved the issue! I had to connect the monitor twice until the MacBook used the proper resolution but all back to normal it seems 😃

**Comment by alin23** [comment]
Ok, I also found the bug that made that button appear erroneously. You can use this alpha build which contains the fix and what I'm working on for the next version: https://f.lunar.fyi/bJdpYa/Lunar-5.9.6a4.dmg

Let me know if I can help you with the brightness not working. LG Ultrafines like yours should support the Apple Native protocol which appears like this:

![image](https://user-images.githubusercontent.com/3819725/220145658-0b1e9808-bb8e-4bac-bbe1-249182ee45e5.png)

If it doesn't work, it's possible that the communication is blocked by something external. Usually it's a hub/dock/adapter or a cable that doesn't support the full Thunderbolt communication. It may also be a system bug.

You can also try disabling Apple Native from the [Controls menu](https://app.lunar.fyi/display/controls) and falling back to DDC brightness control in case that works: 

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/3819725/220146445-714939e6-7bad-4c8e-a16c-9468e2cd0e0a.png">

**Comment by va1entin** [comment]
Lunar only offers Hardware DDC (and Software Dimming) for the screen. It appears as "LG HDR 5K" and is connected with the official Thunderbolt cable. 
Hardware DDC is perfectly fine for me though since I just want to change brightness every now and then.
Thanks again for the fast and excellent support! ❤️ 

The notch button has disappeared now by the way. I did **not** install the alpha from your last comment yet.
