### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by ozum** [alin23/Lunar#512]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro 2018

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Benq BL3201PT

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    miniDisplayPort

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Auto Mode

- Tried Lunar Diagnostics?
> 1. Click on **Open external monitor diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

  Yes

# Issue description:

Related to #510

When using Shortcuts "DDC Green" cannot be adjusted. Red and Blue are OK.

DDC Green works when using Lunar. Also every command including Advanced Settings (Hardware DDC RGB etc.) works on LUNAR GUI.

![image](https://user-images.githubusercontent.com/1497060/220152658-63e8986e-0a2b-4458-b7bc-b61d2e40ba77.png)

**Comment by ozum** [comment]
@alin23

> How are you checking if the green was applied?

I checked through the monitor's menu and also the view is obviously greenish.

![IMG_2593 Large](https://user-images.githubusercontent.com/1497060/220249726-1e3f2f89-df4b-4fe5-ad0d-03d81b5e61a2.jpeg)


I have two monitors. It works for Dell both via GUI and Shortcuts. However for Benq, it only works via GUI, but not Shortcuts. Since GUI works for both of them, I know the monitors support DDC.

I even tried some tricks hoping to get a result:
- "Wait longer between DDC requests",
- Added the same command twice hoping the second one catches if the first one misses.

![image](https://user-images.githubusercontent.com/1497060/220249008-c3a4ee45-27ef-405d-b59f-32585fb44850.png)

![image](https://user-images.githubusercontent.com/1497060/220249423-ee3f90d0-9cf0-4261-81eb-297265a10243.png)

Do you know if there is any more data (logs etc.) I can collect and provide?

**Comment by alin23** [comment]
Try this alpha build: https://f.lunar.fyi/Tv4E2A/Lunar-5.9.6a4.dmg

I added a way to send color values with a small delay between:

![image](https://user-images.githubusercontent.com/3819725/220452353-504af727-92c1-4632-9187-44c5bcf8268a.png)

**Comment by ozum** [comment]
Thanks. This fixed the problem.
