### ISSUE TITLE
Shortcut works half when Lunar is off.

### ISSUE THREAD

**Issue by ozum** [alin23/Lunar#513]
This issue is not a problem for me, but I wanted to report hoping it helps development.

When Lunar is open (the icon is on the menu bar) shortcuts work as expected.

If I quit Lunar and execute a shortcut, Lunar is opened by Shortcut briefly during the actions. However, only a few of the actions are applied.

For example only brightness and Red are applied if Lunar is not open:

![image](https://user-images.githubusercontent.com/1497060/220609388-cbd9882b-afa3-4f68-9226-7f73f4741ff8.png)

**Comment by alin23** [comment]
Shortcuts need the whole app code, and the displays and their states already loaded in memory. For such a complex app it's not possible to run the Shortcuts out of process.
