### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/jET2m/lunar.log.enc]

### ISSUE THREAD

**Issue by lgandecki** [alin23/Lunar#52]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No, not on external monitors neither on the macbook display

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Macbook pro 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
HDMI-to-USB-C and USB-C-to-USB-C

- Using an USB Docking Station or Hub:
I do but displays are not connected

- Lunar mode used (check it in the top-right corner of the Lunar interface)
I tried different modes, none of them seem to change the brightness (I'd expect setting the percentage from 0% to 100% and all in between to make a difference, but it didn't)

<img width="366" alt="image" src="https://user-images.githubusercontent.com/4002543/70393708-42bc8b00-1a06-11ea-8dcc-022bd88b10d4.png">

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl

nope.
```
D: NSScreen #1986003208 (3200x1800 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: SONY TV  *00
D: action: b: 10
D: setting VCP control #16 => 10
E: Failed to send DDC command!
D: action: c: 10
D: setting VCP control #18 => 10
E: Failed to send DDC command!
```

interestingly, it only sees one external display, but I use two.

# Issue description:
Nothing seems to work unfortunately :( none of the modes or manual tweaking make any difference.

**Comment by lgandecki** [comment]
I guess the question is, can I expect this to work with TVs? I have a sony 55" OLED + LG 43UD79-B, which supposedly is a monitor, but it's really a TV with a tuner.

**Comment by alin23** [comment]
Hi @lgandecki ! Thanks for the detailed report!

I have tested Lunar with 4 different TVs and none of them worked. It's not Lunar at fault here, TVs just don't care about DDC and there's nothing we can do in software about that.

So I would say that's the issue here. If `ddcctl` doesn't work then I'm sure there's no way to make Lunar work either.
