### ISSUE TITLE
complete crash on mac OS Catalina

### ISSUE THREAD

**Issue by ggrrll** [alin23/Lunar#53]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    kind of...

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    macbook pro 

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *DisplayPort*

- Using an USB Docking Station or Hub:
    *no*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

# Issue description:

I think there is a problem with the latest update and catalina 10.15.1. 
my laptop quickly shut down when:
1 - I tried to change the brightness once
2- simply hover the mouse over the applet in the toolbar

...then I removed the app

**Comment by alin23** [comment]
Can you install the latest version from https://
lunar.fyi and try that?
There was a particular version _2.9.1_ that had an issue and freezed the system for monitors that didn't support reading values from them.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ggrrll** [comment]
that's what I did this morning ...

**Comment by alin23** [comment]
I also have macOS 10.15.1, so that's not the issue here. Either the monitor has an incompatibility or Lunar has a bug. Unfortunately it's impossible to diagnose this kind of issue because the crash log is lost if the system freezes or restarts.

One thing you could do to help me diagnose this issue is to run this utility in the terminal and send me the output: https://transfer.sh/14j1FF/EDIDReader

It will dump the monitor internal data and try to read its brightness, contrast and other values. From that I could see if there is any error in the data retrieval logic.

**Comment by ggrrll** [comment]
in that link there is nothing apparently

ps: my monitor is DELL P2414H

**Comment by alin23** [comment]
Sorry, it expired: https://transfer.sh/pzmPu/EDIDReader

**Comment by ggrrll** [comment]
dms file? https://fs-uae.net ?

**Comment by alin23** [comment]
It is a compiled binary that you have to run in the terminal:
1. Open Terminal.app
2. Go to the folder that has the file (probably Downloads) by running the following command: `cd ~/Downloads`
3. Run the file with the following command: `./EDIDReader`
4. Copy and paste the output of the command here

**Comment by ggrrll** [comment]
( thanks, I  know the basics of  bash :))

still, it gives `command not found`

**Comment by cmiller734** [comment]
Hi guys, I've had the total crashing issue before too. It happens on my Mac when I checked "read display values" or something similar from the main menu. Before that, worked like a charm. It comes unchecked, did you check it?

**Comment by alin23** [comment]
@cmiller734 I responded to your issue, please check that 😄

**Comment by alin23** [comment]
This should be fixed in 3.0.0. Feel free to reopen if the issue persists.
