### ISSUE TITLE
Lunar Diagnostics Report

### ISSUE THREAD

**Issue by cmiller734** [alin23/Lunar#54]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   What diagnostics process?

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI to Thunderport hub to thunderports

- Using an USB Docking Station or Hub:
    Yup

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Syng

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
So I love lunar but it completely stopped working for me after I selected the option to Read Display Values or whichever tick mark makes the computer crash. I used the 'defaults write' command, but that didn't work. Is there any way to COMPLETELY overhaul the application, including defaults? Thanks

**Comment by alin23** [comment]
You used the diagnostics report issue template, and this is automatically selected when you use Lunar Diagnostics from the Lunar menu, that's why there's a diagnostics related question. I should make another template for manual issues.

So Lunar reads its settings from `~/Library/Preferences/site.lunarapp.Lunar.plist` and the `defaults` command modifies that file, but if Lunar is running while you do that, the change will be overwritten by Lunar. Make sure you quit Lunar from the menu bar before doing that.

If you really want to reset Lunar, just quit Lunar, delete that file and relaunch Lunar.

**Comment by cmiller734** [comment]
Hi, I confirmed the refreshBrightness system preference was set to 0 and tried again. Still crashed. I uninstalled and re-installed completely - still crashed. So the two proposed solutions unfortunately didn't work :/

**Comment by alin23** [comment]
I'm sorry, I have no idea what could be the issue here. You could try to search for anything called `Lunar` inside `~/Library/` and delete that. There is no other place that Lunar looks for settings.

**Comment by cmiller734** [comment]
I'll try deleting the plist and try again.

**Comment by cmiller734** [comment]
Hi!!

I wanted to let you know that I was able to get it going after deleting my preferences for Lunar (the plist file).

Perhaps suggest in the read through that if the first options fail (deleting and re-installing, or changing that flag via writing via the command line), you should delete the entire plist file and restart. Or suggest that after trying the writing via cmd, and before uninstalling and reinstalling the whole thing.

Nice job on this app, man. Real solid work I’ve been looking for this for years.

~Caleb

On Dec 16, 2019, at 11:42 AM, Alin Panaitiu <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm sorry, I have no idea what could be the issue here. You could try to search for anything called Lunar inside ~/Library/ and delete that. There is no other place that Lunar looks for settings.

**Comment by alin23** [comment]
I'm glad you finally got it working again! 
I added some more instructions about that here: 
https://github.com/alin23/Lunar#troubleshooting
