### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/Nue1y/lunar.log.enc] [AC3BCF481335C0D95E2FB1BC4F1A689DDB31F4B5772F03F3D6D0ECF4FFF8CB3D] [2.9.11]

### ISSUE THREAD

**Issue by jahewson** [alin23/Lunar#58]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   USB-C to DisplayPort cable

- Using an USB Docking Station or Hub:
    Yes, built-in to monitor, connected with separate USB-C -> USB-A adapter.

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    Yes

# Issue description:
Lunar crashes (and does not restart itself).

**Comment by alin23** [comment]
This should be fixed in 3.0.0. Feel free to reopen if the issue persists.
