### ISSUE TITLE
Lunar doesn't work properly with two monitors with the exact same model

### ISSUE THREAD

**Issue by muneebabbas** [alin23/Lunar#59]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook Pro 2018 15 inch*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *Dell U2717D*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C-to-HDMI and HDMI-to-HDMI*

- Using an USB Docking Station or Hub:
    *promate barHub-C*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*Lunar doesn't work when both the monitors are of the exact same model. I am certain that isn't a problem with a particular connection type (One connected through hub and one connected directly) as it was working perfectly fine with a different monitor. Also Lunar identifies one monitor correctly and this changes. For example, monitor A would work and after reboot monitor B would start working. One of the monitors appear as Luna and one correctly (which one appears correctly is random). This seems to be a bug where both monitors have the exact same model.*

**Comment by alin23** [comment]
I know about this bug. Unfortunately there's no way to work around it, the vendors are lazy and write the same exact data inside the monitor EDID structure so there's no way to distinguish them. I worked about 2-3 months to make this work at least in the most basic way but I couldn't find any solution to this.

**Comment by muneebabbas93** [comment]
@alin23 https://github.com/the0neyouseek/MonitorControl
This particular utility works perfectly with the same setup, just came across it. Maybe some inspiration for a workaround can be taken from there. Thanks for the amazing application though and feel free to close this issue if this is a known bug and you don't plan on working on it!

**Comment by alin23** [comment]
@muneebabbas93 thanks for the suggestion! I'll take a look to see if I can steal something from MonitorControl.

**Comment by alin23** [comment]
I'll close this as I couldn't find a specific solution that MonitorControl implements and Lunar doesn't.
