### ISSUE TITLE
App name is missing in Bartender 3

### ISSUE THREAD

**Issue by nhat** [alin23/Lunar#6]
Please see screen shot below.

Maybe this is not an issue on Lunar's side, but Bartender doesn't show any menu item name.

macOS High Sierra 10.13.6
Bartender 3.0.47

<img width="853" alt="lunar-menu-name" src="https://user-images.githubusercontent.com/2656835/46914659-abde7500-cfa0-11e8-8875-8ada12f23b53.png">

**Comment by alin23** [comment]
Huh, you're right. This might be a Lunar issue, I'll look into it

**Comment by alin23** [comment]
This should be fixed now
