### ISSUE TITLE
Feature: Command line utility

### ISSUE THREAD

**Issue by timtraversy** [alin23/Lunar#60]
### Name of the feature

Lunar command line utility

### What problem does this feature solve?

I would like a way to interact with Lunar programmatically, so I can update my monitor settings from the command line or from scripts. I think a command line util would be the most convenient way to do this.

I haven't been able to find many resources about interaction with Mac apps from the command line, but I'd be happy to work on this if you think it would be valuable.

### How should the feature work
```
$ lunar brightness 35
$ lunar contrast 55
```

**Comment by alin23** [comment]
I think the best solution for this is to use ddcctl directly, which is what Lunar is based on: https://github.com/kfix/ddcctl

It can also control other things like volume, red/green/blue gain etc.

What do you think, would that suffice?

**Comment by timtraversy** [comment]
Awesome, thanks for pointing me to that, I'm pretty sure that's all I need.
