### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/iYB9P/lunar.log.enc]

### ISSUE THREAD

**Issue by Guidiom** [alin23/Lunar#61]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *write response here*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *write response here*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *write response here*

- Using an USB Docking Station or Hub:
    *write yes or no here*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location or Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*

**Comment by alin23** [comment]
@Guidiom please fill up the required info in the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
