### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/v8HRn/lunar.log.enc]

### ISSUE THREAD

**Issue by Meistache** [alin23/Lunar#63]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes it did.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 13-inch Mid 2012, Core i5 2.5 GHz model (Intel 4000 Graphics)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    miniDisplayPort-to-DisplayPort, cable connected, 100 Hz frequency rate

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    Yes it does, as usual output follows:

```
Blue-Wars:ddcctl meistache$ ddcctl -h
D: NSScreen #2026671049 (1920x1080 0°) 70.00 DPI
I: found 1 external display
Blue-Wars:ddcctl meistache$ ddcctl -b 40 -c 60 -d 1
D: NSScreen #2026671049 (1920x1080 0°) 70.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: AG322FWG4
D: action: b: 40
D: setting VCP control #16 => 40
D: action: c: 60
D: setting VCP control #18 => 60
```

# Issue description:

Monitor model is a AOC Agon AG322FWG4 32"

Since I've updated to Catalina I've been experiencing frequent crashes during startup. (I didn't want to but I had to do a battery replacement and then I needed to update for troubleshooting an abnormal heating). I usually experience two or three reboots until I can actually log in with both displays connected unless I workaround it by just disconnecting my displayport and log in, even if the "Start at login" option is unchecked (it's not working, anyway, so as the login item, which actually makes the problem even worse). 

As I went for a fresh install on a brand new SSD it was easier to diagnose it was related to Lunar after this, since it was occuring after the update, but it's still going on even after reinstalling the whole disk with no Time Machine system backups and no other critical applications running at the startup which affects the external display besides, maybe, Lunar. Specially because my diagnostic steps were installing some critical audio applications I work with (and they use to be very troublesome at times, system-wise), restart, doing a whole backup, installing a few other system apps, restart, backup, check everything up, and only so working system tweaks like startup items, and it was since then I found Lunar could really have a potential bug. Being a nice unobstrusive software it would be the last point of failure I would ever suspect of.

Matter of fact it's unclear to me how "start at login" should work and maybe this is the actual problem, since it doesn't generate any LaunchAgent or LaunchDaemon in any of the instances (system extensions, system libraries or user libraries), but it might be doing some bit of mess somewhere else with the window manager, as I could check at the system console a few times when it first occured.

By the way I would gladly appreciate if I could have the EDIDReader since I couldn't proactively find it. And thanks for the hard work on Lunar, it's a great piece of software so far!

**Comment by alin23** [comment]
Hi @Meistache 

Lunar is still using a classic LoginItem for starting at login, you can check the code in the LunarService directory. 

The only way Lunar can cause a kernel panic is by trying to read the external monitor brightness with a misaligned DDC response delay. This is an option that was on by default in 2.9.2 and I made it off by default in all subsequent versions. You can toggle the option in the menu from the menu bar icon, or see how you can force disable it in the troubleshooting section of the README. 

But first of all, install the latest version of Lunar either from lunar.fyi or from the GitHub releases page.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Meistache** [comment]
Hi @alin23 

Thanks for the support! I already had the latest version (2.9.10), so I thought it would be a further step into diagnosis to delete the `site.lunarapp.Lunar.plist`. Anyway I just reinstalled my app using homebrew so I can keep track of the updates as well. 

I've done tests since them and I think it's working fine  under different startup/reboot circumstances just following the actual troubleshooting steps. 

I suppose it would be nice to close this issue by now unless there's some anomaly, right? I should not need any further modifications to the Lunar preferences by now so I'll let you know if something is out of control besides a bad DDC response delay alignment from my monitor.

**Comment by alin23** [comment]
Ok, thanks for letting me know! I'm working on making DDC compatible with more displays and more types of GPUs, but it will take some time to find testers to fit all major cases.
