### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/V8sqS/lunar.log.enc]

### ISSUE THREAD

**Issue by alonpr** [alin23/Lunar#66]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    brightness - yes, contrast - no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2017

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
contrast value is changing in the app but not on the monitor

**Comment by alin23** [comment]
Hi @alonpr ! What monitor model are you using?

Is it some kind of LG Ultrafine?

**Comment by alonpr** [comment]
Hi,
I wish 😂it's a Dell P2715Q

**Comment by alin23** [comment]
That's weird. Dell P2715Q is a known compatible monitor. Maybe try to look through the monitor firmware settings (using the monitor buttons) and see if there is any contrast setting interfering with DDC. Usually there is a Dynamic Contrast setting, maybe try disabling that.

**Comment by alin23** [comment]
Uniformity Compensation is another setting that can interfere with contrast settings

**Comment by alonpr** [comment]
Uniformity compensation is OFF.
DDC/CI is ON but I'd assume it's required that the software would be able
to control brightness/contrast of the monitor, isn't it?

**Comment by alin23** [comment]
Yes DDC/CI needs to be on for Lunar to work. I'm sorry, if those settings don't affect Lunar then I don't know what could be the problem.

**Comment by alonpr** [comment]
I apologize, I sent you a wrong monitor model, the P2715Q works flawlessly
actually. The one that has issues is *Dell U3818DW*

**Comment by alin23** [comment]
Looks to have most of the same options in the firmware. So if disabling Dynamic Contrast doesn't help, then it's possible that it uses a different code for contrast settings.

You can try https://github.com/kfix/ddcctl as that has support for all kinds of DDC properties like volume, RGB gain etc.
Maybe you find that one of the properties works for contrast.

**Comment by alin23** [comment]
This doesn't seem to be an issue with Lunar so I'll close this as it isn't fixable.
