### ISSUE TITLE
Listeners for media keys only work for Desktop

### ISSUE THREAD

**Issue by lijunkang12** [alin23/Lunar#69]
First of all, thank you for this new release! I The feature that we can use media keys as hotkeys is wonderful.

However, I notice that this feature only works for Desktop. If the cursor is on any other full-screen apps (such as Finder, Safari, Chrome, Preview, etc), press keyboard brightness keys only change the brightness of the Mac.

**Comment by alin23** [comment]
Unfortunately this seems to be a system limitation. The system reports the display as built-in even when it isn't and the media keys are not overridden on the builtin display.

I'll close this as I can't do anything to fix it.
