### ISSUE TITLE
Clip min/max brightness of built-in display

### ISSUE THREAD

**Issue by stygmate** [alin23/Lunar#70]
### Name of the feature

Hard clip min max brightness

### What problem does this feature solve?

external monitors that don't have the extended brightness range of internal macbook display can have 100% brightness when internal brightness is 80%

**Comment by alin23** [comment]
Working on it 😊 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alin23** [comment]
This was added in Lunar v3.1.5

Please let me know if it works as expected @stygmate

**Comment by stygmate** [comment]
Hi, it works at expected ! I've matched my external screens range and curve to my internal macbook display and it is perfect !
