### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/sWeEn/lunar.log.enc] [ECCF69787BB76C2DC36DEE925CD79E379CD2D0854BCFAAE4C9F6DDC122B6A698] [3.0.0]

### ISSUE THREAD

**Issue by zierka** [alin23/Lunar#71]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
Yes!

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MacBook Pro 2017

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
Mac - USB-C Adapter - Displayport - Monitor

- Using an USB Docking Station or Hub:
Yes (USB-C Multiport Adapter (USB-C, DisplayPort))

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

# Issue description:
Changing brightness/contrast stops working from the menubar popup and menubar menu after the monitor is disconnected and then reconnected to the Mac. It works from the Preferences pane, although it shows an "Non-responsive DDC" message, and it doesn't allow to set the brightness/contrast to 0 (the minimum is brightness 5 and contrast 20).

Restarting Lunar fixes the issue.
Lunar 2.9.10 doesn't have this issue.

**Comment by alin23** [comment]
It seems that your monitor fails to respond to some DDC messages from time to time and Lunar counts those and sees the monitor as non responsive when the fail count reaches 20. I think I'll have to reset the counter periodically to avoid this. 

The minimum and maximum limits of brightness and contrast are configurable from the main page of Lunar if you use Sync or Location mode, or from the Configuration page (the yellow one) if you use manual mode.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zierka** [comment]
Thanks for the updates! Let me know if I can help you with anything regarding this bug.

**Comment by alin23** [comment]
This should be fixed in Lunar 3.1. Let me know if there's anything that doesn't work as expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
