### ISSUE TITLE
Ability to adjust brightness curve without affecting max brightness

### ISSUE THREAD

**Issue by grahamburgsma** [alin23/Lunar#72]
### Name of the feature

Ability to adjust brightness curve without affecting max brightness

### What problem does this feature solve?

I'd like the ability to change the brightness curve to better match the brightness of my Mac (In adaptive mode). However changing the brightness offset also changes the max brightness. For example, -50 brightness offset makes my monitor brightness curve best match my Mac's brightness. However the max brightness is then 80 for the monitor. (Tested by setting Mac screen to full brightness, Lunar then shows 80 in the menu bar hover window.)

Interestingly a brightness offset of 0 makes the max brightness 96, which is odd. It's possible this is more of a bug than a new feature.

Love the app, let me know if you need more details!

**Comment by alin23** [comment]
The brightness limits are only set by the MIN/MAX fields on the main page of Lunar (the ones on the left of the display icon). Brightness offset always operates within those limits and will never set a brightness higher/lower than those values. 

Can you please post some screenshots with the min/max values and the configuration page of Lunar? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by grahamburgsma** [comment]
Min is 0, max is 100. However I reinstalled and restarted my computer and monitor, now it seems to be working as it should! I don't think I changed any settings, but oh well, it's working great now. Thanks for the support, closing this issue.

**Comment by grahamburgsma** [comment]
@alin23 It's happening again, but I figured out the cause. The system brightness setting `Automatically adjust brightness` seems to affect the max brightness of the monitor. Even though the system brightness slider is at max. Not sure if that's fixable or a weird side effect of something Apple is doing.

![Screen Shot 2020-03-02 at 7 22 36 AM](https://user-images.githubusercontent.com/9092289/75676201-ca591500-5c56-11ea-955e-9bd606a08ef0.png)
![Screen Shot 2020-03-02 at 7 22 55 AM](https://user-images.githubusercontent.com/9092289/75676202-caf1ab80-5c56-11ea-8ca4-cd5ce8f68e04.png)

**Comment by alin23** [comment]
What Sync mode actually does is read the brightness of the built-in display and after applying the curve algorithm and min/max limits to it, sends it to the external monitors.

So if the limits are reaching 0/100 and the offset is set to something sensible like 5 or -5 then your monitor should be able to reach 0/100.

This is what I have and my monitor's brightness can reach 100 with _Automatically adjust brightness_ enabled
![image](https://user-images.githubusercontent.com/3819725/75705948-0fb42b80-5cc5-11ea-9332-953d0f846ec6.png)

It's also possible that macOS sets a different brightness than 100 for you when automatic brightness is enabled.
