### ISSUE TITLE
3.0.0 breaks System Preference Shortcuts

### ISSUE THREAD

**Issue by unknowndomain** [alin23/Lunar#76]
# Issue description:
The all versions of macOS 10 support pressing Option + Media Keys to launch the relivent system preference.

The update to 3.0.0 which introduces media key support has broken this operating system functionality for Volume and Brightness even though the Option modifier is ignored.

**Comment by alin23** [comment]
The library that I'm using to listen for media keys, ignores media key events when the cursor is on the built-in screen. I just tested and when pressing Option+Brightness/Volume keys while the cursor is on the built-in display of my Macbook the System Preferences window opens as expected.

If it doesn't work for you then it's possible that it is related to the main screen detection issue. I'm working on that as we speak.

**Comment by unknowndomain** [comment]
I am on a MacBook Pro 15" with the lid closed and two LG 27UL850 or 27UK850 attached via USB-C, it looks like this is broken then for me also looks like actually none of the media keys are working like play/pause.

**Comment by alin23** [comment]
That's odd. Play/pause also works for me no matter where I have the cursor, and I don't override them in Lunar code so I don't see why they wouldn't work.

I will try some more stuff to fix this for you. Until then can you confirm that play/pause works if you disable the _Use media keys as hotkeys_ option?
![image](https://user-images.githubusercontent.com/3819725/75704946-fe6a1f80-5cc2-11ea-87d9-28a64c264bac.png)

**Comment by unknowndomain** [comment]
Yeah they are not, maybe this is a catalina issue then

**Comment by alin23** [comment]
Probably not as I'm also using latest Catalina. Do those keys work if you quit Lunar?

**Comment by alin23** [comment]
This should be fixed in Lunar 3.1. Let me know if there's anything that doesn't work as expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
