### ISSUE TITLE
Multiple monitor support for brightness media keys

### ISSUE THREAD

**Issue by unknowndomain** [alin23/Lunar#78]
### Name of the feature

Multiple monitor support for brightness media keys

### What problem does this feature solve?

Currently only the 'active' monitor can be adjusted, it's unclear what an active monitor is.

### How should the feature work

macOS already has a solution for this issue, normally with two Apple displays connected pressing Control and the brightness up or down key affects the secondary monitor, this is limited to two monitors i.e. with or without Control pressed, however this is more intuitive.

This would be best done sooner than later as it will confuse Lunar users who would now be using Control for contrast rather than second monitor as macOS already supports.

**Comment by alin23** [comment]
Lunar currently uses media keys to control the monitor that the cursor is on. That is how macOS defines the _main display_. This needs to work like this to have support for any number of external 
monitors.

I know the macOS uses ctrl for the secondary monitor, but Lunar is supposed to be a replacement for the native brightness adjustment (for external monitors) and as it has support for more than just brightness, it is hard to make it work exactly like macOS does already.

**Comment by unknowndomain** [comment]
I assumed that active display either meant the screen the mouse was on or the one with the 'bright' menu bar, but the brightness adjustment doesn't work.

That said I still think it would be better to support the shortcuts the way macOS does, I appreciate for some people this might be a replacement but for the vast majority of people who don't have Apple displays those brightness controls don't work unless you use this app.

**Comment by alin23** [comment]
I think I'm doing the main display detection wrong, I'll try to fix it in the next version.
As for the ctrl thing, how would you envision this working along with contrast controls and support for any number of monitors?

I'm having a hard time finding a way to incorporate these features in the macOS way.

**Comment by unknowndomain** [comment]
I guess it depends if you want to support both, one way would be to have a flag to switch between macOS mode and Lunar mode.

I could manage with the mouse thing if it worked tbh, I am just a shortcut person and currently my every day short cuts aren't working.

**Comment by alin23** [comment]
I'm working on fixing this as soon as possible.

**Comment by alin23** [comment]
This should be fixed in Lunar 3.1. Let me know if there's anything that doesn't work as expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
