### ISSUE TITLE
Lunar Feature - clamshell mode documentation

### ISSUE THREAD

**Issue by sfdye** [alin23/Lunar#79]
### Name of the feature

Documentation for clamshell mode

### What problem does this feature solve?

Provide more documentation for clamshell users

### How should the feature work

What's the recommended settings for clamshell mode? I am guess because the sensor is covered, we should only use location mode?

### Visual description

NA

**Comment by alin23** [comment]
Hi @sfdye ! Yes, Sync mode is out of the question because the sensor is covered in clamshell mode. 
You can: 
- Use Location mode for some automatic adjustments based on the sun position 
- Use Manual mode if you just want to use hotkeys/media keys 
- Disable clamshell detection in the Lunar menu if you never use the laptop with the lid open when connected to a monitor

There's not much else to say about this. I've been planning to update the official website with some documentation about each feature. Thanks for letting me know that this is needed, I'll make sure to include some words about clamshell mode there.

**Comment by sfdye** [comment]
> Use Location mode for some automatic adjustments based on the sun position

I've been patient for a few days but the location mode does not seem to work at all (I don't see the numbers change throughout the day) 

![image](https://user-images.githubusercontent.com/1016390/76418760-28fe5b80-63da-11ea-8c66-4df7cd21b129.png)

Am I doing anything wrong?

**Comment by alin23** [comment]
Your monitor is set to Manual. It needs to be set to Adaptive for that to work. Click on the `Manual` button to switch back to Adaptive mode

**Comment by alin23** [comment]
When you change to brightness manually, Lunar automatically sets your monitor into Manual mode to avoid unwanted changes from Location/Sync mode algorithm

**Comment by sfdye** [comment]
The moment I change to Adaptive mode:

![image](https://user-images.githubusercontent.com/1016390/76419124-cf4a6100-63da-11ea-8f72-3c4887d61d96.png)

(of course under clamshell mode)

**Comment by alin23** [comment]
Can you show me your Lunar configuration page?

This is how mine looks (with coordinates redacted):
<img width="1062" alt="Screenshot 2020-03-11 at 15 01 43" src="https://user-images.githubusercontent.com/3819725/76419731-862de900-63a9-11ea-8ec6-76c6caec2be9.png">

**Comment by sfdye** [comment]
![image](https://user-images.githubusercontent.com/1016390/76419885-1d139900-63dc-11ea-947b-a54c5ed75dd9.png)

Now it looks like this.

I also tried manually fill in my coordinates, didn't help either.

FYI clicking "Reset" does nothing for me.

**Comment by sfdye** [comment]
![image](https://user-images.githubusercontent.com/1016390/76420085-84314d80-63dc-11ea-9403-0d0ca44e3fa6.png)

I realize that I didn't grant location services permission for `Lunar` yet. I don't remember the app requesting for it 🤔

**Comment by alin23** [comment]
Yep, that is the problem. Lunar requests for location access the first time it starts.

**Comment by sfdye** [comment]
Now it works. 

> Lunar requests for location access the first time it starts.

Really I don't remember I said No to yet 🤔

**Comment by alin23** [comment]
It definitely does that. I just tested the functionality now and it still works. But there were a number of bugs in the macOS new permissions system. It's possible you encountered one
