### ISSUE TITLE
Does lunar have TouchBar multi touch featured for brightness control? 

### ISSUE THREAD

**Issue by mvaneijgen** [alin23/Lunar#81]
# Issue description:
I run BetterTouchTool with a three finger drag to adjust the brightness on my macbook, but if Lunar is active it spaces out. I have the feeling Lunar is also detecting the three finger drag and tries too also adjust the brightens. Are you working on a experimental feature? If so is there a way to disable it. 

# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Macbook Pro 2019

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
Dell U2518D

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB-c to CalDigit hub to display port

- Using an USB Docking Station or Hub:
CalDigit hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

**Comment by alin23** [comment]
Lunar is listening for media keys and the three finger drag just sends a brightness key press event. 
Nothing special, I'm not working with the touchbar at all. If you want to skip this, you have to disable the media keys listener in Lunar or keep the cursor on the built-in display while using the touchbar gesture.
