### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/pnewM/lunar.log.enc] [C1827C7975963EF80E47996E79A8A6918661A3BC7C266A1EE9F8B71E060BDD35] [3.1.0]

### ISSUE THREAD

**Issue by juandrei** [alin23/Lunar#82]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
macbook pro 16"  ( connecting to Apple Cinema Display 2010 )

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB-C with Baseus converter to mini-DP

- Using an USB Docking Station or Hub:
USB-C with Baseus converter to mini-DP

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
n/a

# Issue description:
Tool does NOT control external display whatsoever, neither in sync mode nor manual, although the numbers the tools reads for brightness contrast, etc. seem to change as the display adapts to different lights

**Comment by alin23** [comment]
If ddcctl doesn't work for you, then it's a connection problem and Lunar can't do anything. Most probably the baseus converter doesn't forward DDC messages properly. Try a direct connection if you have the possibility.
