### ISSUE TITLE
Unable to run newer versions of Lunar

### ISSUE THREAD

**Issue by marcelkooi** [alin23/Lunar#84]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Macbook Pro 2017

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
LG Pavilion 32 Display

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
HDMI-to-USB-C

- Using an USB Docking Station or Hub:
Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
N/A

# Issue description:
Lunar was working just fine for several months, but today I installed the update and it stopped working. It no longer showed up in the Menu bar. I quit Lunar through Activity Monitor, and tried to open it back up, and got a message along the lines of "Application 'Lunar' could not be opened."

I installed Lunar v2.9.9 through the releases page and that version works perfectly.

Let me know if there's any more information I can provide.

Thank you for your work on this project!

**Comment by alin23** [comment]
It's possible that you have an older version of macOS without Swift 5 libraries installed.
Check point 1 in the Troubleshooting section: https://github.com/alin23/Lunar#troubleshooting

**Comment by marcelkooi** [comment]
That seemed to fix it! Installed v3.1 without any issues. I am running High Sierra so you were right. Thanks again!
