### ISSUE TITLE
Cannot deactivate hotkeys in Preferences window 

### ISSUE THREAD

**Issue by gianza** [alin23/Lunar#88]
# Issue description:
In Lunar v.3.1.3 (latest), opening the "Preferences..." option and navigating to the "Hotkeys" window, we can unassign each hotkey by clicking on the X button. However, the deactivation doesn't work and it's not saved: when re-opening the "Hotkeys" window, the previous hotkey sequence is shown again as active.

Could you please check?

Thanks for the great work and have a nice week!

**Comment by alin23** [comment]
Hi @gianza .

There hasn't been any change in the hotkey management code. I also just checked and the hotkeys can be disabled as expected on my part (and persists even after quitting Lunar):
![image](https://user-images.githubusercontent.com/3819725/77903870-406b8e80-728c-11ea-8016-a813f2483ea0.png)

Is there a specific hotkey you're having trouble with?

**Comment by gianza** [comment]
Hi @alin23 ,

I checked again and it is not working for the Volume Down, Volume Up and Mute Audio hotkeys, and for the 'Hold Option for fine adjustments' checkbox in Volume Up/Down.

**Comment by alin23** [comment]
Got it! It will be fixed in the next version

**Comment by alin23** [comment]
Fixed in 3.1.4
