### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by mkbctrl** [alin23/Lunar#89]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 16 2019

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Samusung U32R59x - https://www.samsung.com/us/computing/monitors/curved/32-ur59c-curved-4k-uhd-monitor-lu32r590cwnxza/

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    usb-c-to-hdmi

- Using an USB Docking Station or Hub:
    false

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
<img width="950" alt="Screenshot 2020-04-03 at 07 01 13" src="https://user-images.githubusercontent.com/10107362/78325904-4c4f9d00-7579-11ea-9f05-35d699a5a022.png">

In manual mode I can't get above 90 for some reason. In Sync mode it's fine.

**Comment by alin23** [comment]
Hi @mkbctrl 

This is not a bug, there is a configurable limit in the Settings page of Lunar. Swipe left or press left arrow on the keyboard to see it:

![image](https://user-images.githubusercontent.com/3819725/78338828-27205600-759c-11ea-85a2-294e913a42bb.png)
