### ISSUE TITLE
No UI displayed

### ISSUE THREAD

**Issue by jsalbre** [alin23/Lunar#9]
Running El Capitan, Lunar's icon shows up in Activity Monitor but with no name, and no UI or Menubar item ever appears.

The following lines appear in the logs:

04.02.19 17:52:28.752 Lunar[3711]: [Crashlytics] Version 3.10.5 (130)
04.02.19 17:52:28.839 Lunar[3711]: CoreData: Failed to load optimized model at path '/Applications/Lunar.app/Contents/Resources/Model.momd/Model v2.omo'
04.02.19 17:52:29.227 Lunar[3711]: *** -[NSBackgroundActivityScheduler invalidate]: This activity has not been scheduled
04.02.19 17:52:36.382 com.apple.xpc.launchd[1]: (com.alinp.LunarService[3713]) Could not find and/or execute program specified by service: 45: Operation not supported: com.alinp.LunarService
04.02.19 17:52:36.385 com.apple.xpc.launchd[1]: (com.alinp.LunarService) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

The last two lines repeat every 10 seconds.

**Comment by alin23** [comment]
Thanks for reporting!

This might happen because the latest version of Lunar was compiled using a beta version of Xcode.
I'll push an update with a recompiled version to (hopefully) fix this.

**Comment by alin23** [comment]
Should be fixed in v2.2.1
