### ISSUE TITLE
Lunar Feature

### ISSUE THREAD

**Issue by irodrigo17** [alin23/Lunar#91]
### Name of the feature

Request location permissions after install

### What problem does this feature solve?

Avoid manually going to System Preferences and enabling location services for the app.

### How should the feature work

Show the standard macOS location services permission request dialog when app starts.

### Visual description

Use standard macOS UI.

**Comment by irodrigo17** [comment]
Just found Lunar after being blinded by my big ass display when working from home at night, it works great, thanks! I'm happy to send a PR for this on the weekend if you like the idea.

**Comment by alin23** [comment]
Hi @irodrigo17 !

Lunar already has this feature, but it seems the way to request for authorisation changed in macOS 10.15 and the prompt does not appear anymore. I'll take a look today.

**Comment by irodrigo17** [comment]
Cool, thanks!

**Comment by alin23** [comment]
@irodrigo17 this will be fixed in the next version

![image](https://user-images.githubusercontent.com/3819725/78926662-1db85180-7aa6-11ea-8af7-246466ddffc5.png)

**Comment by irodrigo17** [comment]
Thanks @alin23!
