### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/fJX3C/lunar.log.enc] [713E97B996A80332ADB74BE4E50E633E47A9A952159293FEE937152A6056D5F4] [3.1.4]

### ISSUE THREAD

**Issue by clarkFransje** [alin23/Lunar#92]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    USB hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Location

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    I know, I tried this, but it didn't work. I got this error: 
D: NSScreen #59593026 (1920x1080 0°) 93.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: HP 24fw
I: got edid.serial: --   
D: action: v: 30
D: setting VCP control #98 => 30
E: Failed to send DDC command!

# Issue description:
*write a short description of what doesn't work as expected*
Not be able to change the brightness of my external display.

**Comment by alin23** [comment]
Hi @clarkFransje! 

Try connecting the monitor directly to the Macbook (skip the hub) if you can. 
If you can't do that, try using a different cable.

If `ddcctl` can't send the command, then it's either a problem with the hub or the cable.

I'll close the issue as it is not a Lunar bug and I can't do anything to fix it. But you can post updates here and we can keep chatting about your problem if you have the possibility to try different hardware solutions.
