### ISSUE TITLE
Volume adjustment breaks when changing bluetooth headphones

### ISSUE THREAD

**Issue by hurshagrawal** [alin23/Lunar#93]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 16 inch

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    HP Z27

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    usb-c-to-usb-c

- Using an USB Docking Station or Hub:
  no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   n/a

# Issue description:
Disconnecting and reconnecting bluetooth headphones makes volume adjustments not work. At a higher level, Lunar is _amazing_ for monitor settings but the built-in sound controls are completely fine when I have bluetooth headphones connected. It would be nice to have some way to disable Lunar handling sound controls and use it *just* for brightness/contrast. I looked in settings everywhere for this but couldn't find a way to disable lunar's volume integration.

**Comment by alin23** [comment]
Hi @hurshagrawal !

I added this in 3.1.5 😊

![image](https://user-images.githubusercontent.com/3819725/79147081-122d9900-7dcc-11ea-8f15-dbececd53627.png)

**Comment by hurshagrawal** [comment]
Amazing! Thanks!

**Comment by hurshagrawal** [comment]
Yep works great. Thanks a lot.
