### ISSUE TITLE
Lunar Diagnostics Report [76B0E1D9B5D264C15E0EEE3816228FC46EE9967A568836F8D3394BDB57E9A265] [3.1.5]

### ISSUE THREAD

**Issue by jkylehumphrey** [alin23/Lunar#96]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    2019 MacBook Pro 13"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to HDMI

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Nothing changes.  I am using a TV as a monitor, which may affect the apps ability to change settings. 

![image](https://user-images.githubusercontent.com/418102/79336190-477fd700-7ef1-11ea-94bd-239dab7e8add.png)
LG UN7300PUF

**Comment by alin23** [comment]
Hi @jkylehumphrey ! Unfortunately, most TVs don't implement the DDC write functionality needed by Lunar to work. I tested Lunar myself on 4 different TVs and none worked.

**Comment by jkylehumphrey** [comment]
I figured it wouldn’t. Thanks for reply. App looks great, btw! Wish it worked for my setup.
