### ISSUE TITLE
Lunar Diagnostics Report [B9BF380CBB93337EBD961EEB190033E190850F566315841C77015C3B65B54981] [3.1.5]

### ISSUE THREAD

**Issue by Auer1329** [alin23/Lunar#98]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2017 15"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Unfortunately display sync mode and location mode is not working most of the time for my LG27UK850-W with the latest versions of Lunar.

**Comment by alin23** [comment]
Hi @Auer1329 ! Thanks for the feedback!

Can you explain in more details what doesn't work? 
Doesn't the sync mode change your monitor brightness according to your built-in display brightness at all?
Doesn't Location mode adjust your monitor brightness throughout the day?

Can you please also post screenshots with the white and yellow pages of the Lunar UI in both Sync mode and Location mode? It would help me understand if one of the settings is interfering with the functionality.

**Comment by alin23** [comment]
Also, please try to disable this option in the Lunar _Advanced_ menu

![image](https://user-images.githubusercontent.com/3819725/79554288-85722c00-80a6-11ea-8cff-fe79fb301174.png)


I can see in your logs that it's interfering with the Sync/Location modes.
